### ISSUE TITLE
Add RELEASE-NOTES.md

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1008]
It is better to add a release note file.

FYI: https://github.com/apache/shardingsphere/blob/master/RELEASE-NOTES.md

Please copy release note from each tag which in https://github.com/apache/shardingsphere-elasticjob-lite/tags and translate to English.

Tasks are:

- [ ] Create RELEASE-NOTES.md file
- [ ] Copy content from each tag which in https://github.com/apache/shardingsphere-elasticjob-lite/tags
- [ ] Translate to English

**Comment by kekerzzZ** [comment]
I can do it.

**Comment by terrymanu** [comment]
@kekerzzZ Thank you very much
