### ISSUE TITLE
预计什么时间发布新版本呢

### ISSUE THREAD

**Issue by qhsword** [apache/shardingsphere-elasticjob#1016]
预计什么时间发布新版本呢

**Comment by Technoboy-** [comment]
Will do the release in the next two weeks if possible. 
And please keep in English for any issues next time.

**Comment by terrymanu** [comment]
FYI: https://lists.apache.org/thread.html/r5aa032cebc95aaa3bf3af7f401ddaf0432947553448bb90c711a1e5a%40%3Cdev.shardingsphere.apache.org%3E
