### ISSUE TITLE
Consider about improvement of get IP address inaccurate

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1039]
If the job server has multiple network interface cards may cause the ip address get inaccurate.
It is better to consider about how to improve IP address getting accuracy.

The tasks priority are:

1. Why getIP return null in sometimes.
2. Multiple network interface cards env problem
3. Consider about use env variable to accept ip passed by user

**Comment by Technoboy-** [comment]
Please assign to me, I will fix it later, thanks

**Comment by Technoboy-** [comment]
1. Why getIP return null in sometimes.
   Guess : IP6 is not supported and return null.
   And I have sent an email to the reporter but no reply, So I think we can update the IPUtils first.
2. Multiple network interface cards env problem.
   Yes, we will select the first up and reachable card to get the IP.
3. Consider about use env variable to accept ip passed by user.
   Yes, support.

**Comment by vsover** [comment]
try jvm args add "-Djava.net.preferIPv4Stack=true"
