### ISSUE TITLE
Suggested support for tasks with expiry date and dynamic addition of tasks

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#1042]
1、
Some tasks only need to be run once or more at a specific time.  For example the  task is:  “Send 618 promotional messages” .

When the task is over, we want it to be removed automatically.

2、
We look forward to supporting APIs that add tasks dynamically.  When a task is added to ZK, all nodes can sense and load it.

**Comment by johnyannj** [comment]
In addition, when will the new version of elastic job be released? thx.

**Comment by viviel** [comment]
If the progress is normal, within a week

**Comment by viviel** [comment]
About your two suggestions
1. The new version is already supported
2. I'm sorry I don't understand what you mean. Can you describe it in detail?

**Comment by viviel** [comment]
If you want to dynamically increase the number of jobs and dynamically adjust the sharing parameters, the new version also supports it. You need to deploy the console module, which can implement the features I mentioned above

**Comment by johnyannj** [comment]
@viviel 
很抱歉，英文不好
1、支持有截止时间的任务，当到达截止时间，任务自动从zookeeper里清除记录
2、sdk支持动态添加任务，一个任务节点添加了任务到zk以后，其他任务节点监听zk，能感知到，并加载。

如果以上特性在最近代码里已经支持了，我去编译一个试一试。 之前elastic-job-lite 2.1.5 里是没有的。3Q~

**Comment by terrymanu** [comment]
Can we close this issue?

**Comment by terrymanu** [comment]
Will close soon
