### ISSUE TITLE
Use CloudJobConfigurationPOJO instead of CloudJobConfiguration for CloudJobRestfulApi

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1047]
We are using CloudJobConfiguration to exchange message from frontend and backend.
The class `JobConfigurationGsonTypeAdapter` is adapter with object and JSON string.
It is better to remove class `JobConfigurationGsonTypeAdapter`, and reuse CloudJobConfigurationPOJO to exchange message.
The tasks are:

- [x] Use CloudJobConfigurationPOJO instead of CloudJobConfiguration in CloudJobRestfulApi
- [x] Adjust JavaScript of frontend
- [x] Remove `GsonFactory.registerTypeAdapter(CloudJobConfiguration.class, new JobConfigurationGsonTypeAdapter())` from CloudJobRestfulApi.init()
- [x] Remove class `JobConfigurationGsonTypeAdapter`

**Comment by rudy2steiner** [comment]
I'd like to do  it!

**Comment by zhaoyuguang** [comment]
Assign to me too
