### ISSUE TITLE
Use CloudAppConfigurationPOJO instead of CloudAppConfiguration for CloudAppRestfulApi 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1048]
This task is similar with #1047. 
The tasks are:

- [x] Use CloudAppConfigurationPOJO instead of CloudAppConfiguration in CloudAppRestfulApi
- [x] Adjust JavaScript of frontend
- [x] Remove `GsonFactory.registerTypeAdapter(CloudAppConfiguration.class, new CloudAppConfigurationGsonFactory.CloudAppConfigurationGsonTypeAdapter())` from CloudAppRestfulApi.init()
- [x] Remove class CloudAppConfigurationGsonFactory

**Comment by garyGao2014** [comment]
I want to get this assignment

**Comment by zhaoyuguang** [comment]
i will finish it

**Comment by zhaoyuguang** [comment]
Assign to me too

**Comment by luky116** [comment]
i want to try this
