### ISSUE TITLE
Use spring boot instead of jetty for cloud console

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1050]
The console of ElasticJob Lite has already use spring boot, but the cloud console is still use jetty.
We need to keep consist with them.
Please Use spring boot instead of `RestfulServer` in ElasticJob Cloud.

We need call spring boot at `SchedulerService.start()`, replace of `restfulService.start()`

**Comment by kekerzzZ** [comment]
please assign to me

**Comment by kekerzzZ** [comment]
ok. I will add the test. because many changes this time, so a pr was mentioned first.
