### ISSUE TITLE
Split frontend project and refactor with VUE instead of jQuery

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere-elasticjob#1059]
Hello, Community.
According to the advance development of this project, it's time for us to split frontend project and refactor with VUE instead of jQuery now. 
@renfufei @EasonFeng5870 @menghaoranss 

- [x] split frontend project

- [x] refactor with VUE instead of jQuery

**Comment by menghaoranss** [comment]
I counted the following pages that need to be refactored：

1.  Global settings @menghaoranss 
  - [x] Registry center
       - [x] registry_center.html
  - [x] Event trace data source
       - [x] event_trace_data_source.html
2. Job operation @renfufei
  - [x] Job dimension
       - [x] job_config.html
       - [x] job_status_detail.html
       - [x] job_status_overview.html
  - [x] Server dimension
       - [x] server_status_detail.html
       - [x] server_status_overview.html
3. Job history 
  - [x] Job trace
       - [x] job_event_trace_history.html
  - [x] History status
       - [x] job_status_history.html

**Comment by renfufei** [comment]
Hi, @kimmking , 
I want to join the following develop task:


> 2、 Job operation
> 
> * [ ]  Job dimension
>   
>   * [ ]  job_config.html
>   * [ ]  job_status_detail.html
>   * [ ]  job_status_overview.html
> * [ ]  Server dimension
>   
>   * [ ]  server_status_detail.html
>   * [ ]  server_status_overview.html
