### ISSUE TITLE
Use Guava Strings class instead of assertj Strings class.

### ISSUE THREAD

**Issue by dongzl** [apache/shardingsphere-elasticjob#1076]
In the `ElasticJobLiteAutoConfiguration` class, import `org.assertj.core.util.Strings` class for String null or empty.

I suggest import `com.google.common.base.Strings` instead of `org.assertj.core.util.Strings`.

**Comment by zhaoyuguang** [comment]
assign to me

**Comment by qhsword** [comment]
Maybe you should try [langx-java](https://github.com/fangjinuo/langx-java)

@zhaoyuguang 
@dongzl

**Comment by dongzl** [comment]
> Maybe you should try [langx-java](https://github.com/fangjinuo/langx-java)
> 
> @zhaoyuguang
> @dongzl

Hi @fangjinuo , It's a good project. I'll learn about it.
