### ISSUE TITLE
the version of curator is too low, upgrade it, 

### ISSUE THREAD

**Issue by qhsword** [apache/shardingsphere-elasticjob#1078]

**Comment by qhsword** [comment]
curator 2.x using the guava version is 16.x
the version of guava in my project is 22.x
guava version conflict， so upgrade the guava to resolve it

after the curator upgraded , the curator version conflict was found。
but shardingsphere-elasticjob are using a low curator, so can't upgrade curator, so can't upgrade the guava.

if don't upgrade the guava , other functions in my project will fail .


DEAD loop

**Comment by dongzl** [comment]
Hi @fangjinuo , we have already upgrade `guava` and `curator ` version, it will be included elasticjob's new version and the  new version will be released right now.

**Comment by terrymanu** [comment]
Fixed by #1060
