### ISSUE TITLE
示例JavaMain代码执行会漏执行

### ISSUE THREAD

**Issue by readazusa** [apache/shardingsphere-elasticjob#1086]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

执行代码：
  private static void setUpSimpleJob(final CoordinatorRegistryCenter regCenter, final TracingConfiguration tracingConfig) {
        new ScheduleJobBootstrap(regCenter, new JavaSimpleJob(), JobConfiguration.newBuilder("javaSimpleJob", JobType.SIMPLE, 3)
                .cron("0/5 * * * * ?").shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou").build(), tracingConfig).schedule();
    }
    
执行日志：
![image](https://user-images.githubusercontent.com/7780584/87656009-7ffead80-c78b-11ea-9538-5b0e3b3eedee.png)

**Comment by terrymanu** [comment]
How to reproduce it?

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
