### ISSUE TITLE
支持广播模式执行job吗？比如我有n台机器，n台机器都需要执行一次任务（例如日志清理），如何配置？

### ISSUE THREAD

**Issue by songShiPeng** [apache/shardingsphere-elasticjob#1093]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
