### ISSUE TITLE
Translate feature doc to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1105]
- [x] Translate docs/content/features/schedule-model.en.md
- [x] Translate docs/content/features/elastic.en.md
- [x] Translate docs/content/features/resource.en.md
- [x] Translate docs/content/features/failover.en.md
- [x] Translate docs/content/features/misfire.en.md
- [x] Translate docs/content/features/job-type.en.md

**Comment by Technoboy-** [comment]
Hi, John!
   I want to try the below three :
```
Translate docs/content/features/failover.en.md
 Translate docs/content/features/misfire.en.md
 Translate docs/content/features/job-type.en.md
```
 And if others wanna join, misfire and job-type can give out.

**Comment by zhaoyuguang** [comment]
@Technoboy-  friend ping  `job-type.en.md` give me

**Comment by Technoboy-** [comment]
> @Technoboy- friend ping `job-type.en.md` give me

Sure

**Comment by Technoboy-** [comment]
Only elastic.en.md needs to translate, volunteer wanted !

**Comment by kezhenxu94** [comment]
I'll take over `docs/content/features/elastic.en.md`
