### ISSUE TITLE
Support job-type configuration of spring namespace

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1114]
The current spring namespace support job-ref which for classed job only.
We need to adaptor typed job type for now.
The tasks are:

- [x] Add job-type attribute in spring namespace xsd
- [x] Modify `JobBeanDefinitionParser` to judge `job-ref` and `job-type`
- [x] Add test case for `job-ref`
- [x] Fix spring namespace example for `SCRIPT` type

**Comment by jiang2015** [comment]
please assigned to me，thanks
