### ISSUE TITLE
Adjust spring module structure

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1116]
The current spring module structure is not good enough after we add the spring boot starter module.
The current structure is:

```
--elasticjob-lite-spring
--elasticjob-lite-spring-boot-starter
```

How about adjust them to:

```
--elasticjob-lite-spring
----elasticjob-lite-spring-boot-starter
----elasticjob-lite-spring-namespace
```

***It is better to adjust example modules too.***

**Comment by cocodroid** [comment]
Please assign it to me

**Comment by cocodroid** [comment]
Finish

**Comment by terrymanu** [comment]
@cocodroid, 
Hi, I add some code review suggestions for your pr, please fix them.

**Comment by cocodroid** [comment]
@terrymanu 
Sorry, I ignored it. I will fix it.

**Comment by terrymanu** [comment]
@cocodroid Sorry, I need to revert your pr, because this pr do not move the spring boot's test cases, and the test cases are missing.
