### ISSUE TITLE
Translate user-manual\elasticjob-lite\job-api doc to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1118]
- [x]  Translate `docs/content/user-manual/elasticjob-lite/usage/job-api/job-interface.en.md`
- [x]  Translate `docs/content/user-manual/elasticjob-lite/usage/job-api/java-api.en.md`
- [x]  Translate `docs/content/user-manual/elasticjob-lite/usage/job-api/spring-boot-starter.en.md`
- [x]  Translate `docs/content/user-manual/elasticjob-lite/usage/job-api/spring-namespace.en.md`

**Comment by dongzl** [comment]
I will do it.
