### ISSUE TITLE
Translate user-manual\elasticjob-lite\job-listener doc to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1131]
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/job-listener/_index.en.md
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/job-listener/listener-interface.en.md
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/job-listener/java-api.en.md
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/job-listener/spring-namespace.en.md

**Comment by zhaoyuguang** [comment]
assign to me~ PL
