### ISSUE TITLE
how to kill elastic job instance

### ISSUE THREAD

**Issue by medlying** [apache/shardingsphere-elasticjob#1132]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Just call `ScheduleJobBootstrap.shutdown`

**Comment by medlying** [comment]
> Just call `ScheduleJobBootstrap.shutdown`

i see the ScheduleJobBootstrap.shutdown() function is to stop the scheduler(do not create next schedule job instance?).  “how to kill elastic job instance ” meaning is to kill the job instance(the thread or process)

**Comment by terrymanu** [comment]
Stop schedule mean stop the thread. If you want to kill process, do you need to kill -9 in the system?

**Comment by terrymanu** [comment]
Will close soon if no response
