### ISSUE TITLE
Translate user-manual\elasticjob-lite\event-trace doc to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1138]
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/event-trace/_index.en.md
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/event-trace/table-structure.en.md
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/event-trace/java-api.en.md
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-boot-starter.en.md
- [x] Translate docs/content/user-manual/elasticjob-lite/usage/event-trace/spring-namespace.en.md

**Comment by dongzl** [comment]
I will do it.
