### ISSUE TITLE
Translate user-manual\elasticjob-lite\configuration to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1151]
- [x] docs/content/user-manual/elasticjob-lite/configuration/_index.en.md
- [x] docs/content/user-manual/elasticjob-lite/configuration/java-api.en.md
- [x] docs/content/user-manual/elasticjob-lite/configuration/spring-namespace.en.md
- [x] docs/content/user-manual/elasticjob-lite/configuration/spring-boot-starter.en.md
- [x] docs/content/user-manual/elasticjob-lite/configuration/props.en.md

**Comment by dongzl** [comment]
I will do it.
