### ISSUE TITLE
Consider about cannot permit port as -1 for disable SnapshotService

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1152]
If user has already use SnapshotService, it is no reason to disable the port.

It is better to do not permit set the port as -1.

Please modify for:

- [x] SnapshotService
- [x] Spring namespace
- [x] Update document at `docs/content/user-manual/elasticjob-lite/configuration/spring-namespace.cn.md`

**Comment by jiang2015** [comment]
please assign to me,thanks
