### ISSUE TITLE
Translate user-manual\elasticjob-lite\operation to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1161]
- [x] docs/content/user-manual/elasticjob-lite/operation/deploy-guide.en.md
- [x] docs/content/user-manual/elasticjob-lite/operation/dump.en.md
- [x] docs/content/user-manual/elasticjob-lite/operation/execution-monitor.en.md
- [x] docs/content/user-manual/elasticjob-lite/operation/web-console.en.md

**Comment by zhaoyuguang** [comment]
assign to me~ PL

**Comment by viviel** [comment]
Let me translate this execution-monitor.en.md

**Comment by zhaoyuguang** [comment]
I will translate the last,  at now as soon
```
docs/content/user-manual/elasticjob-lite/operation/web-console.en.md
```
