### ISSUE TITLE
Translate user-manual\elasticjob-cloud to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1179]
- [x] docs/content/user-manual/elasticjob-cloud/usage/dev-guide.en.md
- [x] docs/content/user-manual/elasticjob-cloud/usage/local-executor.en.md
- [x] docs/content/user-manual/elasticjob-cloud/configuration/_index.en.md
- [x] docs/content/user-manual/elasticjob-cloud/operation/deploy-guide.en.md
- [x] docs/content/user-manual/elasticjob-cloud/operation/high-availability.en.md
- [x] docs/content/user-manual/elasticjob-cloud/operation/web-console.en.md

**Comment by viviel** [comment]
Let me finish the task

**Comment by zhaoyuguang** [comment]
I will translate under follow first 
```
docs/content/user-manual/elasticjob-cloud/operation/high-availability.en.md
docs/content/user-manual/elasticjob-cloud/operation/web-console.en.md
```

**Comment by luky116** [comment]
I will translate under follow first

> docs/content/user-manual/elasticjob-cloud/configuration/_index.en.md

**Comment by Technoboy-** [comment]
I will translate deploy-guide.en.md.
luky116 will give this to me !

**Comment by luky116** [comment]
> I will translate deploy-guide.en.md.
> luky116 will give this to me !

ok

**Comment by zhaoyuguang** [comment]
I will finish the last
```
docs/content/user-manual/elasticjob-cloud/configuration/_index.en.md
```
