### ISSUE TITLE
Merge spring boot starter to one module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1192]
We have 3 spring boot starter modules now which are not consist with spring namespace.
It is better to merge these 3 modules in to one module.

We need move `elasticjob-registry-center-spring-boot-starter` and `elasticjob-tracing-spring-boot-starter` into `elasticjob-lite-spring-boot-starter`.

Just create new package for them:
just put `elasticjob-registry-center-spring-boot-starter` into package `org.apache.shardingsphere.elasticjob.lite.spring.boot.reg`;
put `elasticjob-tracing-spring-boot-starter` into package `org.apache.shardingsphere.elasticjob.lite.spring.boot.tracing`.

**Comment by cocodroid** [comment]
Please assign to me, thank you

**Comment by TeslaCN** [comment]
Please assign to me, thanks.
