### ISSUE TITLE
Consider about use socket for cloud RESTful API

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1193]
The current RESTful API for cloud is using Jersey and will replace to Spring Boot soon.
We need to consider about move the console to UI module and create new module for app publish and job management.
It is better to keep consist with Snapshot service, just socket to communicate with ElasticJob-Cloud scheduler.

- [ ] Create new module name as elasticjob-command module to process socket management
- [ ] Refactor snapshot service to reuse elasticjob-command module
- [ ] Define commands of operator
- [ ] Replace RESTful API to socket in elasticjob-cloud-scheduler

**Comment by TeslaCN** [comment]
Please assign to me, thanks.

**Comment by terrymanu** [comment]
Invalid because we discuss use netty+http instead of it.
Ref #1284
