### ISSUE TITLE
Fix test case TaskExecutorThreadTest.assertLaunchTaskWithWrongElasticJobClass

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1200]
The test case TaskExecutorThreadTest.assertLaunchTaskWithWrongElasticJobClass is not reach the catch block, the assertion is missing.

Please fix this test case and recover the `(expected = JobSystemException.class)`

**Comment by gzdzss** [comment]
Please assign it to me. Thank you
