### ISSUE TITLE
Resolve license incompatibility.

### ISSUE THREAD

**Issue by kekerzzZ** [apache/shardingsphere-elasticjob#1206]
Because the license of some of the referenced jar packages is not compatible with apache, it needs to be removed.

1. remove jersey
1. remove javax.transaction-api-1.2
1. remove jaxb-impl-2.2.3-1
1. remove stax-api-1.0-2

**Comment by kekerzzZ** [comment]
please assign it to me.

**Comment by tuohai666** [comment]
When I package the lite-bin distribution, there's still javax.transaction-api-1.2.jar.
