### ISSUE TITLE
Refactor cloud console with VUE instead of jquery

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere-elasticjob#1223]
Same as #1059 , we need refactor cloud console pages with VUE , there are pages that need to be refactored: 

1.  APP
  - [x] Config
2. Registry center
  - [x] Config
3. Job
  - [x] Config
  - [x] Status    
4. Job history
  - [x] Dashboard
  - [x] Job trace
  - [x] History status

Here are some pictures of the pages:
1. APP
![image-20200720183402666](https://user-images.githubusercontent.com/60651792/88036008-89b25780-cb75-11ea-89d9-c7c670f93453.png)
![image-20200720183420220](https://user-images.githubusercontent.com/60651792/88036020-8e770b80-cb75-11ea-9974-68f881be697a.png)

2. Job
![image-20200720183437998](https://user-images.githubusercontent.com/60651792/88036089-a51d6280-cb75-11ea-91bf-83abf7922657.png)
![image-20200720183448925](https://user-images.githubusercontent.com/60651792/88036095-a9498000-cb75-11ea-9100-2bf46a8256bc.png)
![image-20200720183508395](https://user-images.githubusercontent.com/60651792/88036128-b5354200-cb75-11ea-82cf-4400c8f205af.png)
![image-20200720183518655](https://user-images.githubusercontent.com/60651792/88036138-b8c8c900-cb75-11ea-9094-007e9585b4da.png)
![image-20200720183530147](https://user-images.githubusercontent.com/60651792/88036144-bbc3b980-cb75-11ea-9fac-938e0fe29df0.png)

3. Job hisotry
![image-20200720183556923](https://user-images.githubusercontent.com/60651792/88036239-dd24a580-cb75-11ea-9881-0f9e71d45d0a.png)
![image-20200720183617459](https://user-images.githubusercontent.com/60651792/88036253-e0b82c80-cb75-11ea-82a9-fa45b99ba7d6.png)
![image-20200720183719518](https://user-images.githubusercontent.com/60651792/88036309-f3cafc80-cb75-11ea-9869-afc508db4d67.png)
![image-20200720183732637](https://user-images.githubusercontent.com/60651792/88036318-f6c5ed00-cb75-11ea-838c-d584f43f923f.png)

**Comment by renfufei** [comment]
Hi,  @menghaoranss 
I Want to develop the third part:

> 3、 Job
> 
> * [x]  Config
> * [x]  Status
>
