### ISSUE TITLE
啥时候发布新版本啊，啥时候支持springboot start，啥时候更新console页面管理

### ISSUE THREAD

**Issue by FN20200222** [apache/shardingsphere-elasticjob#1238]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
For English only, other languages will not accept.
