### ISSUE TITLE
Elastic-Job can tracing with SkyWalking

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/shardingsphere-elasticjob#1256]
SkyWalking issue
https://github.com/apache/skywalking/issues/5152

Main change from elastic-job 2.x
1 LocalSpan change EntrySpan 
2 operateName is ElasticJob/jobName
3 tag will more detail than older

**Comment by zhaoyuguang** [comment]
Please assign to me,  and i will finish at 3.0.0-alpha publish

**Comment by terrymanu** [comment]
Wonderful job.
