### ISSUE TITLE
the job was offline, how to change the job to be online 

### ISSUE THREAD

**Issue by Fengxu1234** [apache/shardingsphere-elasticjob#1261]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Just restart your job application

**Comment by Fengxu1234** [comment]
@RequestMapping(value = "/addJob", method = RequestMethod.POST)
    public void addJob(@RequestBody String data, HttpServletRequest request, HttpServletResponse response) {

        JSONObject dataS = JSONObject.parseObject(data);
        String id = dataS.getString("id");
        String cron = dataS.getString("corn");
        JobCoreConfiguration coreConfig = JobCoreConfiguration.newBuilder("JobA" + id, cron, 1).jobParameter(Id).build();
        SimpleJobConfiguration simpleJobConfig = new SimpleJobConfiguration(coreConfig, JobA.class.getCanonicalName());
        JobScheduler jobScheduler = new JobScheduler(zookeeperRegistryCenter, LiteJobConfiguration.newBuilder(simpleJobConfig).build(),jobEventConfiguration);
      
            jobScheduler.init();
 
    }

Passing parameter id to the JobA, ervery  id create a Job as "JobA"+id . This scenario , how to implement to be distributed ?

**Comment by Technoboy-** [comment]
In current implementation,  you should deploy the above API in two applications at least, and call it on every one .

**Comment by Fengxu1234** [comment]
it means ervery applications also call the api to use the same JobName ?

**Comment by Technoboy-** [comment]
> it means ervery applications also call the api to use the same JobName ?

Yes, take a try.

**Comment by Fengxu1234** [comment]
> > it means ervery applications also call the api to use the same JobName ?
> 
> Yes, take a try.

it's ok , but have a problem , once the application is down , the job could not be brought back online by restarting.

**Comment by terrymanu** [comment]
Does it duplicate with #696?
