### ISSUE TITLE
Looking for a comfortable command format for cloud RESTful API refactoring

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1284]
## Discussion
Links #1193 .

According to my statistics, there are 25 APIs in elasticjob-cloud-scheduler need to be refactored.
We are going to replace RESTful API with socket to keep the command style consistent with SnapshotService.
Now we need to redefine the following APIs in a format like `dump@jobName`, so that we can send request in the way like:
```bash
echo "dump@jobName" | nc localhost 9888
```

CloudAppController:
- POST /app
- PUT /app
- GET /app/list
- GET /app/{appName}
- GET /app/{appName}/disable
- POST /app/{appName}/disable
- POST /app/{appName}/enable
- DELETE /app/{appName}

CloudJobController:
- POST /job/register
- PUT /job/update
- DELETE /job/{jobName}/deregister
- GET /job/{jobName}/disable
- POST /job/{jobName}/disable
- POST /job/{jobName}/enable
- POST /job/trigger
- GET /job/jobs
- GET /job/jobs/{jobName}
- GET /job/tasks/running
- GET /job/tasks/ready
- GET /job/tasks/failover
- GET /job/events/executions
- GET /job/events/statusTraces

CloudOperationController:
- POST /operate/reconcile/explicit
- POST /operate/reconcile/implicit
- GET /operate/sandbox

There is something needs to be discussed:
1. How to express HTTP methods and URL in a comfortable command line format?
2. What format do we use to attach a request body to the command?
3. What format do we use to attach authentication information to the command?

If you have any suggestions at all, whether large or small, please leave your comments.

**Comment by terrymanu** [comment]
My suggestion is we just keep consist with original RESTful API for now. 
After 3.0.0-alpha release, we can discuss the 3rd question, how to add the authentication

**Comment by TeslaCN** [comment]
To the 3rd question: 
Maybe we can use HTTP Basic Authentication which has been implemented in cloud-scheduler.

**Comment by TeslaCN** [comment]
At present, elasticjob-cloud-scheduler provides RESTful API via Spring Boot Web and it works properly.
But one the one hand, dependencies of Spring Boot Web are too heavy for a lightweight framework. One the other hand, cloud-scheduler just use only a fraction of the features of Spring Boot stack.  
We have discussed about it and decided to refactor cloud-scheduler with Netty. 

This process can be divided into 3 steps:  
- [x] Implement a lightweight HTTP Service module.
- [x] Refactor RESTful API of cloud-scheduler with the HTTP Service.
- [ ] (Optional) Provide RESTful API of SnapshotService.
