### ISSUE TITLE
The frequency of program execution is not in accordance with the regulations

### ISSUE THREAD

**Issue by readazusa** [apache/shardingsphere-elasticjob#1288]
## Question
I use JavaSimpleJob example  cron "0/2 * * * * ?",The program should be executed every 2 seconds
But the program is still executed every 5  seconds.

The code:
 new ScheduleJobBootstrap(regCenter, new JavaSimpleJob(), JobConfiguration.newBuilder("javaSimpleJob", 3)
                .cron("0/2 * * * * ?").overwrite(true).shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou").build(),
				tracingConfig).schedule();

The program running log is as follows:
Item: 0 | Time: 13:35:15 | Thread: 32 | SIMPLE
Item: 1 | Time: 13:35:20 | Thread: 35 | SIMPLE
Item: 2 | Time: 13:35:25 | Thread: 38 | SIMPLE
Item: 0 | Time: 13:35:30 | Thread: 43 | SIMPLE
Item: 1 | Time: 13:35:35 | Thread: 46 | SIMPLE
Item: 2 | Time: 13:35:40 | Thread: 49 | SIMPLE
Item: 0 | Time: 13:35:47 | Thread: 57 | SIMPLE

Is my understanding wrong? can you help me.

I debug the program found has a code Always wait 5 seconds to execute 

That's it "         JobExecutionEvent jobExecutionEvent = new JobExecutionEvent(IpUtils.getHostName(), IpUtils.getIp(), shardingContexts.getTaskId(), jobConfig.getJobName(), executionSource, item);
"

**Comment by terrymanu** [comment]
Did you set `overwrite=true`?
FYI: https://shardingsphere.apache.org/elasticjob/current/en/faq/#3-why-is-the-job-configuration-modified-in-the-code-or-spring-xml-file-but-the-registry-center-is-not-updated

**Comment by readazusa** [comment]
I have set overwrite=true
`new ScheduleJobBootstrap(regCenter, new JavaSimpleJob(), JobConfiguration.newBuilder("javaSimpleJob", 3)
.cron("0/2 * * * * ?").overwrite(true).shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou").build(),
tracingConfig).schedule();`


I found the code `   JobExecutionEvent jobExecutionEvent = new JobExecutionEvent(IpUtils.getHostName(), IpUtils.getIp(), shardingContexts.getTaskId(), jobConfig.getJobName(), executionSource, item);
`
Stay for 5 seconds at a time, but I don't found code sleep.
I want to know where this sentence code sleep is realized, can you help me

**Comment by terrymanu** [comment]
Can you provide your job configuration which persisted in zookeeper?

**Comment by readazusa** [comment]
`
cron: 0/2 * * * * ?
description: ''
disabled: false
failover: false
jobName: javaSimpleJob
jobParameter: ''
maxTimeDiffSeconds: -1
misfire: true
monitorExecution: true
overwrite: true
reconcileIntervalMinutes: 10
shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
shardingTotalCount: 3



`

**Comment by Technoboy-** [comment]
And please paste JavaSimpleJob

**Comment by readazusa** [comment]
`public class JavaSimpleJob implements SimpleJob {

    @Override
    public void execute(final ShardingContext shardingContext) {
		System.out.println(String.format("Item: %s | Time: %s | Thread: %s | %s", shardingContext.getShardingItem(), new SimpleDateFormat("HH:mm:ss").format(new Date()), Thread.currentThread().getId(), "SIMPLE"));
	}
}
`

**Comment by readazusa** [comment]
I tested and found that the MAC  Catalona system java version 1.8.0_ 202, there will be the above problems, windows is normal。

**Comment by terrymanu** [comment]
Did you use docker for testing?

**Comment by gzdzss** [comment]
Try adding configuration to hosts

`127.0.0.1 your_host_name`

**Comment by Technoboy-** [comment]
We find that maybe it's the IpUtils.getHostName() that leads the latency of the scheduling.
So we add cache for it #1328 .
