### ISSUE TITLE
Where is elasticjob-lite-console？

### ISSUE THREAD

**Issue by bywei** [apache/shardingsphere-elasticjob#1289]
## Question

Where is elasticjob-lite-console？

Do you have a project structure description?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
FYI: https://github.com/apache/shardingsphere-elasticjob-ui
