### ISSUE TITLE
LiteJob will create a shutdownhook thread every time as execute job

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob#1297]
This is the same issue with DaemonTaskScheduler. 
Quartz will schedule to execute job and create a new Job instance every time, that means it will create LiteJob every time.
As LiteJob executes job with guava executor that create shutdownhook thread internal. 
So LiteJob#createExecutor will create extra thread as job executes.

**Comment by Technoboy-** [comment]
![image](https://user-images.githubusercontent.com/6297296/88913047-d6431480-d292-11ea-88e4-9ca7a1059325.png)

**Comment by jiang2015** [comment]
I find that the class [ElasticJobExecutor] Constructor is called by other class place as follows：
1. LocalTaskExecutor#createElasticJobExecutor 
2.DaemonTaskScheduler#createJobExecutor
3.TaskExecutor#createJobExecutor
4.LiteJob.createExecutor

2,3 more modified as singleton class
1.4 still new Object（）

I think the base resolve the problem，ElasticJobExecutor is modified as Sington class it‘s better。
