### ISSUE TITLE
The event thread pool may be stacking problems.

### ISSUE THREAD

**Issue by viviel** [apache/shardingsphere-elasticjob#1301]
I simply looked at the code flow, which is the same as the life cycle of a job schedule, which is used to listen to the execution state of the job task, which means that the thread pool is either reused or destroyed with the end of a schedule.

<img width="786" alt="unchecked" src="https://user-images.githubusercontent.com/37171953/88999565-7f3b4f00-d327-11ea-83fc-5ccd1a2120f5.png">

Here, the life cycle of the jobFacade object is scheduled once, and the event thread pool is managed by jobFacade.

The problem now is that after a job scheduling is over, the event thread pool has a survival time of five minutes, which can lead to the event thread pool stacking if the schedule frequency is high.

**Comment by terrymanu** [comment]
Fixed by #1305
