### ISSUE TITLE
Support HTTP job

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1339]
Create new maven module for `elasticjob-http-executor` under `elasticjob-executor-type` to implement new job type for HTTP.

**Comment by TeslaCN** [comment]
Please assign to me, thanks.

**Comment by terrymanu** [comment]
The task of RESTful API is a big task, could you consider about finish it first?

**Comment by Technoboy-** [comment]
> The task of RESTful API is a big task, could you consider about finish it first?

I will take this task, and if @TeslaCN is interested in this task,  you can help me as you finish Rest API.
