### ISSUE TITLE
分片数设置为1，多个节点部署，有没有办法可以让第一个启动的节点存在的时候一直作为主节点？

### ISSUE THREAD

**Issue by bjhan** [apache/shardingsphere-elasticjob#1342]
## Question
分片数设置为1，多个节点部署，有没有办法可以让第一个启动的节点存在的时候一直作为主节点？在后面节点新增的时候，即使重新选举主节点，选举出来的结果也是第一个启动的节点为主节点？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
