### ISSUE TITLE
分片待调整

### ISSUE THREAD

**Issue by RitchieWong** [apache/shardingsphere-elasticjob#1349]
When using this control platform, our company may go online frequently, and the setting time of timing tasks may be very long, which will result in that most of the time in this state is in the state of fragmentation to be adjusted, instead of manually triggering this function.
Is there a way to trigger this sharding once when deploying the service, or can it be triggered manually without sharding?

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
