### ISSUE TITLE
If the number of partitions is set to 1 and multiple nodes are deployed, is there any way to make the first started node as the primary node when it exists?

### ISSUE THREAD

**Issue by bjhan** [apache/shardingsphere-elasticjob#1350]
## Question

If the number of partitions is set to 1 and multiple nodes are deployed, is there any way to make the first started node as the primary node when it exists? When the following nodes are added, even if the primary node is re elected, the result of the election is the first activated node as the master node?

**Comment by terrymanu** [comment]
It is possible if you customize your job sharding strategy.
FYI: 
https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/configuration/built-in-strategy/sharding/
& 
https://shardingsphere.apache.org/elasticjob/current/en/dev-manual/sharding/

**Comment by bjhan** [comment]
> It is possible if you customize your job sharding strategy.
> FYI:
> https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/configuration/built-in-strategy/sharding/
> &
> https://shardingsphere.apache.org/elasticjob/current/en/dev-manual/sharding/

thank you
