### ISSUE TITLE
Sharding flag

### ISSUE THREAD

**Issue by RitchieWong** [apache/shardingsphere-elasticjob#1352]
When using this control platform, our company may go online frequently, and the setting time of timing tasks may be very long, which will result in that most of the time in this state is in the state of Sharding flag, instead of manually triggering this function.
Is there a way to trigger this sharding once when deploying the service, or can it be triggered manually without sharding?

**Comment by Technoboy-** [comment]
Currently you can set shardingTotalCount to 1 to avoid sharding. and can modify on the console.
Does it match your need in this way ?

**Comment by RitchieWong** [comment]
> Currently you can set shardingTotalCount to 1 to avoid sharding. and can modify on the console.
> Does it match your need in this way ?

However, if this is changed, as soon as the service is started, its status is still Sharding flag, and there is still no way to click the Trigger

**Comment by Technoboy-** [comment]
> > Currently you can set shardingTotalCount to 1 to avoid sharding. and can modify on the console.
> > Does it match your need in this way ?
> 
> However, if this is changed, as soon as the service is started, its status is still Sharding flag, and there is still no way to click the Trigger

You can set overwrite to false

**Comment by terrymanu** [comment]
@wangjiaqi-gh Can you change the title for good summary and search friendly?

**Comment by terrymanu** [comment]
I just set `invalid` until the title changed

**Comment by Technoboy-** [comment]
This issue can be closed. I have talked with him via email and resolved it.
@terrymanu
