### ISSUE TITLE
Support Dubbo job

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/shardingsphere-elasticjob#1359]
I want create new maven module for elasticjob-kafka-executor under `elasticjob-executor-type` to implement new job type for Dubbo. use telnet

**Comment by terrymanu** [comment]
Is the telnet used normally with Dubbo?

**Comment by zhaoyuguang** [comment]
Yes, Telnet is used for a lot of things, Unless telent Port is forced to be turned off.

**Comment by terrymanu** [comment]
From my understanding, the most advantages of Dubbo are transparent RPC and Service governance in application (for example: java application).
Telnet is not a general way using by  business application, is it?

**Comment by zhaoyuguang** [comment]
> From my understanding, the most advantages of Dubbo are transparent RPC and Service governance in application (for example: java application).
> Telnet is not a general way using by business application, is it?

yes,

**Comment by dai19470** [comment]
this is a good idea

**Comment by terrymanu** [comment]
If there is unnecessary to do Dubbo job for now, I suggest close this issue.

**Comment by zhaoyuguang** [comment]
OK
