### ISSUE TITLE
Currently spring-Boot does not support a listener

### ISSUE THREAD

**Issue by caopengan** [apache/shardingsphere-elasticjob#1360]
## Question
If I use Spring-Boot and Listener, they cannot be used together, otherwise the registry configuration will be loaded twice, could this be optimized to cache the registry data

**Comment by TeslaCN** [comment]
DAG is comming soon.

**Comment by Technoboy-** [comment]
I think this should be supported even if DAG is coming.

**Comment by TeslaCN** [comment]
> I think this should be supported even if DAG is coming.

Listener API may be removed or marked as deprecated after DAG merged. I think it is unnecessary to support Listener.

@caopengan Instance of RegistryCenter can be injected by Autowired  or retrieved from ApplicationContext, there is no need to create a Registry manually.
