### ISSUE TITLE
Class 'IpUtils'  has a bug ?    

### ISSUE THREAD

**Issue by jwolf123456** [apache/shardingsphere-elasticjob#1365]
![image](https://user-images.githubusercontent.com/61695475/89870598-aed03e00-dbe8-11ea-9c83-2f1cd649bb51.png)

**Comment by zhaoyuguang** [comment]
I will test, then fix

**Comment by zhaoyuguang** [comment]
Throw a HostException？
ipAddress has '/' is normal

**Comment by jsdtcx** [comment]
isValidAddress(final InetAddress inetAddress)这个验证ip是否有效的方法有bug：
inetAddress.isReachable(100)，这个超时时间100太短了，我在本地测试了，我的机器只有设置成10000，才能保证是true，设置成1000都不能保证每次都是true。这就导致一直报"ip is null"

**Comment by zhaoyuguang** [comment]
Is your local computer Windows? I've come across this in other frameworks before, but 10s is definitely too long

**Comment by zhaoyuguang** [comment]
Looking at the other frames, I tend to remove `inetAddress.isReachable(100)`, what do you think @terrymanu  @Technoboy-

**Comment by jsdtcx** [comment]
> Is your local computer Windows? I've come across this in other frameworks before, but 10s is definitely too long

windows

**Comment by Technoboy-** [comment]
Try to set '-Djava.net.preferIPv4Stack=true'

**Comment by jsdtcx** [comment]
> Try to set '-Djava.net.preferIPv4Stack=true'

ok,i will try again

**Comment by jwolf123456** [comment]
> Try to set '-Djava.net.preferIPv4Stack=true'

i tried, but useless

**Comment by jwolf123456** [comment]
@jsdtcx   in linux system,'java -jar xx.jar' works well,but in win7 system,it always throws  exception——'ip is null'

**Comment by jsdtcx** [comment]
> @jsdtcx in linux system,'java -jar xx.jar' works well,but in win7 system,it always throws exception——'ip is null'



> > Try to set '-Djava.net.preferIPv4Stack=true'
> 
> i tried, but useless

me too

**Comment by jsdtcx** [comment]
> @jsdtcx in linux system,'java -jar xx.jar' works well,but in win7 system,it always throws exception——'ip is null'

yes,win7 doesn't work well

**Comment by Technoboy-** [comment]
In Win7, find the eth name by ipconfig, and try to set '-Delasticjob.preferred.network.interface=XXX' to test if this can help to speed up.

**Comment by Technoboy-** [comment]
Hi, could you give some feedback about whether this issue resolved or not ? @jwolf123456

**Comment by Technoboy-** [comment]
> In Win7, find the eth name by ipconfig, and try to set '-Delasticjob.preferred.network.interface=XXX' to test if this can help to speed up.

@jsdtcx Can you give some feedback ?

**Comment by Technoboy-** [comment]
Close this issue due to no feedback.

**Comment by hebeichegu** [comment]
Win7 doesnt work. Bug is still there. Is the fix on the plan？
