### ISSUE TITLE
IpUtils有bug

### ISSUE THREAD

**Issue by jsdtcx** [apache/shardingsphere-elasticjob#1366]
isValidAddress(final InetAddress inetAddress)这个验证ip是否有效的方法有bug：
inetAddress.isReachable(100)，这个超时时间100太短了，我在本地测试了，我的机器只有设置成10000，才能保证是true，设置成1000都不能保证每次都是true。这就导致一直报"ip is null"

**Comment by jsdtcx** [comment]
一般设置成2000就可以了，我这边1000以下都是不行的，这个应该是每台机器的情况不一样

**Comment by jwolf123456** [comment]
> 一般设置成2000就可以了，我这边1000以下都是不行的，这个应该是每台机器的情况不一样

100这个超时参数不能配置，你是怎么设置的呢

**Comment by jsdtcx** [comment]
> > 一般设置成2000就可以了，我这边1000以下都是不行的，这个应该是每台机器的情况不一样
> 
> 100这个超时参数不能配置，你是怎么设置的呢

拿源码测试的

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by jsdtcx** [comment]
> **For English only**, other languages will not accept.

呦西，原谅我英语太差，普通话比较适合我
