### ISSUE TITLE
使用AverageAllocationJobShardingStrategy分片策略，每个节点都执行所有分片

### ISSUE THREAD

**Issue by menggudaoke** [apache/shardingsphere-elasticjob#1368]
总分片数为3，无论集群节点扩容到几个，每个节点都执行了所有分片。
我使用了SimpleJob，共3个分片，数据库中共有9条记录，每个分片的执行条件为如果 数据记录id % totalShardingCount == shardingItem，则该分片执行该记录对应的任务，分片与其执行的记录对应关系本身没有错，但集群中每个节点都执行了0 1 2这三个分片，我感觉好像集群中的节点并无感知其他节点的存在，因此导致每个节点都执行了所有的分片。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by menggudaoke** [comment]
Oh, I know the reason. Thanks.
I know why, because I've set the JobName on each node to be different, causing each node to think it's running a Job with a different name, so it can't load balance.
我知道原因了，原因是我把每个节点上的JobName都设置成不同的了，导致每个节点认为自己都运行了一个不同名称的Job，所以无法负载均衡。
