### ISSUE TITLE
The pattern "yyyy-mm-dd HH:MM:SS" is correct?

### ISSUE THREAD

**Issue by JancySong** [apache/shardingsphere-elasticjob#1369]
Class org.apache.shardingsphere.elasticjob.tracing.rdb.storage.RDBJobEventStorage 
<img width="901" alt="pattern" src="https://user-images.githubusercontent.com/51478567/89979538-96245e80-dca2-11ea-996c-2d2fd339f4a5.png">

**Comment by Technoboy-** [comment]
I think this is a bug, and would you like to make a pull request for it ?
