### ISSUE TITLE
Using the quick start, the idea console prints a large number of zookeeper logs with the level of debug. How can I disable the printing of debug logs

### ISSUE THREAD

**Issue by GeomancerMrYuan** [apache/shardingsphere-elasticjob#1371]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by Technoboy-** [comment]
Set root logger level to INFO.

**Comment by GeomancerMrYuan** [comment]
> Set root logger level to INFO.
Java API is used. The log framework is not introduced into the project. I think it is the internal log of curator framework, but I don't know how to set it. Google has not found it for a long time

**Comment by terrymanu** [comment]
This issue is not ElasticJob;s scope, it is better to submit issue for the log framework, I just close it.
