### ISSUE TITLE
动态创建的任务，服务重启后不继续执行

### ISSUE THREAD

**Issue by christ258** [apache/shardingsphere-elasticjob#1373]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

当动态创建任务后，本服务重启后不继续执行，在多个不同ip的服务时，也无法获取并注册到此服务，无法继续执行。
动态创建使用如下方式：
`

public void addSimpleJob(final String jobName , final SimpleJob simpleJob, final String cron, final int shardingTotalCount,
                        final String shardingItemParameters){
        simpleJobScheduler(jobName,simpleJob,cron,shardingTotalCount,shardingItemParameters).init();
    }
private JobScheduler simpleJobScheduler(final String jobName , final SimpleJob simpleJob, final String cron, final int shardingTotalCount, final String shardingItemParameters) {
        LiteJobConfiguration liteJobConfiguration = getLiteJobConfiguration(jobName ,simpleJob.getClass(), cron, shardingTotalCount, shardingItemParameters);
        return new SpringJobScheduler(simpleJob, regCenter,liteJobConfiguration,elasticJobListener);
    }
    private LiteJobConfiguration getLiteJobConfiguration(final String jobName ,final Class<? extends SimpleJob> jobClass, final String cron, final int shardingTotalCount, final String shardingItemParameters) {
        JobCoreConfiguration jobCoreConfiguration = JobCoreConfiguration.newBuilder(
                jobName, cron, shardingTotalCount).shardingItemParameters(shardingItemParameters).build();
        JobTypeConfiguration jobTypeConfiguration = new SimpleJobConfiguration(jobCoreConfiguration, jobClass.getCanonicalName());
        return LiteJobConfiguration.newBuilder(jobTypeConfiguration).overwrite(true).build();
    }

`

**Comment by Technoboy-** [comment]
Hi, please try to describe the issue in English next time. 
From your description,  I understand your issue.
Creating job dynamically will not schedule after restarting due to not calling `init` method.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
