### ISSUE TITLE
Dynamically create tasks and zk data management issues

### ISSUE THREAD

**Issue by christ258** [apache/shardingsphere-elasticjob#1378]
If the task is created dynamically, how to synchronize to other servers? For example, there is a task A. When the execution time of a service is modified, how can the other service obtain the latest information?
Another question is how to create a lot of tasks, all of them are single tasks, millions of tasks per day, will zk data be automatically cleaned up? If not, what should I do?
version=2.1.5

**Comment by Technoboy-** [comment]
Hi, 
The task can't synchronize with other servers.
> If the task is created dynamically, how to synchronize to other servers? 

You have to pause the job first and then update the time, and resume last.
> When the execution time of a service is modified, how can the other service obtain the latest information?

You have to remove the zk data by yourself.
> will zk data be automatically cleaned up?

**Comment by christ258** [comment]
Thanks for the reply. 
If I monitor zk by myself, which path should I monitor? In order to obtain valid job information.
If I delete the invalid zk by myself, can I delete /namespace/jobName? I think there is a path called /elastic-job. What does this do?

**Comment by Technoboy-** [comment]
You should monitor the path for '${namespace}/jobName'.
> If I monitor zk by myself, which path should I monitor? In order to obtain valid job information.

This is a demo namespace for users. you can specify any.
> I think there is a path called /elastic-job. What does this do?

**Comment by christ258** [comment]
Is there a complete example of zk operation?

**Comment by Technoboy-** [comment]
> Is there a complete example of zk operation?

Sorry, no example right now.  You'd better shutdown the job by calling JobBootstrap#shutdown, and then delete ${namespace}/jobName directly.

**Comment by Technoboy-** [comment]
Try to do as the above way to test if it works. and remember to close the issue after it resolved.

**Comment by christ258** [comment]
Thank you
