### ISSUE TITLE
是否有计划支持k8s调度。

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1381]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

问题1：由于目前很多公司的资源调度系统都是通过k8s，使用mesos的较少。elasticjob有没有计划将资源调度、任务执行、任务失败重试等都借助于k8s api来完成。或者是支持yarn的调度。mesos、k8s、yarn这三种调度哪种更适合分布式调度一些

问题2：zk存在性能瓶颈，有没有计划通过其他方式来减轻或者替换掉zk

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
