### ISSUE TITLE
will elasticjob submit jobs running on k8s or yarn？ 

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1383]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

1、we know elasticjob cloud submit jobs running on mesos.in recent years, k8s is more widely used in many companies for resource management than mesos,so will elasticjob submit jobs running on k8s in the future?

2、yarn does better in big data jobs such as map reduce and support more complicated dag work flow，so will elasticjob submit jobs running on yarn in the future?

3、other plans on mitigating relying on zookeeper as zookeeper limit the performance when running large quality of jobs

**Comment by Technoboy-** [comment]
For the 1 and 2, I think they are the same features about centralized-scheduling and executing. They are big features, and welcome to join the community to discuss for more details. If you're interested, please add my id : 465553115.

RegCenter is now designed by SPI, you can support to implement others.
> other plans on mitigating relying on zookeeper as zookeeper limit the performance when running large quality of jobs

**Comment by terrymanu** [comment]
We are consider about running on k8s, no plan for yarn now.

**Comment by terrymanu** [comment]
The most important thing is not support K8S, but extract schedule module from mesos and can run independent.
Then we can consider about how to use the independent schedule module and resource assign module work together.

This is a big change, so I'd like do schedule and executor split in version 3.1.x, the version 3.0.x should focus on RESTful API and DAG.

**Comment by linghengqian** [comment]
- Follow https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 .  Affected by the Mesos upstream ecosystem, discussions have been opened to remove ElasticJob Cloud.

- This issue looks like it will no longer be relevant, or does the issue description need to be changed?

**Comment by linghengqian** [comment]
Since both ElasticJob Cloud and mesos integration modules have been removed from the master branch, close the current issue.
