### ISSUE TITLE
tracing module put event info into mysql using druid datasource report error

### ISSUE THREAD

**Issue by arick-wang** [apache/shardingsphere-elasticjob#1385]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?
3.0.0
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Expected behavior
tracingdata正常入库
### Actual behavior
数据库集成druid之后，入库时经常会出现报错的情况
when i use the alibaba druid datasource, the rdb tracing data process, would report error info all the time. 
### Reason analyze (If you can)
运行状态在update失败后会执行insert，然后如果报主键冲突会再执行update，第二部的时候就会报错。
druid拦截器拦截了报错做了日志输出。第二部执行的sql是这个JOB_EXECUTION_LOG.INSERT_COMPLETE，
是否可以考虑把这个sql后面加上
ON DUPLICATE KEY UPDATE 
is_success=values(is_success),
complete_time=values(complete_time)，使用这种方式自动更新，会不会就不再报错了。

(conside to add ON DUPLICATE KEY UPDATE 
is_success=values(is_success),
complete_time=values(complete_time) staffs to the end of the JOB_EXECUTION_LOG.INSERT_COMPLETE )
### Steps to reproduce the behavior.
use druid
### Example codes for reproduce this issue (such as a github link).
JOB_EXECUTION_LOG.INSERT_COMPLETE

**Comment by Technoboy-** [comment]
Hi, please give more details. And could you add my wechat 465553115 for discussing?

**Comment by terrymanu** [comment]
For English only, other languages will not accept.
