### ISSUE TITLE
Discuss if BlockUtils#waitingShortTime sleep too long

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob#1388]
When job need to be sharded,  other nodes(not leader) need to wait for sharding to complete.
```
    private void blockUntilShardingCompleted() {
        while (!leaderService.isLeaderUntilBlock() && (jobNodeStorage.isJobNodeExisted(ShardingNode.NECESSARY) || jobNodeStorage.isJobNodeExisted(ShardingNode.PROCESSING))) {
            log.debug("Job '{}' sleep short time until sharding completed.", jobName);
            BlockUtils.waitingShortTime();  //sleep 100ms
        }
    }
    
    private void waitingOtherShardingItemCompleted() {
        while (executionService.hasRunningItems()) {
            log.debug("Job '{}' sleep short time until other job completed.", jobName);
            BlockUtils.waitingShortTime(); //sleep 100ms
        }
    }
```
I wonder if the job is scheduled by second, it will cause at least 100ms delay. Should we change it to 30ms or other values ?

**Comment by Technoboy-** [comment]
@terrymanu

**Comment by Technoboy-** [comment]
@kezhenxu94

**Comment by kezhenxu94** [comment]
> I wonder if the job is scheduled by second, it will cause at least 100ms delay. Should we change it to 30ms or other values ?

For second-level jobs, it causes delay indeed, but for long-running jobs, shorter waiting time causes higher CPU spinning frequency, IMO, this is a tradeoff actually.

It would be ideal to have a notification mechanism between nodes

**Comment by terrymanu** [comment]
The sleep only happen in the sharding scenario, which is not trigger frequently.
Sharding only happen when job node crash or new job node online.
I cannot give the advice for 30ms or 100ms, but in the past 4 years, did we really meet something wrong with it?
If yes, we can try to adjust interval; it is better to just leave it there if nothing happen.

**Comment by Technoboy-** [comment]
> The sleep only happen in the sharding scenario, which is not trigger frequently.
> Sharding only happen when job node crash or new job node online.
> I cannot give the advice for 30ms or 100ms, but in the past 4 years, did we really meet something wrong with it?
> If yes, we can try to adjust interval; it is better to just leave it there if nothing happen.

Yes, really impacts nothing. Just want to point out if we can do a little optimization.
