### ISSUE TITLE
How to handle the resources that cause by job execute only once?

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob#1389]
Suppose we have 100 jobs that every job trigger only once like cron '0 0 0 22 8 ? 2020'.
What I mean is that it will be trigger only once sometime in the future. After that , the ejob resource retains in the memory.
How could we handle this, like shutdown the instance or cleanup the zk datas ?
If we support centralized scheduling, we can handle it easily. But could we need to support in lite or can we discuss out a good idea for this?

**Comment by terrymanu** [comment]
Even jobs run only once, we still need to keep job configs and status in ZooKeeper.
Because we can not assume that user never change the config and trigger jobs again.

**Comment by Technoboy-** [comment]
> Even jobs run only once, we still need to keep job configs and status in ZooKeeper.
> Because we can not assume that user never change the config and trigger jobs again.

Yes, but users really have the need to trigger only once, no more.
This issue is produced by #1378 . And want to discuss more about it.

**Comment by zhaoyuguang** [comment]
Whether we can support the once job at once time, To replace Cron job

like
```
.cron("0/5 * * * * ?")
```
to
```
.triggerTime(timestamp)
```

**Comment by Technoboy-** [comment]
> Whether we can support the once job at once time, To replace Cron job
> 
> like
> 
> ```
> .cron("0/5 * * * * ?")
> ```
> 
> to
> 
> ```
> .triggerTime(timestamp)
> ```

Yes，we support by OneOffJob.

**Comment by Technoboy-** [comment]
> Whether we can support the once job at once time, To replace Cron job
> 
> like
> 
> ```
> .cron("0/5 * * * * ?")
> ```
> 
> to
> 
> ```
> .triggerTime(timestamp)
> ```

Maybe I'm catching what you mean. I will try to figure out the idea.

**Comment by Technoboy-** [comment]
After discussing, we can not find out a nice idea to do it. So close this issue.
