### ISSUE TITLE
Add tasks by java api and do not init again

### ISSUE THREAD

**Issue by wdl861202** [apache/shardingsphere-elasticjob#1391]
**I met a scene that users want to add tasks by themselves.
Does the new version supports to add tasks by java api anytime after the JobScheduler init except to use JobScheduler ini again？**

## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by Technoboy-** [comment]
As discuss before, we will support this feature in the version 3.1X.

**Comment by wdl861202** [comment]
Thanks!  when does version 3.1X release?

**Comment by Technoboy-** [comment]
You can subscribe [mail list](mailto:dev@shardingsphere.apache.org) or add wechat : ss_assistant_1 to join group for news.

**Comment by wdl861202** [comment]
Thank you very much!
