### ISSUE TITLE
In Windows env, run ShardingSphere-ElasticJob-UI, could not find or load main class org.apache.shardingsphere.elasticjob.lite.ui.Bootstrap.

### ISSUE THREAD

**Issue by hunter4088** [apache/shardingsphere-elasticjob#1402]
Answer：

Some decompression tools may truncate the file name when decompressing the ShardingSphere-ElasticJob-UI binary package, resulting in some classes not being found

Open cmd.exe and execute the following command: 
```
tar zxvf apache-shardingsphere-elasticjob-${RELEASE.VERSION}-lite-ui-bin.tar.gz
```

**Comment by Technoboy-** [comment]
Hi, hunter!
Please add this to the FAQ,  be aware of for _index.cn.md and _index.en.md
https://github.com/apache/shardingsphere-elasticjob/blob/master/docs/content/faq/_index.cn.md
https://github.com/apache/shardingsphere-elasticjob/blob/master/docs/content/faq/_index.en.md

**Comment by Technoboy-** [comment]
#1403
