### ISSUE TITLE
There is a very low probability to reproduce SocketTimeoutException when executing testcase of HttpJobExecutor

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1405]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Actual behavior
```
-------------------------------------------------------------------------------
Test set: org.apache.shardingsphere.elasticjob.http.executor.HttpJobExecutorTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.723 sec <<< FAILURE! - in org.apache.shardingsphere.elasticjob.http.executor.HttpJobExecutorTest
assertProcessWithGet(org.apache.shardingsphere.elasticjob.http.executor.HttpJobExecutorTest)  Time elapsed: 7.853 sec  <<< ERROR!
org.apache.shardingsphere.elasticjob.infra.exception.JobExecutionException: java.net.SocketTimeoutException: Read timed out
	at org.apache.shardingsphere.elasticjob.http.executor.HttpJobExecutorTest.assertProcessWithGet(HttpJobExecutorTest.java:95)
Caused by: java.net.SocketTimeoutException: Read timed out
	at org.apache.shardingsphere.elasticjob.http.executor.HttpJobExecutorTest.assertProcessWithGet(HttpJobExecutorTest.java:95)
```

### Steps to reproduce the behavior.
Just run `mvn install`.

**Comment by Technoboy-** [comment]
Test url (https://github.com) may cause the read timeout.

**Comment by TeslaCN** [comment]
> Test url (https://github.com) may cause the read timeout.

So the test result is partly depended on build environment. Is there any better way?

**Comment by Technoboy-** [comment]
> > Test url (https://github.com) may cause the read timeout.
> 
> So the test result is partly depended on build environment. Is there any better way?

I think we can start an embed rest server(as you have done rest module) and request the internal api.
We can do this after branch rest-api merged to master.  Do you agree ?

**Comment by TeslaCN** [comment]
> > > Test url (https://github.com) may cause the read timeout.
> > 
> > 
> > So the test result is partly depended on build environment. Is there any better way?
> 
> I think we can start an embed rest server(as you have done rest module) and request the internal api.
> We can do this after branch rest-api merged to master. Do you agree ?

That's a good idea.

**Comment by terrymanu** [comment]
How about start a embed web server (tomcat) for test URL?

**Comment by terrymanu** [comment]
> > > > Test url (https://github.com) may cause the read timeout.
> > > 
> > > 
> > > So the test result is partly depended on build environment. Is there any better way?
> > 
> > 
> > I think we can start an embed rest server(as you have done rest module) and request the internal api.
> > We can do this after branch rest-api merged to master. Do you agree ?
> 
> That's a good idea.

I prefer this way too
