### ISSUE TITLE
What should I do if I want to upgrade zookeeper to 3.6.x in version 2.1.5

### ISSUE THREAD

**Issue by KerwinAusten** [apache/shardingsphere-elasticjob#1418]
Hello, I have observed that the new 3.0.0-alpha upgrade the zookeeper version. Now we use 2.1.5 in production, and we also want to upgrade the zookeeper version.
The 3.0.0-alpha related issues are so many, I can't find what you did when upgrade the zookeeper version.
So cound you tell me is there any other changes when upgrade the zookeeper version?

**Comment by Technoboy-** [comment]
Really we do much more refactors and fix known issues in 3.0.0-alpha. But it will not impact upgrading zookeeper version as we just update curator indeed. 
Zookeeper is being a registry center in elastic-job, storage structure or api are not changed.

**Comment by KerwinAusten** [comment]
> Really we do much more refactors and fix known issues in 3.0.0-alpha. But it will not impact upgrading zookeeper version as we just update curator indeed.
> Zookeeper is being a registry center in elastic-job, storage structure or api are not changed.

OK.Emmm...Is there complete test for zk upgrade? After all, elastic-job used many curator listeners. Maybe the listener's mechanism changed between 3.4.x and 3.6.x

**Comment by Technoboy-** [comment]
> > Really we do much more refactors and fix known issues in 3.0.0-alpha. But it will not impact upgrading zookeeper version as we just update curator indeed.
> > Zookeeper is being a registry center in elastic-job, storage structure or api are not changed.
> 
> OK.Emmm...Is there complete test for zk upgrade? After all, elastic-job used many curator listeners. Maybe the listener's mechanism changed between 3.4.x and 3.6.x

We do some updates about listeners and test as We think it could release. But maybe still have bugs. We are welcome any volunteer to help us improve.

**Comment by terrymanu** [comment]
The version 2.x is out of service
