### ISSUE TITLE
The property Content-Type of HTTP job only works with x-www-form-urlencode

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1422]
https://github.com/apache/shardingsphere-elasticjob/blob/a8573f5beb089d8061ed5154659078893f6517b8/elasticjob-executor/elasticjob-executor-type/elasticjob-http-executor/src/main/java/org/apache/shardingsphere/elasticjob/http/executor/HttpJobExecutor.java#L64-L69

I have some ideas:
1. The shardingContext is been serialized as key-value format. It is incompatiable with request body in JSON format.
What's more, I think the scenarios of HTTP job is biased to Restful API. 
2. Why doesn't pass the sharding context if the data is empty? Maybe we can attach sharding context to query when using GET method.

**Comment by Technoboy-** [comment]
Yes, really. We just support the basic type and method right now. 
We can refactor this component by HttpClient.

**Comment by Technoboy-** [comment]
We can set shardingContext as a Header key, so that we can resolve this issue easily and no need to refactor by HttpClient.
