### ISSUE TITLE
OneOffJobBootstrap doesn't support parameters

### ISSUE THREAD

**Issue by specYyt** [apache/shardingsphere-elasticjob#1430]
Hello!

I think OneOffJob is different with SimpleJob or FlowJob.

SimpleJob focus on loop but oneoffjob focus on dispatch. So oneOffJob should have parameters.

![Snipaste_2020-08-31_12-00-54](https://user-images.githubusercontent.com/30110741/91681658-b0ef4200-eb81-11ea-9c6c-7aec5ce66b0d.png)

 Looking forward to your reply!

**Comment by Technoboy-** [comment]
Yes, we are aware of this issue. We will support it soon. 
Please add ( ss_assistant_1) to join our wechat group .

**Comment by huran111** [comment]
What is the current stable version？

**Comment by TeslaCN** [comment]
In my opinion, OneOffJob is a type of Bootstrap and SimpleJob or FlowJob are types of ElasticJob, they are different concepts. Parameters can be provided by JobConfiguration and distinguish by ShardingContext. Just create a custom implementation of JobItemExecutor and you can get JobConfiguration and ShardingContext. There is no need to change the API of OneOffJobBootstrap.
What do you think? @Technoboy- @specYyt

**Comment by Technoboy-** [comment]
> In my opinion, OneOffJob is a type of Bootstrap and SimpleJob or FlowJob are types of ElasticJob, they are different concepts. Parameters can be provided by JobConfiguration and distinguish by ShardingContext. Just create a custom implementation of JobItemExecutor and you can get JobConfiguration and ShardingContext. There is no need to change the API of OneOffJobBootstrap.
> What do you think? @Technoboy- @specYyt

Yes, keep the current api, and will support parameters in JobConfiguration.

**Comment by Technoboy-** [comment]
> What is the current stable version？

Master branch is more preferred. No unresolved bugs.  We are talking about the extension of OneOffJob.

**Comment by huran111** [comment]
according to OCP ， Yes,keep the current api




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tboy"<notifications@github.com&gt;; 
发送时间: 2020年9月2日(星期三) 上午10:19
收件人: "apache/shardingsphere-elasticjob"<shardingsphere-elasticjob@noreply.github.com&gt;; 
抄送: "努力努力❌努力"<1345122890@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [apache/shardingsphere-elasticjob] OneOffJobBootstrap doesn&#39;t support parameters (#1430)





  
In my opinion, OneOffJob is a type of Bootstrap and SimpleJob or FlowJob are types of ElasticJob, they are different concepts. Parameters can be provided by JobConfiguration and distinguish by ShardingContext. Just create a custom implementation of JobItemExecutor and you can get JobConfiguration and ShardingContext. There is no need to change the API of OneOffJobBootstrap.
 What do you think? @Technoboy- @specYyt
  
Yes, keep the current api, and will support parameters in JobConfiguration.

**Comment by Technoboy-** [comment]
After talking about the details, we think it's not a common scenario, and will not support recently.  Thanks for your reporting.
