### ISSUE TITLE
There was an error using the HTTP job demo. The exception message was of HTTP type and could not be found

### ISSUE THREAD

**Issue by lsiuf** [apache/shardingsphere-elasticjob#1436]
## Question

![微信截图_20200904151817](https://user-images.githubusercontent.com/44636496/92210953-3fd1c680-eec2-11ea-9184-411dc78c0586.png)

![微信图片_20200904151758](https://user-images.githubusercontent.com/44636496/92210888-229cf800-eec2-11ea-8f44-6f9d5a75fc86.png)

![微信截图_20200904151920](https://user-images.githubusercontent.com/44636496/92210918-30527d80-eec2-11ea-94b5-97c7378beaaf.png)

**Comment by TeslaCN** [comment]
The HTTP is a feature in 3.0.0-beta, which has not been released yet.

**Comment by lsiuf** [comment]
> The HTTP is a feature in 3.0.0-beta, which has not been released yet.

![image](https://user-images.githubusercontent.com/44636496/92212212-377a8b00-eec4-11ea-8e5f-f667a5a561d7.png)

The 3.0.0-alpha version is used. I just found that the contents of the Chinese and English versions are inconsistent in the official documents, which leads to this problem. Thank you for your reply

**Comment by Technoboy-** [comment]
> > The HTTP is a feature in 3.0.0-beta, which has not been released yet.
> 
> ![image](https://user-images.githubusercontent.com/44636496/92212212-377a8b00-eec4-11ea-8e5f-f667a5a561d7.png)
> 
> The 3.0.0-alpha version is used. I just found that the contents of the Chinese and English versions are inconsistent in the official documents, which leads to this problem. Thank you for your reply

Are you interested in taking a pull request to sync the document?

**Comment by Technoboy-** [comment]
@TeslaCN Does the newest document keep the same ?

**Comment by lsiuf** [comment]
> > > The HTTP is a feature in 3.0.0-beta, which has not been released yet.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/44636496/92212212-377a8b00-eec4-11ea-8e5f-f667a5a561d7.png)
> > The 3.0.0-alpha version is used. I just found that the contents of the Chinese and English versions are inconsistent in the official documents, which leads to this problem. Thank you for your reply
> 
> Are you interested in taking a pull request to sync the document?

I think so, thanks

**Comment by TeslaCN** [comment]
It is better to update the documents to clarify the HTTP job is a feature in 3.0.0-beta.
