### ISSUE TITLE
Version 2.1.5 and version 3.0.0 share the same ZooKeeper

### ISSUE THREAD

**Issue by lsiuf** [apache/shardingsphere-elasticjob#1444]
## Question

The company already has a elasticJob use scheme based on version 2.1.5. There is a elasticJob annotation and a Wrapper around Spring Boot Starst.The original code business and code are too tangled to maintain. Consider building a new version 3.0.0 elasticJob use service. Two services can be used at the same time, but there are requirements for two elasticJob versions corresponding to ZooKeeper？

**Comment by Technoboy-** [comment]
Ejob 3.X needs zookeeper 3.6 or higher.

**Comment by Technoboy-** [comment]
Would you like to join the community and contribute the annotation feature ?

**Comment by lsiuf** [comment]
> Ejob 3.X needs zookeeper 3.6 or higher.
If ejob 2.1.5 use zookeeper 3.6 or higher

**Comment by lsiuf** [comment]
> Ejob 3.X needs zookeeper 3.6 or higher.

If ejob 2.1.5 use zookeeper 3.6 or higher

**Comment by lsiuf** [comment]
> Would you like to join the community and contribute the annotation feature ?

It's my pleasure ! But Since I'm not particularly good at coding, I can try to contribute some simple features.

**Comment by Technoboy-** [comment]
> > Ejob 3.X needs zookeeper 3.6 or higher.
> 
> If ejob 2.1.5 use zookeeper 3.6 or higher

This may lead to some unknown problems.

**Comment by lsiuf** [comment]
> > > Ejob 3.X needs zookeeper 3.6 or higher.
> > 
> > 
> > If ejob 2.1.5 use zookeeper 3.6 or higher
> 
> This may lead to some unknown problems.

thank you for the response
