### ISSUE TITLE
how  to shutdown

### ISSUE THREAD

**Issue by jr981008** [apache/shardingsphere-elasticjob#1447]
Some stateful tasks cannot be retried on any node. During the module upgrade, the node needs to be removed and then added to the cluster again. How can I enable the node to wait for the completion of the current task and no longer accept new fragments when it learns that the node is to be removed?

**Comment by Technoboy-** [comment]
Try to disable `failover` before instance down.

**Comment by jr981008** [comment]
Remove the node, do not affect other tasks in the cluster, do not accept new task scheduling, complete the currently executing task, safeshudown, to avoid the failover of the current task

**Comment by Technoboy-** [comment]
> Remove the node, do not affect other tasks in the cluster, do not accept new task scheduling, complete the currently executing task, safeshudown, to avoid the failover of the current task

Could you add my WeChat id (465553115) to discuss ？

**Comment by terrymanu** [comment]
Closed because of no response anymore
