### ISSUE TITLE
为什么3.0  ScheduleJobBootstrap 构造器官网文档上的参数和实际对不上

### ISSUE THREAD

**Issue by Mranxiaoranran** [apache/shardingsphere-elasticjob#1448]
您好，

 构造ScheduleJobBootstrap放置监听器的参数在官网是3个，实际是4个，多了一个elasticJobType,应该传什么值，不管传什么就报错

**Comment by Technoboy-** [comment]
Could you change the issue description in English?

**Comment by Technoboy-** [comment]
Close due to English only.
