### ISSUE TITLE
shardingsphere-elasticjob  3.0.0-beta-SNAPSHOT - example startup error

### ISSUE THREAD

**Issue by averyzhujinbo** [apache/shardingsphere-elasticjob#1449]
zookeeper 版本 3.6.0
zookeeper 可视化客户端(zookeeper-dev-ZooInspector.jar)连接远程zookeeper 测试正常 

直接运行 examples - >elasticjob-example-lite-springboot 应用报错：

[INFO ] 2020-09-10 17:55:42,896 --main-- [org.apache.shardingsphere.elasticjob.lite.internal.snapshot.SnapshotService] Elastic job: Snapshot service is running, the port is '9999' 
[WARN ] 2020-09-10 17:55:43,306 --main-SendThread(192.168.1.156:2181)-- [org.apache.zookeeper.ClientCnxn] Session 0x10000045fc90020 for sever 192.168.1.156/192.168.1.156:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. 
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x10000045fc90020, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75) ~[zookeeper-3.6.0.jar:3.6.0]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348) ~[zookeeper-3.6.0.jar:3.6.0]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262) ~[zookeeper-3.6.0.jar:3.6.0]
[ERROR] 2020-09-10 17:55:43,306 --main-- [org.apache.curator.framework.imps.CuratorFrameworkImpl] Ensure path threw exception 
org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /elasticjob-example-lite-spring

**Comment by Technoboy-** [comment]
what is the port of 3.6.0?

**Comment by averyzhujinbo** [comment]
> what is the port of 3.6.0?


zookeeper3.6.0  配置文件：
clientPort: 2181
=======================

tickTime=20000
initLimit=100
syncLimit=50
dataDir=/usr/local/apache-zookeeper-3.6.0/data
dataLogDir=/usr/local/apache-zookeeper-3.6.0/datalogs
clientPort=2181

**Comment by Technoboy-** [comment]
Examples use the embed zk and the port is 5181 in spring , 6181 in spring-boot. 

>  直接运行 examples - >elasticjob-example-lite-springboot 应用报错：

Spring-boot will use namespace  -> elasticjob-lite-springboot.  but your stack trace log is -> elasticjob-example-lite-spring

**Comment by Technoboy-** [comment]
Close due to issue not match the description.

**Comment by zlshi** [comment]
set base-sleep-time-milliseconds max-sleep-time-milliseconds max-retries vaue bigger can solve my problem
