### ISSUE TITLE
Occasionally the application fails to start

### ISSUE THREAD

**Issue by youngszy2015** [apache/shardingsphere-elasticjob#1452]
## Question
From the startup log，main thread create job, then Curator-TreeCache-0 thread shutdown the job. Not often encounter this problem,But I have encountered it several times in production deployment.

elastic-job-lite version:2.1.5
elastic-job-lite-spring version:2.1.5
curator-framework version:2.12.0

Application log:
![shutdown2](https://user-images.githubusercontent.com/59565957/93040013-99cd4b80-f67b-11ea-99c6-3222393b74c7.png)

**Comment by Technoboy-** [comment]
Hi @youngszy2015, you are using an older version that not maintained anymore, could you upgrade to the newest version and try our new features?

**Comment by Technoboy-** [comment]
Any questions, please join the wechat group (ss_assistant_1).
Close due to not any more feedback.
