### ISSUE TITLE
Add jobs dynamically by API, the jobs offline and non-execution  when application restart.    elastic-job-lite  version:2.1.5

### ISSUE THREAD

**Issue by Fengxu1234** [apache/shardingsphere-elasticjob#1466]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by Technoboy-** [comment]
Yes. As restart, ejob will not schedule the jobs created dynamically. we will support this in cloud at version 3.1.x.
Welcome to join the wechat group , contact for help : ss_assistant_1

**Comment by kristiWan** [comment]
You can notify the job status by refreshing the zk node to support dynamic tasks

**Comment by lovepoem** [comment]
https://github.com/apache/shardingsphere-elasticjob/issues/1435
