### ISSUE TITLE
why use spring-boot-parent as a dependency for every module ?

### ISSUE THREAD

**Issue by qhsword** [apache/shardingsphere-elasticjob#1477]
in the inner network of company, there a maven nexus server,  some jars  are exists, but not all。

when use 3.0.0.M1-snapshot ， elastic-job can work, but when upgrade it to 3.0.0-alpha , will not work.

the reason is the spring-boot-parent  was be imported as a pom dependency mandatory

**Comment by Technoboy-** [comment]
> the reason is the spring-boot-parent was be imported as a pom dependency mandatory

What do you mean?  spring-boot-parent is dependencyManagement, not dependency

**Comment by qhsword** [comment]
yes, spring-boot-parent is dependencyManagement，you are right.

However, when building, maven will load all dependency's pom.xml what was declared in spring-boot-parent pom.xml.

in our internal network,  not all dependecies are exists in the nexus server，so the build action will fail

**Comment by Technoboy-** [comment]
> in our internal network, not all dependecies are exists in the nexus server，so the build action will fail

In actual, when depedencies do not exist in internal server, it will request the outside maven repo.

**Comment by Technoboy-** [comment]
And please check if #1483 can match your idea.

**Comment by TeslaCN** [comment]
Once #1483 been merged. You can exclude module 'elasticjob-lite-spring' temporarily to build other module.

**Comment by Technoboy-** [comment]
Please reference #1483, thanks for your kindly feedback.  Welcome to join the wechat group (ss_assistant_1).

**Comment by qhsword** [comment]
@Technoboy-   notice:   in the internal network of our company

**Comment by qhsword** [comment]
#1483 is fine
