### ISSUE TITLE
Update for dingtalk module

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob#1485]
- [ ] Use yaml instead of Properties. Name the elasticjob-dingtalk.properties to error-handler-dingtalk.yaml
- [ ] Update the test case relatively.
- [ ] Update the relative doc.
- [ ] Update pom.xml in dingtalk, use ${project.version} instead of 3.0.0-beta-SNAPSHOT

**Comment by gzdzss** [comment]
assigne to me .
