### ISSUE TITLE
When using esJob service to run, add a job through the interface

### ISSUE THREAD

**Issue by lsiuf** [apache/shardingsphere-elasticjob#1492]
## Question

In the process of using esJob, I need to use the business scenario of adding jobs dynamically. Can this function be implemented?

In addition, I found some extension functions of adding jobs dynamically on the Internet. The general principle is to initialize a job class that has been implemented in business code, and then add it to relevant configuration and context through ZK and Spring. Is there any risk in doing so?

[https://github.com/yinjihuan/elastic-job-spring-boot-starter](https://github.com/yinjihuan/elastic-job-spring-boot-starter)
This is esJob2.1.0 Spring Boot Starter, which I already use in my old project, and includes a function to dynamically add jobs.In my daily use, I find that dynamically added jobs sometimes fail, but job-related configurations are registered with ZK, and in fact jobs do not take effect

**Comment by Technoboy-** [comment]
Please refer to the same issue with #1466 .
