### ISSUE TITLE
Confusing exception information when  construct `JobScheduler`

### ISSUE THREAD

**Issue by vran-dev** [apache/shardingsphere-elasticjob#1496]
If  param  `elasticJob` is null, the following `JobScheduler` contructor will throw **JobConfigurationException:  Can not find executor for elastic job type `null`**

```java
// at line 78
public JobScheduler(final CoordinatorRegistryCenter regCenter,
                    final ElasticJob elasticJob,
                    final JobConfiguration jobConfig,
                    final TracingConfiguration<?> tracingConfig,
                    final ElasticJobListener... elasticJobListeners)
```

this constructor don't care param `String elasticJobType`, so the error message  make user confusing. 

It's caused by the following code segment

```java
// at line 78
public JobScheduler(...) {
    // in this constructor,  elasticJobType is always null
    elasticJobType = null; // at line 82
    // elasticJob is null, will call `ElasticJobExecutor` constructor, then throw JobConfigurationException
    jobExecutor = null == elasticJob ? new ElasticJobExecutor(elasticJobType, jobConfig, jobFacade) : new ElasticJobExecutor(elasticJob, jobConfig, jobFacade); // at line 87
}
```

so, i think

- should do Pre-check for param `elasticJob`
- give more clearly error message

could i improve it ?

**Comment by Technoboy-** [comment]
Yes. but this has been updated by #1476 . please check.
Btw, welcome to do any improvement.

**Comment by vran-dev** [comment]
> Yes. but this has been updated by #1476 . please check.
> Btw, welcome to do any improvement.

I checked the latest changes, the problem still exists.

please assign to me, i will try to improve it

**Comment by terrymanu** [comment]
Invalid, I put the reason to the pr
