### ISSUE TITLE
When will a stable release be released

### ISSUE THREAD

**Issue by zhangpengtent** [apache/shardingsphere-elasticjob#1497]
Hello,

From the github i see the lastest version is 3.0.0-alpha, can i know when will a stable release be released.

BR,
Thanks

**Comment by Technoboy-** [comment]
We are going to release 3.0.0-beta.  The stable version may release after Oct

**Comment by zhangpengtent** [comment]
many thanks, does  shardingsphere-elasticjob-ui  will  have the same version  to adapt elasticjob.
