### ISSUE TITLE
Use SPI to initialize JobErrorHandler in test cases

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1515]
- [ ] IgnoreJobErrorHandlerTest
- [ ] LogJobErrorHandlerTest
- [ ] ThrowJobErrorHandlerTest
- [ ] EmailJobErrorHandlerTest
- [ ] WechatJobErrorHandler
- [ ] DingtalkJobErrorHandlerTest

**Comment by jiang2015** [comment]
please assign to me！
