### ISSUE TITLE
Use java properties to config error handler's configuration

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1516]
We are using YAML file to config the error handler's configuration which is not keep consist with original elasticjob config.
It is better to use java configuration only. YAML just one of way to `core config`.

- [ ] error-handler-email.yaml
- [ ] error-handler-wechat.yaml
- [ ] error-handler-dingtalk.yaml

**Comment by gzdzss** [comment]
assigne to me.
