### ISSUE TITLE
Testcase always failed in travis ci machine

### ISSUE THREAD

**Issue by lovepoem** [apache/shardingsphere-elasticjob#1534]
### Which version of ElasticJob did you use?
<version>3.0.0-beta-SNAPSHOT</version>

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
elasticjob-lite

### Expected behavior
The result of testcases  are success 

### Actual behavior
Faild in  shardingsphere-elasticjob/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-namespace
![image](https://user-images.githubusercontent.com/827112/94819072-69cec800-0431-11eb-8dfd-358f3b933f42.png)

https://travis-ci.org/github/apache/shardingsphere-elasticjob/builds/731935366

In my pc , it occurred once :
![image](https://user-images.githubusercontent.com/827112/94819266-a26ea180-0431-11eb-9176-d26fafa0b46d.png)
![image](https://user-images.githubusercontent.com/827112/94819281-a6022880-0431-11eb-80c1-86fa99319d77.png)
![image](https://user-images.githubusercontent.com/827112/94819295-aac6dc80-0431-11eb-8090-74f22ed9e0fe.png)

### Reason analyze (If you can)

When a  case failed ,  3181 port  that  `EmbedTestingServer` used is not closed . So other cases should wait for 30s , then the whole testcases will fail after  30 minutes

**Comment by jiang2015** [comment]
assign to me

**Comment by jiang2015** [comment]
this problem is not happend local.

**Comment by lovepoem** [comment]
It seems ok now
