### ISSUE TITLE
SPI may be inconsistent between nodes if job configuration changed

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1544]
### Which version of ElasticJob did you use?
3.0.0-alpha
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Reason analyze (If you can)
There is no listener is listening change of jobErrorHandlerType.

**Not only JobErrorHandler, the following interfaces also have this problem:**
- JobExecutorServiceHandler
- ElasticJobListener

### Steps to reproduce the behavior.
1. Start a new process and schedule job 'simple' with job error handler type 'foo'.
2. Start another new process and schedule job 'simple' with job error handler type 'bar'.

### Example codes for reproduce this issue (such as a github link).

Schedule 'simple' job with 'foo' error handler.
```java
        new ScheduleJobBootstrap(REGISTRY_CENTER, new ErrorSimpleJob(),
                JobConfiguration.newBuilder("simple", 3)
                        .cron("0/5 * * * * ?")
                        .shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou")
                        .jobErrorHandlerType("foo")
                        .overwrite(true)
                        .build(),
                TRACING_CONFIGURATION)
                .schedule();
```

Schedule 'simple' job with 'bar' error handler.
```java
        new ScheduleJobBootstrap(REGISTRY_CENTER, new ErrorSimpleJob(),
                JobConfiguration.newBuilder("simple", 3)
                        .cron("0/5 * * * * ?")
                        .shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou")
                        .jobErrorHandlerType("bar")
                        .overwrite(true)
                        .build(),
                TRACING_CONFIGURATION)
                .schedule();
```

### Expected behavior
All instances of 'simple' job use same error handler.
### Actual behavior
Node A using 'foo' error handler while Node B using 'bar' handler.

**Comment by TeslaCN** [comment]
I have tried enhancing JobRegistry and refactor ElasticJobExecutor to resolve this problem, but I found that ElasticJobExecutor is used by both Lite and Cloud. The enhancement of JobRegistry is for Lite only.

My second idea is introducing a concept 'reload'. We already have the operation 'resharding'. Can we introduce an operation named 'reload' to reload the job?

**Comment by terrymanu** [comment]
The first way may better. 
Reload should be automatic when reg center's data changed.
