### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/shardingsphere-elasticjob#1555]
https://github.com/apache/shardingsphere-elasticjob/blob/2e181cb8a48afecbde7f38df6448d3d247836c0c/elasticjob-error-handler/elasticjob-error-handler-type/elasticjob-error-handler-dingtalk/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/DingtalkJobErrorHandler.java#L75

The program can potentially fail to release a system resource.

**Comment by Technoboy-** [comment]
Thanks for your report.

**Comment by Technoboy-** [comment]
This issue will be fixed after merging #1550 .

**Comment by Technoboy-** [comment]
Close due to merging #1550 .
