### ISSUE TITLE
How to configure that the last task has not been executed, and the next task will be postponed,

### ISSUE THREAD

**Issue by lxyyouxiang123** [apache/shardingsphere-elasticjob#1560]
## Question

How to configure that the last task has not been executed, and the next task will be postponed,

**Comment by Technoboy-** [comment]
Elasticjob is based on quartz, so please refer to [Misfire Instructions](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-04.html). and config for elasticjob is here :
https://github.com/apache/shardingsphere-elasticjob/blob/master/elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/schedule/JobScheduleController.java#92
