### ISSUE TITLE
Finish document for job error handler

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1581]
Please add more document for job error handler both English and Chinese:

The documents are in https://github.com/apache/shardingsphere/tree/master/docs/document/content/user-manual/elasticjob-lite/configuration/built-in-strategy/sharding.en.md and https://github.com/apache/shardingsphere/tree/master/docs/document/content/user-manual/elasticjob-lite/configuration/built-in-strategy/sharding.cn.md

Please add: 

- [x] Fill config for job error handler send message via Email
- [x] Fill config for job error handler send message via Dingtalk
- [x] Fill config for job error handler send message via Wechat

**Comment by wwj-go** [comment]
Please assign it to me, I think the file should be `error-handler.cn.md` instead of  `sharding.cn.md` , am I right?
