### ISSUE TITLE
Add builder to create ErrorHandlerConfiguration to permit default value

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1599]
Reference: `JobConfiguration.Builder`

- [x] Add builder to EmailConfiguration
- [x] Add builder to WechatConfiguration
- [x] Add builder to DingtalkConfiguration

Please check todo to confirm default value. Please add test cases as well.

**Comment by ZHZstruggle** [comment]
assgin to me
