### ISSUE TITLE
Add test cases for JobPropertiesValidator

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1648]
- [x] Add test cases for JobPropertiesValidateRule
- [x] Add test cases for EmailJobErrorHandlerPropertiesValidator
- [x] Add test cases for WechatJobErrorHandlerPropertiesValidator
- [x] Add test cases for DingtalkJobErrorHandlerPropertiesValidator

**Comment by gzdzss** [comment]
I want to do
