### ISSUE TITLE
JobSpringNamespaceWithTypeTest#jobScriptWithJobTypeTest runs failure

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob#1661]
Ref : https://travis-ci.org/github/apache/shardingsphere-elasticjob/builds/738899935

**Comment by TeslaCN** [comment]
TrivisCI is still so slow even if the directory ".m2" is cached. My local environments with directory ".m2" cached only takes 2 minutes to execute `mvn install`.

**Comment by Technoboy-** [comment]
Fixed by #1663 .
