### ISSUE TITLE
 implements SimpleJob   0 0/5 * * * ?

### ISSUE THREAD

**Issue by damogui** [apache/shardingsphere-elasticjob#1664]
0 0/5* * * ?  
It is executed every 5 minutes. After a period of time, it will not be executed. There is no error log. The third-party interface will be called internally

rely on：
 <dependency>
            <groupId>com.dangdang</groupId>
            <artifactId>elastic-job-lite-core</artifactId>
            <version>2.1.5</version>
            <exclusions>
                <exclusion>
                    <artifactId>org.apache.curator</artifactId>
                    <groupId>curator-framework</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>org.apache.curator</artifactId>
                    <groupId>curator-recipes</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.dangdang</groupId>
            <artifactId>elastic-job-lite-spring</artifactId>
            <version>2.1.5</version>
        </dependency>

**Comment by wwj-go** [comment]
Sorry, it is difficult for me to locate and solve your problem based on your description information，can you  try the latest version? 
https://github.com/apache/shardingsphere-elasticjob/releases

**Comment by damogui** [comment]
Thank you very much for your reply. It is the problem on my side. The production and testing zookeeper are not isolated. I will close this bug. Thank you

**Comment by damogui** [comment]
Thank you very much for your reply. It is the problem on my side. The production and testing zookeeper are not isolated. I will close this bug. Thank you
