### ISSUE TITLE
TimeZone support?

### ISSUE THREAD

**Issue by hzy1992** [apache/shardingsphere-elasticjob#1688]
How to support the time zone function? If i don't use the time zone for daylight saving time and Eastern time, it will be very difficult to handle.

**Comment by terrymanu** [comment]
We need to develop this feature, do you interest to develop it?

**Comment by johnny2002** [comment]
What is the detail requirement, I may contribute on it

**Comment by johnny2002** [comment]
If you just want to specify the timezone, does jvm parameter "--Duser.timezone=GMT+08" work for you？

**Comment by hzy1992** [comment]
> If you just want to specify the timezone, does jvm parameter "--Duser.timezone=GMT+08" work for you？

I want to set the job's timezone when i creating it

**Comment by johnny2002** [comment]
> > If you just want to specify the timezone, does jvm parameter "--Duser.timezone=GMT+08" work for you？
> 
> I want to set the job's timezone when i creating it
Then you may try to add a timezone parameter when starting up the job app like "-Duser.timezone=Asia/Shanghai"
