### ISSUE TITLE
获取当前节点的所有分片

### ISSUE THREAD

**Issue by 06112497liu** [apache/shardingsphere-elasticjob#1691]
有没有提供获取当前节点的所有分片的方法呢？我需要一次性拿到所有分片

**Comment by gzdzss** [comment]
See:
[org.apache.shardingsphere.elasticjob.api.JobConfiguration](https://github.com/apache/shardingsphere-elasticjob/blob/master/elasticjob-api/src/main/java/org/apache/shardingsphere/elasticjob/api/JobConfiguration.java)
- shardingItemParameters
- jobParameter

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
