### ISSUE TITLE
Consider whether to provide one Spring Boot starter

### ISSUE THREAD

**Issue by ruoshuixuelabi** [apache/shardingsphere-elasticjob#1695]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by gzdzss** [comment]
Click [HERE](https://github.com/apache/shardingsphere-elasticjob/tree/master/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter) to find out more!


```xml
<dependency>
    <groupId>org.apache.shardingsphere.elasticjob</groupId>
    <artifactId>elasticjob-lite-spring-boot-starter</artifactId>
    <version>${latest.version}</version>
</dependency>
```

**Comment by ruoshuixuelabi** [comment]
十分感谢，是我自己没仔细看内部的结构，现在没问题了，我去测试测试，以前用过可惜后来天就不维护就去用xxl-job了，感谢开源如此好的项目，现在重新调研。打算改造架构以及新项目用它了
