### ISSUE TITLE
A required class was missing while executing org.apache.maven.plugins:maven-enforc er-plugin:1.4:enforce: org/apache/maven/enforcer/rule/api/EnforcerRuleException

### ISSUE THREAD

**Issue by aibowen** [apache/shardingsphere-elasticjob#1697]
when i compiled the whole project, i got the following error
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (enforce-maven-version) on project elasticjob: Execution enforce-maven-ve
rsion of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce failed: A required class was missing while executing org.apache.maven.plugins:maven-enforc
er-plugin:1.4:enforce: org/apache/maven/enforcer/rule/api/EnforcerRuleException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-enforcer-plugin:1.4
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/apache-maven/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4/maven-enforcer-plugin-1.4.jar
[ERROR] urls[1] = file:/D:/apache-maven/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```

**Comment by TeslaCN** [comment]
I cannot reproduce this problem in my environment. Consider clearing your local maven repository.

**Comment by aibowen** [comment]
I found that this class came from enforcer-api.jar, Is it included after your project is successfully built.

**Comment by TeslaCN** [comment]
> I found that this class came from enforcer-api.jar, Is it included after your project is successfully built.

"enforcer-api.jar" is in my local repository.

**Comment by TeslaCN** [comment]
Hello @aibowen,
Have you solved your problem?

**Comment by aibowen** [comment]
It has not been resolved. I cannot upload to the private warehouse after executing the packaging command.
----- 原始邮件 -----
发件人：吴伟杰 <notifications@github.com>
收件人：apache/shardingsphere-elasticjob <shardingsphere-elasticjob@noreply.github.com>
抄送人：aibowen <bowen_job@sina.com>,  Mention <mention@noreply.github.com>
主题：Re: [apache/shardingsphere-elasticjob] A required class was missing while executing org.apache.maven.plugins:maven-enforc er-plugin:1.4:enforce: org/apache/maven/enforcer/rule/api/EnforcerRuleException (#1697)
日期：2020年12月01日 23点37分


Hello @aibowen,

Have you solved your problem?

&mdash;

**Comment by TeslaCN** [comment]
What's your maven version?

**Comment by aibowen** [comment]
3.6.3
----- 原始邮件 -----
发件人：吴伟杰 <notifications@github.com>
收件人：apache/shardingsphere-elasticjob <shardingsphere-elasticjob@noreply.github.com>
抄送人：aibowen <bowen_job@sina.com>,  Mention <mention@noreply.github.com>
主题：Re: [apache/shardingsphere-elasticjob] A required class was missing while executing org.apache.maven.plugins:maven-enforc er-plugin:1.4:enforce: org/apache/maven/enforcer/rule/api/EnforcerRuleException (#1697)
日期：2020年12月02日 10点26分


What's your maven version?

&mdash;

**Comment by TeslaCN** [comment]
The problem you asked at first does it resolved? Does `mvn install` runs properly?

**Comment by aibowen** [comment]
I run it crrectly
----- 原始邮件 -----
发件人：吴伟杰 <notifications@github.com>
收件人：apache/shardingsphere-elasticjob <shardingsphere-elasticjob@noreply.github.com>
抄送人：aibowen <bowen_job@sina.com>,  Mention <mention@noreply.github.com>
主题：Re: [apache/shardingsphere-elasticjob] A required class was missing while executing org.apache.maven.plugins:maven-enforc er-plugin:1.4:enforce: org/apache/maven/enforcer/rule/api/EnforcerRuleException (#1697)
日期：2020年12月02日 23点46分


The problem you asked at first does it resolved? Does mvn install runs properly?

&mdash;

**Comment by TeslaCN** [comment]
`mvn install` runs properly means this issue is done. If you have other problems related with elasticjob cannot find a solution, you may open another issue.
