### ISSUE TITLE
jobErrorHandlerType  配置LOG ，THROW  为什么效果是一样的，都不会中断作业

### ISSUE THREAD

**Issue by kongxiaodong** [apache/shardingsphere-elasticjob#1698]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
