### ISSUE TITLE
cloud version issues

### ISSUE THREAD

**Issue by huayhuy** [apache/shardingsphere-elasticjob#1714]
Hello, when I was deploying the cloud version, the service node kept printing "elastic job: xxx has leadership". There were about 30 logs per second, and it could not be accessed through 8899. I don't know why this happens. Could you please help me?

Cheers,
Hua

**Comment by TeslaCN** [comment]
Cloud required mesos library. Ref https://mesos.apache.org/documentation/latest/building/

If you are going to run cloud scheduler in IDE, you may need to set the following properties:
https://github.com/apache/shardingsphere-elasticjob/blob/3b88d317f3fd52b0a68b1ebddbfe0b3ad1a45568/elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/resources/bin/start.sh#L26

**Comment by huayhuy** [comment]
> Cloud required mesos library. Ref https://mesos.apache.org/documentation/latest/building/
> 
> If you are going to run cloud scheduler in IDE, you may need to set the following properties:
> https://github.com/apache/shardingsphere-elasticjob/blob/3b88d317f3fd52b0a68b1ebddbfe0b3ad1a45568/elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/resources/bin/start.sh#L26


I deployed it on a linux server. And I started the scheduler service based on mesos, and I saw that mesos was registered successfully on zookeeper.
This problem gave me the feeling that the scheduler service did not start successfully, but no error message was reported.

**Comment by huayhuy** [comment]
> Cloud required mesos library. Ref https://mesos.apache.org/documentation/latest/building/
> 
> If you are going to run cloud scheduler in IDE, you may need to set the following properties:
> https://github.com/apache/shardingsphere-elasticjob/blob/3b88d317f3fd52b0a68b1ebddbfe0b3ad1a45568/elasticjob-distribution/elasticjob-cloud-scheduler-distribution/src/main/resources/bin/start.sh#L26

我是在linux服务器上部署的scheduler，并且在启动之前已经启动mesos了，并且mesos可以确认启动成功。这个问题给我的感觉是服务注册失败，但是没有任何报错信息，只会打印"elastic job:xxx has leadership"这一条日志，并且是以每分钟二十多条的速度。

**Comment by TeslaCN** [comment]
Have you install mesos library into library path? such as `/usr/local/lib:/usr/lib:/usr/lib64`

For instance, my mesos lib is under `/usr/local/lib/libmesos.so`, and I run cloud scheduler with `-Djava.library.path=/usr/local/lib`.

logs:
```
[INFO ] 2020-11-12 17:19:29,649 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 127.0.0.1:8899 has leadership 
[INFO ] 2020-11-12 17:19:30,339 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.FacadeService] Elastic Job: Start facade service 
[INFO ] 2020-11-12 17:19:30,341 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.cloud.scheduler.producer.ProducerManager] Start producer manager 
[INFO ] 2020-11-12 17:19:30,370 --Curator-LeaderSelector-0-- [org.quartz.impl.StdSchedulerFactory] Using default implementation for ThreadExecutor 
[INFO ] 2020-11-12 17:19:30,386 --Curator-LeaderSelector-0-- [org.quartz.core.SchedulerSignalerImpl] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl 
[INFO ] 2020-11-12 17:19:30,386 --Curator-LeaderSelector-0-- [org.quartz.core.QuartzScheduler] Quartz Scheduler v.2.3.2 created. 
[INFO ] 2020-11-12 17:19:30,386 --Curator-LeaderSelector-0-- [org.quartz.plugins.management.ShutdownHookPlugin] Registering Quartz shutdown hook. 
[INFO ] 2020-11-12 17:19:30,387 --Curator-LeaderSelector-0-- [org.quartz.simpl.RAMJobStore] RAMJobStore initialized. 
[INFO ] 2020-11-12 17:19:30,387 --Curator-LeaderSelector-0-- [org.quartz.core.QuartzScheduler] Scheduler meta-data: Quartz Scheduler (v2.3.2) 'ELASTIC_JOB_CLOUD_TRANSIENT_PRODUCER' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 24 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
 
[INFO ] 2020-11-12 17:19:30,387 --Curator-LeaderSelector-0-- [org.quartz.impl.StdSchedulerFactory] Quartz scheduler 'ELASTIC_JOB_CLOUD_TRANSIENT_PRODUCER' initialized from an externally provided properties instance. 
[INFO ] 2020-11-12 17:19:30,388 --Curator-LeaderSelector-0-- [org.quartz.impl.StdSchedulerFactory] Quartz scheduler version: 2.3.2 
[INFO ] 2020-11-12 17:19:30,388 --Curator-LeaderSelector-0-- [org.quartz.core.QuartzScheduler] Scheduler ELASTIC_JOB_CLOUD_TRANSIENT_PRODUCER_$_NON_CLUSTERED started. 
[INFO ] 2020-11-12 17:19:30,413 --task-launch-processor STARTING-- [org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.TaskLaunchScheduledService] Elastic Job: Start task-launch-processor 
[INFO ] 2020-11-12 17:19:30,585 --nioEventLoopGroup-2-1-- [org.apache.shardingsphere.elasticjob.restful.NettyRestfulService] Restful Service started on port 8899. 
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@753: Client environment:zookeeper.version=zookeeper C client 3.4.8
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@757: Client environment:host.name=wwj
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@764: Client environment:os.name=Linux
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@765: Client environment:os.arch=5.4.0-52-generic
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@766: Client environment:os.version=#57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@774: Client environment:user.name=wuweijie
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@782: Client environment:user.home=/home/wuweijie
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@794: Client environment:user.dir=/home/wuweijie/IdeaProjects/shardingsphere-elasticjob
2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@zookeeper_init@818: Initiating client connection, host=127.0.0.1:2181 sessionTimeout=10000 watcher=0x7f050f73ae65 sessionId=0 sessionPasswd=<null> context=0x7f044c000d78 flags=0
2020-11-12 17:19:30,587:536475(0x7f05010c2700):ZOO_INFO@check_events@1763: initiated connection to server [127.0.0.1:2181]
I1112 17:19:30.588145 536538 sched.cpp:239] Version: 1.10.0
2020-11-12 17:19:30,592:536475(0x7f05010c2700):ZOO_INFO@check_events@1809: session establishment complete on server [127.0.0.1:2181], sessionId=0x100053554190004, negotiated timeout=10000
I1112 17:19:30.594702 536548 group.cpp:341] Group process (zookeeper-group(1)@127.0.1.1:42997) connected to ZooKeeper
I1112 17:19:30.594847 536548 group.cpp:831] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I1112 17:19:30.594884 536548 group.cpp:419] Trying to create path '/mesos' in ZooKeeper
```

**Comment by huayhuy** [comment]
> Have you install mesos library into library path? such as `/usr/local/lib:/usr/lib:/usr/lib64`
> 
> For instance, my mesos lib is under `/usr/local/lib/libmesos.so`, and I run cloud scheduler with `-Djava.library.path=/usr/local/lib`.
> 
> logs:
> 
> ```
> [INFO ] 2020-11-12 17:19:29,649 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 127.0.0.1:8899 has leadership 
> [INFO ] 2020-11-12 17:19:30,339 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.FacadeService] Elastic Job: Start facade service 
> [INFO ] 2020-11-12 17:19:30,341 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.cloud.scheduler.producer.ProducerManager] Start producer manager 
> [INFO ] 2020-11-12 17:19:30,370 --Curator-LeaderSelector-0-- [org.quartz.impl.StdSchedulerFactory] Using default implementation for ThreadExecutor 
> [INFO ] 2020-11-12 17:19:30,386 --Curator-LeaderSelector-0-- [org.quartz.core.SchedulerSignalerImpl] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl 
> [INFO ] 2020-11-12 17:19:30,386 --Curator-LeaderSelector-0-- [org.quartz.core.QuartzScheduler] Quartz Scheduler v.2.3.2 created. 
> [INFO ] 2020-11-12 17:19:30,386 --Curator-LeaderSelector-0-- [org.quartz.plugins.management.ShutdownHookPlugin] Registering Quartz shutdown hook. 
> [INFO ] 2020-11-12 17:19:30,387 --Curator-LeaderSelector-0-- [org.quartz.simpl.RAMJobStore] RAMJobStore initialized. 
> [INFO ] 2020-11-12 17:19:30,387 --Curator-LeaderSelector-0-- [org.quartz.core.QuartzScheduler] Scheduler meta-data: Quartz Scheduler (v2.3.2) 'ELASTIC_JOB_CLOUD_TRANSIENT_PRODUCER' with instanceId 'NON_CLUSTERED'
>   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
>   NOT STARTED.
>   Currently in standby mode.
>   Number of jobs executed: 0
>   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 24 threads.
>   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
>  
> [INFO ] 2020-11-12 17:19:30,387 --Curator-LeaderSelector-0-- [org.quartz.impl.StdSchedulerFactory] Quartz scheduler 'ELASTIC_JOB_CLOUD_TRANSIENT_PRODUCER' initialized from an externally provided properties instance. 
> [INFO ] 2020-11-12 17:19:30,388 --Curator-LeaderSelector-0-- [org.quartz.impl.StdSchedulerFactory] Quartz scheduler version: 2.3.2 
> [INFO ] 2020-11-12 17:19:30,388 --Curator-LeaderSelector-0-- [org.quartz.core.QuartzScheduler] Scheduler ELASTIC_JOB_CLOUD_TRANSIENT_PRODUCER_$_NON_CLUSTERED started. 
> [INFO ] 2020-11-12 17:19:30,413 --task-launch-processor STARTING-- [org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.TaskLaunchScheduledService] Elastic Job: Start task-launch-processor 
> [INFO ] 2020-11-12 17:19:30,585 --nioEventLoopGroup-2-1-- [org.apache.shardingsphere.elasticjob.restful.NettyRestfulService] Restful Service started on port 8899. 
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@753: Client environment:zookeeper.version=zookeeper C client 3.4.8
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@757: Client environment:host.name=wwj
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@764: Client environment:os.name=Linux
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@765: Client environment:os.arch=5.4.0-52-generic
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@766: Client environment:os.version=#57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@774: Client environment:user.name=wuweijie
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@782: Client environment:user.home=/home/wuweijie
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@log_env@794: Client environment:user.dir=/home/wuweijie/IdeaProjects/shardingsphere-elasticjob
> 2020-11-12 17:19:30,586:536475(0x7f05766be700):ZOO_INFO@zookeeper_init@818: Initiating client connection, host=127.0.0.1:2181 sessionTimeout=10000 watcher=0x7f050f73ae65 sessionId=0 sessionPasswd=<null> context=0x7f044c000d78 flags=0
> 2020-11-12 17:19:30,587:536475(0x7f05010c2700):ZOO_INFO@check_events@1763: initiated connection to server [127.0.0.1:2181]
> I1112 17:19:30.588145 536538 sched.cpp:239] Version: 1.10.0
> 2020-11-12 17:19:30,592:536475(0x7f05010c2700):ZOO_INFO@check_events@1809: session establishment complete on server [127.0.0.1:2181], sessionId=0x100053554190004, negotiated timeout=10000
> I1112 17:19:30.594702 536548 group.cpp:341] Group process (zookeeper-group(1)@127.0.1.1:42997) connected to ZooKeeper
> I1112 17:19:30.594847 536548 group.cpp:831] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
> I1112 17:19:30.594884 536548 group.cpp:419] Trying to create path '/mesos' in ZooKeeper
> ```

我按照你推荐的方法重新安装了一下，结果还是一样的。
我的mesos是安装在docker上的，我不知道和这个是否有关系。
[INFO ] 2020-11-13 10:10:35,529 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,532 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,535 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,538 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,541 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,544 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,547 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,550 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,553 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,556 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,559 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,562 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,564 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
[INFO ] 2020-11-13 10:10:35,568 --Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership 
这个是我打印的日志

**Comment by TeslaCN** [comment]
Take a look at the top of the logs. Is there any log about failed to load Mesos library like the following?
```
Failed to load native Mesos library from /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
```
![image](https://user-images.githubusercontent.com/20503072/99020687-1b692900-259a-11eb-945d-570f86519a63.png)

**Comment by huayhuy** [comment]
> Take a look at the top of the logs. Is there any log about failed to load Mesos library like the following?
> 
> ```
> Failed to load native Mesos library from /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
> ```
> 
> ![image](https://user-images.githubusercontent.com/20503072/99020687-1b692900-259a-11eb-945d-570f86519a63.png)

没有。
因为我是在liunx下启动的，我只能看到log和error log，errorlog并没有内容，log中只有
--Curator-LeaderSelector-0-- [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperElectionService] Elastic job: 10.11.0.182:8899 has leadership

**Comment by huayhuy** [comment]
> Take a look at the top of the logs. Is there any log about failed to load Mesos library like the following?
> 
> ```
> Failed to load native Mesos library from /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
> ```
> 
> ![image](https://user-images.githubusercontent.com/20503072/99020687-1b692900-259a-11eb-945d-570f86519a63.png)

JAVA_OPTS=" -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djava.library.path=/home/mesos/lib"
以上是我脚本的部分内容，我的libmesos.so文件在/home/mesos/lib，请问我这样修改对吗

**Comment by TeslaCN** [comment]
For English only.

Mesos error log is printed to stderr. You can run `bin/start.sh 1> /dev/null` to check if it failed to load Mesos library.

![image](https://user-images.githubusercontent.com/20503072/99024846-6ab35780-25a2-11eb-850f-98f2c53e4114.png)

![image](https://user-images.githubusercontent.com/20503072/99023892-8289dc00-25a0-11eb-843e-fc7313666138.png)

**Comment by TeslaCN** [comment]
Hello @huayhuy ,
Have you solved your problem?

**Comment by TeslaCN** [comment]
No feedback from author.
