### ISSUE TITLE
all SimpleJob executed on the same machine

### ISSUE THREAD

**Issue by shuohao** [apache/shardingsphere-elasticjob#1724]
I have 3 node machine and several SimpleJobs, Each job has a shard，These jobs are triggered almost at the same time. and found that these jobs are all executed on the same machine, This will cause too much load and oom, Is there a way to dynamically adjust the load？
English is not good, only machine translation

**Comment by TeslaCN** [comment]
You may try a different `jobShardingStrategyType` or implement your own `JobShardingStrategy`.

Ref: https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/configuration/built-in-strategy/sharding/

**Comment by shuohao** [comment]
> You may try a different `jobShardingStrategyType` or implement your own `JobShardingStrategy`.
> 
> Ref: https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/configuration/built-in-strategy/sharding/

3q
