### ISSUE TITLE
maven-release-plugin and flatten-maven-plugin cannot work together very well

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1726]
## Bug Report

`flatten-maven-plugin` was introduced by @lovepoem in #1672. It replaced project version with placeholder to manage project version uniformly. But `maven-release-plugin` replaced placeholder in project version with specific version again. So we need to find a way to make `maven-release-plugin` and `flatten-maven-plugin` work together.

**Comment by lovepoem** [comment]
I think this issue should appear in the release process operated by the  release manager. I will have a look
