### ISSUE TITLE
Task meta-information Management

### ISSUE THREAD

**Issue by lixiongliang** [apache/shardingsphere-elasticjob#1731]
## Question

Task metadata, each time the container environment is re-published, metadata information remains in ZooKeeper; As a result, many tasks can be seen in the Console, which is difficult to find manual trigger. I hope it can provide a mechanism to automatically delete the history of useless meta information after the restart

**Comment by TeslaCN** [comment]
Could you clarify which meta information is useless?

**Comment by TeslaCN** [comment]
No response from author.
