### ISSUE TITLE
spring boot can not 'org.apache.shardingsphere.elasticjob.api.ShardingContext' bean

### ISSUE THREAD

**Issue by skddyj** [apache/shardingsphere-elasticjob#1743]
i'm using springboot 2.1.7 and elasticjob-lite-spring-boot-starter 3.0.0 beta, i've configued by [USER MANUAL](https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/configuration/spring-boot-starter/) , when i start my project it show that:
![image](https://user-images.githubusercontent.com/13520699/100590260-1d1f4480-332f-11eb-9b96-2b89e449318e.png)

it seems like that spring can not find a ShardingContext bean, what's wrong with my configuration?

**Comment by TeslaCN** [comment]
ShardingContext is not a bean. Could you show me your code?

**Comment by skddyj** [comment]
i've reboot my computer and cleaned my project just now, and the error is gone :( , thanks for your reply!
