### ISSUE TITLE
Job conflict with register center

### ISSUE THREAD

**Issue by PANIXS** [apache/shardingsphere-elasticjob#1745]
## Bug Report
I write a job in springboot, first time,it started success, but when i restart, it cant start, the exception is

rg.apache.shardingsphere.elasticjob.infra.exception.JobConfigurationException: Job conflict with register center. The job 'tyydHistoryJob' in register center's class is 'com.qx.job.jobs.tyyd.QueryFlowHistory$$EnhancerBySpringCGLIB$$d7a64376', your job class is 'com.qx.job.jobs.tyyd.QueryFlowHistory$$EnhancerBySpringCGLIB$$b20aaec1'

I already set the overwrite=true,but not work,there is my config:

    tyydHistoryJob:
      overwrite: true
      elasticJobClass: com.qx.job.jobs.tyyd.QueryFlowHistory
      cron: 0/3 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

**Comment by TeslaCN** [comment]
This issue has been fixed by #1106 and released in 3.0.0-alpha.

**Comment by TeslaCN** [comment]
Thanks for your feedback, we will fix it as soon as possible.

**Comment by PANIXS** [comment]
I tried the 3.0.0-alpha version and use new namespace,and still has this problem

**Comment by TeslaCN** [comment]
This problem does exist. A JobClassNameProvider for class enhanced by Cglib should be introduced into Spring Boot Starter.

**Comment by PANIXS** [comment]
ok,thank you,may i ask how long can you guys fix this bug

**Comment by TeslaCN** [comment]
I'm not sure about this. We may release next version in this month. Are you interested in fixing this issue?

**Comment by PANIXS** [comment]
this problem looks already resolved,i found a SpringProxyJobClassNameProvider in the code, but my package is from mvnrepository.com, it just not update to it

**Comment by candyYu** [comment]
> this problem looks already resolved,i found a SpringProxyJobClassNameProvider in the code, but my package is from mvnrepository.com, it just not update to it

how i actually use it in project?
