### ISSUE TITLE
Question about failover

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1748]
![image](https://user-images.githubusercontent.com/52127183/100839071-92655380-34ae-11eb-9341-b7ecbbf696f9.png)

when are the failoverItems not empty and program will go to code at line between 81 and 84

**Comment by TeslaCN** [comment]
Actually this should be named `failoveringItems`. If an instance down while executing failover item, the item would be appeared in this List.
