### ISSUE TITLE
Does failover work depending on opening monitor_execution?

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1751]
Does failover work depending on opening monitor_execution? I did not find the code of failover process depending on opening monitor_execution.

**Comment by TeslaCN** [comment]
No, it doesn't. Even `monitorExecution` is false, the feature failover still works.

**Comment by kaihekaihe** [comment]
![image](https://user-images.githubusercontent.com/52127183/100871593-7c21bc80-34db-11eb-8e23-a03ae059677e.png)

I found this and have doubt about this。Maybe the document shoud be updated？

**Comment by TeslaCN** [comment]
Thanks for your feedback! The document does need to be updated. You may submit a PR if you are interested in, or we will update it later.

**Comment by gzdzss** [comment]
I'll try

**Comment by wx4625820** [comment]
I saw that this issue has not been fixed yet, so I submit a pr
