### ISSUE TITLE
One sharding item is stuck

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1754]
I have one job named “cronJob” running on two servers。I found that three sharding items was stuck at the moment，I manually triggered the job，then sharding item 0、2 started to run as the cron principle，but sharding item 1 was still stuck。The dumped information is below：

/cronJob/sharding |
/cronJob/sharding/2 |
/cronJob/sharding/2/running |
/cronJob/sharding/2/instance | ip1@-@102156
/cronJob/sharding/1 |
/cronJob/sharding/1/instance | ip2@-@165035
/cronJob/sharding/0 |
/cronJob/sharding/0/running |
/cronJob/sharding/0/instance | ip1@-@102156
/cronJob/servers |
/cronJob/servers/ip1 | ENABLED
/cronJob/servers/ip2 | ENABLED
/cronJob/leader |
/cronJob/leader/sharding |
/cronJob/leader/failover |
/cronJob/leader/failover/items |
/cronJob/leader/election |
/cronJob/leader/election/instance | ip1@-@102156
/cronJob/instances |
/cronJob/instances/ip1@-@102156 |
/cronJob/instances/ip2@-@165035 |
/cronJob/config | cron: 0/10 * * * * ?
description: ''
disabled: false
failover: true
jobErrorHandlerType: ''
jobExecutorServiceHandlerType: ''
jobName: cronJob
jobParameter: 0=Beijing1,1=Shanghai,2=Guangzhou,3=Guangzhou
jobShardingStrategyType: ''
maxTimeDiffSeconds: -1
misfire: true
monitorExecution: true
overwrite: true
reconcileIntervalMinutes: -1
shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou,3=Guangzhou
shardingTotalCount: 3

**Comment by TeslaCN** [comment]
I cannot reproduce this problem in my environment. Try setting the `maxTimeDiffSeconds` to `1` to check if servers' time are equivalent.

**Comment by kaihekaihe** [comment]
Setting the maxTimeDiffSeconds to 1 ,I need to restart the executor.But after the restarting,the problem may be gone and the environment will be destroyed.

**Comment by TeslaCN** [comment]
Could you check if servers' time are consistent.

**Comment by TeslaCN** [comment]
Hi @kaihekaihe ,

Have you solved the problem?

**Comment by kaihekaihe** [comment]
Two servers,ip1 and ip2. their time are consistent.Differrence is less than 1 second.
I have not solved the problem

**Comment by TeslaCN** [comment]
Do you know how to reproduce it?

**Comment by kaihekaihe** [comment]
I need to think how to reproduce.I have another question.
What would maxTimeDifference beteween executor and zk which is very big affect ?

**Comment by TeslaCN** [comment]
If time difference exceed max allow, an exception will occur.

**Comment by kaihekaihe** [comment]
The cause may be debugging in one executor.

**Comment by kaihekaihe** [comment]
Debugging in one executor for about 10 minutes,the procedure will hung while debugging。Then stop debugging，the executor will still run for a period of time，but will stop for unknown cause。There is no exception found。

**Comment by TeslaCN** [comment]
@kaihekaihe  Could you show me your job logic?

**Comment by kaihekaihe** [comment]
My application is just elasticjob examples

**Comment by TeslaCN** [comment]
I've tried suspending the application for tens of miniutes, After I resume the program, it reconnected to Zookeeper and continue scheduling.
