### ISSUE TITLE
Refactor elasticjob cloud and support elasticjob cloud on kubernetes 

### ISSUE THREAD

**Issue by avalon5666** [apache/shardingsphere-elasticjob#1761]
In order to making elasticjob cloud easier to deploy, I intend to support elasticjob cloud to work on kubernetes.

The task is as follows:

* [ ] The communication between master and work is independent of mesos
  * [ ] Define communication api based on event bus
  * [ ] Implementation of communication api based on mesos
  * [ ] Implementation of communication api based on zookeeper
* [ ] The task execute is independent of mesos
  * [ ] Define task execute api
  * [ ] Implementation of task execute api based on mesos
  * [ ] Implementation of task execute api based on kubernetes
* [ ] Support resources limit
* [ ] Cleanup code

**Comment by avalon5666** [comment]
#1690

**Comment by terrymanu** [comment]
Because ElasticJob Cloud is a mesos framework which depend mesos API, we need to decouple them first. Is it in the plan?

**Comment by avalon5666** [comment]
Yes, I will finish 1.1, 1.2, 2.1, 2.2 first.

**Comment by terrymanu** [comment]
It is a good idea
