### ISSUE TITLE
Is the elasticjob-lite 3.0.0-beta compatible with spring boot 2.1.1?

### ISSUE THREAD

**Issue by zewade** [apache/shardingsphere-elasticjob#1765]
## Question

Hello。My project use the elastic-job-lite v2.1.5 with spring boot 2.1.1.RELEASE, can I update elastic job lite to v3.0.0-beta without update the spring boot version?

**Comment by TeslaCN** [comment]
You can keep using Spring Boot 2.1.1.

**Comment by TeslaCN** [comment]
I'm closing this issue. You may open a new issue if you have other questions.
