### ISSUE TITLE
YamlEngine function dumpAsMap data format incompatible

### ISSUE THREAD

**Issue by jackycchen** [apache/shardingsphere-elasticjob#1767]
### Is your feature request related to a problem?
Code location: YamlEngine.java#marshal
`public static String marshal(final Object value) {
        return new Yaml(new ElasticJobYamlRepresenter()).dumpAsMap(value);
    }`
The function dumpAsMap detail is :
`public String dumpAsMap(Object data) {
        return this.dumpAs(data, Tag.MAP, FlowStyle.BLOCK);
    }`

Problem is **data format incompatible**
When the third parameter is FlowStyle.BLOCK，the result of function dumpAsMap is yaml format string
When set third parameter to null, the the result of function dumpAsMap is json format string

I found that elasticjob client store the config of a task in zookeeper is json format string in the older version(**like 2.1.5**), this will lead to incompatible with the current version.

### Describe the feature you would like.
**should modify the function dumpAsMap like this:**
`public String dumpAsMap(Object data) {
        return this.dumpAs(data, Tag.MAP, null);
    }`

I think the data format should not be incompatible, thus will cause difficult to upgrade.

**Comment by TeslaCN** [comment]
The API has already changed in `3.0.0`. It's still incompatible with 2.x even if using a same format to marshal/unmarshal configuration.
