### ISSUE TITLE
请问elasticjob-example-lite-springboot 如何启动

### ISSUE THREAD

**Issue by namelcx** [apache/shardingsphere-elasticjob#1768]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by TeslaCN** [comment]
**For English only!**
