### ISSUE TITLE
How can I get the stable version in public maven repository.

### ISSUE THREAD

**Issue by horizonzy** [apache/shardingsphere-elasticjob#1769]
## Question

I want to repalce dangdang's release by apache. 
But in the mvn repository, I just found `3.0.0-beta` and `3.0.0-alpha`, how can I get stable version of this.
https://mvnrepository.com/artifact/org.apache.shardingsphere.elasticjob/elasticjob-lite-core

**Comment by TeslaCN** [comment]
The latest version is `3.0.0-beta`. Stable version is coming soon.

**Comment by horizonzy** [comment]
Why not upload this release to mvn repository? any defect？
https://github.com/apache/shardingsphere-elasticjob/releases/tag/2.1.5

**Comment by TeslaCN** [comment]
The earlier version can be found here: https://mvnrepository.com/artifact/com.dangdang/elastic-job-lite-core/2.1.5

**Comment by horizonzy** [comment]
> The earlier version can be found here: https://mvnrepository.com/artifact/com.dangdang/elastic-job-lite-core/2.1.5

It's dangdang's release, wait apache next  release, the new version already upgrade curator's version to 4.x? 
The `2.1.5` use old version curator, some project already use 4.x. the curator's high version and low version is incompatible.

**Comment by TeslaCN** [comment]
The curator has been upgraded to 5.1.0 in `3.0.0-beta`.

**Comment by horizonzy** [comment]
ok. Look forward to next release.
