### ISSUE TITLE
Feature failover works after zk session timeout，How to decrease consuming time of the process。

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1777]
I know decreasing zk session timeout can work.

Decreasing the inteval of reconcile service do not work, because it also depends on the zk session timeout. Am i right?

**Comment by TeslaCN** [comment]
`ReconcileService` works on situation that doesn't need sharding but some shards belongs to offline servers. The probability of that situation is very small.

**Comment by kaihekaihe** [comment]
According to the code.shards belongs to offline servers can only be found after zk session timeout.

If server is offline,but temprary node does not disappear,ReconcileService can not find the offline server.

**Comment by TeslaCN** [comment]
I don't think `ReconcileService` is used for this situation. Normally, when server offline, listener will be aware of offline event and set reshard flag. `ReconcileService` works in extreme cases.

**Comment by kaihekaihe** [comment]
@TeslaCN 
I have one suggestion. 
Adding shutdown hook to delete the temprary  instance node immediately，other executors will be notified more quickly which does not rely on session timeout
