### ISSUE TITLE
The spring-boot-starter-jdbc is not optional in ElasticJob Spring Boot Starter

### ISSUE THREAD

**Issue by liujunjia1996** [apache/shardingsphere-elasticjob#1791]
Must i configure a RDB？

**Comment by TeslaCN** [comment]
Tracing module is optional. You could run your jobs without Tracing configuration.

**Comment by liujunjia1996** [comment]
> Tracing module is optional. You could run your jobs without Tracing configuration.

what can i do to close tracing feature.
I read the doc but not found.

**Comment by TeslaCN** [comment]
Tracing doesn't enable by default.
If you are using Spring Boot, tracing won't enable if missing `elasticjob.tracing.type=RDB`.

**Comment by liujunjia1996** [comment]
I use the `elasticjob-lite-spring-boot-starter` ,and i true do not configure the `elasticjob.tracing.type`,but i must exclude `spring-boot-starter-jdbc` and `h2` and then my application can run.
this is my pom:

         <dependency>
            <groupId>org.apache.shardingsphere.elasticjob</groupId>
            <artifactId>elasticjob-lite-spring-boot-starter</artifactId>
            <version>3.0.0-RC1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-jdbc</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.h2database</groupId>
                    <artifactId>h2</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-test</artifactId>
            <version>5.1.0</version>
        </dependency>


and this is my application.yml:

    elasticjob:
      regCenter:
        serverLists: localhost:2181
        namespace: operation-log-elastic-job
      jobs:
        simpleJob:
          elasticJobClass: com.example.demo.OldLogDeleteJob
          cron:  0/5 * * * * ?
          shardingTotalCount: 1

**Comment by liujunjia1996** [comment]
if don't exclude,i will get this:

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by TeslaCN** [comment]
@qaqLjj I see the problem. Maybe we need to add `<optional>true</optional>` to dependency `spring-boot-starter-jdbc`  in `elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/pom.xml`.

**Comment by liujunjia1996** [comment]
> @qaqLjj I see the problem. Maybe we need to add `<optional>true</optional>` to dependency `spring-boot-starter-jdbc` in `elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/pom.xml`.

ok,thanks for your patience.

**Comment by TeslaCN** [comment]
Hi @qaqLjj 
Are you interested in contributing? You may submit a PR to fix this issue.

**Comment by liujunjia1996** [comment]
![image](https://user-images.githubusercontent.com/43411944/103186524-c5f39c00-48fb-11eb-90cb-f85ba2a13446.png)
