### ISSUE TITLE
Why elasticjob must be update zookeeper to 3.6.x? 

### ISSUE THREAD

**Issue by zewade** [apache/shardingsphere-elasticjob#1796]
Dose the elasticjob use some new feature on zookeeer 3.6.x? Because we already use zookeeper 3.5.5 in production env as microservice registry, can I simplely replace the ZookeeperRegistryCenter.java to the one in elasticjob v2.1.5 source code to support zookeeper 3.5.5?

**Comment by TeslaCN** [comment]
Hi @zewade 
ElasticJob 3.0.0 has upgraded Curator to 5.1.0.

**Comment by zewade** [comment]
> Hi @zewade
> ElasticJob 3.0.0 has upgraded Curator to 5.1.0.

I checked the release note of Curator 5.1.0, it only says that it no long support 3.4.x.So why 3.5.5 also can't work with elasticjob?
I have tested the CuratorCacheExample under the source code of Curator 5.1.0, and it can run properly with zookeeper 3.5.5.

**Comment by TeslaCN** [comment]
You may check the Curator's dependencies in https://mvnrepository.com/artifact/org.apache.curator/curator-client/5.1.0 .
The curator-client 5.1.0 is using Zookeeper 3.6.0, I'm not sure if the Curator 5.1.0 is compatible with Zookeeper 3.5.x.
