### ISSUE TITLE
What is the use of BeanPostProcessor for ElasticJobBootstrapConfiguration？

### ISSUE THREAD

**Issue by wwj-go** [apache/shardingsphere-elasticjob#1801]
## Question

What is the use of BeanPostProcessor for ElasticJobBootstrapConfiguration？
```
public class ElasticJobBootstrapConfiguration implements ApplicationContextAware, BeanPostProcessor {
......
}
```
I find that the class ElasticJobBootstrapConfiguration do not implement any methods in BeanPostProcessor, so is it enough like below? 
```
public class ElasticJobBootstrapConfiguration implements ApplicationContextAware{
......
}
```

**Comment by TeslaCN** [comment]
You may check what I did in #1696

**Comment by wwj-go** [comment]
@TeslaCN I have got it！
The reason is that the bean which implements BeanPostProcessor will be initialized earlier than normal beans.
Thanks for your reply !
