### ISSUE TITLE
zk 不稳定，部分任务不执行

### ISSUE THREAD

**Issue by 15168326318** [apache/shardingsphere-elasticjob#1805]
ejob:2.1.5
zk:3.5.5
curator: 2.13.0

zk注册中心不稳定，经常有任务不执行。日志打印已经关闭，如下：
 [Curator-TreeCache-1] [org.quartz.core.QuartzScheduler:666] - trace[] Scheduler DictEffectDataEsJob_$_NON_CLUSTERED shutting down.
[Curator-TreeCache-1] [org.quartz.core.QuartzScheduler:585] - trace[] Scheduler DictEffectDataEsJob_$_NON_CLUSTERED paused.
 [Curator-TreeCache-1] [org.quartz.core.QuartzScheduler:740] - trace[] Scheduler DictEffectDataEsJob_$_NON_CLUSTERED shutdown complete.

**Comment by TeslaCN** [comment]
**For English only**, other languages will not accept.
