### ISSUE TITLE
ZK is unstable, some missions are not executed

### ISSUE THREAD

**Issue by 15168326318** [apache/shardingsphere-elasticjob#1807]
ejob:2.1.5
zk:3.5.5
curator: 2.13.0
The ZK registry is not stable, there are often tasks not executed.Log printing has been turned off, as follows:
[Curator-TreeCache-1] [org.quartz.core.QuartzScheduler:666] - trace[] Scheduler DictEffectDataEsJob_$NON_CLUSTERED shutting down.
[Curator-TreeCache-1] [org.quartz.core.QuartzScheduler:585] - trace[] Scheduler DictEffectDataEsJob$NON_CLUSTERED paused.
[Curator-TreeCache-1] [org.quartz.core.QuartzScheduler:740] - trace[] Scheduler DictEffectDataEsJob$_NON_CLUSTERED shutdown complete.

**Comment by TeslaCN** [comment]
If connection to registry center lost, jobs will be suspended. If max retry times reached, the jobs may be shutdown.

**Comment by 15168326318** [comment]
同一个项目中的jobs，应该是都关闭才对，为什么我们只是其中的一两个会关闭，很多是好的

**Comment by 15168326318** [comment]
而且我本地测试，把注册中心关闭，等很久之后注册中心启动后还是可以执行的。

**Comment by TeslaCN** [comment]
Hi @15168326318 
We need more info about this issue.

**Comment by TeslaCN** [comment]
Close due to no response.
