### ISSUE TITLE
定时任务执行完成之后，进入了重试机制

### ISSUE THREAD

**Issue by WooXooM** [apache/shardingsphere-elasticjob#1808]
是用的版本是elastic-job-lite 2.1.5
定时任务执行成功了，中间没有抛异常，但是进入了重试。重试配置的是maxRetries=3， baseSleepTimeMilliseconds=1000， maxSleepTimeMilliseconds=3000。定时任务执行完成之后，又在30秒之后执行了一次，然后30秒之后又执行了一次。
执行成功之后，发现上送的结果是request:: '/test-job/errorLogMonitorJob/sharding/0/running,-1
下面是日志
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:818) [Reading reply sessionid:0x761d4cd6a77e8f, packet:: clientPath:null serverPath:null finished:false header:: 137918,3  replyHeader:: 137918,124916452976,0  request:: '/test-job/errorLogMonitorJob/sharding/0/running,F  response:: s{124916452952,124916452952,1610013058012,1610013058012,0,0,0,33246263107878543,0,0,124916452952} ]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:741) [Got notification sessionid:0x761d4cd6a77e8f][DEBUG 2021-01-07 17:50:58.163] [SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:763) [Got WatchedEvent state:SyncConnected type:NodeDeleted path:/test-job/errorLogMonitorJob/sharding/0/running for sessionid 0x761d4cd6a77e8f]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:741) [Got notification sessionid:0x761d4cd6a77e8f][DEBUG 2021-01-07 17:50:58.163] [EventThread] [] TreeCache.process(TreeCache.java:341) [process: WatchedEvent state:SyncConnected type:NodeDeleted path:/errorLogMonitorJob/sharding/0/running]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:763) [Got WatchedEvent state:SyncConnected type:NodeChildrenChanged path:/test-job/errorLogMonitorJob/sharding/0 for sessionid 0x761d4cd6a77e8f]
[EventThread] [] TreeCache.publishEvent(TreeCache.java:834) [publishEvent: TreeCacheEvent{type=NODE_REMOVED, data=ChildData{path='/errorLogMonitorJob/sharding/0/running', stat=124916452952,124916452952,1610013058012,1610013058012,0,0,0,33246263107878543,0,0,124916452952, data=[]}}]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:818) [Reading reply sessionid:0x761d4cd6a77e8f, packet:: clientPath:null serverPath:null finished:false header:: 137919,2  replyHeader:: 137919,124916452978,0  request:: '/test-job/errorLogMonitorJob/sharding/0/running,-1  response:: null]
[EventThread] [] TreeCache.process(TreeCache.java:341) [process: WatchedEvent state:SyncConnected type:NodeChildrenChanged path:/errorLogMonitorJob/sharding/0]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:818) [Reading reply sessionid:0x761d4cd6a77e8f, packet:: clientPath:null serverPath:null finished:false header:: 137920,3  replyHeader:: 137920,124916452978,0  request:: '/test-job/errorLogMonitorJob/leader/election/instance,F  response:: s{124916067793,124916067793,1610009670012,1610009670012,0,0,0,33246263107878543,19,0,124916067793} ]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:818) [Reading reply sessionid:0x761d4cd6a77e8f, packet:: clientPath:null serverPath:null finished:false header:: 137921,3  replyHeader:: 137921,124916452978,-101  request:: '/test-job/errorLogMonitorJob/leader/sharding/necessary,F  response::  ]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:818) [Reading reply sessionid:0x761d4cd6a77e8f, packet:: clientPath:/test-job/errorLogMonitorJob/sharding/0 serverPath:/test-job/errorLogMonitorJob/sharding/0 finished:false header:: 137922,12  replyHeader:: 137922,124916452978,0  request:: '/test-job/errorLogMonitorJob/sharding/0,T  response:: v{'instance},s{122601031744,122601031744,1598593909804,1598593909804,0,2279171,0,0,0,1,124916452978} ]
[EventThread] [] TreeCache.processResult(TreeCache.java:371) [processResult: CuratorEventImpl{type=CHILDREN, resultCode=0, path='/errorLogMonitorJob/sharding/0', name='null', children=[instance], context=null, stat=122601031744,122601031744,1598593909804,1598593909804,0,2279171,0,0,0,1,124916452978, data=null, watchedEvent=null, aclList=null}]
[SendThread(zk:2181)] [] ClientCnxn.readResponse(ClientCnxn.java:818) [Reading reply sessionid:0x761d4cd6a77e8f, packet:: clientPath:null serverPath:null finished:false header:: 137923,3  replyHeader:: 137923,124916452978,-101  request:: '/test-job/errorLogMonitorJob/sharding/0/misfire,F  response::  ]
[errorLogMonitorJob_QuartzSchedulerThread] [] QuartzSchedulerThread.run(QuartzSchedulerThread.java:276) [batch acquisition of 1 triggers]
[Thread-60] [] PoolingHttpClientConnectionManager.closeExpiredConnections(PoolingHttpClientConnectionManager.java:428) [Closing expired connections]
[Thread-60] [] PoolingHttpClientConnectionManager.closeIdleConnections(PoolingHttpClientConnectionManager.java:421) [Closing connections idle longer than 30 SECONDS]
[errorLogMonitorJob_QuartzSchedulerThread] [] PropertySettingJobFactory.newJob(SimpleJobFactory.java:51) [Producing instance of Job 'DEFAULT.errorLogMonitorJob', class=com.dangdang.ddframe.job.lite.internal.schedule.LiteJob]

**Comment by TeslaCN** [comment]
**For English only**
