### ISSUE TITLE
Bean is not eligible for getting processed by all BeanPostProcessors 

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1810]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?
1.0.0-RC1
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Actual behavior
INFO ] 2021-01-15 11:42:54,819 --main-- [org.apache.shardingsphere.elasticjob.lite.example.SpringBootMain] The following profiles are active: dev 
[INFO ] 2021-01-15 11:42:57,341 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'elasticjob-org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobProperties' of type [org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,342 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'org.apache.shardingsphere.elasticjob.lite.spring.boot.reg.ElasticJobRegistryCenterConfiguration' of type [org.apache.shardingsphere.elasticjob.lite.spring.boot.reg.ElasticJobRegistryCenterConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,347 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'elasticjob.reg-center-org.apache.shardingsphere.elasticjob.lite.spring.boot.reg.ZookeeperProperties' of type [org.apache.shardingsphere.elasticjob.lite.spring.boot.reg.ZookeeperProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,536 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'zookeeperRegistryCenter' of type [org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,538 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'org.apache.shardingsphere.elasticjob.lite.spring.boot.tracing.ElasticJobTracingConfiguration' of type [org.apache.shardingsphere.elasticjob.lite.spring.boot.tracing.ElasticJobTracingConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,541 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,550 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,585 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'dataSource' of type [com.zaxxer.hikari.HikariDataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
[INFO ] 2021-01-15 11:42:57,611 --main-- [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] Bean 'org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
### Reason analyze (If you can)
These none eligible beans is initialized in too earlier phase to be handled  by some beanPostProcessers which have not be ready。
### Steps to reproduce the behavior.
Running springboot example
### Example codes for reproduce this issue (such as a github link).

These INFO logs do not affect the job running。

**Comment by workswan** [comment]
use the default zookeper,maybe your zookeeper version is avaliable

**Comment by workswan** [comment]
sorry,use the zookeeper on version 3.6.3 haven the some question ,but is not influnce it works
