### ISSUE TITLE
Separate API and implementations from elasticjob-registry-center

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1814]
## Discuss

The current registry center API and implementation are in one package. To support different implementations of registry center (such as etcd), it's better to separate API and implementations into the following structure.

```
└── elasticjob-registry-center
    ├── elasticjob-registry-center-api
    └── elasticjob-registry-center-provider
        ├── elasticjob-registry-center-etcd
        └── elasticjob-registry-center-zookeeper-curator
        └── elasticjob-registry-center-zookeeper-curator2
```

**Comment by terrymanu** [comment]
Good idea. It is similar with ShardingSphere's governance module.

**Comment by cn-src** [comment]
I agree. I want to use relational database or redis. Because my business scenario is simple and I don't want to install ZooKeeper anymore.
