### ISSUE TITLE
apache-shardingsphere-elasticjob-3.0.0-RC1-lite-ui-bin.tar.gz  modification  job 

### ISSUE THREAD

**Issue by qjc1024join** [apache/shardingsphere-elasticjob#1816]
Failed to specialize base type org.apache.shardingsphere.elasticjob.infra.yaml.config.YamlConfiguration<org.apache.shardingsphere.elasticjob.api.JobExtraConfiguration> as org.apache.shardingsphere.elasticjob.tracing.yaml.YamlTracingConfiguration, problem: Type parameter #1/1 differs; can not specialize org.apache.shardingsphere.elasticjob.api.JobExtraConfiguration with org.apache.shardingsphere.elasticjob.tracing.api.TracingConfiguration<$1> (through reference chain: org.apache.shardingsphere.elasticjob.lite.ui.web.response.ResponseResult["model"]->org.apache.shardingsphere.elasticjob.infra.pojo.JobConfigurationPOJO["jobExtraConfigurations"]->java.util.ArrayList[0])

What's going on?

**Comment by TeslaCN** [comment]
This is a bug. https://github.com/apache/shardingsphere-elasticjob-ui/issues/97

**Comment by TeslaCN** [comment]
Close due to https://github.com/apache/shardingsphere-elasticjob-ui/pull/105 has been merged.
