### ISSUE TITLE
The console does not display job history

### ISSUE THREAD

**Issue by LebronCurry** [apache/shardingsphere-elasticjob#1822]
Hello,I confirm that the job has been executed correctly, but the console does not display the job record. Is there a problem with my configuration?
version: 3.0.0-RC1
![image](https://user-images.githubusercontent.com/48313599/105659535-e8310780-5f03-11eb-9e01-53f26e0a7e95.png)
![image](https://user-images.githubusercontent.com/48313599/105659571-f97a1400-5f03-11eb-9a0a-4c5e8aff5318.png)

**Comment by TeslaCN** [comment]
Have you configured DataSource?

**Comment by LebronCurry** [comment]
> Have you configured DataSource?
Yes,
![image](https://user-images.githubusercontent.com/48313599/105794786-b03ec880-5fc6-11eb-97d4-4dff4b7043a7.png)

**Comment by TeslaCN** [comment]
I have some suggestions for your:
1. Check if data present in your MySQL;
2. Restart the Lite Console backend application.

**Comment by LebronCurry** [comment]
> I have some suggestions for your:
> 
> 1. Check if data present in your MySQL;
> 2. Restart the Lite Console backend application.

There is no data in mysql, I tried restarting. I use JavaApi for elastic-job development and SpringBootStarter for event tracking. Is this a problem,thanks for reply

**Comment by TeslaCN** [comment]
You need to add TracingConfiguration to JobConfiguration manually when using the Java API.

**Comment by LebronCurry** [comment]
> You need to add TracingConfiguration to JobConfiguration manually when using the Java API.

I have solved this problem,thanks.
