### ISSUE TITLE
monitor job schedule

### ISSUE THREAD

**Issue by guanziao** [apache/shardingsphere-elasticjob#1827]
hi, 
 I wonder to ask whether elasticjob-lite has a monitor function which can  automaticly notice on the console when a cron not work as expectely. If not , will it be plan in the future version.
Thanks！

**Comment by TeslaCN** [comment]
Hi @guanziao ,
Do you have any idea about how to do that? Starting another timer to check it?

**Comment by guanziao** [comment]
> Hi @guanziao ,
> Do you have any idea about how to do that? Starting another timer to check it?

Thanks for you reply @TeslaCN . My idea is to analyze cron to get the right schedule time and check the log by a new thread.

**Comment by TeslaCN** [comment]
The ElasticJob is a SDK, not an application. I think it's too tedious for the SDK that starting another timer to check if its timer works properly. The checking may be done in the application layer.

**Comment by guanziao** [comment]
> The ElasticJob is a SDK, not an application. I think it's too tedious for the SDK that starting another timer to check if its timer works properly. The checking may be done in the application layer.

Could we add this function in the UI because UI is an application

**Comment by guanziao** [comment]
> The ElasticJob is a SDK, not an application. I think it's too tedious for the SDK that starting another timer to check if its timer works properly. The checking may be done in the application layer.

Thanks！
