### ISSUE TITLE
ReconcileService

### ISSUE THREAD

**Issue by guanziao** [apache/shardingsphere-elasticjob#1829]
I have a question about ReconcileService.
The job config 'reconcileIntervalMinutes' describe in user manual is:

In a distributed system, due to network, clock and other reasons, ZooKeeper may be inconsistent with the actual running job. This inconsistency cannot be completely avoided through positive verification. It is necessary to start another thread to periodically calibrate the consistency between the registry center and the job status, that is, to maintain the final consistency of ElasticJob.

But , the default value is 10 minutes. Is it too long for checking the environment ？
Furthermore, in ReconcileService it only checks the sharding when hasShardingInfoInOfflineServers() is true.  
So, I thinks the function in ReconcileService is not matching the description in user manual.

I don't know if I'm wrong. 
Thanks

**Comment by TeslaCN** [comment]
Maybe the describe is too abstract. Under normal conditions, `sharding/necessary` flag will be set when any instance was offline. I think the probability of `hasShardingInfoInOfflineServers` is very small, so default 10 minutes is enough. You may specify a smaller value for your scenarios.
