### ISSUE TITLE
The next version

### ISSUE THREAD

**Issue by qjc1024join** [apache/shardingsphere-elasticjob#1833]
When is the next release expected？ elasticjob-ui-3.0.0-RC1/apache-shardingsphere-elasticjob-3.0.0-RC1-lite-ui-bin.tar.gz  Have the problems been fixed？ You' ve had a long day

**Comment by nevenchen** [comment]
I have the same question, when will ElasticJob release the stable version?

**Comment by TeslaCN** [comment]
The issue https://github.com/apache/shardingsphere-elasticjob-ui/issues/97 has been fixed at master branch. The next version we are still working on it.
