### ISSUE TITLE
job status is always pending

### ISSUE THREAD

**Issue by jxguosuspectx** [apache/shardingsphere-elasticjob#1835]
## Question

job status is always pending，restarting the job does not works，what reasons may cause this and how  to fix it?
the using version is 2.0.3.

**Comment by TeslaCN** [comment]
Could you dump your Zookeeper's data?

https://shardingsphere.apache.org/elasticjob/legacy/lite-2.x/02-guide/dump/

**Comment by linghengqian** [comment]
Closed due to not being able to reproduce.
