### ISSUE TITLE
When a sharding item failure

### ISSUE THREAD

**Issue by guanziao** [apache/shardingsphere-elasticjob#1842]
When a sharding item failure, is the whole job failure or success?
Is there any transactional method for rolling back the whole job when a sharding item failure?
Or any sharding item is independency, it running status or result does not depend on other item in the same job.
Thanks！

**Comment by TeslaCN** [comment]
Each sharding item is independent. You need to maintain the transaction on your own.

**Comment by guanziao** [comment]
I got it, thanks!
