### ISSUE TITLE
Parsing commandline fails

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1850]
My commandline  is ：
`echo `date +‘%Y-%m-%d %H:%M:%S'` > /tmp/cloudjob_cluster.log`

But while executing the commandline,the console has output:

`date "+%Y-%m-%d %H:%M:%S`" > /tmp/cloudjob_cluster.log {"jobName":"manualScriptJobBean","taskId":"manualScriptJobBean@-@0@-@READY@-@ip1@-@334934","shardingTotalCount":1,"jobParameter":"","shardingItem":0}

The execution result is not the same as that by executing mannally on liunx os。

**Comment by TeslaCN** [comment]
The current script job executor will append the sharding context in JSON format to command arguments.

**Comment by kaihekaihe** [comment]
After execution of the commandline，the date is not in the file

**Comment by TeslaCN** [comment]
If the script job executor cannot satisfy your requirements, you may implement your own `JobItemExecutor`.
