### ISSUE TITLE
I can't find the branch which includes the code from Bug fix for Failover #714 

### ISSUE THREAD

**Issue by sucg** [apache/shardingsphere-elasticjob#1868]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

![image](https://user-images.githubusercontent.com/13437670/113835139-414bd000-97be-11eb-9e12-3850072cba2e.png)

Hi，Bug fix for Failover #714  merged into  apache:3.0 branch，but   I  can't find  the apache:3.0 branch

And I can't find the code from Bug fix for Failover #714 in the master branch.

So, I'd like to find which branch includes the code from Bug fix for Failover #714, thx~

**Comment by TeslaCN** [comment]
It seems that the commits were missing when refactoring this project. Could you submit a new PR?

**Comment by sucg** [comment]
of course , my pleasure~
