### ISSUE TITLE
任务执行后重启服务增加tracing功能不生效

### ISSUE THREAD

**Issue by Fdemo123** [apache/shardingsphere-elasticjob#1876]
## Bug Report

任务执行后重启服务增加tracing功能不生效，反过来也一样
源码中这段代码一直获取到的都是旧值
public JobConfiguration load(final boolean fromCache) {
        String result;
        if (fromCache) {
            result = jobNodeStorage.getJobNodeData(ConfigurationNode.ROOT);
            if (null == result) {
                result = jobNodeStorage.getJobNodeDataDirectly(ConfigurationNode.ROOT);
            }
        } else {
           result = jobNodeStorage.getJobNodeDataDirectly(ConfigurationNode.ROOT);
        }
        return YamlEngine.unmarshal(result, JobConfigurationPOJO.class).toJobConfiguration();
    }

**Comment by TeslaCN** [comment]
**For English only**
You may set `overwrite` to `true` to overwrite the configurations in Zookeeper.
