### ISSUE TITLE
Specify an ip when job instance application deployed on a multi-ip server.

### ISSUE THREAD

**Issue by gonedays** [apache/shardingsphere-elasticjob#1881]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No

### Describe the feature you would like.
When application doployed on a server with multi-ip, then the job instance will register to ZK with the first ip of org.apache.shardingsphere.elasticjob.infra.env.IpUtils#getIP(),  this may cause some network problem.  E.g, sheduling task failed to communicate with instance. Hope there is a configuration to specify the ip registed to ZK.

**Comment by TeslaCN** [comment]
Hi @gonedays 
You may specify an interface by `-Delasticjob.preferred.network.interface=eth0`

**Comment by SkyMoreStars** [comment]
Your computer's firewall Settings in stealth mode may cause this problem.

**Comment by TeslaCN** [comment]
Maybe we can sort out this issue to FAQ.

**Comment by gonedays** [comment]
Hi,@TeslaCN,
There is still a problem, when multiple application instances deployed on different server, and each server has different netwrok interfaces, but we has unified deployment script, then no way to specify the network interface for each application instance.
I guess we can have a better way, refer to spring cloud's choice(spring.cloud.inetutils.preferredNetworks=ip regular express), specify the prefix of ip address, or use regular express.  What do you think?

> Hi @gonedays
> You may specify an interface by `-Delasticjob.preferred.network.interface=eth0`
