### ISSUE TITLE
LiteJobFacade#isExecuteMisfired method is to first obtain the need for points from zk, and then determine whether misfired is turned on

### ISSUE THREAD

**Issue by seeger12138** [apache/shardingsphere-elasticjob#1883]
## Feature Request

**The LiteJobFacade#isExecuteMisfired method first obtains whether points are needed from zk`(!isNeedSharding())`, and then judges whether misfired is enabled`configService.load(true).isMisfire()`. This is a performance loss for the misfired configuration that is not turned on.**

### Is your feature request related to a problem?
**just suggestion**

### Describe the feature you would like.
**Reverse order` !isNeedSharding() && configService.load(true).isMisfire()` -> `configService.load(true).isMisfire() && !isNeedSharding()`. According to the short-circuit characteristics, if the misfired configuration is not turned on, there will be no additional performance loss.**

**Comment by TeslaCN** [comment]
Hi @seeger12138 
Thanks for your feedback! Are you interested in submitting a PR to fix this issue?

**Comment by seeger12138** [comment]
I am very happy to do this. Recently, I will take a detailed look at other places that can be optimized like this issue, and then make a summary and raise a PR together.
