### ISSUE TITLE
IpUtils.getIp()方法获取不到ip

### ISSUE THREAD

**Issue by chiangyn** [apache/shardingsphere-elasticjob#1889]
InetAddress..isReachable always false

**Comment by skaic** [comment]
this is your problem

**Comment by chiangyn** [comment]
这是InetAddress..isReachable java方法问题，在某些操作系统下会取不到ip。建议替换这个方法的使用

**Comment by chiangyn** [comment]
https://www.cnblogs.com/passedbylove/p/7561006.html 有人讨论过JDK bug这个问题

**Comment by TeslaCN** [comment]
Hi @chiangyn 
Could you please translate this issue to **English**?
I've read the solutions in the blog but I don't think those are suitable. Do you have any idea?

**Comment by TeslaCN** [comment]
Close due to no response.
