### ISSUE TITLE
add Tracing Api 

### ISSUE THREAD

**Issue by skaic** [apache/shardingsphere-elasticjob#1891]
## Question

I want have a Tracing Api , and I can use it to show the Tracing log in my admin page.

**Comment by TeslaCN** [comment]
Hi @skaic 
Could you query tracing logs from the database?

**Comment by sunkai-cai** [comment]
> Hi @skaic
> Could you query tracing logs from the database?

Of course , this is my new account, :)

**Comment by sunkai-cai** [comment]
> Hi @skaic
> Could you query tracing logs from the database?

of course. i do it now.
