### ISSUE TITLE
Task not performed at the expected time

### ISSUE THREAD

**Issue by forrimerico** [apache/shardingsphere-elasticjob#1893]
### Which version of ElasticJob did you use?
2.1.5
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Expected behavior
I got a task like 
Scheculed(Cron = 0 0 0 * *  ? *)
public void task()...

It is expected to be executed at 0 o'clock every day

### Actual behavior

In fact, it will be executed at a time other than 0 o'clock for no reason

**Comment by skaic** [comment]
Hi, @forrimerico

**Comment by skaic** [comment]
Hi @forrimerico 

When will it be executed after 0:00？

**Comment by linghengqian** [comment]
Cannot reproduce in master branch. Please provide unit tests.

**Comment by linghengqian** [comment]
Closed due to complete inability to reproduce in master branch.
