### ISSUE TITLE
Invoking other services

### ISSUE THREAD

**Issue by chenyujie-lab** [apache/shardingsphere-elasticjob#1895]
[Timed tasks call the Fegin interface, and there is a non-execution time execution]

**问题复现步骤:**

1. [Define a timed task to be executed every second, invoking service B]
2. [Start service B]
3. [Start service Job]

**期望的表现:**

[Service B is called every second]

**观察到的表现:**

[There are two calls per second]

![Console log](https://user-images.githubusercontent.com/49234299/119609112-9e145000-be29-11eb-9ff0-e76341403f2c.png)

**Elastic-Job版本:** [2.1.5-lite-spring]
**操作系统及版本:** [windows 10]

**Comment by TeslaCN** [comment]
Could you provide your job configurations? Is it possible that misfire happened?

**Comment by 9527J** [comment]
> 
> 
> Could you provide your job configurations? Is it possible that misfire happened?

`
    <reg:zookeeper id="regCenter" server-lists="127.0.0.1:2181" namespace="garbage-job" base-sleep-time-milliseconds="1000"
                   max-sleep-time-milliseconds="3000" max-retries="1" />
    <job:simple id="testTxLcnJob" class=""
                registry-center-ref="regCenter" cron="0/1 * * * * ?" overwrite="true" failover="false"
                sharding-item-parameters="0=a" description="This is a timed task" sharding-total-count="1"/>
`

**Comment by 9527J** [comment]
> 
> 
> Could you provide your job configurations? Is it possible that misfire happened?

**Comment by 9527J** [comment]
> 
> 
> Could you provide your job configurations? Is it possible that misfire happened?

@TeslaCN

**Comment by chenyujie-lab** [comment]
> 
> 
> Could you provide your job configurations? Is it possible that misfire happened?

`
    <job:simple id="testTxLcnJob" class=""
                registry-center-ref="regCenter" cron="0/1 * * * * ?" overwrite="true" failover="false"
                sharding-item-parameters="0=a" description="This is a timed task" sharding-total-count="1"/>
`
`
    <reg:zookeeper id="regCenter" server-lists="127.0.0.1:2181" namespace="garbage-job" base-sleep-time-milliseconds="1000"
                   max-sleep-time-milliseconds="3000" max-retries="1" />
`
