### ISSUE TITLE
I can't find the branch which includes the code from "Bug fix for clean resource when shutdown job. #705"

### ISSUE THREAD

**Issue by cjoin** [apache/shardingsphere-elasticjob#1897]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Hi，Bug fix for clean resource when shutdown job. #705 merged into apache:3.0 branch，but I can't find the apache:3.0 branch

And I can't find the code from Bug fix for clean resource when shutdown job. #705 in the master branch.

So,I think it is like issue #1868, It seems that the commits were missing when refactoring this project.

For this bug:  clean resource when shutdown job. I find three pull: #705 #798 #1867. Only first one can't find in master branch.

Can you confirm that these issues #605 #683 #686 #702 have been fixed in master branch?

**Comment by linghengqian** [comment]
- You are right, https://github.com/apache/shardingsphere-elasticjob/pull/705 is not on the master branch, Do you want to open a PR?

**Comment by linghengqian** [comment]
Although the relevant PR is not in the master branch, the relevant unit tests do not fail. Please consider providing your unit tests.

**Comment by linghengqian** [comment]
Closed due to not being able to reproduce.
