### ISSUE TITLE
Unable to find property 'jobClass' on class: org.apache.shardingsphere.elasticjob.infra.pojo.JobConfigurationPOJO

### ISSUE THREAD

**Issue by nanjinglex** [apache/shardingsphere-elasticjob#1899]
{"success":false,"errorCode":500,"errorMsg":"Unable to find property 'jobClass' on class: org.apache.shardingsphere.elasticjob.infra.pojo.JobConfigurationPOJO","model":null}

**Comment by nanjinglex** [comment]
![image](https://user-images.githubusercontent.com/44739893/121021317-d88bce80-c7d3-11eb-8cbb-b025f04a6730.png)

**Comment by TeslaCN** [comment]
ElasticJob 3.x is incompatible with 2.x. Try cleanup your ZooKeeper.
