### ISSUE TITLE
Filename too long error

### ISSUE THREAD

**Issue by xiangtao123** [apache/shardingsphere-elasticjob#1904]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Actual behavior

git push -u origin mastererror: open("elasticjob-ecosystem/elasticjob-error-handler/elasticjob-error-handler-type/elasticjob-error-handler-dingtalk/s
rc/main/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/DingtalkJobErrorHandler.java"): Filename too long
error: unable to index file 'elasticjob-ecosystem/elasticjob-error-handler/elasticjob-error-handler-type/elasticjob-error-ha
ndler-dingtalk/src/main/java/org/apache/shardingsphere/elasticjob/error/handler/dingtalk/DingtalkJobErrorHandler.java'
fatal: adding files failed

**Comment by skaic** [comment]
windows gui？you can search in google。

**Comment by TeslaCN** [comment]
https://shardingsphere.apache.org/document/current/en/faq/#13-in-windows-environmentwhen-cloning-shardingsphere-source-code-through-git-why-prompt-filename-too-long-and-how-to-solve-it
