### ISSUE TITLE
shardingsphere-elasticjob 节点 重启后 部分任务下线

### ISSUE THREAD

**Issue by G927538242** [apache/shardingsphere-elasticjob#1912]
![image](https://user-images.githubusercontent.com/48881364/123611842-97b43200-d834-11eb-909f-87eae4551221.png)
![image](https://user-images.githubusercontent.com/48881364/123611871-9e42a980-d834-11eb-99a3-2e93752c6b20.png)
![image](https://user-images.githubusercontent.com/48881364/123611892-a39ff400-d834-11eb-961e-9f97b459bb2f.png)

**Comment by TeslaCN** [comment]
Could you please translate the title into **English** and tell us the ElasticJob's version?

**Comment by G927538242** [comment]
ok
