### ISSUE TITLE
Specify an ip when job instance application deployed on multi-ip server with different network interface

### ISSUE THREAD

**Issue by gonedays** [apache/shardingsphere-elasticjob#1919]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
yes, [https://github.com/apache/shardingsphere-elasticjob/issues/1881](url)

### Describe the feature you would like.
The solution provided -Delasticjob.preferred.network.interface=eth0 can't meet the requirement as below:
When application instances deployed on different server, and each server has different netwrok interfaces, but we have unified deployment script, then no way to specify the network interface for each application instance.
I guess we can have a better way, refer to spring cloud's choice(spring.cloud.inetutils.preferredNetworks=ip regular express), specify the prefix of ip address, or use regular express. What do you think?

**Comment by sunkai-cai** [comment]
I can do it, assign to me thanks.
