### ISSUE TITLE
Is Operation API module still in incubation?

### ISSUE THREAD

**Issue by stanstanwang** [apache/shardingsphere-elasticjob#1924]
## Question

https://github.com/apache/shardingsphere-elasticjob/issues

Is Operation API module still in incubation?

and When will it be released？

**Comment by sunkai-cai** [comment]
It is released.  You can have a look [elasticjob-lite-lifecycle](https://github.com/apache/shardingsphere-elasticjob/tree/master/elasticjob-lite/elasticjob-lite-lifecycle)

**Comment by stanstanwang** [comment]
> It is released. You can have a look [elasticjob-lite-lifecycle](https://github.com/apache/shardingsphere-elasticjob/tree/master/elasticjob-lite/elasticjob-lite-lifecycle)

thanks
