### ISSUE TITLE
How should runtime job timeouts be checked？

### ISSUE THREAD

**Issue by dawang1024** [apache/shardingsphere-elasticjob#1926]
## How should runtime job timeouts be checked
this is question
![image](https://user-images.githubusercontent.com/67535305/124903958-14a29100-e017-11eb-9f55-0b746e2bbe58.png)

**Comment by sunkai-cai** [comment]
For English only.

**Comment by sunkai-cai** [comment]
Did you set the `job:distributed-listener:started-timeout-milliseconds` or `job:distributed-listener:completed-timeout-milliseconds` ?

**Comment by wangyanan0629** [comment]
I'm not setting

**Comment by dawang1024** [comment]
**Thank you. I figured out what the problem was**
