### ISSUE TITLE
How to configure Operation and maintenance platform and RESTFul API deployment？

### ISSUE THREAD

**Issue by happy999999999** [apache/shardingsphere-elasticjob#1927]
The elastic-job-lite-console is in the description document, but now, it cannot be implemented in the project. What should I do now to get "elasticjob-lite-console-${version}.tar.gz"?

**Comment by happy999999999** [comment]
> elastic-job-lite-console在描述文档中，但是现在在项目中无法实现。我现在应该怎么做才能获得“elasticjob-lite-console-${version}.tar.gz”？
https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/operation/deploy-guide/

**Comment by sunkai-cai** [comment]
look here. https://github.com/apache/shardingsphere-elasticjob-ui

**Comment by TeslaCN** [comment]
@sunkai-cai Thanks for your answer!
