### ISSUE TITLE
Is there a way for each application node to run a specified number of shards?  

### ISSUE THREAD

**Issue by lwtao** [apache/shardingsphere-elasticjob#1928]
比方说，应用有3个节点，设置每个节点运行1个分片，那该任务整个集群会运行3个分片，当应用进行扩容，到了5个节点，那系统会让新的节点也分配一个分片，整个集群会运行5个分片。

**Comment by TeslaCN** [comment]
Hi @lwtao 
Could you please translate your issue into English? Other language will not accept.
