### ISSUE TITLE
Elastic-Job task persistence

### ISSUE THREAD

**Issue by Yenuo** [apache/shardingsphere-elasticjob#1946]
1. Elastic-job supports the persistence of scheduled tasks to the database. The next time you start the service, you can read the scheduled tasks from the database for scheduled execution. At present, elasticjob-Lite does not support this, but elasticjob-Lite supports the tracking and persistence of task events to the database. Is there a plan to implement this persistence to the database?

2. Elastic-job inherits quartz. Why doesn't quartz's tasks persist to the database? The next time the service starts, you can call up all tasks in batch to continue to execute. Has elastic job removed this function?

3. I have a problem using elasticjob-Lite. Is this problem caused by not using elastic job correctly? Please help guide, thank you.
I using  elasticjob-Lite version 3.0.0

**Comment by Yenuo** [comment]
In other words, after the service is restarted, how to pull up the tasks in zookeeper and execute scheduled tasks.

**Comment by Yenuo** [comment]
https://github.com/apache/shardingsphere-elasticjob/issues/706
The problem is the same as mine，How did you solve it？

**Comment by TeslaCN** [comment]
ElasticJob doesn't rely on Database. Job configurations are persisted in the Registry Center. Quartz is used to trigger the job.
Could you tell me something about your scenario?

**Comment by Yenuo** [comment]
My appeal is that the service needs to be able to dynamically add and delete scheduled tasks, and can continue to execute the previously created scheduled tasks after the service is restarted. 
Service refers to the dynamic management task implemented by job scheduling using elasticjob-Lite（ https://shardingsphere.apache.org/elasticjob/current/cn/quick-start/elasticjob-lite/ ）

**Comment by Yenuo** [comment]
> ElasticJob doesn't rely on Database. Job configurations are persisted in the Registry Center. Quartz is used to trigger the job.
> Could you tell me something about your scenario?

 Registry center refers to the zookeeper?  
Two more questions about this zookeeper?
1. How to re launch the crashed task?
2. Why are some tasks executed by two instances and some by only one instance?
![image](https://user-images.githubusercontent.com/29774996/127444238-cf63bfe7-29a7-400a-81a0-da1f0bd2cbeb.png)

**Comment by TeslaCN** [comment]
> > ElasticJob doesn't rely on Database. Job configurations are persisted in the Registry Center. Quartz is used to trigger the job.
> > Could you tell me something about your scenario?
> 
> Registry center refers to the zookeeper?
> Two more questions about this zookeeper?
> 
> 1. How to re launch the crashed task?
> 2. Why are some tasks executed by two instances and some by only one instance?
>    ![image](https://user-images.githubusercontent.com/29774996/127444238-cf63bfe7-29a7-400a-81a0-da1f0bd2cbeb.png)

ElasticJob is a SDK, you can make good use of it in your way. I wrote a demo about schedule jobs dynamically, you may refer to it.
https://github.com/TeslaCN/flexijob/blob/master/src/main/java/icu/wwj/flexijob/internal/listener/NewJobListener.java
