### ISSUE TITLE
Maybe JobScheduler adjusts the constructor to init jobConfig first?

### ISSUE THREAD

**Issue by CherishCai** [apache/shardingsphere-elasticjob#1951]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
invoke first `this.jobConfig = setUpFacade.setUpJobConfiguration(jobClassName, jobConfig);` .

### Describe the feature you would like.
Process jobConfig first, whichever is in the configuration center or now Overwrite.

adjust like this:
```java
        String jobClassName = JobClassNameProviderFactory.getProvider().getJobClassName(elasticJob);
        this.jobConfig = setUpFacade.setUpJobConfiguration(jobClassName, jobConfig);
        Collection<ElasticJobListener> jobListeners = getElasticJobListeners(jobConfig);
        setUpFacade = new SetUpFacade(regCenter, jobConfig.getJobName(), jobListeners);
```

**Comment by CherishCai** [comment]
![image](https://user-images.githubusercontent.com/16837364/128282670-7acf9126-441c-4a7b-b1d6-8141187b8406.png)

**Comment by CherishCai** [comment]
At present, the configuration in ZK shall prevail, but not all, so there will be ambiguity.

目前是以 zk 内的配置为准又不是全部为准，所以会有歧义。

**Comment by linghengqian** [comment]
- Would you like to file a PR on this?

**Comment by CherishCai** [comment]
> * Would you like to file a PR on this?

Sorry, I haven't followed this for a long time, so I couldn't PR on this

**Comment by linghengqian** [comment]
- It looks like the adjustment you requested is handled in #2187.
