### ISSUE TITLE
Feature: ElasticJobListener has an order or Reverse order call afterJobExecuted().

### ISSUE THREAD

**Issue by CherishCai** [apache/shardingsphere-elasticjob#1961]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem? Describe the feature you would like.

JobConfiguration can set multiple ElasticJobListeners, In some scenarios, it is expected that this listener will be triggered sequentially, and perhaps the front and rear listeners have related dependencies.

So, 
1. Maybe ElasticJobListener has an order,

2. Or Reverse order call afterJobExecuted().
```java
@Override
    public void beforeJobExecuted(final ShardingContexts shardingContexts) {
        for (ElasticJobListener each : elasticJobListeners) {
            each.beforeJobExecuted(shardingContexts);
        }
    }
    
    @Override
    public void afterJobExecuted(final ShardingContexts shardingContexts) {
        for (int i = elasticJobListeners.size() - 1; i >= 0; i--) {
            elasticJobListeners.get(i).afterJobExecuted(shardingContexts);
        }
    }
```

**Comment by sunkai-cai** [comment]
Hi @CherishCai 

Thanks for your proposal, the ElasticJobListener supported it in the next version. look at this: https://github.com/apache/shardingsphere-elasticjob/pull/1943.

**Comment by CherishCai** [comment]
Oh, I'm sorry, I already mentioned it.

**Comment by CherishCai** [comment]
Like this: #1943. So close.
