### ISSUE TITLE
请问，单机但是有大量的定时任务的场景适用吗？

### ISSUE THREAD

**Issue by NiuGui8** [apache/shardingsphere-elasticjob#1964]
## Question
用于边缘服务器有大量定时任务的场景，边缘服务器通常都是单机的，这种情况适用吗？

**Comment by sunkai-cai** [comment]
Hi @NiuGui8 

Welcome to question.  Please translate your issue into English, thanks.

shardingsphere-elasticjob able to support singl-machine service.
