### ISSUE TITLE
How to clear dynamic tasks?

### ISSUE THREAD

**Issue by xiebin2015** [apache/shardingsphere-elasticjob#1969]
Hello, I have a dynamic task (executed once at a certain time point). In fact, my expectation is that it will be cleared automatically after only one execution. What should I do?

**Comment by TeslaCN** [comment]
I think my idea #1654 is similar with this issue. How do you think?

**Comment by linghengqian** [comment]
> How to clear dynamic tasks? 

- Feel free to check out #2426 in `org.apache.shardingsphere.elasticjob.test.natived.it.operation.JavaTest` for ways to add, delete, modify, and query jobs. Directly define `org.apache.shardingsphere.elasticjob.bootstrap.type.OneOffJobBootstrap` dynamically.
