### ISSUE TITLE
在elasticjob-lite-spring-boot-starter中当任务对象有子类时启动报错

### ISSUE THREAD

**Issue by dengbin19910916** [apache/shardingsphere-elasticjob#1973]
使用ElasticJobBootstrapConfiguration时如果Job class 被继承之后，应用启动报错，
原因是：ElasticJobBootstrapConfiguration#registerClassedJob中获取elasticJob bean的代码 ElasticJob elasticJob = applicationContext.getBean(jobConfigurationProperties.getElasticJobClass());只使用了elasticJobClass，而没有使用jobName。这个地方是否可以通过 ElasticJob elasticJob = applicationContext.getBean(jobName， jobConfigurationProperties.getElasticJobClass());获取job bean，或者添加一个beanName协助获取唯一的job bean。

**Comment by TeslaCN** [comment]
Hi @dengbin19910916 
For English only. Could you please translate your issue into English?

**Comment by dengbin19910916** [comment]
@TeslaCN 英语不好怎么办？可以用百度翻译吗？

**Comment by TeslaCN** [comment]
**For English only**, other languages will not accept.
