### ISSUE TITLE
How to dynamically add tasks in elastic job 3?

### ISSUE THREAD

**Issue by xiebin2015** [apache/shardingsphere-elasticjob#1974]
Hi, I'm using elasitcjob3 now. How can I dynamically add tasks?

**Comment by TeslaCN** [comment]
Hi @xiebin2015 
I have an idea about adding jobs dynamically. Starting a listener and persist job configurations to Registry Center. This is a demo of my idea.
https://github.com/TeslaCN/flexijob/blob/master/src/main/java/icu/wwj/flexijob/internal/listener/NewJobListener.java

**Comment by xiebin2015** [comment]
Hello, thank you for your suggestion. Another question is, how can I dynamically modify the task configuration, such as execution time？

**Comment by xiebin2015** [comment]
Hi, I already have a solution, thank you
