### ISSUE TITLE
JobOperateAPIImpl#trigger not work

### ISSUE THREAD

**Issue by stanstanwang** [apache/shardingsphere-elasticjob#1981]
### Which version of ElasticJob did you use?
3.0.0

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Expected behavior
https://shardingsphere.apache.org/elasticjob/current/cn/user-manual/elasticjob-lite/usage/operation-api/#%E5%90%AF%E7%94%A8%E4%BD%9C%E4%B8%9A

runonce and clean the trigger flag

### Actual behavior

the job not run anymore  , and the trigger flag not change
![image](https://user-images.githubusercontent.com/19669879/134809479-592e7dff-003c-4d07-8d90-ee710dfb0e65.png)

### Steps to reproduce the behavior.

1. start a cron job
2. the job run in cron normally
3. using the api JobOperateAPI#trigger
4. the job no run anymore

**Comment by sunkai-cai** [comment]
Hi， @stanstanwang 

Could you provide more information about it?

**Comment by stanstanwang** [comment]
my probolem is using the api `org.apache.shardingsphere.elasticjob.lite.lifecycle.internal.operate.JobOperateAPIImpl#trigger`  to trigger the cron job run once not work !

and the cron job  zk instance node with the `TRIGGER` flag no change,   which cause the cron job not run anymore.

This is the Actual Behavior ,  is there any bug in the API itself ? but I don't know how to check, could you plese share some approch to check this.. thanks

**Comment by stanstanwang** [comment]
> Hi， @stanstanwang
> 
> Could you provide more information about it?

my probolem is using the api `org.apache.shardingsphere.elasticjob.lite.lifecycle.internal.operate.JobOperateAPIImpl#trigger` to trigger the cron job run once not work !

and the cron job zk instance node with the`TRIGGER` flag no change, which cause the cron job not run anymore.

This is the Actual Behavior , is there any bug in the API itself ? but I don't know how to check, could you plese share some approch to check this.. thanks

**Comment by sunkai-cai** [comment]
Maybe you can try to check the parameter  `regCenter`  of ` new JobOperateAPIImpl(regCenter)`.

**Comment by stanstanwang** [comment]
> Maybe you can try to check the parameter `regCenter` of ` new JobOperateAPIImpl(regCenter)`.

![image](https://user-images.githubusercontent.com/19669879/134852401-67552875-4f22-456f-953e-023d09aa7d6a.png)


the same, i have already connected the zk server ,seeing the instance node  with `TRIGGER` flag, 

which before using this api  `JobOperateAPIImpl#trigger`  the value as below

![image](https://user-images.githubusercontent.com/19669879/134853128-9ba60e17-3713-419e-857f-6405e7d14c3d.png)

**Comment by stanstanwang** [comment]
is there only work in 3.0.0-RC1 ? now my version is  3.0.0, i change the version to 3.0.0-RC1,this works.

the difference between the two version is in  3.0.0-RC1 zk instance node ' s  value is empty

![image](https://user-images.githubusercontent.com/19669879/134856084-08648261-f6b9-4459-a196-aeffccb98149.png)

**Comment by TeslaCN** [comment]
Thanks for your report. This is a bug in 3.0.0 and has been fixed in master branch.
https://github.com/apache/shardingsphere-elasticjob/pull/1936
