### ISSUE TITLE
why i can't find the code where the LiteJobFacade.getShardingContexts() is called?

### ISSUE THREAD

**Issue by colin0000007** [apache/shardingsphere-elasticjob#1983]
I read the elasticjob-lite-core source code through the official tutorial demo code recently. when i read the resharding part, i found that the ShardingTotalCountChangedJobListener and ListenServersChangedJobListener will set a /jobName/leader/sharding/necessary flag when /jobName/instances node or /jobName/server node or config node changed, but the listener only set a flag which indicates it need to reshard. I guess the /jobName/sharding/necessary node adding will trigger to call ShardingService.shardingIfNecessary(). yes, the getShardingContexts function called shardingIfNecessary(). But I never find the code where the LiteJobFacade.getShardingContexts() is called. 

ElasticJob version:3.0.0

**Comment by sunkai-cai** [comment]
`LiteJobFacade.getShardingContexts()`  be called When ElasticJob executing, in `ElasticJobExecutor.execute()` .

**Comment by colin0000007** [comment]
ok,thanks
