### ISSUE TITLE
如果分片的任务失败（代码业务异常），会是什么状态，能进行重试么？

### ISSUE THREAD

**Issue by chenlei0615** [apache/shardingsphere-elasticjob#1984]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by sunkai-cai** [comment]
hi @chenlei0615 

Welcome your question. Could you please translate your issue into English?

**Comment by chenlei0615** [comment]
If an error occurs in a sharding task (eg: The exception occurs in the business logic of the code ), Does it support retry? how can i retry it?

**Comment by TeslaCN** [comment]
> If an error occurs in a sharding task (eg: The exception occurs in the business logic of the code ), Does it support retry? how can i retry it?

Hi @chenlei0615
Please translate the title of your issue into English.
Could you try the `failover`?
