### ISSUE TITLE
Roadmap？路线图？

### ISSUE THREAD

**Issue by zhenchuan9r** [apache/shardingsphere-elasticjob#1998]
I am very intereted in this project but I'm not aware of what is going on in this project.
I don't really like db-based event tracing mechanism in this project, because it requires us to share un/pw among projects.
However, plans of an alternative method is not published.
Thus I think a roadmap of this project is greatly appreciated.
我对这个项目很感兴趣，但是我不清楚贵方在开发什么特性。
我其实很讨厌基于DB的时间追踪方法，因为它要求我们在各个项目中共用相关数据库的用户名和密码。
然而，虽然文档里面说目前是这样，但是没有说有什么替代方案的开发计划。
所以若贵方能提供一个路线图，万分感谢。

**Comment by sunkai-cai** [comment]
hi @zhenchuan9r 
You can extend the tracing through SPI.

**Comment by zhenchuan9r** [comment]
> hi @zhenchuan9r You can extend the tracing through SPI.

Thanks for you information. Nevertheless, I think a roadmap of this project is necessary.
除此之外，更需要的是整个项目的路线图。

**Comment by zhenchuan9r** [comment]
Like, if you have a plan to integrate elasticjob-cloud with Kubernetes rather than Meso.
Or, if you have a plan to offer another version of elasticjob-cloud without a dependency on Meso.
比如，是否有计划让Elasticjob-cloud和Kubernetes进行更深度的整合并且剔除Meso，或者另开一个不依赖Meso版本。

**Comment by sunkai-cai** [comment]
of course， you can look at https://github.com/apache/shardingsphere-elasticjob/issues/1690
