### ISSUE TITLE
Do we have a detailed plan/roadmap  for Job Dependency

### ISSUE THREAD

**Issue by cyq89051127** [apache/shardingsphere-elasticjob#2000]
## Question

When i check the docs, i  see a greate feature (Job Dependency) which is very import for our situation,  but it's a TODO featre .   Do we have a  detailed plan/roadmap  for Job Dependency .

**Comment by linghengqian** [comment]
- Located at https://shardingsphere.apache.org/elasticjob/current/en/dev-manual/roadmap/ .
