### ISSUE TITLE
应用服务接了 elastic job ,应用服务容器化后，每次启动了对应的服务ip都是不同的，导致 servers 的ip列表会越来越多，一个应用比如有几十个节点多次重启后就会导致这个job的 servers有上千个，接入的应用越多，导致zk节点存储的 servers 的ip 越来越多，有啥好的解决方法？

### ISSUE THREAD

**Issue by hujin031140211** [apache/shardingsphere-elasticjob#2008]
![image](https://user-images.githubusercontent.com/6998006/141437729-7d05710a-1d52-4cb4-b808-e0c3bb80bfea.png)

应用服务接了 elastic job ,应用服务容器化后，每次启动了对应的服务ip都是不同的，导致 servers 的ip列表会越来越多，一个应用比如有几十个节点多次重启后就会导致这个job的 servers有上千个，接入的应用越多，导致zk节点存储的 servers 的ip 越来越多，有啥好的解决方法？

**Comment by TeslaCN** [comment]
Hi @hujin031140211 
For English only. Please translate your issue into English.

**Comment by hujin031140211** [comment]
not

**Comment by wenliumeng** [comment]
这个问题有啥好的解决思路了没？

**Comment by hujin031140211** [comment]
定时删除无效的节点&nbsp;


黄进
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "seymour ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午2:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [apache/shardingsphere-elasticjob] 应用服务接了 elastic job ,应用服务容器化后，每次启动了对应的服务ip都是不同的，导致 servers 的ip列表会越来越多，一个应用比如有几十个节点多次重启后就会导致这个job的 servers有上千个，接入的应用越多，导致zk节点存储的 servers 的ip=?UTF-8?Q?_=E8=B6=8A=E6=9D=A5=E8=B6=8A=E5=A4=9A=EF=BC=





 
这个问题有啥好的解决思路了没？

**Comment by bruse-peng** [comment]
> 定时删除无效的节点&nbsp; 黄进 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "seymour ***@***.***&gt;; 发送时间: 2022年10月26日(星期三) 下午2:10 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [apache/shardingsphere-elasticjob] 应用服务接了 elastic job ,应用服务容器化后，每次启动了对应的服务ip都是不同的，导致 servers 的ip列表会越来越多，一个应用比如有几十个节点多次重启后就会导致这个job的 servers有上千个，接入的应用越多，导致zk节点存储的 servers 的ip=?UTF-8?Q?_=E8=B6=8A=E6=9D=A5=E8=B6=8A=E5=A4=9A=EF=BC= 这个问题有啥好的解决思路了没？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

怎么确定是无效的节点？
