### ISSUE TITLE
APPLICATION FAILED TO START ”A component required a bean named '***' that could not be found.“

### ISSUE THREAD

**Issue by prefect1005** [apache/shardingsphere-elasticjob#2014]
### Which version of ElasticJob did you use?
elasticjob-lite-spring-boot-starter  3.0.1

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Actual behavior

***************************
APPLICATION FAILED TO START
***************************
Description:
A component required a bean named 'myOneOffJobBean' that could not be found.

my config:
elasticjob.jobs.oneOffJob.elasticJobClass=com.example.demo.MyElasticJob
elasticjob.jobs.oneOffJob.jobBootstrapBeanName=myOneOffJobBean
elasticjob.jobs.oneOffJob.shardingTotalCount=3

in controller:
@Resource(name = "myOneOffJobBean")
private OneOffJobBootstrap myOneOffJobBean;

### Reason analyze (If you can)

in 3.0.0 version is ok
i find  
https://github.com/apache/shardingsphere-elasticjob/issues/1810
this issues 

and  in this merge
https://github.com/apache/shardingsphere-elasticjob/pull/1930/commits/0446a5d9a12e8a83300316b8de044c107328ddd7
JobBootstrapBeans instantiation in afterSingletonsInstantiated

just because of this，in application Controller ， the OneOffJobBootstrap has not init.
so what can i do? 

hope to reply, thanks

**Comment by prefect1005** [comment]
@skaic

**Comment by DoolinMa** [comment]
@prefect1005 you can put @Lazy annotation on Controller to make sure the application is running normally
```
@Lazy
public class OneOffJobController {
```

**Comment by cocodroid** [comment]
You can also use @Autowried(required=false) @Qualifier("myOneOffJobBean")

**Comment by ceylog** [comment]
I also have the same problem

**Comment by kingkh1995** [comment]
I take this issue.
my [mr](https://github.com/apache/shardingsphere-elasticjob/pull/2306)

**Comment by kingkh1995** [comment]
I take this issue 
#2307

**Comment by kingkh1995** [comment]
#1930 this fix is the cause of this issue, i think the only solution is lazy init, **but OneOffBootStrap is final**.

#1810 if we need to autowire OneOffBootStrap, OneOffBootStrap need to be registered before AutowiredAnnotationBeanPostProcessor, so ElasticJobProperties bean need to be initialized before AutowiredAnnotationBeanPostProcessor, which means ElasticJobProperties will be not eligible for getting processed by all BeanPostProcessors.

**Comment by linghengqian** [comment]
> #1930 this fix is the cause of this issue, i think the only solution is to lazy init, **but OneOffBootStrap is final**.

- I'm tracking this behavior at https://github.com/apache/shardingsphere-elasticjob/issues/2258 .  There are known issues with the Spring Bean introspection of ElasticJob Lite's Spring Boot Starter, and similar behavior has been found in many third-party Spring Boot Starters.

**Comment by kingkh1995** [comment]
another way is to use @Lookup, is this okay? @linghengqian 
```
@Lookup("onceJobBootstrap")
public OneOffJobBootstrap getOnceJobBootstrap() {
    return null;
}
```

**Comment by linghengqian** [comment]
- @prefect1005 I'm no Spring expert, but the reality is that some beans in ElasticJob's Spring Boot Starter may require additional fully parameterized constructors.

- There is no movement in #2258 mainly because I am working on https://github.com/apache/shardingsphere/issues/29052 and can’t spare much time.

**Comment by linghengqian** [comment]
- Reproduced at https://github.com/apache/shardingsphere-elasticjob/pull/2417 . I will fix this documentation issue.
- I personally would never recommend using `@Lazy`, it is not in line with normal human thinking.
