### ISSUE TITLE
How can I  use job tracing rdb  diff  from  job main program

### ISSUE THREAD

**Issue by kevinsir** [apache/shardingsphere-elasticjob#2015]
## base
springboot 2.5.5
elasticjob-lite-core 3.0.0
elasticjob-lite-spring-boot-starter 3.0.0
Every thing is ok. I can run and trace the job .However I  want to store the trace differ  from job program. Now they are using the same mysql database. I want to use two database . One is the job database,one is the tracing database
How can  I do it ?

**Comment by TeslaCN** [comment]
The ElasticJob Spring Boot Starter doesn't support this yet. You may use the Java API.
https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/usage/tracing/java-api/
