### ISSUE TITLE
jobs can not be distributed to multi nodes

### ISSUE THREAD

**Issue by bjwsz** [apache/shardingsphere-elasticjob#2017]
1.Use elasticjob-lite to add mulit jobs to same zookeeper and same namespace, with sharding count is 1, I tested with 100 jobs with 3 servers, all of the jobs will run only on one sever, once the running server is down, then all jobs will turned to another server.
_**jobConfig = JobConfiguration.newBuilder(task.getId() + "@" + task.getName(), 1).cron(task.getCron()).overwrite(true).build();**_
2.If sharding count is greater than one, then the shading will run on various servers, but my job is simple, no sharding.
3.I just want the jobs to run on multi servers by distribution.

**Comment by TeslaCN** [comment]
Hi @bjwsz 
You may change the job sharding strategy in `JobConfiguration`.
Refer to https://shardingsphere.apache.org/elasticjob/current/en/dev-manual/sharding/

**Comment by bjwsz** [comment]
Solved, it is perfect to use 'ROUND_ROBIN' strategy. 
Thanks a lot.
