### ISSUE TITLE
Jobs executed in wrong time

### ISSUE THREAD

**Issue by ilyng** [apache/shardingsphere-elasticjob#2023]
I hava a job execute every day, the cron is 00 58 23 * * ? *

but, yesterday, I found the job executed at 15:42.

I hava no idea about why the job triggered

![image](https://user-images.githubusercontent.com/24428629/147176484-ed46f90e-5ce4-4af1-9406-395421d7b733.png)

**Comment by TeslaCN** [comment]
Did you enabled the `failover`?

**Comment by ilyng** [comment]
> Did you enabled the `failover`?

yes,failover is enabled，and I found that，it  happened when the server was restart. I have closed the failover, it work well now. thanks for reply
