### ISSUE TITLE
Sharding item for job is empty

### ISSUE THREAD

**Issue by lisongyuegit** [apache/shardingsphere-elasticjob#2031]
公司需要处理的数据量算中等,后面计划用多台服务器执行,现在就一台定时任务服务器部署了ElasticJob,设置了总分片数据为1,但是会出现Sharding item for job is empty.然后就下线了,请问下是什么原因

**Comment by TeslaCN** [comment]
Hi @lisongyuegit Please translate your issue into English.
And we need you to provide more info to help us reproduce this issue, thank you.

**Comment by ilyng** [comment]
I have a situation just like this, but my job not shutnow.

I hava 2 servers to run my job, and the job's sharding total count is 1.
The trace status log just like below.

![image](https://user-images.githubusercontent.com/24428629/148023064-7518f64c-6349-4f90-b6fd-f43ec065fa8f.png)

I hava no idea about whether it is right.

**Comment by TeslaCN** [comment]
> I have a situation just like this, but my job not shutnow.
> 
> I hava 2 servers to run my job, and the job's sharding total count is 1. The trace status log just like below.
> 
> ![image](https://user-images.githubusercontent.com/24428629/148023064-7518f64c-6349-4f90-b6fd-f43ec065fa8f.png)
> 
> I hava no idea about whether it is right.

Your situation is normal. There is only 1 sharding item, so there will be only 1 server executes the task and the others will execute no sharding item.

**Comment by smartBun** [comment]
> 

Thank you
