### ISSUE TITLE
Under what circumstances will the task appear offline?

### ISSUE THREAD

**Issue by lisongyuegit** [apache/shardingsphere-elasticjob#2040]
Sharding item for job 'jobName' is empty. appears after the scheduled task runs for a period of time

Then it goes offline. Under what circumstances will the task go offline?

**Comment by sunkai-cai** [comment]
I can‘t get your point. Can you give an example?

**Comment by linghengqian** [comment]
Closed due to lack of reproducible unit tests and no response.
