### ISSUE TITLE
Is there a possibility to save the Jobs' configuration in the database?

### ISSUE THREAD

**Issue by springmonster** [apache/shardingsphere-elasticjob#2043]
## Question
Hello, we are currently using springboot + elasticjob-lite to manage our jobs.

But because there are too many jobs in the production environment, it is a bit inconvenient to configure jobs in the YAML file or PROPERTIES file. 

We want to ask about is it possible or is there a way to read job information from the database? This will make it easier for us to maintain.

If possible, what should we do in a proper way?

Thanks very much!

**Comment by sunkai-cai** [comment]
if support annotation Job,  see whether it work or not ？https://github.com/apache/shardingsphere-elasticjob/issues/1445
