### ISSUE TITLE
I think ElasticJobBootstrapConfiguration implements SmartInitializingSingleton have a bug

### ISSUE THREAD

**Issue by Summary-wcj** [apache/shardingsphere-elasticjob#2044]
I think ElasticJobBootstrapConfiguration implements SmartInitializingSingleton have a bug.

I use ElasticJob Lite

I don't know how to describe this error, but you can repeat this problem. I use the starter and email dependency of version 3.0.0, then use the job in OneOffJobBootstrap, and then start the program. It will appear that the bean of this task cannot be obtained during injection.

1.version: 
    3.0.1
    ElasticJob Lite
2.Expected 
    start success
3.Actual 
    start fail
4.Reason analyze
    I think implements SmartInitializingSingleton after @RestController is loaded and The bean was not taken over by spring when it was used.
5.Steps to reproduce the behavior
   a.Configure one-time scheduled tasks in the YML file
   b.Write a controller
   c.Write a task implements simplejob and add @Component annotation on the class
6.Example codes for reproduce this issue
   https://github.com/Summary-wcj/elastic-job.git

**Comment by cocodroid** [comment]
#2014

**Comment by Summary-wcj** [comment]
thanks very much
