### ISSUE TITLE
starter修改分片数量不起作用。

### ISSUE THREAD

**Issue by cdTigr** [apache/shardingsphere-elasticjob#2063]
starter version:   
     <dependency>
            <groupId>org.apache.shardingsphere.elasticjob</groupId>
            <artifactId>elasticjob-lite-spring-boot-starter</artifactId>
            <version>3.0.1</version>
        </dependency>

yaml:
`elasticjob:
  regCenter:
    serverLists: 127.0.0.1:2181
    namespace: elasticjob-lite-new
  jobs:
    uploadProject:
      elasticJobClass: xxxxxx
      cron: 0/15 * * * * ?
      sharding-total-count: 2`

question step:
 1. 首次设置分片数量为5。执行正常
 2. 修改分片数量值为2，仍然按照第一次的分片数量在执行
 3. 修改namespace重启服务，执行正常
 4. 重启zookeeper之后执行的仍然是第一次的配置。

**Comment by TeslaCN** [comment]
Please translate your issue into English.
You may need to set overwrite to `true`.
