### ISSUE TITLE
why elasticjob cloud use apache mesos instead of k8s(docker)?

### ISSUE THREAD

**Issue by sola634** [apache/shardingsphere-elasticjob#2064]
Hi @terrymanu 
    
    We're studying elasticjob and want to adopt it in our project, but we found it use apache mesos in elaticjob cloud. We're curious that why you use apache mesos in elasticjob cloud project instead of use k8s(docker) as a popular technology. May I know what's your consider about for it, and the main reason to use apache mesos? 

We're hoping your reply, many thanks.

Best regards,
Sola.

**Comment by TeslaCN** [comment]
ElasticJob has already integrated with Apache Mesos in early version. Since the Apache Mesos was retired to the Attic, we may remove it from future release and try integrating with Kubernetes or something else.

**Comment by sola634** [comment]
> ElasticJob has already integrated with Apache Mesos in early version. Since the Apache Mesos was retired to the Attic, we may remove it from future release and try integrating with Kubernetes or something else.

noted & thanks.

**Comment by TeslaCN** [comment]
I'm closing this. Please open a new issue if you have any other questions.
