### ISSUE TITLE
Multi slice useless scheduling

### ISSUE THREAD

**Issue by muchengyang** [apache/shardingsphere-elasticjob#2067]
When I use Lite core to develop a 3-slice task, the same actuator will be called three times. Is this a little redundant? And the more slices, the more frequent this useless call. Personally, I think this is mainly useful when centralization is used. Decentralized scheduling is actually useless. Can it be improved
![image](https://user-images.githubusercontent.com/16506338/163911398-ae20ddbd-f977-400d-9f6c-055dc45662c6.png)

**Comment by muchengyang** [comment]
config
cron: 0/5 * * * * ?
description: ''
disabled: false
failover: false
jobExtraConfigurations:
- !!org.apache.shardingsphere.elasticjob.tracing.yaml.YamlTracingConfiguration
  tracingStorageConfiguration: !!org.apache.shardingsphere.elasticjob.tracing.rdb.yaml.YamlDataSourceConfiguration
    dataSourceClassName: org.apache.commons.dbcp2.BasicDataSource
    props:
      logAbandoned: false
      numTestsPerEvictionRun: 3
      url: jdbc:h2:mem:job_event_storage
      timeBetweenEvictionRunsMillis: -1
      enableAutoCommitOnReturn: true
      removeAbandonedTimeout: 300
      lifo: true
      driverClassName: org.h2.Driver
      softMinEvictableIdleTimeMillis: -1
      rollbackOnReturn: true
      abandonedUsageTracking: false
      testOnBorrow: true
      testOnReturn: false
      numIdle: 1
      maxIdle: 8
      minIdle: 0
      logExpiredConnections: true
      maxTotal: 8
      numActive: 0
      defaultTransactionIsolation: -1
      testOnCreate: false
      removeAbandonedOnMaintenance: false
      fastFailValidation: false
      password: ''
      cacheState: true
      initialSize: 0
      maxWaitMillis: -1
      validationQueryTimeout: -1
      evictionPolicyClassName: org.apache.commons.pool2.impl.DefaultEvictionPolicy
      maxOpenPreparedStatements: -1
      removeAbandonedOnBorrow: false
      connectionInitSqls: []
      testWhileIdle: false
      autoCommitOnReturn: true
      minEvictableIdleTimeMillis: 1800000
      maxConnLifetimeMillis: -1
      username: sa
  type: RDB
jobName: scriptElasticJob
jobParameter: ''
maxTimeDiffSeconds: -1
misfire: true
monitorExecution: true
overwrite: false
props:
  script.command.line: D:\workspace\shardingsphere-elasticjob\examples\elasticjob-example-lite-java\target\classes\script\demo.bat
reconcileIntervalMinutes: 10
shardingItemParameters: ''
shardingTotalCount: 3
staticSharding: false

**Comment by TeslaCN** [comment]
The logic is same, but the elements in `items` are different between instances.

**Comment by muchengyang** [comment]
Yes, the processing elements are different. It's just that any instance is executing this useless for loop. I think it's just unnecessary

**Comment by TeslaCN** [comment]
> Yes, the processing elements are different. It's just that any instance is executing this useless for loop. I think it's just unnecessary

Sorry, I can't get your point. Why the loop is useless and what is unnecessary?

**Comment by TeslaCN** [comment]
Close due to no response.
