### ISSUE TITLE
Build CuratorFrameworkFactory supports an option to skip Ensemble tracking.

### ISSUE THREAD

**Issue by smallersoup** [apache/shardingsphere-elasticjob#2072]
### Is your feature request related to a problem?
Yes，in my scene，the curator connects to the zookeeper cluster in Kubernetes, the Pod may restart at any time, and the pod IP changes, so to close the ensembleTracker, then curator connects the zookeeper service cluster IP forever.

### Describe the feature you would like.

Build CuratorFrameworkFactory lacks an option to skip Ensemble tracking.
CuratorFrameworkFactory.Builder include a new option that allows to skip ensemble tracking. This can be useful in certain scenarios in which CuratorFramework is accessing to zookeeper clusters via load balancer or Virtual IPs. In this case ensemble tracking is avoiding CuratorFramework to support this kind of connectivity.

Proposal suggest including in ZookeeperConfiguration new field:
● private boolean ensembleTracker = true that allows to enable / disable ensembleTracker，then default value will return true for backwards compatibility.
● init method in ZookeeperRegistryCenter build CuratorFrameworkFactory set ensembleTracker(zkConfig.isEnsembleTracker()).

This Proposal suggest can refer to: [https://issues.apache.org/jira/browse/CURATOR-568](https://issues.apache.org/jira/browse/CURATOR-568)

**Comment by linghengqian** [comment]
- So you want to PR this?

**Comment by xull1995** [comment]
I'm facing the same issue. My ZooKeeper cluster is deployed on Kubernetes, and the ZooKeeper nodes are using a headless service. As a result, the headless domain is written under the` /zookeeper/config` znode. Because Curator (version higher than 3.0.0) defaults to enabling Ensemble tracking, this causes the client program to resolve the headless domain and fail during reconnection.

 have any plans for a fix?

**Comment by linghengqian** [comment]
- @xull1995 It depends on whether you or someone else is interested in submitting a PR. I am only a committer on the ShardingSphere side, so I don’t know much about the internal structure of the ShardingSphere Elasticjob side.

**Comment by linghengqian** [comment]
- I have opened https://github.com/apache/shardingsphere-elasticjob/pull/2458 .
