### ISSUE TITLE
elasticjob-lite v3.0.1 After the job is created in the project, the timer can be scheduled normally. But once the project restarts, the jobs created are invalidated

### ISSUE THREAD

**Issue by jbgzz** [apache/shardingsphere-elasticjob#2082]
创建方式：
JobConfiguration jobConfig = JobConfiguration.newBuilder(command.getName(), shardingTotalCount)
        .timeZone("GMT+8")
        .cron(command.getCron())
        .jobParameter(JsonUtils.serialize(parameterMap))
        .monitorExecution(true)
        .failover(true)
        .misfire(true)
        .maxTimeDiffSeconds(60)
        .reconcileIntervalMinutes(1)
        .addExtraConfigurations(new TracingConfiguration("RDB", this.dataSource))
        .description(command.getDescription())
        .jobErrorHandlerType("EMAIL")
        .build();
setEmailProperties(jobConfig, sysAppid, sysSaleItemKey);
new ScheduleJobBootstrap(registryCenter, new MySimpleJob(), jobConfig).schedule();

在项目中创建作业后，定时器可以正常调度。但是一旦项目重启后创建的作业就失效了
重启项目后zk的leader下的节点消失，任务调度失效

**Comment by jbgzz** [comment]
Create a way:

JobConfiguration jobConfig = JobConfiguration.newBuilder(command.getName(), shardingTotalCount)
.timeZone("GMT+8")
.cron(command.getCron())
.jobParameter(JsonUtils.serialize(parameterMap))
.monitorExecution(true)
.failover(true)
.misfire(true)
.maxTimeDiffSeconds(60)
.reconcileIntervalMinutes(1)
.addExtraConfigurations(new TracingConfiguration("RDB", this.dataSource))
.description(command.getDescription())
.jobErrorHandlerType("EMAIL")
.build();
setEmailProperties(jobConfig, sysAppid, sysSaleItemKey);
new ScheduleJobBootstrap(registryCenter, new MySimpleJob(), jobConfig).schedule();

**After the job is created in the project, the timer can be scheduled normally. But once the project restarts, the jobs created are invalidated**

**Comment by TeslaCN** [comment]
Please make sure `new ScheduleJobBootstrap(registryCenter, new MySimpleJob(), jobConfig).schedule();` would be executed after process restarted.

**Comment by jbgzz** [comment]
> Please make sure `new ScheduleJobBootstrap(registryCenter, new MySimpleJob(), jobConfig).schedule();` would be executed after process restarted.

Because there are already registered jobs, restart and execute new ScheduleJobBootstrap(registryCenter, new MySimpleJob(), jobConfig).schedule(); the premise is to get all the registered jobConfig, and then new ScheduleJobBootstrap(registryCenter, new MySimpleJob(), jobConfig).schedule();
So how to get registered jobConfig

**Comment by TeslaCN** [comment]
Please try the API in `elasticjob-lite-lifecycle`.
