### ISSUE TITLE
Jobs executed in wrong time when failover enabled

### ISSUE THREAD

**Issue by CattyWu** [apache/shardingsphere-elasticjob#2090]
i have jobs execute periodically , the cron is like '0 30 2 * * ?' or '0 30,55 * * * ?'
when i enabled failover, some time i found the jobs will be triggered when the instances nodes restart. After that i closed the  failover then it works well.
But in some scenarios,i need to use the failover ability.
This report seems like  [#2023](https://github.com/apache/shardingsphere-elasticjob/issues/2023)
By the way,our applications deploy in k8s,the ip,port and instance name will change after every deployeement.
 
### Which version of ElasticJob did you use?
3.0.0
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
elasticjob-lite

**Comment by cocodroid** [comment]
yes it's a bug

**Comment by wjdxw** [comment]
when i enabled failover and the job shardingTotolCount has one,In a multi-server environment, after the current instances node executing the job goes down, the other server will also execute the job immediately, which looks very similar to the above problem,is it the same bug?

**Which version of ElasticJob did you use?**
3.0.0

**Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?**
elasticjob-lite
