### ISSUE TITLE
Where is the source code of elasticjob-lite-spring-boot-starter?

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/shardingsphere-elasticjob#2093]
## Question
Hi all,

I have seen the starter `elasticjob-lite-spring-boot-starter` from the official website, I want to learn more about the starter,but I cant't find the repository about `elasticjob-lite-spring-boot-starter`, Can you give me the repository url of `elasticjob-lite-spring-boot-starter`?

```
<dependency>
    <groupId>org.apache.shardingsphere.elasticjob</groupId>
    <artifactId>elasticjob-lite-spring-boot-starter</artifactId>
    <version>${latest.release.version}</version>
</dependency>
```

   Have a great day!
    
   Oliver

**Comment by sunkai-cai** [comment]
you can see it.  [elasticjob-lite-spring-boot-starter](https://github.com/apache/shardingsphere-elasticjob/tree/master/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter)

**Comment by Oliverwqcwrw** [comment]
Thank you very much!
