### ISSUE TITLE
Cron expression exception

### ISSUE THREAD

**Issue by wrj15034011352** [apache/shardingsphere-elasticjob#2097]
### Which version of ElasticJob did you use?
      <dependency>
            <groupId>org.apache.shardingsphere.elasticjob</groupId>
            <artifactId>elasticjob-lite-spring-boot-starter</artifactId>
            <version>3.0.1</version>
        </dependency>

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite 

### Expected behavior And  Actual behavior
I configured the task to be executed every 5S, but it is actually executed every 20s

elasticjob:
  regCenter:
    serverLists: 192.168.1.57:2181
    namespace: elasticjob-lite-springboot
  jobs:
    simpleJob:
      elasticJobClass: com.example.elasticjobdemo.job.MySimpleJob
      cron: /5 * * * * ? *
      timeZone: GMT+08:00
      shardingTotalCount: 1
      overwrite: true
server:
  port: 9000

![image](https://user-images.githubusercontent.com/38170277/174709314-990420de-4f3d-4fcc-9c08-3bc6cc5ec87a.png)

![image](https://user-images.githubusercontent.com/38170277/174709346-4306cccc-ecb2-4072-933c-1d96b0ec6561.png)

**Comment by zhangzc0419** [comment]
check your registration center task config， maybe not overwrited

**Comment by qianweiming** [comment]
I also have this problem

**Comment by BinLee218** [comment]
I also have this problem

**Comment by linghengqian** [comment]
- To be honest, I cannot reproduce this problem on the master branch.  Can anyone provide an example git with minimal reproducible unit tests?

**Comment by linghengqian** [comment]
Closed due to lack of reproducible unit tests and no response.
