### ISSUE TITLE
Job is electing leader constantly，causing job can not be triggered

### ISSUE THREAD

**Issue by zxinGit** [apache/shardingsphere-elasticjob#2102]
Version:  ElasticJob-Lite 3.0.1 & Curator 5.2.0
problem：we found console print “Leader is electing, waiting for 100 ms” constantly ，and our jobs are never be triggered。After we restart application ，it becomes normal。

![1](https://user-images.githubusercontent.com/50131372/176852313-71a7b83e-eabb-40dc-bd1e-f5a0fbc47049.jpg)

and we dump zookeeper transaction log found that job is creating and deleting trigger nodes ，and also found error like “zxid ***** error -101 null” and  “zxid ***** error -111 null” 
![微信图片_20220701160902](https://user-images.githubusercontent.com/50131372/176853417-866e9440-ff99-4a17-b697-cb93d86d617c.jpg)

**Comment by hehan-wang** [comment]
The same problem to me 
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/18670007/180612425-e8712db4-dd9a-46bc-b350-24b59ee11a36.png">

**Comment by pandaapo** [comment]
What circumstances do triggered the election? or when?

**Comment by linghengqian** [comment]
- Closed due to lack of reproducible unit tests and no response.
