### ISSUE TITLE
EJ version 2.1.1，old GC will be triggered at runtime

### ISSUE THREAD

**Issue by LIWJason** [apache/shardingsphere-elasticjob#2107]
After running for a period of time, old GC will be triggered
<img width="967" alt="image" src="https://user-images.githubusercontent.com/20430125/179358913-123dc30c-76f4-4aaf-ae1a-1ab1a7df4036.png">

**Comment by TeslaCN** [comment]
Hi @LIWJason 
The version 2.1.1 is no longer maintained. Please try the latest version.
