### ISSUE TITLE
one job exceute long time,others must be wait!

### ISSUE THREAD

**Issue by austgh** [apache/shardingsphere-elasticjob#2113]
The machine has five shards, and the job is scheduled to be executed for 1 minute. One of the jobs was executed for 5 minutes because of too much data. It was found that within five minutes, the other jobs were executed only once, and the next four were not executed. Different shards should not be affected by the timing of other job seekers. versin 2.1.5 elastic-job-lite.
code may be AbstractElasticJobExecutor. process() 
Using asynchronous to synchronous, if one task is executed for too long, other tasks will wait all the time.

**Comment by cxx-cxx** [comment]
oh

**Comment by linghengqian** [comment]
- Can you reproduce this issue using ElasticJob 3.0.3?  I couldn't reproduce it with curator-test's embedded zookeeper server.

**Comment by austgh** [comment]
3.0.3 暂时没有使用&nbsp; 一个作业执行超过间隔时间，则导致所有的作业都会延迟到下一次执行 代码在2.15 中的bstractElasticJobExecutor. process()
Using asynchronous to synchronous, if one task is executed for too long, other tasks will wait all the time.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere-elasticjob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月13日(星期三) 凌晨3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere-elasticjob] one job exceute long time,others must be wait! (Issue #2113)





  
Can you reproduce this issue using ElasticJob 3.0.3?  I couldn't reproduce it with curator-test's embedded zookeeper server.

**Comment by linghengqian** [comment]
> 3.0.3 暂时没有使用&nbsp; 一个作业执行超过间隔时间，则导致所有的作业都会延迟到下一次执行 代码在2.15 中的bstractElasticJobExecutor. process()
> Using asynchronous to synchronous, if one task is executed for too long, other tasks will wait all the time.
> 

- @austgh It is no longer possible to continue the release process with ElasticJob 2.x.  For the current master branch, neither `AbstractElasticJobExecutor` nor `bstractElasticJobExecutor` exists.

**Comment by linghengqian** [comment]
Closed due to lack of reproducible unit tests and no response.
