### ISSUE TITLE
Maybe some place log.warn, eg. `log.warn("Failover job ...")`

### ISSUE THREAD

**Issue by CherishCai** [apache/shardingsphere-elasticjob#2118]
### Which version of ElasticJob did you use?
3.0.1

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Expected behavior
> log.warn("Failover job '{}' begin, crashed item '{}'", jobName, crashedItem);

### Actual behavior
> log.debug("Failover job '{}' begin, crashed item '{}'", jobName, crashedItem);

### Example codes for reproduce this issue (such as a github link).
![image](https://user-images.githubusercontent.com/16837364/185600110-64e2b006-7513-4e4c-a444-caa81b2fdfac.png)

**Comment by pandaapo** [comment]
I think changing to 'log.info' is more suitable. Because it is a normal execution in a sense.

**Comment by TeslaCN** [comment]
Different application has different requirement. You may configure logging on your own.

**Comment by CherishCai** [comment]
> Different application has different requirement. You may configure logging on your own.

Thanks, I try to configure the logging.
