### ISSUE TITLE
Whether there is a elasticjob version that supports JDK1.6？

### ISSUE THREAD

**Issue by liubron** [apache/shardingsphere-elasticjob#2119]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by TeslaCN** [comment]
You may try the versions like 2.x or 1.x.

**Comment by liubron** [comment]
已收到您的来信，谢谢！Thanks,I have received this letter.

**Comment by liubron** [comment]
已收到您的来信，谢谢！Thanks,I have received this letter.
