### ISSUE TITLE
Using AbstractDistributeOnceElasticJobListener，why every instance execute these two methods ： doBeforeJobExecutedAtLastStarted 、doAfterJobExecutedAtLastCompleted？ 

### ISSUE THREAD

**Issue by csz5667757** [apache/shardingsphere-elasticjob#2142]
**version elastic-job-lite-core 3.0.1**

## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by TeslaCN** [comment]
Could you help us to reproduce this issue? I cannot reproduce this.

**Comment by csz5667757** [comment]
@TeslaCN hi
use **OneOffJobBootStrap** and 
my **config** is 
JobConfiguration.newBuilder("job",8).failover(true).overwrite(true).jobListener("listener").build();
my **listener config** is 
startedTimeoutMilliseconds is 2000, completedTimeoutMilliseconds is 2000

use 2 server build job
**final result**
node1： log print in doBeforeJobExecutedAtLastStarted 、doAfterJobExecutedAtLastCompleted
node2： log print in doBeforeJobExecutedAtLastStarted 、doAfterJobExecutedAtLastCompleted
