### ISSUE TITLE
CI Test failed:ZookeeperRegistryCenterQueryWithoutCacheTest assertGetRegistryCenterTime

### ISSUE THREAD

**Issue by cocodroid** [apache/shardingsphere-elasticjob#2145]
## Bug Report

**For English only**, other languages will not accept.
fail details:https://github.com/apache/shardingsphere-elasticjob/actions/runs/3330370892/jobs/5508768776
![image](https://user-images.githubusercontent.com/11642752/198890728-71763f0e-7ab3-4ea8-a6eb-eb913d743bf6.png)

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Expected behavior
assertTrue(regCenterTime < updatedRegCenterTime); ==> true
### Actual behavior
assertTrue(regCenterTime < updatedRegCenterTime); ==> false
### Example codes for reproduce this issue (such as a github link).
    @Test
    public void assertGetRegistryCenterTime() {
        long regCenterTime = zkRegCenter.getRegistryCenterTime("/_systemTime/current");
        assertTrue(regCenterTime <= System.currentTimeMillis());
        long updatedRegCenterTime = zkRegCenter.getRegistryCenterTime("/_systemTime/current");
        assertTrue(regCenterTime < updatedRegCenterTime);
    }

**Comment by cocodroid** [comment]
It seems to be occasionally，

**Comment by TeslaCN** [comment]
Thanks for your report.

**Comment by linghengqian** [comment]
- According to https://github.com/apache/shardingsphere-elasticjob/actions/runs/4571083643 , it looks like CI has been fixed?

**Comment by linghengqian** [comment]
CI looks normal.
