### ISSUE TITLE
ejob-lite why not let servers as ephemeral node? What other considerations are there?

### ISSUE THREAD

**Issue by huaronghao** [apache/shardingsphere-elasticjob#2165]
When we use k8s deploy our service which integrated with ejob-lite，service IP is always not fixed. Zookeeper Servers node list is getting longer and longer. JobShutdownHookPlugin won't clear services node, and servers node also not as ephemeral node, both have other considerations?

**Comment by songxiaosheng** [comment]
>  When we use k8s deploy our service which integrated with ejob-lite，service IP is always not fixed. Zookeeper Servers node list is getting longer and longer. JobShutdownHookPlugin won't clear services node, and servers node also not as ephemeral node, both have other considerations?
> 

Persistent nodes are used to record the status whether the current IP status is restarted or not. They can be recorded, such as disabled or specified. 

Temporary nodes are used to record the process survival status. The temporary nodes have process IDs on them. If it is not necessary to record these status nodes, it is also a solution to consider moving the persistent nodes out of the container environment
