### ISSUE TITLE
Failed to run SpringBoot project

### ISSUE THREAD

**Issue by tbj-825** [apache/shardingsphere-elasticjob#2169]
I want to run a demo for Elastic-Job, when i add elastic-job-springboot-starter dependence,it does not work, if remove it that is work normal.

version
- SpringBoot 2.3.3
- Mybatis SpringBoot Starter 2.2.2
- elastic-job springBoot Starter 3.0.2

this is my pom file

`

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.shardingsphere.elasticjob</groupId>
			<artifactId>elasticjob-lite-spring-boot-starter</artifactId>
			<version>3.0.2</version>
		</dependency>

		
		<dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
			<version>2.2.2</version>
		</dependency>

		<dependency>
			<groupId>com.oracle.database.jdbc</groupId>
			<artifactId>ojdbc8</artifactId>
		</dependency>

		<dependency>
			<groupId>com.oracle.database.nls</groupId>
			<artifactId>orai18n</artifactId>
		</dependency>`

this is the error message 
`Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:122)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 95 more`

**Comment by sunknightzy** [comment]
Is there someone to resolve this issue?

**Comment by jinqiangshou** [comment]
> Is there someone to resolve this issue?

I had the same problem. After trial and error, I make it work by downgrading elastic-job springBoot Starter version from 3.0.2 to 3.0.1. You may try it.

Not sure what happened between these two revisions.

**Comment by sunknightzy** [comment]
Thanks.

**Comment by oemboy** [comment]
the version 3.0.3 and 3.0.2  start with error "java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required".

**Comment by linghengqian** [comment]
- I haven't seen ElasticJob Lite using Mybatis, I tend to think it's a configuration issue. Who can provide a minimum reproducible example?

**Comment by linghengqian** [comment]
Closed due to lack of reproducible unit tests and no response.
