### ISSUE TITLE
elastic cloud集成mesos后，启动多个elastic cloud后关闭其中一个在选举后，之前的任务出现2个正在运行的任务

### ISSUE THREAD

**Issue by GitHub-19** [apache/shardingsphere-elasticjob#2170]
elastic-cloud-3.0.2版本
mesos为1.11.0版本

![image](https://user-images.githubusercontent.com/55374958/211230664-fd5fe495-968e-4c68-803a-c426408f1999.png)

**Comment by linghengqian** [comment]
- Please follow https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 .  Affected by the Mesos upstream ecosystem, discussions have been opened to remove ElasticJob Cloud.

**Comment by linghengqian** [comment]
Since both ElasticJob Cloud and mesos integration modules have been removed from the master branch, close the current issue.
