### ISSUE TITLE
tracingDataSource 数据源导致自动配置失败。

### ISSUE THREAD

**Issue by yupd** [apache/shardingsphere-elasticjob#2171]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?

3.0.2

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?

ElasticJob-Lite

### Expected behavior

springboot版本为：2.7.7
引入 org.springframework.boot:spring-boot-starter-jdbc 数据源和事务自动配置失效。

### Actual behavior
 
DataSourceInitializationConfiguration:
      Did not match:
         - @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) did not find a primary bean from beans 'tracingDataSource', 'dataSource' (OnBeanCondition)

DataSourceTransactionManagerAutoConfiguration.JdbcTransactionManagerConfiguration:
      Did not match:
         - @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) did not find a primary bean from beans 'tracingDataSource', 'dataSource' (OnBeanCondition)

### Reason analyze (If you can)

tracingDataSource 数据源导致容器中有多个数据源，没有主数据源，导致一些自动配置失效。

**Comment by zhangethan** [comment]
@yupd  I encountered the same problem, could you tell me how to fix it?

**Comment by yupd** [comment]
> [@yupd](https://github.com/yupd) I encountered the same problem, could you tell me how to fix it?

https://github.com/apache/shardingsphere-elasticjob/pull/2174

这个是我修改的代码，重新编译一下应该就行了，很早的问题了，都忘了。
https://github.com/yupd/shardingsphere-elasticjob/blob/master/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/main/java/org/apache/shardingsphere/elasticjob/lite/spring/boot/tracing/ElasticJobTracingConfiguration.java
