### ISSUE TITLE
Data source rejected establishment of connection,  message from server: "Too many connections"

### ISSUE THREAD

**Issue by follow-me-f** [apache/shardingsphere-elasticjob#2172]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?
3.0.2
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Cloud
### Example codes for reproduce this issue (such as a github link).
![image](https://user-images.githubusercontent.com/8908076/211292342-061e39c5-d355-43dd-a695-986b7161ae36.png)
![image](https://user-images.githubusercontent.com/8908076/211292389-295e774d-dcc9-4524-a82c-d9e34be29be0.png)
![image](https://user-images.githubusercontent.com/8908076/211292432-40fe42d6-9a75-4319-bb32-391af368bfb8.png)

**Comment by linghengqian** [comment]
- Please follow https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 .  Affected by the Mesos upstream ecosystem, discussions have been opened to remove ElasticJob Cloud.

**Comment by linghengqian** [comment]
Since both ElasticJob Cloud and mesos integration modules have been removed from the master branch, close the current issue.
