### ISSUE TITLE
dataSource auto configuration failed.

### ISSUE THREAD

**Issue by yupd** [apache/shardingsphere-elasticjob#2173]
### Which version of ElasticJob did you use?

3.0.2

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?

ElasticJob-Lite

### Expected behavior

import org.springframework.boot:spring-boot-starter-jdbc dependence，auto config datasource failed.

### Actual behavior

DataSourceInitializationConfiguration:
Did not match:
- @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) did not find a primary bean from beans 'tracingDataSource', 'dataSource' (OnBeanCondition)

DataSourceTransactionManagerAutoConfiguration.JdbcTransactionManagerConfiguration:
Did not match:
- @ConditionalOnSingleCandidate (types: javax.sql.DataSource; SearchStrategy: all) did not find a primary bean from beans 'tracingDataSource', 'dataSource' (OnBeanCondition)

### Reason analyze (If you can)

multiple data sources cause auto config failed.

**Comment by oemboy** [comment]
the same question~
