### ISSUE TITLE
ScheduleJobBootstrap load  SimpleJob，what value of elasticJobType to set ？

### ISSUE THREAD

**Issue by astorage** [apache/shardingsphere-elasticjob#2177]
## Question
version：3.0.2
ScheduleJobBootstrap load  SimpleJob，what value of elasticJobType to set ？
code：
```
//using
String elasticJobType = ?
ScheduleJobBootstrap scheduleJobBootstrap =
                    new ScheduleJobBootstrap(registryCenter, elasticJobType,  jobConfig);



//define  org.apache.shardingsphere.elasticjob.lite.api.bootstrap.impl.ScheduleJobBootstrap

 public ScheduleJobBootstrap(final CoordinatorRegistryCenter regCenter, final String elasticJobType, final JobConfiguration jobConfig) {
        jobScheduler = new JobScheduler(regCenter, elasticJobType, jobConfig);
    }
```

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by TeslaCN** [comment]
`SCRIPT`, `HTTP` are available elasticJob type. You could implement your own type executor by SPI.

https://github.com/apache/shardingsphere-elasticjob/blob/8b54bba845c6c6e4a4e30a19c0cd222f704a2c3b/elasticjob-ecosystem/elasticjob-executor/elasticjob-executor-type/elasticjob-http-executor/src/main/java/org/apache/shardingsphere/elasticjob/http/executor/HttpJobExecutor.java
