### ISSUE TITLE
web interface search page is slow

### ISSUE THREAD

**Issue by liucx1201** [apache/shardingsphere-elasticjob#2181]
elastic-job web interface search page is slow

connected is zookeeper cluster

job number is  2000+

the application service is the pod of  k8s 

Is there any way to solve it ?

**Comment by liucx1201** [comment]
![微信截图_20230215232135](https://user-images.githubusercontent.com/40434832/219072502-64b0a694-5947-40ba-9c74-f542ebbd9979.png)

**Comment by liucx1201** [comment]
已解决

**Comment by SuperCarrys** [comment]
求问，如何解决的，我这边遇到了同样的情况，k8s中的服务每更新一次都会注册新的podip到zk上，导致查询很慢

**Comment by liucx1201** [comment]
> 求问，如何解决的，我这边遇到了同样的情况，k8s中的服务每次更新一次都会注册新的podip到zk上，引导查询很慢
写了个py脚本，解决方法：https://www.cnblogs.com/liucx/p/17127383.html

**Comment by liucx1201** [comment]
@SuperCarrys 我写了个py脚本，解决方法：https://www.cnblogs.com/liucx/p/17127383.html，希望能帮助到你哈
