### ISSUE TITLE
Does ElasticJob Lite Spring Boot Starter 3.0.2 support Spring Boot 3.x?

### ISSUE THREAD

**Issue by CarterCL** [apache/shardingsphere-elasticjob#2199]
I tried to integrate ElasticJob Lite 3.0.2 with Spring Boot 3.0.4, but failed. The scheduled tasks didn't run after Spring Boot started.  
 Downgrading Spring Boot to 2.x resolved the issue.  

Is ElasticJob Lite 3.0.2 currently not supported in Spring Boot 3.x? Are there any plans to support it in the future?

**Comment by shuangpai** [comment]
可以自己在classpath写SpringBoot3的启动方式，把原先的spring.factories中的内容出来，比如
src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports中添加
org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobLiteAutoConfiguration

**Comment by CarterCL** [comment]
> 可以自己在classpath写SpringBoot3的启动方式，把原先的spring.factories中的内容出来，比如 src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports中添加 org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobLiteAutoConfiguration

OK，谢谢！
