### ISSUE TITLE
Database password may be compromised

### ISSUE THREAD

**Issue by taopanwoaini** [apache/shardingsphere-elasticjob#2201]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Thanks for see this question!   

today , i find the config of job in zookeeper, and this config context contain ( username, password, ip:port:url ) for my mysql db;

i think , that will expose my database info; 

i do not konw why do this of design?

appliction is has  datasource already , but Putting the configuration into the zookeeper is something I cannot understand;

and it makes me feel scared;

thanks you answering!

**Comment by linghengqian** [comment]
- One design issue involved here is that we should not provide this encryption operation on the ElasticJob side. We always assume that everything with ElasticJob occurs in an intranet environment, and this includes Zookeeper Server.  

- I think cryptographic behavior like this should be left to the user to try to handle themselves, or expose a configurable SPI on the ElasticJob side.

**Comment by linghengqian** [comment]
- Consider https://shardingsphere.apache.org/elasticjob/current/en/user-manual/configuration/external-integration/sasl/ . Please enable SASL for Zookeeper Server directly. Zookeeper Server should not expose access to itself directly.
