### ISSUE TITLE
Springboot3 启动报错

### ISSUE THREAD

**Issue by stephenson37** [apache/shardingsphere-elasticjob#2207]
Springboot3 启动报错，不兼容
有没有计划兼容Springboot3 ，大概什么时候

**Comment by linghengqian** [comment]
@stephenson37 

- Hi, can you translate the title and content of your issue into English so others can search? 

- I'm sure you're referring to ShardingSphere Elasticjob Lite?

**Comment by linghengqian** [comment]
- I work on this issue.
