### ISSUE TITLE
什么时候支持 springboot 3.0

### ISSUE THREAD

**Issue by niguibin** [apache/shardingsphere-elasticjob#2214]

**Comment by TeslaCN** [comment]
Please try building and using the master branch.

**Comment by niguibin** [comment]
> Please try building and using the master branch.

谢谢，我拉取 master 分支 build 之后，支持 springboot 3.0，可以正常使用

不过目前导入 elasticjob 的包会被扫出一个关于 org.yaml:snakeyaml  的漏洞，旧版本的 springboot 使用的是 1.29 版本的 snakeyaml，这个漏洞在 2.0 版本中被修复了， 但是直接从 elasticjob 中排除 snakeyaml，并且重新导入 2.0 的 snakeyaml 是不可行的，2.0 的 snakeyaml 中 Representer 这个类取消了无参构造器，在 elasticjob 源码以及旧版本的 springboot/spring 中仍然使用了 Representer 的无参构造器，这部分在 springboot  2.7.10 中被修改为有参构造器，因此建议你们能升级一下 elasticjob 中 springboot/spring 的版本（springboot 2.7.10 及以上）

**Comment by linghengqian** [comment]
> > Please try building and using the master branch.
> 
> 谢谢，我拉取 master 分支 build 之后，支持 springboot 3.0，可以正常使用
> 
> 不过目前导入 elasticjob 的包会被扫出一个关于 org.yaml:snakeyaml  的漏洞，旧版本的 springboot 使用的是 1.29 版本的 snakeyaml，这个漏洞在 2.0 版本中被修复了， 但是直接从 elasticjob 中排除 snakeyaml，并且重新导入 2.0 的 snakeyaml 是不可行的，2.0 的 snakeyaml 中 Representer 这个类取消了无参构造器，在 elasticjob 源码以及旧版本的 springboot/spring 中仍然使用了 Representer 的无参构造器，这部分在 springboot  2.7.10 中被修改为有参构造器，因此建议你们能升级一下 elasticjob 中 springboot/spring 的版本（springboot 2.7.10 及以上）

- For this issue, it has been fixed in the master branch.  

- For SnakeYAML, discussed at https://github.com/apache/shardingsphere-elasticjob/pull/2216 .

**Comment by yqbboy** [comment]
elastic-job 3.0.3支持springboot3+吗

**Comment by linghengqian** [comment]
> elastic-job 3.0.3支持springboot3+吗

- Not supported, need to wait for the Release of ElasticJob 3.0.4.  

- Or you put the new file from https://github.com/apache/shardingsphere-elasticjob/commit/a7042cf4872d784d619e4560cdfa0f92b0311965 into the corresponding location of 'resources/META-INF/spring/' of your project.

**Comment by niguibin** [comment]
> elastic-job 3.0.3支持springboot3+吗

不支持，现在的 master 分支支持，自己 pull master 分支 build 即可

**Comment by niguibin** [comment]
> > > Please try building and using the master branch.
> > 
> > 
> > 谢谢，我拉取 master 分支 build 之后，支持 springboot 3.0，可以正常使用
> > 不过目前导入 elasticjob 的包会被扫出一个关于 org.yaml:snakeyaml  的漏洞，旧版本的 springboot 使用的是 1.29 版本的 snakeyaml，这个漏洞在 2.0 版本中被修复了， 但是直接从 elasticjob 中排除 snakeyaml，并且重新导入 2.0 的 snakeyaml 是不可行的，2.0 的 snakeyaml 中 Representer 这个类取消了无参构造器，在 elasticjob 源码以及旧版本的 springboot/spring 中仍然使用了 Representer 的无参构造器，这部分在 springboot  2.7.10 中被修改为有参构造器，因此建议你们能升级一下 elasticjob 中 springboot/spring 的版本（springboot 2.7.10 及以上）
> 
> * For this issue, it has been fixed in the master branch.
> * For SnakeYAML, discussed at [Upgrade snakeyaml to 2.0 and springboot to 2.7.10 #2216](https://github.com/apache/shardingsphere-elasticjob/pull/2216) .

好的，谢谢
