### ISSUE TITLE
请问3.X版本是否支持作业依赖(TODO)

### ISSUE THREAD

**Issue by 18210206490** [apache/shardingsphere-elasticjob#2220]
3.X文档中未找到相关配置，源码中未找到相关代码实现，请问是不支持吗，如果支持，请给提供一下springboot相关配置链接，谢谢

**Comment by linghengqian** [comment]
- The answer, for ElasticJob 3.0.3, is no. Refer to https://shardingsphere.apache.org/elasticjob/current/en/user-manual/elasticjob-lite/usage/job-listener/ .

> After the job dependency (DAG) function is developed, the job listener function may be considered to be deleted.

- Please write the issue title and description in English to make it easier for others to search. If you have any questions, please open a new issue in English.

**Comment by linghengqian** [comment]
- Until concrete implementation comes, you may have to resort to job listeners.
