### ISSUE TITLE
The dispatch was not executed on time

### ISSUE THREAD

**Issue by zyz199221** [apache/shardingsphere-elasticjob#2222]
Please help to answer;We had a task that was done at ten past one every day; But it was not carried out on 5-18, and the rest of our missions at that point in time were normal. Then the mission was executed twice at 0:10 on 5-19. May I ask why the dispatch meeting is not executed? And if you don't do it why don't you do it every other minute? Our failover=true;; misfire=true; 
<elastic-job.version>2.1.5</elastic-job.version>

**Comment by linghengqian** [comment]
- You need to use elasticjob 3.0.4 for testing and provide git with minimal reproducible unit tests.

**Comment by linghengqian** [comment]
Closed because it could not be reproduced.
