### ISSUE TITLE
2.0.4.REVISED-SNAPSHOT迁移到3.x

### ISSUE THREAD

**Issue by winer77444** [apache/shardingsphere-elasticjob#2224]
问题一.大版本迁移需要注意什么?比如我的jdk1.6  spring 3.x 是否需要整体都升级
问题二.目前2.x版本使用最大的问题是，随着作业的增加我不知道我的作业服务器集群的瓶颈在哪里，什么时候扩容？比如我目前作业已经到了1000+，作业服务器8个，怎么去评估。

**Comment by linghengqian** [comment]
> 问题一.大版本迁移需要注意什么?比如我的jdk1.6 spring 3.x 是否需要整体都升级

- I don't know what version 2.0.4.REVISED-SNAPSHOT is. But since there will obviously be no commits back to the old branch, I suggest you start the configuration from scratch.

> 问题二.目前2.x版本使用最大的问题是，随着作业的增加我不知道我的作业服务器集群的瓶颈在哪里，什么时候扩容？比如我目前作业已经到了1000+，作业服务器8个，怎么去评估。

- It really depends on your means. Or do you plan to submit a PR?

**Comment by linghengqian** [comment]
- I plan to break forward compatibility at https://github.com/apache/shardingsphere-elasticjob/pull/2431 . You need to redeploy ElasticJob and Zookeeper Server.
