### ISSUE TITLE
Change the ip node under servers to a temporary node

### ISSUE THREAD

**Issue by SuperCarrys** [apache/shardingsphere-elasticjob#2229]
After reading the source code of the job, I have a question, why not set the ip child node under the servers node as a temporary node, but save it permanently, so that with the release of services in k8s, there will be more and more ip child nodes , and these ip nodes will be traversed when judging the job status, which will cause problems as the number increases.
I think it is feasible to set the node under servers as a temporary node. After the release, the old ip is useless, and it doesn't matter if it is deleted. I will do a test locally.
Regarding this point, I may have some inconsiderations, and I hope the official can see if it is feasible.

`    /**
     * 持久化作业服务器上线信息.
     * 
     * @param enabled 作业是否启用
     */
    public void persistOnline(final boolean enabled) {
        if (!JobRegistry.getInstance().isShutdown(jobName)) {
//            jobNodeStorage.fillJobNode(serverNode.getServerNode(JobRegistry.getInstance().getJobInstance(jobName).getIp()), enabled ? "" : ServerStatus.DISABLED.name());
            //改为临时节点
            jobNodeStorage.fillEphemeralJobNode(serverNode.getServerNode(JobRegistry.getInstance().getJobInstance(jobName).getIp()), enabled ? "" : ServerStatus.DISABLED.name());
        }
    }
    `

**Comment by SuperCarrys** [comment]
![image](https://github.com/apache/shardingsphere-elasticjob/assets/53105317/0103881d-9e68-4377-bcad-9e284aac8cf8)

**Comment by SuperCarrys** [comment]
`   /**
     * 持久化作业服务器上线信息.
     * 
     * @param enabled 作业是否启用
     */
    public void persistOnline(final boolean enabled) {
       
 if (!JobRegistry.getInstance().isShutdown(jobName)) {

//           jobNodeStorage.fillJobNode(serverNode.getServerNode(JobRegistry.getInstance().getJobInstance(jobName).getIp()), enabled ? "" : ServerStatus.DISABLED.name());
            
//改为临时节点
            jobNodeStorage.fillEphemeralJobNode(serverNode.getServerNode(JobRegistry.getInstance().getJobInstance(jobName).getIp()), enabled ? "" : ServerStatus.DISABLED.name());
        }
    }
    `

**Comment by SuperCarrys** [comment]
![image](https://github.com/apache/shardingsphere-elasticjob/assets/53105317/1f48ebe1-e19e-4f9b-a470-0e8531d5bee5)

**Comment by SuperCarrys** [comment]
![image](https://github.com/apache/shardingsphere-elasticjob/assets/53105317/b03f01fe-4b0c-4d23-a828-5d5a78b2bac5)

Change code screenshot： https://github.com/apache/shardingsphere-elasticjob/assets/53105317/b03f01fe-4b0c-4d23-a828-5d5a78b2bac5

**Comment by songxiaosheng** [comment]
持久ip用于记录一些持久化的状态，建议搞个定时任务清理下，后续再ej上默认集成下
