### ISSUE TITLE
Springboot integrates elasitc-job and set cron: 59 59 23 * * ? Start the java service and find that the job is executed immediately, not every time, but occasionally when the service is restarted, it will be executed. What is the reason?

### ISSUE THREAD

**Issue by 754466488** [apache/shardingsphere-elasticjob#2231]
Springboot integrates elasitc-job and set cron: 59 59 23 * * ? Start the java service and find that the job is executed immediately, not every time, but occasionally when the service is restarted, it will be executed. What is the reason?

**Comment by songxiaosheng** [comment]
会不会是触发了失效转移低版本重启进程就会补偿执行

**Comment by songxiaosheng** [comment]
你们这个触发时间设置的不太好，接近一个边界时间0点很容易触发时钟回拨，如果做一些时间性处理可能会有问题
