### ISSUE TITLE
怎么清理垃圾数据

### ISSUE THREAD

**Issue by bruse-peng** [apache/shardingsphere-elasticjob#2239]
elastic-job运行会在zk里面写数据，我们是容器服务，每次发布重启就会向zookeeper的servers里面写入ip信息，这样历史数据越积越多，这个elastic-job有提供好的办法吗？

**Comment by songxiaosheng** [comment]
有个instance节点是临时节点，如果临时节点不存在则可以删除server下对应的ip，（server下的ip用来存储有状态的数据，用不到可以直接删除）
