### ISSUE TITLE
Update tracing record reports Error

### ISSUE THREAD

**Issue by Albert-F** [apache/shardingsphere-elasticjob#2243]
Hi

Elastic Job Lite v3.0.3

As described in the doc
1.when the job is executed，program will create one record in the JOB_EXECUTION_LOG...
2.when the job completes execution，program will update the record,update the columns of is_success,complete_time and failure_cause(if the job execution falis)

when i use tracing，the record insert into database is ok，but update is error.Almost all the records udpate error，only few records update successfully.
![image](https://github.com/apache/shardingsphere-elasticjob/assets/73283029/6dc5feb5-1435-46e4-a80b-a70625d0e44c)
![image](https://github.com/apache/shardingsphere-elasticjob/assets/73283029/21866b72-1f0b-449f-ac64-008c5855e06c)

error log in console
![image](https://github.com/apache/shardingsphere-elasticjob/assets/73283029/2e2f3d1a-7a27-4784-bff3-08bbc929628b)

**Comment by zjx990** [comment]
Can you provide a reproduction code or engineering？

**Comment by linghengqian** [comment]
Closed due to no response.
