### ISSUE TITLE
When using digest to access zookeeper, the server has been waiting (fake death)

### ISSUE THREAD

**Issue by ocean30** [apache/shardingsphere-elasticjob#2249]
## Bug Report
elastic-job-lite-core:2.0.4 When using digest to access zookeeper, the server has been waiting (fake death).

### Which version of ElasticJob did you use?
elastic-job-lite-core:2.0.4
### Expected behavior
LeaderLatch election ends
### Actual behavior
LeaderLatch has been waiting for the election to end
### Reason analyze
After ElasticJob adds digest, when an election occurs, a child node with digests will be created under the latch node. The server that has not been upgraded does not have digest, resulting in no permission to access the newly generated node, which eventually leads to election waiting.
Zookeeper server returns type=GET_DATA, resultCode=-102 , but GET_DATA does not process resultCode=-102 when processResult.
### Steps to reproduce the behavior.
1. 8 servers, 10 jobs, no digest running
2. Add digest to the code, restart the server one by one, some machines will wait forever (fake death)

### Log and code 
1、elasticjob log data zookeeper response  type=GET_DATA data:
`2023-07-27 22:33:55.224 [DEBUG] [localhost-startStop-1-EventThread] [] [] [] - o.a.c.f.r.c.TreeCache : processResult: CuratorEventImpl{type=GET_DATA, resultCode=-102, path='/xxx/leader/election/latch/_c_bccccdcc-1134-4e0a-bb52-59a13836434a-latch-0000000047', name='null', children=null, context=null, stat=null, data=null, watchedEvent=null, aclList=null}`
2、elasticjob process zookeeper  type=GET_DATA result,Only the logic that returned the result of OK (0) and NONODE (-101) was processed, while the processing of the returned result of NoAuth (-102) was ignored, so it caused the election to wait and no exception was thrown.
org.apache.curator.framework.recipes.cache.TreeCache.TreeNode#processResult
```
public void processResult(CuratorFramework client, CuratorEvent event) throws Exception
        {
            LOG.debug("processResult: {}", event);
            Stat newStat = event.getStat();
            switch ( event.getType() )
            {
            case EXISTS:
                {...}
                break;
            case CHILDREN:
                {...}
                break;
            case GET_DATA:
                if ( event.getResultCode() == KeeperException.Code.OK.intValue() )*
                {...}
                else if ( event.getResultCode() == KeeperException.Code.NONODE.intValue() )
                {
                    wasDeleted();
                }
               //todo need process NoAuth (-102) 
                break;
            default:
                // An unknown event, probably an error of some sort like connection loss.
                LOG.info(String.format("Unknown event %s", event));
                // Don't produce an initialized event on error; reconnect can fix this.
                outstandingOps.decrementAndGet();
                return;
            }

        }
```

**Comment by linghengqian** [comment]
- Can you reproduce this issue using ElasticJob 3.0.3?  I couldn't reproduce it with curator-test's embedded zookeeper server.

**Comment by zjx990** [comment]
@linghengqian 这个问题跟elastic job版本无关。 主要是因为在滚动部署的过程中存在带密码和不带密码的版本，它们选主的过程中存在阻塞情况，具体见如下示意图。
![image](https://github.com/apache/shardingsphere-elasticjob/assets/66360103/23c00292-b761-4a39-896e-6b948bf15e49)

**Comment by linghengqian** [comment]
- I'm not sure where the reasonable processing should be for now. If any friends are willing to submit a PR, I will assist in reviewing it.  

- Such a fix may be late to reach the 3.0.4 milestone. Friends from the parent project ShardingSphere require ElasticJob to complete the 3.0.4 release as soon as possible.

**Comment by zjx990** [comment]
@linghengqian 这可能不是一个真正的bug。我的本意是不让线上的分布式任务受到版本更新的影响选择了滚动部署。但是结果是如果这样做会存在工程启动时假死和进行时假死俩种情况。我们最后选择了停止所有的实例，然后让所有实例用带密码的版本统一更新，这样做的前提是我们算出所有作业执行时间的间隙并选择了一个安全时间范围。

**Comment by zjx990** [comment]
@linghengqian 我希望官网文档中可以标注如果zk做授权更新，一定需要注意新老版本相互竞争阻塞的问题
补充一下会存在的问题:
1.会存在实例启动假死
2.版本回滚也会存在假死，无法正常回退到历史版本。(需要删除zk根节点下所有目录)

**Comment by zjx990** [comment]
<img width="1503" alt="image" src="https://github.com/apache/shardingsphere-elasticjob/assets/66360103/eb344ea5-083b-4b99-a50b-df126982025b">
使用zk digest时需注意假死问题。

**Comment by linghengqian** [comment]
- @zjx990 It looks like relevant instructions should be placed at https://shardingsphere.apache.org/elasticjob/current/en/faq/ , any documentation PRs would be welcome. 

- I'm still dealing with https://github.com/apache/shardingsphere-elasticjob/issues/2258 and I maybe don't have time to manage this issue at the moment.

**Comment by zjx990** [comment]
@linghengqian 我会整理一篇详细的问题分析和我目前能想到的最好的解决方案，请问如何能将我发现的问题提交进FAQ中。

**Comment by linghengqian** [comment]
- @zjx990 The file you need to change is located at https://github.com/apache/shardingsphere-elasticjob/tree/master/docs/content/faq . You can add a new FAQ directly at the bottom of each file.
- For the operation of pull request, it may be more reasonable to refer to Github's own documentation.

**Comment by zjx990** [comment]
@linghengqian 好的，感谢，我会尽快提交PR

**Comment by zjx990** [comment]
@linghengqian 我提交了最新的PR,麻烦看下还有无需要修改的地方
