### ISSUE TITLE
version 3.0.2+  cause Spring's transaction to fail.

### ISSUE THREAD

**Issue by hzlulu** [apache/shardingsphere-elasticjob#2271]
### Which version of ElasticJob did you use?
3.0.2 +
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Actual behavior
影响了springboot(Ver. 2.7.x)的事务，导致事务无法自动配置，无法生效
### Reason analyze (If you can)
elasticjob-lite-core依赖移入elasticjob-lite-spring-core是否有影响
### Steps to reproduce the behavior.
只要引入3.0.2 +依赖就会导致事务失效

**Comment by linghengqian** [comment]
- In ElasticJob 3.0.4, which was released yesterday, the version of Spring Boot for unit testing was upgraded to Spring Boot OSS 2.7. Can you reverify?

**Comment by linghengqian** [comment]
Closed due to no response.
