### ISSUE TITLE
[DISCUSS] Release Plan of ElasticJob 3.0.4

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere-elasticjob#2272]
## Dependencies Upgrade
1. Update dependencies to fix CVE

## Enhancements
1. Support for building with OpenJDK 21
2. Accelerate the startup speed of ElasticJob
3. Migrate from Junit Vintage to Junit Jupiter

**Comment by linghengqian** [comment]
- It would be better if we could bring https://github.com/apache/shardingsphere-elasticjob/pull/2209 into Release Notes.  There are too many issues related to Spring Boot OSS 3.  

- In terms of Bug Fixes, https://github.com/apache/shardingsphere-elasticjob/pull/2254 is worth considering as part of the Release Notes, which explains the behavior of quite a few issues.

- I just want to confirm if https://github.com/apache/shardingsphere-elasticjob/blob/master/RELEASE-NOTES.md is allowed to be changed.
