### ISSUE TITLE
服务重启后，控制台任务都是已下线的怎么办，而且正常调度结束的任务后台也查询不到

### ISSUE THREAD

**Issue by peihaoming** [apache/shardingsphere-elasticjob#2366]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by linghengqian** [comment]
- Can you provide unit tests? Or are you going to just submit a PR?

**Comment by linghengqian** [comment]
Closed because it could not be reproduced.
