### ISSUE TITLE
定时任务提前执行

### ISSUE THREAD

**Issue by bruse-peng** [apache/shardingsphere-elasticjob#2367]
定时任务配置的是12点执行，但是11点就执行了，不知道什么情况
<img width="1632" alt="企业微信截图_99ac9789-50d3-45fb-bfd7-52c1c93e22f0" src="https://github.com/apache/shardingsphere-elasticjob/assets/47881861/8cc09b18-da8c-4bcd-87d0-4391691f3cd1">

**Comment by linghengqian** [comment]
- What application is your UI?

**Comment by wjdxw** [comment]
1.可以查看下服务器设置的时间，是否正常一致
2.是否配置失效转移，配置的话，你这个控制台应该是老版本的job，zk和服务器 因网络原因断开重连的会立即触发失效转移，在zk timeout 时间内重连成功，是不会有日志的，可以查看zk 的instance 节点，会有创建的时间，如果是11点就说明那会的zk 和服务器 有发生断开和重连导致提前执行

这两种问题都是我遇到过的，希望对你有帮助

**Comment by linghengqian** [comment]
Since there is absolutely no way to reproduce, this issue does not make sense to continue opening, unless someone can provide the git of the unit test that includes the assertion failure.
