### ISSUE TITLE
zk集群删除无效数据

### ISSUE THREAD

**Issue by bruse-peng** [apache/shardingsphere-elasticjob#2368]
我们使用k8s 部署的zk集群，然后我们服务部署在k8s，然后每次服务重启就会注册一个ip上来，时间久了就会存在垃圾数据，这个怎么删除了，由于是zk集群，删除数据理论上总有一个时间差，这个有影响吗？

**Comment by songxiaosheng** [comment]
这个问题已经提PR处理过了，每次启动进程时候清理掉有状态的server ip就可以了，没啥影响，可以测试环境验证下
https://github.com/apache/shardingsphere-elasticjob/pull/2251

**Comment by linghengqian** [comment]
Fixed in ElasticJob 3.0.4.
