### ISSUE TITLE
动态创建任务服务重启后未过时的任务可以重新启动吗？

### ISSUE THREAD

**Issue by yezhibo** [apache/shardingsphere-elasticjob#2374]
网上查到有对elasticjob二次扩展，支持服务启动动态扫描zookeeper上的未过期的任务，并重新执行，3.0.4以上的版本有针对这个开放的相关API吗？
相关博客：https://xie.infoq.cn/article/0b0cd01fe77d4da058bd7bc87

**Comment by linghengqian** [comment]
Sounds like an unimplemented feature. Are you going to submit a PR?

**Comment by linghengqian** [comment]
- You can now use `org.apache.shardingsphere.elasticjob.lifecycle.api.JobConfigurationAPI`. See https://shardingsphere.apache.org/elasticjob/current/en/user-manual/usage/operation-api/ and `org.apache.shardingsphere.elasticjob.lifecycle.internal.settings.JobConfigurationAPIImplTest`.
- I am about to add unit tests to nativeTest under GraalVM Native Image.

**Comment by linghengqian** [comment]
Feel free to check out #2426 in `org.apache.shardingsphere.elasticjob.test.natived.it.operation.JavaTest` for ways to add, delete, modify, and query jobs.
