### ISSUE TITLE
Q:  How to set jobs configuration dynamically from database?

### ISSUE THREAD

**Issue by weiwill** [apache/shardingsphere-elasticjob#2382]
As shown below, I want to dynamically read from the database

![image](https://github.com/apache/shardingsphere-elasticjob/assets/3794090/ea15e675-fca7-4a9a-b6bc-d4b8ba98eb05)

**Comment by weiro-9-w7** [comment]
how to handle the function

**Comment by linghengqian** [comment]
- You can use `org.apache.shardingsphere.elasticjob.lifecycle.api.JobConfigurationAPI` to CRUD jobs from Zookeeper Server. For reading jobs from database, you need to submit PR for https://github.com/apache/shardingsphere-elasticjob/issues/2183 first.
- I am about to add unit tests to nativeTest under GraalVM Native Image.

**Comment by linghengqian** [comment]
- Feel free to check out #2426 in `org.apache.shardingsphere.elasticjob.test.natived.it.operation.JavaTest` for ways to add, delete, modify, and query jobs. Reading content from a database is more something that the business layer of downstream projects should do, unless you plan to submit a PR.
