### ISSUE TITLE
jobShardingStrategyType: ROUND_ROBIN is not available

### ISSUE THREAD

**Issue by cheney0728** [apache/shardingsphere-elasticjob#2384]
Now I added several jobs, and they have the same configuration:
```
elasticjob.xxxxxxxxx.sharding-total-count = 2
elasticjob.xxxxxxxxx.sharding-item-parameters = 0=A,1=B
elasticjob.xxxxxxxxx.job-sharding-strategy-type = ROUND_ROBIN
elasticjob.xxxxxxxxx.overwrite = true
```
But the results on zookeeper are different and jobShardingStrategyType: ROUND_ROBIN is invalid，What is the reason for this, please.
<img width="432" alt="image" src="https://github.com/apache/shardingsphere-elasticjob/assets/86450966/5d80bb11-d5b3-4aeb-a1a7-80b7bdb0f83e">

**Comment by linghengqian** [comment]
- Please provide an Example git with unit tests.

**Comment by linghengqian** [comment]
Closed due to complete inability to reproduce in master branch.
