### ISSUE TITLE
任务正常跑一段时间，突然某个任务不再执行，版本2.1.5

### ISSUE THREAD

**Issue by lichaobao** [apache/shardingsphere-elasticjob#2387]
版本2.1.5，
任务正常跑一段时间，
突然某个任务不再执行，
单节点，
管理平台查看任务状态显示正常，
管理平台手动点击任务触发并未执行

**Comment by bbcdabao** [comment]
先打开 监控作业执行配置 monitorExecution=true, 然后就可以看到业务是否阻塞，默认配置作业如何一直没有跑完是不会执行下一次的

**Comment by Nfq226** [comment]
我也是这个版本，没有任何代码和配置上的变动，个别任务突然不执行了，然后过了一天左右又自动恢复了，期间排查过zk, zk有一台机器漂移，漂移时间和服务节点拉取不到分片任务的时间完全吻合，推测可能是zk有问题：1）可能选主失败，2）选主成功后，主节点划分作业分片然后写zk失败，导致服务节点拉取不到zk作业分片；最后排查下来zk选主没问题，但是主节点划分作业写到zk是否成功无法查看，因为定时任务每次调度都会写入，而且问题不好稳定复现。这个大佬们有碰到过或者其他排查思路吗？

**Comment by wjdxw** [comment]
> 我也是这个版本，没有任何代码和配置上的变动，个别任务突然不执行了，然后过了一天左右又自动恢复了，期间排查过zk, zk有一台机器漂移，漂移时间和服务节点拉取不到分片任务的时间完全吻合，推测可能是zk有问题：1）可能选主失败，2）选主成功后，主节点划分作业分片然后写zk失败，导致服务节点拉取不到zk作业分片；最后排查下来zk选主没问题，但是主节点划分作业写到zk是否成功无法查看，因为定时任务每次调度都会写入，而且问题不好稳定复现。这个大佬们有碰到过或者其他排查思路吗？

看下job有没有执行完，没执行完看堆栈哪里卡住了，执行完看堆栈，找到OperableTrigger 这个对象，里面有个triggerState ，如果是PAUSED 或者BLOCKED ，job都不会执行的，控制台看上去是正常的

**Comment by linghengqian** [comment]
> 版本2.1.5， 任务正常跑一段时间， 突然某个任务不再执行， 单节点， 管理平台查看任务状态显示正常， 管理平台手动点击任务触发并未执行

You need to use elasticjob 3.0.4 for testing and provide git with minimal reproducible unit tests.

**Comment by linghengqian** [comment]
Closed because it could not be reproduced.
