### ISSUE TITLE
在使用elasticjob-lite-spring-boot-starter开发手动触发任务时，报错，找不到指定的bean

### ISSUE THREAD

**Issue by yoboygo** [apache/shardingsphere-elasticjob#2389]
根据文档的说明，在配置手动任务时指定jobBootstrapBeanName的名字，会自动创建OneOffJobBootstrap实例，然后在controller里直接注入即可。但是在实际使用的过程中发现，bean的加载顺序有点问题，只有在Controller上添加@lazy的注解才可以正常启动。是我用错了还是什么原因？还有就是如果不设置DB，是不是就不能加载了？

**Comment by linghengqian** [comment]
- You need to provide a git with unit tests, or feel free to raise a PR with a fix.

**Comment by linghengqian** [comment]
- Reproduced at https://github.com/apache/shardingsphere-elasticjob/pull/2417. I will fix this documentation issue.

**Comment by linghengqian** [comment]
- I personally would never recommend using `@Lazy`, it is not in line with normal human thinking.

**Comment by linghengqian** [comment]
> 还有就是如果不设置DB，是不是就不能加载了？

- Not required, unless you need to use `elasticjob.tracing.type` as `RDB`.
