### ISSUE TITLE
40 tasks 150 pods cause zk high cpu

### ISSUE THREAD

**Issue by Pantheooon** [apache/shardingsphere-elasticjob#2403]
## Question

Hi ,we have a service use elastic job ,this service have 40 tasks and 150 pods,when we start these pods,zk's cpu is very high,and service's startup is very slow,can we have any solution about this problem?
we use elastic-job-lite version is 3.0.0

**Comment by linghengqian** [comment]
You need to provide git containing unit tests, can not reproduce. By the way, this sounds more like a problem with the curator client, you can use elasticjob 3.0.4 test.

**Comment by linghengqian** [comment]
Closed because it could not be reproduced.
