### ISSUE TITLE
ElasticJob 2.1.5版本 个别任务突然不执行，一段时间自动恢复

### ISSUE THREAD

**Issue by Nfq226** [apache/shardingsphere-elasticjob#2404]
问题：我们有个定时任务，某一时刻突然不执行了，期间没有任何代码和配置上的变动，然后过了一天左右又自动恢复了；
排查：期间排查过zk, zk有一台机器漂移，漂移时间和服务节点拉取不到任务分片的时间完全吻合，推测可能是zk有问题：1）可能选主失败，2）选主成功后，主节点划分作业分片然后写zk失败，导致服务节点拉取不到zk作业分片；最后排查下来zk选主没问题，但是主节点划分作业写到zk是否成功无法查看，因为定时任务每次调度都会写入，而且问题不好稳定复现。
这个大佬们有碰到过或者其他排查思路吗？

**Comment by linghengqian** [comment]
You need to use elasticjob 3.0.4 for testing and provide git with minimal reproducible unit tests.

**Comment by linghengqian** [comment]
Closed because it could not be reproduced.

**Comment by LeroyPine** [comment]
> Closed because it could not be reproduced.

想知道具体的原因,我们现在线上就经常出现,然后还不能随便升级版本

**Comment by linghengqian** [comment]
> > Closed because it could not be reproduced.
> 
> 想知道具体的原因,我们现在线上就经常出现,然后还不能随便升级版本

You need to provide unit tests, which are completely unrepeatable in the master branch.

If you use a Zookeeper Server deployment in the Docker Image, you can also use https://github.com/Mic92/cntr to debug.

**Comment by linghengqian** [comment]
Since there is absolutely no way to reproduce, this issue does not make sense to continue opening, unless someone can provide the git of the unit test that includes the assertion failure.
