### ISSUE TITLE
How to dynamically adding jobs

### ISSUE THREAD

**Issue by weiro-9-w7** [apache/shardingsphere-elasticjob#2415]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

I viewed the faq document and found it can implement the dynamically add jobs,
but I can't found the interface to implement it; 
how to do ?

Now, All jobs configuration need be loaded from db . 
if found the new job, need dynamiclly create them.
thanks

**Comment by weiro-9-w7** [comment]
Maybe I got , only use 
new ScheduleJobBootstrap(coordinatorRegistryCenter(), new TestJob(), createJobConfiguration());
can dynamically create it, but i'm not sure

**Comment by linghengqian** [comment]
- From my exploration at https://github.com/apache/shardingsphere-elasticjob/blob/master/test/native/src/test/java/org/apache/shardingsphere/elasticjob/test/natived/JavaTest.java , I would say that this is the only way you can add jobs at the moment. 
- Feel free to suggest new ideas, new drafts or PRs.

**Comment by weiro-9-w7** [comment]
@linghengqian 
Thanks!  
I think so too. I viewed an official mention that version 3.1 will support it.

**Comment by linghengqian** [comment]
- I will say that I do not believe the next version will be 3.1.0, and there are currently no committers or PPMCs writing for a potential next version. The next version will probably be 3.0.5.

- The main reason why ElasticJob is still updated irregularly is that ShardingSphere still needs a distributed job framework. Moreover, ShardingSphere requires that the functions of this distributed job framework meet the requirements of ShardingSphere.

**Comment by linghengqian** [comment]
- You can now use `org.apache.shardingsphere.elasticjob.lifecycle.api.JobConfigurationAPI`. See https://shardingsphere.apache.org/elasticjob/current/en/user-manual/usage/operation-api/ and `org.apache.shardingsphere.elasticjob.lifecycle.internal.settings.JobConfigurationAPIImplTest`.
- I am about to add unit tests to nativeTest under GraalVM Native Image.

**Comment by linghengqian** [comment]
- Feel free to check out #2426 in `org.apache.shardingsphere.elasticjob.test.natived.it.operation.JavaTest` for ways to add, delete, modify, and query jobs.
