### ISSUE TITLE
elastic-job-cloud-scheduler.properties中hostname不支持域名

### ISSUE THREAD

**Issue by renbaoyu** [apache/shardingsphere-elasticjob#417]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5
### Please provide the reproduce example codes (such as github link) if possible.
elastic-job-cloud-scheduler.properties中hostname不支持域名，而http://elasticjob.io/docs/elastic-job-cloud/01-start/deploy-guide/的附录中写到，可以是IP地址或者hostname

**Comment by terrymanu** [comment]
This config item is used for mesos directly, we can not support host name if it cannot support by mesos
