### ISSUE TITLE
sharding-total-count配置为0后，再次overwrite也没用

### ISSUE THREAD

**Issue by devenfan** [apache/shardingsphere-elasticjob#434]
当sharding-total-count被设置为0后（overwrite为true），zk中的配置信息会被写为0；此时再次被修改为大于0的值的时候，已经无法启动并覆盖zk中的信息了……

### Job 第一次配置
	<job:simple id="myJob1" class="com.xyz.scheduler.job.TestJob" registry-center-ref="regCenter" cron="0/10 * * * * ?"
				sharding-total-count="0" overwrite="true" failover="true"
	/>

### Job 第二次配置
	<job:simple id="myJob1" class="com.xyz.scheduler.job.TestJob" registry-center-ref="regCenter" cron="0/10 * * * * ?"
				sharding-total-count="1" overwrite="true" failover="true"
	/>

### 错误信息

Caused by: java.lang.IllegalArgumentException: shardingTotalCount should larger than zero.

**Comment by terrymanu** [comment]
直接修改zk并导致的错误不在我们的考虑范围之内，请通过console或程序修改。自行修改zk请保证zk数据的完整性

**Comment by devenfan** [comment]
@terrymanu  并未直接修改zk中的数据，两次都是通过配置文件进行配置的，只不过有一次正好配置sharding-total-count为0，发现再也无法启动了

**Comment by anglewu** [comment]
我也遇到了，后修改下ID名称就好了。如果不修改ID名称，就再也无法启动。
