### ISSUE TITLE
请问是否支持非侵入式的任务调度

### ISSUE THREAD

**Issue by yangmilestone** [apache/shardingsphere-elasticjob#435]
我想寻找这样一个任务调度框架，就是在业务系统中可以不实现官方所规定的接口或者抽象类，业务系统中只提供rpc（暂定为dubbo协议）或者http方式的接口和zk注册中心的地址，调度框架可以根据我配置的内容去自行调用该接口，实现定时任务调度

**Comment by terrymanu** [comment]
目前elastic job不支持这种方式。elastic job是携带分片上下文的，需要通过java api传递分片上下文。可以使用shell的方式，会将分片上下文作为shell的命令行参数传递
