### ISSUE TITLE
Elastic job: ignored exception for: KeeperErrorCode = NoNode

### ISSUE THREAD

**Issue by DTBruce** [apache/shardingsphere-elasticjob#437]
elastic-job-lite：2.15
SimpleJob:15个
分片：30
Docker实例：10
zk集群：5台

问题描述：每次部署上线，15个Job只有4-5个能正常上线，其余直接是下线状态

查看debug日志，发现大量【Elastic job: ignored exception for: KeeperErrorCode = NoNode】的日志
查看zk集群上节点，发现instances下的确没有在线的

奇怪的地方：console中已经下线的Job，在execute中执行的业务日志仍然能够记录到该下线job的执行记录

**Comment by terrymanu** [comment]
dump出来将内容贴过来看一下

**Comment by terrymanu** [comment]
该长时间未跟进，且提出人不再反馈。并且没有可重现的必要条件，因此关闭
