### ISSUE TITLE
http类型的定时任务遇到504后会自动重试吗？

### ISSUE THREAD

**Issue by IcyLemon** [apache/shardingsphere-elasticjob#438]
使用的elastic-job版本：2.1.1。

我的一个定时任务为通过 http 方式（使用 OKHttp 发送 http 请求）执行某个方法（例如：http://ip:port/myapp/synFundData）。

当调用上述接口时如果服务器返回504（后台执行时间太长导致超时），请问该定时任务是否会自动重试？因为我从 Nginx 的日志中发现：每隔30秒Nginx 会收到一个同样的http请求，且返回的状态码都是 504，日志如下：

...remote_user=- [16/Nov/2017:08:40:01 +0800] request="GET /xxx/synFundData HTTP/1.1" status=504 
...remote_user=- [16/Nov/2017:08:40:31 +0800] request="GET /xxx/synFundData HTTP/1.1" status=504 
...remote_user=- [16/Nov/2017:08:41:01 +0800] request="GET /xxx/synFundData HTTP/1.1" status=504 
...remote_user=- [16/Nov/2017:08:41:31 +0800] request="GET /xxx/synFundData HTTP/1.1" status=504 
...
可见每隔30秒，而且一直会重试下去。

请问这是否是 elastic-job的重试机制？

谢谢。

**Comment by terrymanu** [comment]
job的cron表达式怎么配置的？

**Comment by IcyLemon** [comment]
cron是没有问题的，每天凌晨3点：0 0 3 * * ?

这个只有在服务器端返回504的时候才会出现上述每隔30秒重试的情况。比如：3点整执行任务，如果服务器返回504，那么03:00:30、03:01:00、03:01:30... 都会再调一次，一直下去。

一开始以为是Nginx 进行了重试（我们的服务都做了转发），但是运维后面排查不是，所以请问是不是ej的重试机制？

**Comment by terrymanu** [comment]
ej没有重试机制，使用dataflow类型还是simple？

**Comment by IcyLemon** [comment]
用的是 simple。
这两天我们通过不断测试发现：
1、通过非定时任务的方式（如：页面点击、fiddler）发送相同的http请求时，不会每隔30秒重试（从Nginx的access_log日志可以看出）；
2、只要停止了定时任务服务，重试就会终止。

**Comment by terrymanu** [comment]
这个问题应该不易用文字描述，请提供可重现的代码示例

**Comment by IcyLemon** [comment]
好的，我们再跟踪一段时间，到时给出详细的复现过程。谢谢。

**Comment by terrymanu** [comment]
Closed because of no response anymore
