### ISSUE TITLE
支持mesos executor containerizer with docker吗？

### ISSUE THREAD

**Issue by lukangping** [apache/shardingsphere-elasticjob#440]
当前版本2.1.6-SNAPSHOT，没有看到对ContainerInfo的设置，有测试的分支吗？

**Comment by terrymanu** [comment]
目前不支持，因为使用了mesos executor的资源动态追加能力

**Comment by lukangping** [comment]
用mesos container with docker images临时解决了一下:
https://gist.github.com/lukangping/4e1f8b6aec16867d4178b9f500cfaa43
