### ISSUE TITLE
任务会重复执行

### ISSUE THREAD

**Issue by yinjihuan** [apache/shardingsphere-elasticjob#441]
有3个简单任务，凌晨1点执行，下午加了新的任务，重新发布了下，重启之后之前的老任务又重新执行了一遍，请问亮哥这是不是bug，还是我们上面地方配错了

**Comment by terrymanu** [comment]
可以开启monitorExecution配置，详情请阅读文档

**Comment by yinjihuan** [comment]
monitorExecution默认的配置项就是true,还需要手动配置么
