### ISSUE TITLE
关于获取Hostname异常问题

### ISSUE THREAD

**Issue by dudan57** [apache/shardingsphere-elasticjob#442]
job在执行时，需要获取hostname用于记录日志，但我们的项目部署在docker中，获取hostname时抛异常了，导致任务执行失败。建议获取hostname时，不要抛异常，以免影响Job的正常执行

/elastic-job-common-core/src/main/java/com/dangdang/ddframe/job/event/type/JobExecutionEvent.java
/elastic-job-common-core/src/main/java/com/dangdang/ddframe/job/util/env/IpUtils.IpUtils.java()

**Comment by terrymanu** [comment]
请提供异常信息

**Comment by terrymanu** [comment]
这种方式并不能解决问题，只是将异常抛出并且返回空值。
因此这个pr我不能合并。
请提供异常信息，我们会着手解决

**Comment by dudan57** [comment]
Caused by: com.dangdang.ddframe.job.util.env.HostException: java.net.UnknownHostException: 588406e6cbb8: 588406e6cbb8: 域名解析暂时失败
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at com.dangdang.ddframe.job.util.env.IpUtils.getHostName(IpUtils.java:105)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at com.dangdang.ddframe.job.event.type.JobExecutionEvent.<init>(JobExecutionEvent.java:43)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.process(AbstractElasticJobExecutor.java:170)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.execute(AbstractElasticJobExecutor.java:150)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.execute(AbstractElasticJobExecutor.java:122)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at com.dangdang.ddframe.job.lite.internal.schedule.LiteJob.execute(LiteJob.java:26)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         ... 1 common frames omitted
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]: Caused by: java.net.UnknownHostException: 588406e6cbb8: 588406e6cbb8: 域名解析暂时失败
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at com.dangdang.ddframe.job.util.env.IpUtils.getHostName(IpUtils.java:103)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         ... 7 common frames omitted
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]: Caused by: java.net.UnknownHostException: 588406e6cbb8: 域名解析暂时失败
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
Nov 24 16:00:00 gs-dcos12-node33 dockerd[27644]:         at java.net.InetAddress.getLocalHost(InetAddress.java:1500)

**Comment by terrymanu** [comment]
这是不是没定义hosts文件导致的

**Comment by dudan57** [comment]
588406e6cbb8
这串字符就是容器返回的hostname
Host模式没有报错，bridge模式才报的这个错

**Comment by weixuedian** [comment]
docker部署到多台机器上，每一台机器获取到docker的ip都是一样的，导致控制台显示两个一样的ip。这种有什么解决办法吗？

**Comment by nangongh** [comment]
这个问题，有人解决吗。我的应用也报这个错

**Comment by terrymanu** [comment]
Duplicate with #508
