### ISSUE TITLE
AbstractIndividualThroughputDataFlowElasticJob

### ISSUE THREAD

**Issue by chaletli** [apache/shardingsphere-elasticjob#446]
hi，看到说明里有支持高吞吐的数据流作业，ThroughputDataFlow，需要继承AbstractIndividualThroughputDataFlowElasticJob并可以指定返回值泛型。但是我在git里怎么没找到这个类？

**Comment by terrymanu** [comment]
版本问题

**Comment by chaletli** [comment]
@terrymanu 你好，我是直接在github的库里搜索的AbstractIndividualThroughputDataFlowElasticJob，但是提示没有结果。我搜索的branch是master，版本是2.1.5
