### ISSUE TITLE
任务为什么无故不执行了？

### ISSUE THREAD

**Issue by IcyLemon** [apache/shardingsphere-elasticjob#447]
一个每隔5分钟的定时任务（cron没有问题），正常运行一段时间后，就再也不执行了。

控制台的历史轨迹如下：
![-](https://user-images.githubusercontent.com/19788374/33420774-cd13d77a-d5ea-11e7-844f-7d6f3fa7bea6.jpg)

上图红框中，该任务在2017-11-29 23:30:00执行失败后，后面就再也不会执行了！！！而且失败也看不到日志在什么地方。

控制台的历史状态：
![default](https://user-images.githubusercontent.com/19788374/33420498-c991b7a8-d5e9-11e7-9064-fd73cdc3a95b.jpg)

上图红框中，2017-11-29 23:30:00 的时候该任务只有TASK_STAGING一个状态，而 TASK_RUNNING和TASK_FINISHED状态再也没有出现过，而且后续再也没有该任务的运行记录，而控制台上该任务的状态是正常的。

后台日志中和数据库中也未见任何异常。

请问这种情况可能是什么原因导致的？以前有这方面的类似案例吗？谢谢

**Comment by IcyLemon** [comment]
又确认了一下，是所有的定时任务都不执行了，而任务状态又都显示正常，服务器进程也运行正常。

**Comment by terrymanu** [comment]
请将“无故”调研一下，用合理的可重现方法描述一下，否则我们无法接受和修改这个问题。

**Comment by terrymanu** [comment]
长时间无反馈，且无法根据当前信息判断是否为bug，该issue关闭
