### ISSUE TITLE
单机借助zk多项目如何配置模拟elastic-job，定时任务只运行一次

### ISSUE THREAD

**Issue by JiongJiongGe** [apache/shardingsphere-elasticjob#448]
Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
我们认为定时任务只运行一次，就不能称之为定时任务。因此暂时不支持

**Comment by JiongJiongGe** [comment]
应该是我表达的意思不对，我想问的是单机多项目部署，借助zk，如何配置保证多项目的定时任务不重复执行
