### ISSUE TITLE
事件追踪-基于关系型数据库的事件追踪不支持oracle数据库?

### ISSUE THREAD

**Issue by yuweiming2016** [apache/shardingsphere-elasticjob#449]
### Which version of Elastic-Job do you using?
lite-2.1.5

### Actual behavior
事件追踪-基于关系型数据库的事件追踪不支持oracle数据库?

![image](https://user-images.githubusercontent.com/22490427/33872085-59584464-df50-11e7-9995-ff5f9403a8c1.png)

**Comment by terrymanu** [comment]
数据库之间的差别就在ddl，我们目前并无支持oracle的需求，如果可以，请提供pr

**Comment by yuweiming2016** [comment]
改了一个晚上，发现通篇都是用mysql语法写的，不仅是create table，select  ……………… limit，oracle的分页要用子查询嵌套的，放弃了……，，，现在只改到能用oracle语法insert和update成功，查询还没改

**Comment by terrymanu** [comment]
请问目前针对mysql的sql，分页不用limit，还有别的选择么

**Comment by yuweiming2016** [comment]
能否官方提供一个jpa的解决方案？@terrymanu
