### ISSUE TITLE
运行过程中总分片变为0，仍然会有分片在执行

### ISSUE THREAD

**Issue by chenguofu1001** [apache/shardingsphere-elasticjob#455]
我们在生产上碰到这样的场景：运行时总分片设置为2，一共有5台机器，设置了失效转移策略。定时任务每十分钟运行一次，可能存在分片运行超过十分钟的情况。
在生产上发现两个问题：
1.服务器没有宕机，zk会重新进行选择，选择执行分片的机器；
2.在打印的日志中发现，存在总分片数为0，却仍然有分片在执行，导致具体工作被重复处理；
因是生产问题，代码复杂，很难提供源码。请问是否有碰到类似的情况，如何解决？

**Comment by terrymanu** [comment]
总分片数为0是怎么做到的，应该有验证，不会为零。
除非自行改的zk中的数据，这个我们就无法预知了

**Comment by terrymanu** [comment]
issue提交者长时间无跟进。
从描述看属于误操作导致，因此关闭该issue，并按照无效问题处理
