### ISSUE TITLE
增加某一个job由于时间间隔导致的并发运行禁止选项

### ISSUE THREAD

**Issue by douxiaofeng99** [apache/shardingsphere-elasticjob#458]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.0
### Expected behavior
当任务处理时间超过时间间隔是，下一次触发取消
### Actual behavior
导致并发

**Comment by terrymanu** [comment]
分布式job远不像单机job那样简单。这中间涉及到是否跑在所有分片的job都禁止运行，如果其中一个节点运行了，另一个节点没运行又将如何同步。
分布式job本就不该向单机job那样使用，请再次梳理一下自己的需求。如果无需分片，使用quartz即可。
