### ISSUE TITLE
从控制台中enable一个job之后，job不运行

### ISSUE THREAD

**Issue by chaletli** [apache/shardingsphere-elasticjob#461]
使用lite2.1.5版本启动一个SimpleJob，设置如下：
simple.id=springSimpleJob
simple.class=com.dangdang.ddframe.job.example.jobs.SpringSimpleJob
simple.cron=0 0/1 * * * ?
simple.shardingTotalCount=3
simple.shardingItemParameters=0=Beijing,1=Shanghai,2=Guangzhou
simple.failover=true
simple.description=test
simple.disabled=true
simple.overwrite=true

控制台点击该job的enable按钮之后，任务不执行。如果disable设置为false，程序启动自动运行的话，任务是可以跑的

**Comment by chaletli** [comment]
上述问题是由于我自己给job加了一个AbstractDistributeOnceElasticJobListener的子类。然后设置的超时时间都是-1。看起来像是控制台点击了enable之后，没有触发dataChanged的监控。所以startedWait一直在wait。我改成强制超时30秒后，会主动抛错，然后任务就可以跑了。但是业务需求确实要等待控制台点击enable才能跑，所以没法强制超时吧？

**Comment by chaletli** [comment]
刚才跟进源码看了下，AbstractDistributeOnceElasticJobListener的startedWait只有在监听StartedNodeRemovedJobListener的时候才会notifyWaitingTaskStart。页面上点击enable，是走的CronSettingAndJobEventChangedJobListener，所以startedWait永远在等。这是个问题吗？还是说哪里做的不对？

**Comment by terrymanu** [comment]
应该是enable/disable并未考虑使用listener的问题所致，可能是bug，我们有空会调研下

**Comment by wujun8** [comment]
disable 后应该使得对应  Scheduler 的 listener 暂时失效，或者在 listener 里处理 enable/disable

**Comment by terrymanu** [comment]
Fixed by #997
