### ISSUE TITLE
Simple任务执行时候线程一直在上升

### ISSUE THREAD

**Issue by ljz0721cx** [apache/shardingsphere-elasticjob#462]
### 线程一直在上升

![image](https://user-images.githubusercontent.com/4934976/34430188-4ae1dbd4-ec9d-11e7-81f6-8802d76a9901.png)
![image](https://user-images.githubusercontent.com/4934976/34430189-4c66b6dc-ec9d-11e7-9e91-a1e3e2365e09.png)

这种情况正常么，在哪里配置线程池呢？

**Comment by terrymanu** [comment]
可以配置线程池大小，请仔细阅读文档
