### ISSUE TITLE
console的疑问

### ISSUE THREAD

**Issue by mychao** [apache/shardingsphere-elasticjob#464]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
elastic-job-lite-2.1.5
### Expected behavior
控制台可以同时多个namespace进行操作，不会相互被踢。想请教下，这种互斥操作的目的是什么？
### Actual behavior
正处于connected状态，其他人连接了，被迫断开

**Comment by mychao** [comment]
@haocao 还请指教。我想在程序内调用job配置，修改job配置，再调用注册中心去更新配置，是否可以？

**Comment by terrymanu** [comment]
console只是个简单运维工具，目前没考虑对用户和namespace进行控制。
elastic job本身的关注点在于分布式作业，界面类的并不关注，只是给开源社区提供一个桥接，因此，如有需要，自行修改即可
