### ISSUE TITLE
每3秒运行的定时任务，运行几天后，执行任务的线程出现卡顿，导致执行任务的时间变得很长

### ISSUE THREAD

**Issue by rudy2015** [apache/shardingsphere-elasticjob#465]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
elastic-job-lite-spring:2.1.5

**Comment by terrymanu** [comment]
应该是任务中的业务代码导致。定时任务直接使用的qurartz使用，如quartz本身有相关问题，应不会被如此大规模使用。
请自行排查自己的业务代码
