### ISSUE TITLE
Spring ApplicationContextt is null

### ISSUE THREAD

**Issue by wanglong9** [apache/shardingsphere-elasticjob#466]
### 前置条件
项目集成Spring成功。
### 需求
自定义类MySimpleJob实现SimpleJob类，内部通过ApplicationContext获取其他容器bean。
### 问题
当使用JobScheduler初始化job时，在122行
`  result.getJobDataMap().put(ELASTIC_JOB_DATA_MAP_KEY, Class.forName(jobClass).newInstance());`
反射生成MySimpleJob时，会报applicationContext为null无法生成容器中其他的bean。
但当使用SpringJobScheduler初始化时
```
 MySimpleJob job= (MySimpleJob) handlerClz.newInstance();
 SpringJobScheduler springsScheduler = new SpringJobScheduler(job,regCenter,liteJobConfiguration);
 springsScheduler.init();
```
MySimpleJob 内部的ApplicationContext是有值的。

对比了SpringJobScheduler和JobScheduler，并未弄明白为什么会这样，同样是反射生成bean，为什么JobScheduler反射的时候会丢失ApplicationContext上下文

**Comment by terrymanu** [comment]
已经提供了SpringJobScheduler，因此spring相关请使用SpringJobScheduler。在spring使用环境下使用JobScheduler导致的问题按照使用不当处理，我们不会再跟进。
