### ISSUE TITLE
任务已经执行完成，但zk上记录的状态一直是running，导致该任务后面不再执行？

### ISSUE THREAD

**Issue by IcyLemon** [apache/shardingsphere-elasticjob#467]
Hi，问题描述如下：

我的一个任务，通过在execute(ShardingContext shardingContext)方法中记录的运行日志看，是执行完成的（方法最后一行记录了日志），相关的操作结果也是正确的（比如正确入库）。

但是监听器ElasticJobListener的afterJobExecuted(ShardingContexts shardingContexts)方法却没有执行，因为里面的运行日志没有打印；

通过查看zookeeper中该节点的状态，发现其sharding/0中，一直有一个running节点（网络不好，上传截图老失败），而正常情况下执行完成的节点，应该是completed。这样导致该任务后面就不再执行了。

请问上面这个问题可能的原因是什么？

谢谢。

**Comment by terrymanu** [comment]
请提供可重现问题的代码，并提交至您自己的github repo，以帮助我们重现问题

**Comment by xue2lang** [comment]
确实有这个问题，我们也遇到同样的问题

**Comment by xue2lang** [comment]
确实有这个问题，我们也遇到同样的问题，麻烦问一下这个问题如何解决的？？

**Comment by rob89828** [comment]
同样遇到这个问题，zk上看是部分分片始终属于running状态。通过重启服务器或者将zk上running属性删除可以解决。怀疑是某种情况下任务complete的状态没有被zk拿到

**Comment by gerryliu2489** [comment]
同样遇到这个问题，我是同一台机器起了两个节点，运行一会就出现该问题，很容易复现，ejob版本2.1.5

**Comment by rob89828** [comment]
我们也是一台机器两个节点。
之前有一段时间有这种情况，但后来恢复了。
应该是有什么其他的组件导致任务卡住了，我们应该是kafka导致的




344580823@qq.com
 
发件人： gerryliu2489
发送时间： 2019-10-22 11:30
收件人： elasticjob/elastic-job-lite
抄送： rob89828; Comment
主题： Re: [elasticjob/elastic-job-lite] 任务已经执行完成，但zk上记录的状态一直是running，导致该任务后面不再执行？ (#467)
同样遇到这个问题，我是同一台机器起了两个节点，运行一会就出现该问题，很容易复现，ejob版本2.1.5

**Comment by terrymanu** [comment]
Can not reproduce the issue and no code provide. I just close it

**Comment by xishian** [comment]
<img width="342" height="605" alt="Image" src="https://github.com/user-attachments/assets/392d58bb-6e5d-4733-a401-69520e1b3139" />
这个问题还是存在，看来是老bug了，猜测是上报任务状态的逻辑有问题，任务完成后，同步到zk失败，导致任务被当作一直处于running，后续就不再执行
