### ISSUE TITLE
overwrite覆盖注册中心配置Bug

### ISSUE THREAD

**Issue by yinjihuan** [apache/shardingsphere-elasticjob#469]
当刚开始shardingTotalCount配置为0的时候，启动会报下面的异常：
Caused by: java.lang.IllegalArgumentException: shardingTotalCount should larger than zero.

然后把shardingTotalCount改成1，加上overwrite=“true” 这个时候是不会去覆盖默认的配置，这个问题应该是如果注册中心的配置是错误的情况下，就不能用overwrite去覆盖了，只能通过手动的去删除zk中的配置信息了，这个算不算bug?

**Comment by terrymanu** [comment]
应该是bug，我们有空会处理下

**Comment by chenghm123** [comment]
这个BUG是否已经修复？

**Comment by gMan1990** [comment]
木有！！！version-2.1.5
-----------------
只能通过手动的去删除zk中的配置信息了
@yinjihuan 怎么删，我不会/尴尬

**Comment by hyhr** [comment]
我也遇到这个问题，而且每次配置出错都会抛出数据库相关的异常

**Comment by MonkeyDis** [comment]
确实存在这个问题，我用的是2.0.4版本。
临时解决办法：

- 使用zookeeper客户端连接到zk服务器，手动删除Elastic-Job在zookeeper注册的节点（注册中心的配置文件可以看到namesapce）
- 重新启动Elastic-Job

**Comment by Technoboy-** [comment]
Thanks!  Fix in the latest version, please check !
