### ISSUE TITLE
任务重复执行BUG

### ISSUE THREAD

**Issue by kevinye1227** [apache/shardingsphere-elasticjob#470]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.0.5
### Expected behavior
启动task后，在Job平台上点击触发，触发任务执行，执行完后，下一次任务按schedule设定的time触发下一次执行。
### Actual behavior
启动task后，在Job平台上点击触发，触发任务执行，执行完后，没到配置的时间，立即开始了下一次的执行。两次执行完后，Job停止执行。
### Steps to reproduce the behavior
任务schedule的CRON：0 * 12 10 * ?
第一次执行完的时间：01/11 22:50:14.142	
第二次开始执行的时间：01/11 22:50:14.163	
### Please provide the reproduce example codes (such as github link) if possible.
作业的xml配置：

```xml
<!--配置作业注册中心 -->
    <reg:zookeeper id="regCenter" server-lists="#{systemEnvironment.JAVA_ZOOKEEPER_HOST}"
                   namespace="task/dsp-ps-dts" base-sleep-time-milliseconds="1000"
                   max-sleep-time-milliseconds="3000" max-retries="3"/>

<job:simple id="adtsJobA" class="dsp.ps.dts.task.job.DtsJobA" registry-center-ref="regCenter"
                cron="0 * 12 10 * ?" sharding-total-count="1" description="数据迁移任务A"/>
```

Job平台上：
支持自动失效转移 未勾选
支持misfire  已勾选

**Comment by kevinye1227** [comment]
本地环境一直无法重新这个问题，线上环境出现过两次

**Comment by IcyLemon** [comment]
我也遇到过一次，重复执行了好几次。但目前还没有找到复现的方法。

**Comment by terrymanu** [comment]
请再调研一下，提供稳定的可重现条件，否则，仅以当前的信息，我们无法将其认为是bug并立项处理

**Comment by kevinye1227** [comment]
提到这里，是因为无法重现出来这个问题，希望借助这个平台，看下是否有其他同仁用到这个工具，有遇到类似问题，可以提供一些思路想法。

**Comment by richardboot** [comment]
我们也遇到了没按照指定时间执行的情况，查看日志执行时间，推测可能是重启服务器的时候执行的

**Comment by terrymanu** [comment]
请提供源码，以及zk的dump数据

**Comment by wgou** [comment]
同样遇到过莫名执行了两次，同一个任务同一个分片，在相聚不到1s的时间内，被触发两次，根据当时情况以及zk上的数据，没有找到其原因。 而后加上了RDB策略，用于记录任务日志。
另外说明下，RDB创建索引在mysql上报错，每次需要手动建表和索引。
表：JOB_STATUS_TRACE_LOG 索引：TASK_ID_STATE_INDEX
原因:task_id + state 索引超长，建议将task_id 更改为varchar(100).。

**Comment by itshaw89** [comment]
遇到相同的情况，在同一个节点，同一个时间点被触发两次

**Comment by ShawHero** [comment]
发现是不小心在SimpleJob类上多加了个@Component注解，而在配置文件中已经配置了<job:simple>，导致同一个定时任务类实例化了两次

**Comment by superbool** [comment]
遇到相同情况，版本2.0.3   ,配置时间【0 40 7 * * ? 】 执行了两次，当时系统没有其他异常。 
```
2018-09-26 07:40:00.271 +0800 [541_Worker-1] INFO   [AbstractSimpleJob.java:41] - start execute job, jobId is 541, taskId is 1e265324d6a54b34bc0b7639bb54319b
2018-09-26 07:40:00.393 +0800 [541_Worker-1] INFO   [AbstractSimpleJob.java:41] - start execute job, jobId is 541, taskId is 1df00aac53b647fe9fd09173e8988974
```
代码：
```
public abstract class AbstractSimpleJob implements SimpleJob {

    @Override
    public void execute(ShardingContext context) {
        int jobId = Integer.valueOf(context.getJobName());
        String taskId = TaskIdUtils.generateTaskId();
        log.info("start execute job, jobId is {}, taskId is {}", jobId, taskId);
        ...
     }
}
```

**Comment by itshaw89** [comment]
追踪到job被实例化了两次

**Comment by Ah39** [comment]
misfire 设置为false就行了。quartz 手动触发，不在cron的时间运行，会认为是misfire。又执行一次

**Comment by Ah39** [comment]
@ShawHero ，哪个地方创建了jobdetail 两次。

**Comment by Ah39** [comment]
![image](https://user-images.githubusercontent.com/2367243/48527099-e8b1ca80-e8c4-11e8-85cf-90b5dd8b22df.png)
misfire 会创建两个jobdetail，应该确认的，但是不知道哪里调用创建的misfire。misfire导致quartz 线程死循环估计也跟创建了两个joddetail有关

**Comment by fenghy** [comment]
我也碰到过，情景是这样：在一个tomcat下部署了2个相同项目，job每次都是执行2次。原因：2个项目启动的时候相同job会注册2次，所以创建了jobdetail 两次，但是job key是基于ip+jvm name,所以在zk看到的是一个job。

**Comment by wydpp** [comment]
刚才遇到了重复执行的问题。两台机器，设置的sharding-total-count="1"，偶尔有任务会再两台机器上都运行。暂时不知道为什么，所以线上目前关掉了一台机器。后续有结果再反馈。

**Comment by nmyphp** [comment]
@fenghy 建议检查一下是否与你的tomcat配置有关了：
有时候我们为了访问项目时路径中不带dirName，会在<Host autoDeploy="true">标签添加一个<Context>标签，这回导致我们的工程被加载两遍。

**Comment by haodanhui521** [comment]
![image](https://user-images.githubusercontent.com/45254880/79557206-c2551780-80d4-11ea-9c62-ce09999f2f14.png)
![image](https://user-images.githubusercontent.com/45254880/79557193-bc5f3680-80d4-11ea-8ade-e8cd203c72bf.png)

**Comment by terrymanu** [comment]
Can not reproduce the issue and no code provide. I just close it
