### ISSUE TITLE
使用elasticjob，tomcat无法正常关闭

### ISSUE THREAD

**Issue by liub1989** [apache/shardingsphere-elasticjob#471]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.4
spring >= 3.x
### Expected behavior
tomcat的shutdown能正常关闭，不影响再次启动
### Actual behavior
tomcat的shutdown无法完全关闭，再次启动异常。查看jstack
![image](https://user-images.githubusercontent.com/4240450/35027245-9c6b9160-fb8a-11e7-8d5e-f0d9c9906355.png)
属于用户进程且没有关闭
### Steps to reproduce the behavior
bin/shutdown.sh
### Please provide the reproduce example codes (such as github link) if possible.

    <reg:zookeeper id="regCenter" server-lists="${zookeeper.address}" namespace="test"
                   base-sleep-time-milliseconds="1000" max-sleep-time-milliseconds="3000" max-retries="3" />

    <job:simple id="monitorJob" job-ref="monitorJob"
                registry-center-ref="regCenter"
                cron="${cron.monitorJob}"
                sharding-total-count="1"
                description="定时任务的监控任务"
                overwrite="true"/>

**Comment by terrymanu** [comment]
需要自行将ejob的shutdown方法在servlet的destroy中调用吧
