### ISSUE TITLE
如何实现服务一启动不会更新zk中定时任务的失效状态？

### ISSUE THREAD

**Issue by bobyang-coder** [apache/shardingsphere-elasticjob#473]
场景：服务双机房部署，zk数据不同，需要关闭一个机房的定时任务

除了使用job-parameter在代码逻辑中控制开关和双机房使用一个zk情况下，能直接在服务启动的时候不会修改zk中的失效状态吗？

**Comment by terrymanu** [comment]
zk数据不同是两个注册中心。作业也是两套。目前elastic-job不支持同一份作业部署至两套注册中心
