### ISSUE TITLE
如何升级curator版本？

### ISSUE THREAD

**Issue by leasontou** [apache/shardingsphere-elasticjob#475]
curator2.10.0的版本有bug，我项目本身依赖的是3.2.0，如何升级elastic-job依赖的curator？

**Comment by terrymanu** [comment]
curator各种版本之间并不兼容，无论升级与否，都不可能做到全兼容。
因此目前的想法是去掉curator，直接使用zk的原生客户端。
但目前我们暂时没有精力做这件事，因此如果有可能，欢迎各位自行实现并提交pr。

**Comment by kamping** [comment]
请问2.10.0有什么bug

**Comment by ryuhi** [comment]
@kamping 最近做项目，用了dubbo2.6.1，它默认使用curator2.12.0做Zookeeper的客户端，结果和ej的版本冲突，报没有retrypolicy的类，升级版本到4.0.0之后，不报这个错了，但是在执行任务的时候，报没有createBuilder类的某个方法

看了一下，4.0.0版本的返回类和2.12.0/2.10.0的返回类是子类和父类的关系，应该不至于报找不到的错误，很奇怪

**Comment by handosme** [comment]
主要还是curator依赖的guava不能向下兼容吧，我的处理方式是使用maven-shade-plugin重定向com.google路径，然后把源码重新打包，问题解决了！

**Comment by sven-limited** [comment]
@handosme  你好我遇到了 curator的兼容问题 想跟您请教下 18920345531我的微信号  求加微信  万分感谢

**Comment by handosme** [comment]
@sven-limited maven-shade-plugin重新打包源码，下面是mvn插件配置供参考： 
master分支上，修改elastic-job-lite/elastic-job-lite-spring/pom.xml 文件，在</dependencies> 后增加如下内容：  
```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.1.1</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <minimizeJar>true</minimizeJar>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                        <filters>
                            <filter>
                                <artifact>*:*</artifact>
                                <excludes>
                                    <exclude>META-INF/*.SF</exclude>
                                    <exclude>META-INF/*.DSA</exclude>
                                    <exclude>META-INF/*.RSA</exclude>
                                </excludes>
                            </filter>
                        </filters>
                        <relocations>
                            <relocation>
                                <pattern>com.google</pattern>
                                <shadedPattern>com.dangdang.shaded.com.google</shadedPattern>
                            </relocation>
                        </relocations>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by larrychao** [comment]
@handosme 这种方式相当于把guava打包进了项目？会造成jar包很大？

**Comment by ryuhi** [comment]
今天又碰到这个问题，有时间就仔细看了下，4.0.0版本的返回类的父类和2.12.0/2.10.0的返回类（均是接口），继承了多个接口，造成方法列表不一样。包名、类名均相同，方法列表不一样，这样算是两个类吗？如果是两个类，就不存在父子类的问题，返回类型不符合，所以报方法不存在。我这样猜测对吗？请各位指教。

**Comment by nmyphp** [comment]
@ryuhi 你好，看到你的问题引发的主要原因是：
同一pom依赖或间接依赖了elastic-job和dubbo这两个中间件，但他们依赖的curator版本不一致，导致了jar冲突。
建议：将dubbo接口和elastic-job分开放在两个module里面，然后两个module分别去依赖dubbo和elastic-job，并且去掉这两个module的父pom里面的dubbo和elastic-job依赖。
其实这属于项目结构设计方面的经验，依赖jar应该“就近原则”

**Comment by ryuhi** [comment]
> @ryuhi 你好，看到你的问题引发的主要原因是：
> 同一pom依赖或间接依赖了elastic-job和dubbo这两个中间件，但他们依赖的curator版本不一致，导致了jar冲突。
> 建议：将dubbo接口和elastic-job分开放在两个module里面，然后两个module分别去依赖dubbo和elastic-job，并且去掉这两个module的父pom里面的dubbo和elastic-job依赖。
> 其实这属于项目结构设计方面的经验，依赖jar应该“就近原则”

这的确是一个方法，Thanks a lot.

**Comment by JeffreyPan** [comment]
针对Curator版本冲突问题，可以考虑elastic-job升级到4.0.1，Curator-client依赖排除zookeeper，同时再引入公司使用的zookeeper版本

**Comment by ryuhi** [comment]
> 针对Curator版本冲突问题，可以考虑elastic-job升级到4.0.1，Curator-client依赖排除zookeeper，同时再引入公司使用的zookeeper版本

elastic-job没有4.0.1的版本啊，如果是说Curator，那我遇到的问题也和Zookeeper无关

**Comment by Jody-Jiang** [comment]
curator2.10.0的版本有bug,无法选举，造成主线程一直等待，这个如何是好

**Comment by terrymanu** [comment]
Duplicated with #753
