### ISSUE TITLE
任务重复执行BUG且没有按给定的cron执行

### ISSUE THREAD

**Issue by yidinshi** [apache/shardingsphere-elasticjob#476]
设置如下：

```xml
    <job:simple id="appVisitJob" class="com.jobs.AppVisitJob" registry-center-ref="jobRegCenter" cron="0 * 12 10 * ?" sharding-total-count="1" sharding-item-parameters="0=A" />
```

执行结果：
<2018-01-29 11:46:50> <appVisitJob_Worker-1> com.jobs.AppVisitJob.execute(AppVisitJob.java:80) <ERROR> 72消息推送:[, ] 返回结果: 0
SystemJobsManager do something by sharding item 0
PayResult:[, ]
job complete: 0
<2018-01-29 11:47:00> <appVisitJob_Worker-1> com.jobs.AppVisitJob.execute(AppVisitJob.java:80) <ERROR> 72消息推送:[, ] 返回结果: 0
SystemJobsManager do something by sharding item 0
PayResult:[, ]
job complete: 0
<2018-01-29 11:47:10> <appVisitJob_Worker-1> com.jobs.AppVisitJob.execute(AppVisitJob.java:80) <ERROR> 72消息推送:[, ] 返回结果: 0
SystemJobsManager do something by sharding item 0
PayResult:[, ]
job complete: 0
<2018-01-29 11:47:20> <appVisitJob_Worker-1> com.jobs.AppVisitJob.execute(AppVisitJob.java:80) <ERROR> 72消息推送:[, ] 返回结果: 0
SystemJobsManager do something by sharding item 0
PayResult:[, ]
job complete: 0

变成隔10秒就执行一次，换其它cron也会短时间重复执行且不是在设置的时间内

**Comment by terrymanu** [comment]
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上。为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭。
