### ISSUE TITLE
手动触发任务能否实现代码触发

### ISSUE THREAD

**Issue by wudadadaju** [apache/shardingsphere-elasticjob#477]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite-2.1.5
### Expected behavior （您预期的结果是）
一个定时任务所有分片执行结束后，通过监听触发下一个任务。
### Actual behavior （实际运行的结果是）
无，不知道如何触发下一个任务。是不是只能定时。。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
elastic-job主要用于处理定时任务，而非事件驱动的任务，如果需要事件驱动，请使用mq
