### ISSUE TITLE
ElasticJob是线程不安全的类，是否考虑每一个分片，分别使用不同的实例？

### ISSUE THREAD

**Issue by gzlicanyi** [apache/shardingsphere-elasticjob#479]
如题

**Comment by terrymanu** [comment]
elastic job是线程不安全的类，这个结论是如何得出的？

**Comment by gzlicanyi** [comment]
比如一台机器运行多个分片，ElasticJob里面的属性是分片共享的吧，execute操作同一个属性时，就会有并发问题

**Comment by terrymanu** [comment]
这个与使用模式有关。举例说明：写一个servlet，会使用它的属性么，servlet是否非线程安全？

**Comment by gzlicanyi** [comment]
嗯嗯，定位问题，意思都懂
