### ISSUE TITLE
简单任务调度，采用2个分片，调用dubbo服务，dubbo shutdown

### ISSUE THREAD

**Issue by andyliuxl** [apache/shardingsphere-elasticjob#480]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5 dubbo:2.5.9
### Expected behavior （您预期的结果是）
采用SimpleJob任务分片处理，dubbo 服务正常运行
### Actual behavior （实际运行的结果是）
采用SimpleJob任务分片处理，dubbo 所有服务shutdown
### Steps to reproduce the behavior （可重现问题的操作步骤）
任务如下配置：
accountInformation.id=accountInformationJob
accountInformation.class=com.lenovo.thinkiot.job.billingsystems.AccountInformationJob
accountInformation.cron=* 0/1 * * * ?
accountInformation.shardingTotalCount=2
accountInformation.shardingItemParameters=0=1,1=2
#accountInformation.shardingTotalCount=1
#accountInformation.shardingItemParameters=
accountInformation.monitorExecution=false
accountInformation.failover=true
accountInformation.description=\u8D26\u672C\u6587\u4EF6\u5B9E\u65F6\u540C\u6B65
accountInformation.disabled=false
accountInformation.overwrite=true
accountInformation.monitorPort=9888
代码如下：
public class HangzhouAccountInformationJob implements SimpleJob {

    private static final Logger logger = LoggerFactory.getLogger(HangzhouAccountInformationJob.class);

    @Resource(name = "accountInformationService")
    private AccountInformationService accountInformationService;

    @Resource(name = "billingSystemsAbilityService")
    private BillingSystemsAbilityService billingSystemsAbilityService;

    @Override
    public void execute(ShardingContext shardingContext) {
        logger.info(String.format("Item: %s | Time: %s | Thread: %s | %s",
                shardingContext.getShardingItem(), new SimpleDateFormat("HH:mm:ss").format(new Date()), Thread.currentThread().getId(), "SIMPLE"));
        int operatosId = CastUtil.castInt(shardingContext.getShardingParameter());
        logger.info("数据中心【" + operatosId + "】Ftp 准实时帐本同步接口 处理");
        //String pathName_1 = "D:\\accountInformation.txt";
        String[] fileArray = billingSystemsAbilityService.getFileNameList(2, operatosId);
        logger.info("数据中心【" + operatosId + "】准实时读取的文件列表长度"+fileArray.length+"文件名【" + StringUtil.joinString(fileArray, ',') + "】");
        if (fileArray == null || fileArray.length == 0) {
            return;
        }
        for (int i = 0, LEN = fileArray.length; i < LEN; i++) {
            String pathName = fileArray[i];
            logger.info("数据中心【" + operatosId + "】 Ftp获取到的文件【" + pathName + "】开始处理");
            List<Map<String, String>> mapList = billingSystemsAbilityService.downloadLaoGoodsBalance(pathName, operatosId);
            //后期发送到Mq
            logger.info("数据中心【" + operatosId + "】文件内容【" + mapList + "】");

            for (Map<String, String> map : mapList) {
                String useTotal = map.get("USETOTAL");
                String balanceId = map.get("BALANCEID");
                long balance = CastUtil.castLong(balanceId);
                boolean result = accountInformationService.updateBalance(balance, useTotal);
                logger.info("账本【" + balanceId + "】流量实时更新结果【" + result + "】");
                accountInformationService.accountInformationSync(map);
            }

        }

    }
}
启动调用dubbo服务，dubbo服务全部停止工作
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题。为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭。
