### ISSUE TITLE
咨询下 支持spring注解的形式么  类似于：    @Scheduled(cron = "0 0/1 *  * * * ")

### ISSUE THREAD

**Issue by zhuangjiaju** [apache/shardingsphere-elasticjob#482]
咨询下 支持spring注解的形式么  类似于：    @Scheduled(cron = "0 0/1 *  * * * ")
注解就可以自己运行了
我找了好久没找到

**Comment by terrymanu** [comment]
目前应该不支持，ej不是围绕spring的产品，自己比较独立
