### ISSUE TITLE
docker 部署两台机器，由于获取到docker中ip一样！怎么获取宿主机ip，或者任务的执行是根据ip来分配的吗？

### ISSUE THREAD

**Issue by weixuedian** [apache/shardingsphere-elasticjob#483]
docker 部署两台机器，由于获取到docker中ip一样！怎么获取宿主机ip，es-job 分片执行的时候两台获取的到ip是一样的，会影响执行吗？

**Comment by terrymanu** [comment]
这是docker使用host模式导致的吧

**Comment by zhengqz** [comment]
如果不使用host模式，docker 里服务启动注册的IP是docker IP。这个怎么解决？
