### ISSUE TITLE
elastic-job  执行shutdown 方法后，该job 到时间点还会执行

### ISSUE THREAD

**Issue by liangpeichang** [apache/shardingsphere-elasticjob#488]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.0
### Expected behavior （您预期的结果是）
1、通过api执行shutdown 方法，期望还没有到执行时间的job 关闭掉，到了时间不再执行
2、请问下api shutdown 方法和remove 方法有什么区别，执行remove 方法和web 监控页面为啥不一样，
web监控页面执行remove后zookeeper节点进行了物理删除，而api 执行remove 方法 只是状态变成crashed，而没有进行物理删除节点

### Actual behavior （实际运行的结果是）
有时通过shutdown方法，web 监控页面显示分片待调整，有时显示已经失效
### Steps to reproduce the behavior （可重现问题的操作步骤）
1、双机集群环境，分片数量设置的为1
2、设置一个到点执行的cron 定时任务，再还未到执行时间点进行job shutdown  方法，发现到了时间点后改job 还会执行
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
@Override
	public ExecuteResult<Object> shutdownJob(String jobName) {
		Log.info(log, "\n 方法:[{}],入参[{}]", "ActivityJobServiceImpl-shutdownJob",jobName);
		ExecuteResult<Object> result = new ExecuteResult<Object>();
		try {
			if(jobName == null ){
				result.addErrorMessage("参数不可为null");
				return result;
			}
			jobOperateAPI.shutdown(Optional.of(jobName), serverIp);
			JobSettings jobSettings = jobSettingsAPI.getJobSettings(jobName);
			JobParametersDTO jobParametersDTO = JSONUtils.parseObject(jobSettings.getJobParameter(), JobParametersDTO.class);
			//关闭job
			jobParametersDTO.setFinishedStatus(1);
			jobSettings.setJobParameter(JSONUtils.toJSONString(jobParametersDTO));
			jobSettingsAPI.updateJobSettings(jobSettings);
		} catch (Exception e) {
			result.addErrorMessage(e.getMessage());
			Log.error(log,e,"\n 方法:[{}]，异常:[{}]", "ActivityJobServiceImpl-shutdownJob", e.getMessage());
			throw e;
		}
		return result;
	}

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by baiyunpeng1991** [comment]
你观察下shutdown时候是不是disabled的没有被写入

**Comment by terrymanu** [comment]
Closed because of no response anymore
