### ISSUE TITLE
如何知道定时器不走的原因

### ISSUE THREAD

**Issue by liujingjing5** [apache/shardingsphere-elasticjob#489]
### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
如何知道定时器不走的原因
### Actual behavior （实际运行的结果是）
定时器运行良好，有时突然就不走了
### Steps to reproduce the behavior （可重现问题的操作步骤）
不好重现  
### 描述  
和这图一样，突然到这就没了。
![qq](http://jjliu-oss-test.oss-cn-shanghai.aliyuncs.com/QQ%E5%9B%BE%E7%89%8720180308160231.png?Expires=1520561065&OSSAccessKeyId=TMP.AQGJO698PU52nwMhwVp0nRL1xsAwbCUofo8td9_AUxiV74nidjelqSwIkd_zAAAwLAIULdPiBCQiw_XCxWP3CFsdnrOFpWwCFGistqnWY2WPEoTH3b7XQDlrMT5n&Signature=Q5MLZs%2FriaPB0JFfNGGiR6fHC80%3D)
服务器看起来是连着的
![qq2](http://jjliu-oss-test.oss-cn-shanghai.aliyuncs.com/QQ%E6%88%AA%E5%9B%BE20180308160952.png?Expires=1520561432&OSSAccessKeyId=TMP.AQGJO698PU52nwMhwVp0nRL1xsAwbCUofo8td9_AUxiV74nidjelqSwIkd_zAAAwLAIULdPiBCQiw_XCxWP3CFsdnrOFpWwCFGistqnWY2WPEoTH3b7XQDlrMT5n&Signature=IQ6KgrpDWRQ%2BWHoGrdrc8ZhiG00%3D)

**Comment by terrymanu** [comment]
为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭
