### ISSUE TITLE
任务重复执行的问题

### ISSUE THREAD

**Issue by changjiang2016** [apache/shardingsphere-elasticjob#491]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为）
       2.1.5
### Expected behavior （您预期的结果是：）
       任务不能重复执行
### Actual behavior （实际运行的结果是）
       在一台机器上出现了重复执行的情况
### Steps to reproduce the behavior （可重现问题的操作步骤）
       1.搭建两台job节点A和B，分片为6片（两台各自分3片）
       2.启动程序后，一台job机器B的根目录/磁盘满，表现job服务与zk连接不稳定（只能与zk集群中一个节点能连接上，且连接更换到另外的zk节点，原则上与zk集群所有节点都应连接，但事实上始终只有一个连接，zk集群能保证没有问题）
       3.Elastic Job Lite console节点上显示instance节点只有一个A，另外一个B被剔除了，查看任务，所有任务都分配给了A
       4.但从日志和数据结果来看B始终没有死掉，B继续定时执行任务
       5.将B的根目录删除一些文件，腾出空间，B任务恢复，得到分片
    问题就是进行到第4步时，为什么B会继续执行任务，B到下一个时刻不是得去zk获取状态吗？Arunning的情况下，不应该执行啊？

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
基本和elastic-job-example一致
1.业务代码（业务代码内容已屏蔽）
public class xxxJob  implements SimpleJob{
private MessageDao messageDao;
@Override
    public void execute(ShardingContext shardingContext) {
        logger.info(String.format("Item: %s | Time: %s | Thread: %s | %s",
                shardingContext.getShardingItem(), new SimpleDateFormat("HH:mm:ss").format(new Date()), Thread.currentThread().getId(), "SIMPLE"));
        long curren = System.currentTimeMillis();
       
        List messageList= messageDao.getByDate(date,shardingContext.getShardingTotalCount(),shardingContext.getShardingItem());
        if(messageList!=null &&messageList.size()>0){
            List<Future<Integer>> futureList = new ArrayList<Future<Integer>>();
            callThreads(messageList,futureList);
            getResult(futureList);
        }
    }
   private void callThreads(List messageList, List<Future<Integer>> futureList) {
   //多线程处理逻辑
  }
}
2. quazrt.xml
<reg:zookeeper id="regCenter" server-lists="${zookeeper.connection}" namespace="xxx/xxx-job"
                   base-sleep-time-milliseconds="1000" max-sleep-time-milliseconds="3000" max-retries="3" />
    <bean id="xxxJobbean" class="xxxx.xxxx.xxxx.xxxJob">
        <property name="messageDao" ref="messageDao"/>
    </bean>
    
    <job:simple id="xxxJob"  job-ref="xxxxJobbean"  registry-center-ref="regCenter"
                sharding-total-count="6" cron="0 0/10 * * * ?" overwrite="true" >
        <job:distributed-listener class="xxxx.xxx.xxxx.listerner.DistributeOnceElasticJobListener"
                                  started-timeout-milliseconds="1000" completed-timeout-milliseconds="120000"/>

    </job:simple>

3.listener
public class DistributeOnceElasticJobListener extends AbstractDistributeOnceElasticJobListener {

	private static final Logger logger = LoggerFactory.getLogger(DistributeOnceElasticJobListener.class);

    /**
	 * @param startedTimeoutMilliseconds
	 * @param completedTimeoutMilliseconds
	 */
	public DistributeOnceElasticJobListener(long startedTimeoutMilliseconds, long completedTimeoutMilliseconds) {
		super(startedTimeoutMilliseconds, completedTimeoutMilliseconds);
	}

	@Override
	public void doBeforeJobExecutedAtLastStarted(ShardingContexts shardingContexts) {
		logger.info("comment分布式监听器开始……");
	}

	@Override
	public void doAfterJobExecutedAtLastCompleted(ShardingContexts shardingContexts) {
		logger.info("comment分布式监听器结束……");
	}

}

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Did you open `monitorExecution`?

**Comment by terrymanu** [comment]
Closed because of no response anymore
