### ISSUE TITLE
执行日志持久化可以关闭不？

### ISSUE THREAD

**Issue by yeyincai** [apache/shardingsphere-elasticjob#492]
查看执行AbstractElasticJobExecutor 类的 execute)()方法，我们发现如果要保存事件的话，先要判断是否isAllowSendJobEvent
 if (shardingContexts.isAllowSendJobEvent()) {
            jobFacade.postJobStatusTraceEvent(shardingContexts.getTaskId(), State.TASK_STAGING, String.format("Job '%s' execute begin.", jobName));
 }

也就是说  shardingContexts里面有设置isAllowSendJobEvent，但是没有找到去哪里设置，或者怎么设置，请求解？

**Comment by terrymanu** [comment]
If you don't configure event trace data source, elastic-job will not save your event log.
