### ISSUE TITLE
支持有序任务么？

### ISSUE THREAD

**Issue by YangShuqing** [apache/shardingsphere-elasticjob#501]
我们现在有个需求是进行批量任务处理，任务可以分成多个任务队列，但是每个队列中的任务都是有序的，必须处理完第一个后，才能进行下一个。在文档中，没有找到类似的处理案例，不知道 elastic-job能否满足？

**Comment by zhanglc23** [comment]
我也再找这方面的信息好像不支持啊

**Comment by terrymanu** [comment]
Unsupport for now
