### ISSUE TITLE
使用exec比较好~

### ISSUE THREAD

**Issue by gMan1990** [apache/shardingsphere-elasticjob#503]
https://github.com/elasticjob/elastic-job-lite/blob/b022898ef1b8c984e17efb2a422ee45f6b13e46e/elastic-job-lite-console/src/main/resources/bin/start.sh#L34

```
exec java -classpath ${LIB_DIR}:. ${CONSOLE_MAIN} $port
```

**Comment by terrymanu** [comment]
please provide a pull request

**Comment by jiang2015** [comment]
please assigned to me,thanks
