### ISSUE TITLE
服务在重启的时候,不应该执行的job执行了

### ISSUE THREAD

**Issue by newajax-1** [apache/shardingsphere-elasticjob#504]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.4
### Expected behavior （您预期的结果是）
生产环境有两个job分别在每天 23:55(jobA) 和 00:05(jobB)  执行
### Actual behavior （实际运行的结果是）
服务在17:00的时候重启了,部署的是3个节点，jobA和JobB几乎在同一时间(相差毫秒),17:08的时候执行了
### Steps to reproduce the behavior （可重现问题的操作步骤）
在本地启动没有发现该问题,生产服务器时间也查过是对的
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
How to reproduce it? Any hint of the issue?

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue.
If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
