### ISSUE TITLE
dataflow由于处理时间太长，导致无法进行下一次调度任务

### ISSUE THREAD

**Issue by ArvinC** [apache/shardingsphere-elasticjob#506]
使用2.1.5版本，使用的是dataflowJob

我的调度任务每6秒回触发一次
但是有时处理完成后超过30秒。导致后面的调度任务无法正常启动。

**Comment by terrymanu** [comment]
Only one job instance can run in the same time, so the behaviour is correct.
It is better to shard more items and assign more server to handle the job.
