### ISSUE TITLE
失效后任务在同一时间2个节点上都在运行，导致数据处理重复。

### ISSUE THREAD

**Issue by yuexianbing** [apache/shardingsphere-elasticjob#507]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.2
### Expected behavior （您预期的结果是）
一个分片前提下，节点失效时，失效节点运行的任务线程被中断，重新选举后任务在另一个被选举的主节点运行。
### Actual behavior （实际运行的结果是）
失效节点运行的并未中断，在设置1个分片的前提下，2个节点任务同时运行，重复处理一批数据。
### Steps to reproduce the behavior （可重现问题的操作步骤）
现象是任务运行的过程中，主节点zk断连，并不是宕机，应该可以看到两个节点同时运行该任务。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

请问下，我看到官网的配置文档结束，失效选举的过程中，主节点操作会被阻塞，如果是像我上述的情况，任务运行过程中，主节点与zk断连，zk从新选举e-job的从节点为主节点，任务重新执行，而主节点运行的同一个任务并未中断，导致两个节点同一个任务，同一时间都在运行，数据处理重复，这是正常的设计吗？这个地方除了做数据幂等，e-job的组件能不能避免这种问题呢？

**Comment by yuexianbing** [comment]
如果要重现，可以设置两个节点，再主节点的任务运行的时候，断掉主节点与zk的会话链接，看下实际执行。

**Comment by baiyunpeng1991** [comment]
我试了，没有这个问题

**Comment by yuexianbing** [comment]
@baiyunpeng1991 那估计是你没模拟到场景吧。 出现这个问题后，我看了zk的节点数据，zk中显示我们的一个节点不可用(这个节点正常运行,只是与zk断连，节点的应用正常运行)，另一个备节点被选为主节点，也开始执行任务，导致两个任务同时运行，而因为我们这个任务没做数据的唯一约束，两个节点在分片数为1的情况下同时执行，重复创建了 400多张退货单。

**Comment by terrymanu** [comment]
Did you open configuration item of `monitorExecution`?

**Comment by terrymanu** [comment]
Closed because of no response anymore
