### ISSUE TITLE
docker容器部署es-job，使用的是bridge模式，导致获取的ip地址是docker容器的ip

### ISSUE THREAD

**Issue by butioy** [apache/shardingsphere-elasticjob#508]
![docker-ip](https://user-images.githubusercontent.com/3390055/38865873-bd3cfb58-4271-11e8-8359-88cb9725f390.png)
这里面的都是docker的ip，不是宿主机的ip

**Comment by weixuedian** [comment]
遇到同样的问题！

**Comment by ryuhi** [comment]
@butioy 可以通过容器指定ip的方式改成宿主机的ip，另外dubbo新版也可以在配置文件中指定服务节点的ip，但是只能是固定值

**Comment by zhengqz** [comment]
@ryuhi  怎么操作docker ip改为宿主机IP(不要--net=host方式)
我最近也在使用docker 启动服务，启动注册到zookeeper上是docker的ip。
我使用 docker hostname指向宿主机IP，但是不行。。

**Comment by zhengqz** [comment]
```bash
# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	agent agent
192.168.1.120    server

# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.4  netmask 255.255.0.0  broadcast 172.17.255.255
```
![image](https://user-images.githubusercontent.com/12173151/54732799-ba286100-4bd0-11e9-90f4-30d8930456ca.png)

**Comment by zhyErick** [comment]
阿里云k8s flanel网络，用了hostnetwork=true，但获取到的不是宿主机真实ip，是宿主机docker0的ip

**Comment by henryjun0** [comment]
我的docker集群会指向一个虚拟ip，导致ip只有一个，不知道怎么解决，hostname指向也不行

**Comment by terrymanu** [comment]
Ref #1039

**Comment by terrymanu** [comment]
duplicate with #1039
