### ISSUE TITLE
线程随着任务的增加而增加

### ISSUE THREAD

**Issue by fuyanzhang** [apache/shardingsphere-elasticjob#510]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
使用的是2.1.5的版本
### Expected behavior （您预期的结果是）
jvm里的线程数不会随着任务的增加而增加
### Actual behavior （实际运行的结果是）
创建7000个任务时，发现线程数达到2w+
从代码中可以看到，每个任务会有一个quartz的调度器，即一个调度线程，同时会启一个工作线程。这样，7000任务就会有1.4w的线程。同时，每个任务又有一个zk的tree cache线程。如果任务量大的话，就灾难了
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
```
public class TestMain {
    public static void main(String[] args) {
        ApplicationContext context =  new ClassPathXmlApplicationContext("META-INF/ApplicationContext.xml");
        setUpSimpleJob((CoordinatorRegistryCenter) context.getBean("regCenter"));

    }


    private static void setUpSimpleJob(final CoordinatorRegistryCenter regCenter) {
        for (int i =0;i<7000;i++) {
            JobCoreConfiguration coreConfig = JobCoreConfiguration.newBuilder("javaSimpleJob"+i, "0 0 10 * * ?", 3).shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou").build();
            SimpleJobConfiguration simpleJobConfig = new SimpleJobConfiguration(coreConfig, MyElasticJob.class.getCanonicalName());
            new JobScheduler(regCenter, LiteJobConfiguration.newBuilder(simpleJobConfig).build()).init();
        }
    }

}
```
Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by baiyunpeng1991** [comment]
设计上明显是不支持太多job的，为了每个job到时间必须执行，及加上zk监听，一个job最少会开启4个线程；可以优化那个4个线程里，任务状态同步可以优化掉，剩余的3个基本线程按这个设计是没办法改的，只能根据公司的需求，进行符合业务的源码重构

**Comment by terrymanu** [comment]
Duplicated with #702

**Comment by terrymanu** [comment]
For huge jobs, please use ElasticJob cloud
