### ISSUE TITLE
FailOverService ShardingService.

### ISSUE THREAD

**Issue by Ah39** [apache/shardingsphere-elasticjob#511]
A B C 三个机器，一个分片，A机器是选举出来的master
A机器执行任务，A机器挂掉了。
同时开启了fail over，然后B,C 都开始执行Fail Over，等待被选举为master。
则B，C只有一个节点能成为master，则另外一台会永久在等executeInLeader 上等待。

如果是A机器假死之类的，连接断开又连上，这种情况具体是咋样的？？

https://github.com/elasticjob/elastic-job-lite/issues/111
这里还有一个之前的issure，主节点丢失，任务卡住的。
我现在2.0.5 版本，遇到超过5次任务卡住了。
下面这两个方法都能被block住

FailoverService.failoverIfNecessary()
ShardingService.shardingIfNecessary()

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
