### ISSUE TITLE
修改服务器时间重启定时任务 偶尔会连续执行多次

### ISSUE THREAD

**Issue by zhaovincent** [apache/shardingsphere-elasticjob#513]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.4
### Expected behavior （您预期的结果是）
每次执行一次定时任务

### Actual behavior （实际运行的结果是）
每个定时任务执行两次

### Steps to reproduce the behavior （可重现问题的操作步骤）
修改服务器时间到未来一天，比如2018-07-06 重启定时任务执行

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
`  
 <reg:zookeeper id="jobCenter" server-lists="${zookeeper.simple.url}"
                   namespace="qzg-scheduler-zk-${}" base-sleep-time-milliseconds="1000" session-timeout-milliseconds="1000"
                   max-sleep-time-milliseconds="3000" max-retries="3" />

<job:simple id="sendHaierEmpNotificationToPtHrForInsuranceApplicationJob" job-ref="sendHaierEmpNotificationToPtHrForInsuranceApplicationJob" overwrite="true"
                registry-center-ref="jobCenter" cron="${send.haier.emp.notification.to.pthr.for.insurance.application.cron}"
                sharding-total-count="1" failover="true" monitor-execution="true"
    />

`
`@Component("sendHaierEmpNotificationToPtHrForInsuranceApplicationJob")
public class SendHaierEmpNotificationToPtHrForInsuranceApplicationJob implements SimpleJob {
    private static final Logger logger = Logger.getLogger("RECORD");
    private static final Logger l = Logger.getLogger(SendHaierEmpNotificationToPtHrForInsuranceApplicationJob.class);

    @Autowired
    private com.qzg.insurance2b.soaservice.IJobSOAService jobSOAService;

    @Override
    public void execute(ShardingContext context) {
        ResultVO resultVO = jobSOAService.sendHaierEmpNotificationToPtHrForInsuranceApplication(null);
        logger.info("sendHaierEmpNotificationToPtHrForInsuranceApplication=" + JSON.toJSONString(resultVO));
    }
}`

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by newajax-1** [comment]
我也遇到了,我没有修改服务器时间，我是重启的服务的时候发现有任务在不正确的时间点执行了,我感觉应该是job配置失效转移机制,而在重启的时候触发了失效转移机制.具体还要看源码。

**Comment by baiyunpeng1991** [comment]
这是failover的原因

**Comment by abao301** [comment]
我也遇见了，莫名其妙 执行了多次 定时时间还没到，就执行了

**Comment by terrymanu** [comment]
If using failover, job will execute after some job crashed
