### ISSUE TITLE
job启动完成后,控制台一直显示分片待调整

### ISSUE THREAD

**Issue by newajax-1** [apache/shardingsphere-elasticjob#514]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.4 
zk服务版本是3.4.6，和demo中zk版本一致
### Expected behavior （您预期的结果是）
对于每天执行一次的任务,比如每天0点执行，在服务启动完成后,可以手动通过job控制台按钮触发一次
### Actual behavior （实际运行的结果是）
job控制台一直显示分片待调整,没有触发job的按钮
### Steps to reproduce the behavior （可重现问题的操作步骤）
设置一个job比如每天0点执行，启动job，打开job控制台
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by a420355244** [comment]
这个问题还没有解决，有维护的大大在看吗？

**Comment by liubaochuan** [comment]
遇到同样的问题,计划任务跑着跑着就发现分片的instance和leader的instance不一致，后面就一直无法执行计划任务了，重启都不行，断点看请求leader进入了无线循环。

**Comment by Leonidasz** [comment]
The author divided the job into several states on the console. The first state of the job was "Sharding flag",  the job scheduler had not been triggered at that time, so there is no sharding. When the job scheduler was triggered, sharding was completed, and the state at this time would become "OK".The "trigger" button was originally designed to be displayed only in the "OK" state. This will be adjusted in the future releases. Please pay attention to the community.
作者在console上对job划分了几种状态，作业最初的状态就是“分片待调整”，因为此时作业调度还未触发，所以分片分配还未进行，当作业调度触发后，分片分配完成，此时的状态就会变为“正常”。只是最初设计时“触发”功能按钮仅在“正常”状态下才会展示。后续新发版的时候，这块内容会进行调整，请关注社区变化。

@liubaochuan 
If there are any other issues that need to be discussed, please open a new issue and describe details. Thank you.
如果有其他的问题需要讨论，烦请再新开一个issue，然后详细描述下相关内容，谢谢。

**Comment by qq4628241** [comment]
现象如果job配置很多,部分job状态显示分片待调整,部分可用.对于job状态显示为分片待调整的,手动去改下运行时间,等一会就可以使用了
