### ISSUE TITLE
 Elastic-Job 可以支持多少个job? 10万个job，每一分钟执行一次能行么？

### ISSUE THREAD

**Issue by shenjianhua1985** [apache/shardingsphere-elasticjob#516]
Elastic-Job 可以支持多少个job? 10万个job，每一分钟执行一次能行么？

**Comment by wanglianghust** [comment]
每开一个job，都会起线程。我测试过，开了300个job，每个5秒执行一次，机器线程数达到4000多，不一会就电脑down机了。

**Comment by yanmaipian** [comment]
可以使用mesos 来做集群
