### ISSUE TITLE
disabled job后,服务重启job状态又变成可用生效状态

### ISSUE THREAD

**Issue by lkpAgent** [apache/shardingsphere-elasticjob#518]
如题.
job的状态是保存在zk的servers/ip路径下,通过控制台使job失效后,该值为DISABLED.
而通过JobScheduler(..).init()后,它读取的是config里配置的disabled属性.  显然通过控制台的操作并没有改变config里面的配置.

**Comment by terrymanu** [comment]
Duplicated with #589
