### ISSUE TITLE
job的AbstractDataFlowElasticJob的调度类如果集成aop的话，会无法调度

### ISSUE THREAD

**Issue by deanjin** [apache/shardingsphere-elasticjob#519]
问题重现：
<img width="616" alt="default" src="https://user-images.githubusercontent.com/13944043/39746750-e39a2dbc-52dd-11e8-8e20-4c350e0f843c.png">
在SmsTaskJob类中注入切面，这样fetchData就不会被调用

问题原因：
<img width="708" alt="default" src="https://user-images.githubusercontent.com/13944043/39746802-0a842752-52de-11e8-811a-72319de2e574.png">
<img width="958" alt="default" src="https://user-images.githubusercontent.com/13944043/39746830-22cefa4e-52de-11e8-8fb3-fb2bcd0117ff.png">

代理类直接被当做调度类来用了，在执行executejob时候，会判断dataflowtype在调用方法，因为代理类的dataflowtype为空，所有就不会调用方法了。

**Comment by terrymanu** [comment]
Did it fix by #1106?

**Comment by nmyphp** [comment]
I'll follow up on that.

**Comment by nmyphp** [comment]
你好，问题描述中的AbstractDataFlowElasticJob和AbstractBatchSequenceDataFlowElasticJob类都不再es-job的源码中，应该是贵司自己包装的，所以我这边没法复现你的问题。
@deanjin
