### ISSUE TITLE
未执行完成的job，运维平台上状态标识为【失败】

### ISSUE THREAD

**Issue by WeiShengPan** [apache/shardingsphere-elasticjob#520]
问题如下：
job未执行完成时，先插入了一条缺失完成时间和失败原因的记录，运维平台界面上显示为失败状态；是否考虑将该状态的job记录展示为【执行中】或其他状态，避免对不熟悉实现的运维人员出现误导。

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
运维平台界面展示状态为【执行中】或其他状态。
### Actual behavior （实际运行的结果是）
运维平台界面展示状态为【失败】或其他状态。
### Steps to reproduce the behavior （可重现问题的操作步骤）
一个执行时间较长的job，在job刚开始执行时，可在运维平台上看到一条缺失完成时间和失败原因的记录，且执行结果为失败。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by JohnVX** [comment]
支持一下。

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
