### ISSUE TITLE
希望能在设置job的状态为“等待分片”时也可以触发功能

### ISSUE THREAD

**Issue by 834449164** [apache/shardingsphere-elasticjob#521]
版本号:2.1.4

希望能在设置job的状态为“等待分片”时也可以触发功能。

现在如果设置一个job后status为"sharding flag",是没有直接Trigger(触发)的绿色按钮
需要先把crontab时间设置为接下来的时间"* * * * * ?"来先触发一次后，status才变为OK，这是才有Trigger按钮。

希望在status为"sharding flag"时也可以触发（操作栏中出现绿色触发按钮），这样就不用去修改crontab时间触发一次后再把crontab时间调回来。

个人觉得这个功能可以简化一些操作使系统更加易用，若有什么错误之处还望指正。

**Comment by newajax-1** [comment]
赞同!

**Comment by gMan1990** [comment]
支持该功能~~~（直接发http请求可以绕过么？
```javascript
function bindTriggerButton() {
    $(document).off("click", "button[operation='trigger-job'][data-toggle!='modal']");
    $(document).on("click", "button[operation='trigger-job'][data-toggle!='modal']", function(event) {
        var jobName = $(event.currentTarget).attr("job-name");
        $.ajax({
            url: "/api/jobs/" + jobName + "/trigger",
            type: "POST",
            success: function() {
                showSuccessDialog();
                $("#jobs-status-overview-tbl").bootstrapTable("refresh");
            }
        });
    });
}
```

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
