### ISSUE TITLE
开启failover功能后,服务在重启的时候,任务会执行

### ISSUE THREAD

**Issue by newajax-1** [apache/shardingsphere-elasticjob#522]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.4
### Expected behavior （您预期的结果是）
真正在运行时的job,failover才起作用
### Actual behavior （实际运行的结果是）
所有开启了failover功能的job在服务重启的时候都会执行
### Steps to reproduce the behavior （可重现问题的操作步骤）
1、开启一个每天14:00:00点执行一次的job,并部署在2个节点上(A、B)
2、等待job自动执行一次,查看job是在哪个节点上执行的(例如是A)
3、停掉A节点(此时时间是14:05)
4、B节点执行了job
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

我认为是这里判断有点问题
**class JobCrashedJobListener extends AbstractJobListener {
        @Override
        protected void dataChanged(final String path, final Type eventType, final String data) {
            if (isFailoverEnabled() && Type.NODE_REMOVED == eventType && instanceNode.isInstancePath(path)) {
                String jobInstanceId = path.substring(instanceNode.getInstanceFullPath().length() + 1);
                if (jobInstanceId.equals(JobRegistry.getInstance().getJobInstance(jobName).getJobInstanceId())){
                    return;
                }
                List<Integer> failoverItems = failoverService.getFailoverItems(jobInstanceId);
                if (!failoverItems.isEmpty()) {
                    for (int each : failoverItems) {
                        failoverService.setCrashedFailoverFlag(each);
                        failoverService.failoverIfNecessary();
                    }
                } else {
                    for (int each : shardingService.getShardingItems(jobInstanceId)) {
                        failoverService.setCrashedFailoverFlag(each);
                        failoverService.failoverIfNecessary();
                    }
                }
            }
        }
    }**

   我认为应该再加一个判断
 if(!JobRegistry.getInstance().isJobRunning(jobName)){
                    return;
 }
failover功能只有在job执行的过程中出现job失效情况下有效！

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by huuusome** [comment]
您好，有个问题跟您交流一下，我在开启失效转移后，模拟系统宕机，没能实现失效转移，研究源码后，发现源码中有个问题，如下。
失效转移是从JobCrashedJobListener 这个监听器开始的。
`class JobCrashedJobListener extends AbstractJobListener {
    @Override
    protected void dataChanged(final String path, final Type eventType, final String data) {
        if (isFailoverEnabled() && Type.NODE_REMOVED == eventType && instanceNode.isInstancePath(path)) {
            String jobInstanceId = path.substring(instanceNode.getInstanceFullPath().length() + 1);
            if (jobInstanceId.equals(JobRegistry.getInstance().getJobInstance(jobName).getJobInstanceId())) {
                return;
            }
            List<Integer> failoverItems = failoverService.getFailoverItems(jobInstanceId);
            if (!failoverItems.isEmpty()) {
                for (int each : failoverItems) {
                    failoverService.setCrashedFailoverFlag(each);
                    failoverService.failoverIfNecessary();
                }
            } else {
                for (int each : shardingService.getShardingItems(jobInstanceId)) {
                    failoverService.setCrashedFailoverFlag(each);
                    failoverService.failoverIfNecessary();
                }
            }
        }
    }
}`

当zookeeper上有服务器节点被Removed时，触发监听，查询该服务器被分配的任务项
`public List<Integer> getShardingItems(final String jobInstanceId) { JobInstance jobInstance = new JobInstance(jobInstanceId); if (!serverService.isAvailableServer(jobInstance.getIp())) { return Collections.emptyList(); } List<Integer> result = new LinkedList<>(); int shardingTotalCount = configService.load(true).getTypeConfig().getCoreConfig().getShardingTotalCount(); for (int i = 0; i < shardingTotalCount; i++) { if (jobInstance.getJobInstanceId().equals(jobNodeStorage.getJobNodeData(ShardingNode.getInstanceNode(i)))) { result.add(i); } } return result; }`
在查询宕机服务器分配的任务项时，先判断该服务器是否可用，如果可用，才继续查询
`public boolean isAvailableServer(final String ip) {
return isEnableServer(ip) && hasOnlineInstances(ip);
}

private boolean hasOnlineInstances(final String ip) {
    for (String each : jobNodeStorage.getJobNodeChildrenKeys(InstanceNode.ROOT)) {
        if (each.startsWith(ip)) {
            return true;
        }
    }
    return false;
}`

判断服务器节点是否可用的方法如上，如果服务器节点存在，认为可用，这与上面失效转移监听被触发的条件（服务器节点被removed）相矛盾。

这个问题我已经提交了issue，issue号为523，如果对这个问题有了解，请回复

**Comment by huuusome** [comment]
赞同

**Comment by wangjianwen** [comment]
@newajax-1 我也发现类似问题，目前已在[fix_issue_522/529](https://github.com/wangjianwen/elastic-job-lite/tree/fix_issue_522/529)修复，以供参考。
@huuusome , 我之前忘了看isssue了，跟了很长时间，我也提出了类似的修改方案。

**Comment by wangjianwen** [comment]
@huuusome , 我之前忘了看isssue了，跟了很长时间，提出了与你类似的修改方案。

**Comment by wangjianwen** [comment]
@newajax-1 我也发现类似问题，已提交已提交[pull request](https://github.com/elasticjob/elastic-job-lite/pull/547)，等待审核和合并

**Comment by wangjianwen** [comment]
@huuusome 之前大概看了下elastic-job的更新时间，发现很久没更新了，就没有关注issue。最后，自己debug了很长时间，才找到与你类似[解决方案](https://github.com/wangjianwen/elastic-job-lite/tree/fix_issue_522/529)。要是早点看到你的回答，可以减少不少时间。

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
