### ISSUE TITLE
有服务器节点挂掉，没有实现失效转移，从源码看应该是bug

### ISSUE THREAD

**Issue by huuusome** [apache/shardingsphere-elasticjob#523]
试了各种办法模拟失效转移都不成功，仔细研究了源码，发现源码中有个小bug。
`class JobCrashedJobListener extends AbstractJobListener {
        
        @Override
        protected void dataChanged(final String path, final Type eventType, final String data) {
            if (isFailoverEnabled() && Type.NODE_REMOVED == eventType && instanceNode.isInstancePath(path)) {
                String jobInstanceId = path.substring(instanceNode.getInstanceFullPath().length() + 1);
                if (jobInstanceId.equals(JobRegistry.getInstance().getJobInstance(jobName).getJobInstanceId())) {
                    return;
                }
                List<Integer> failoverItems = failoverService.getFailoverItems(jobInstanceId);
                if (!failoverItems.isEmpty()) {
                    for (int each : failoverItems) {
                        failoverService.setCrashedFailoverFlag(each);
                        failoverService.failoverIfNecessary();
                    }
                } else {
                    for (int each : shardingService.getShardingItems(jobInstanceId)) {
                        failoverService.setCrashedFailoverFlag(each);
                        failoverService.failoverIfNecessary();
                    }
                }
            }
        }
    }`

失效转移是从这个监听器开始的，当zookeeper上有服务器节点被Removed时，触发监听，查询该服务器被分配的任务项
`public List<Integer> getShardingItems(final String jobInstanceId) {
        JobInstance jobInstance = new JobInstance(jobInstanceId);
        if (!serverService.isAvailableServer(jobInstance.getIp())) {
            return Collections.emptyList();
        }
        List<Integer> result = new LinkedList<>();
        int shardingTotalCount = configService.load(true).getTypeConfig().getCoreConfig().getShardingTotalCount();
        for (int i = 0; i < shardingTotalCount; i++) {
            if (jobInstance.getJobInstanceId().equals(jobNodeStorage.getJobNodeData(ShardingNode.getInstanceNode(i)))) {
                result.add(i);
            }
        }
        return result;
    }`
在查询宕机服务器分配的任务项时，先判断该服务器是否可用，如果可用，才继续查询
`public boolean isAvailableServer(final String ip) {
        return isEnableServer(ip) && hasOnlineInstances(ip);
    }
    
    private boolean hasOnlineInstances(final String ip) {
        for (String each : jobNodeStorage.getJobNodeChildrenKeys(InstanceNode.ROOT)) {
            if (each.startsWith(ip)) {
                return true;
            }
        }
        return false;
    }`
判断服务器节点是否可用的方法如上，如果服务器节点存在，认为可用，这与上面失效转移监听被触发的条件（服务器节点被removed）相矛盾

**Comment by newajax-1** [comment]
按你的分析话,即使配置了失效转移,也不会真正执行失效转移的功能,而我在测试发现,服务停止了,所有配置了失效转移的job,即使时间没到也执行了
具体看 issues 522

**Comment by huuusome** [comment]
可以看看您的配置吗？还有，您是用kill -9让服务停止的吗？

这是我的配置，请帮忙看看有什么问题吗
<job:simple id="elasticBillingQuartzJob3" class="cn.com.ctsi.csdp.billing.quartz.ElasticBillingQuartzJob3" registry-center-ref="regCenter" sharding-total-count = "10" 
    cron="0 0/5 * * * ?" overwrite="true" failover="true" misfire="true" event-trace-rdb-data-source="elasticJobLog" sharding-item-parameters="0='',1='',2='',3='',4='',5='',6='',7='',8='',9=''" />

**Comment by newajax-1** [comment]
我用的就是官网的elastic-job-example-lite-springboot测试的,我是在idea中测试。起两个Job实例，然后手动停止的。还有一个就是我没有配置misfire=true这个配置

**Comment by huuusome** [comment]
官网给的例子是10秒钟执行一次的，当停止一个job实例时，如果没有实现失效转移，就会进行重新分片，然后各实例获取新的分片开始执行。
您能确定您的Job不是重新分片，而是真的实现了失效转移？

**Comment by newajax-1** [comment]
时间我修改过，每半个小时执行有一次

**Comment by newajax-1** [comment]
我有测了下,部署在2服务器上,确实是没有执行失效转移

**Comment by huuusome** [comment]
可以把你的配置贴出来吗

**Comment by huuusome** [comment]
是不是可以说，使用Elastic-Job提供的原生的example也不能实现失效转移？

**Comment by newajax-1** [comment]
demoJob:
  cron: 0 0/30 0 * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing


@Bean(initMethod = "init")
    public JobScheduler demoJobScheduler(final DemoJob demoJob, @Value("${demoJob.cron}") final String cron, @Value("${demoJob.shardingTotalCount}") final int shardingTotalCount,
                                           @Value("${demoJob.shardingItemParameters}") final String shardingItemParameters) {
        return new SpringJobScheduler(demoJob, regCenter, getLiteJobConfiguration(demoJob.getClass(), cron, shardingTotalCount, shardingItemParameters), jobEventConfiguration);
    }
    
    private LiteJobConfiguration getLiteJobConfiguration(final Class<? extends SimpleJob> jobClass, final String cron, final int shardingTotalCount, final String shardingItemParameters) {
        return LiteJobConfiguration.newBuilder(new SimpleJobConfiguration(JobCoreConfiguration.newBuilder(
                jobClass.getName(), cron, shardingTotalCount).failover(true).shardingItemParameters(shardingItemParameters).build(), jobClass.getCanonicalName())).overwrite(true).build();
    }

**Comment by newajax-1** [comment]
之前我一直在一个服务器上启动2个job实例是可以实现失效转移的,但是部署在2个服务器上确实出现你说的情况

**Comment by newajax-1** [comment]
还有一个问题就是在JobCrashedJobListener监听器中还应该加个判断
 if(!JobRegistry.getInstance().isJobRunning(jobName)){
  return;
 }
**开启表示如果作业在一次任务执行中途宕机，允许将该次未完成的任务在另一作业节点上补偿执行**
这句话是文档上说的,所有我认为应该加上这个判断

**Comment by huuusome** [comment]
根据代码来看，同一台服务器上启动两个实例必然是可以的，
`private boolean hasOnlineInstances(final String ip) {
        for (String each : jobNodeStorage.getJobNodeChildrenKeys(InstanceNode.ROOT)) {
            if (each.startsWith(ip)) {
                return true;
            }
        }
        return false;
    }`
应为这里判断是IP地址。


进入失效转移后，在取需要转移的任务项时，应该过滤该任务项是否正在running，如果不在running，则不转移，否则就过执行了一次。

至于补偿执行，我觉得失效转移最多能做到服务停止后，正在执行的任务可以在其他服务上再触发一次，至于数据回滚什么的，得自己在任务中控制。

**Comment by penghbgit** [comment]
失效转移我的都不生效（同一台机器和不同的机器）
@Configuration
public class DataflowDemo extends ContextLoaderListener {

    @Override
    public void contextInitialized(ServletContextEvent event) {
        new JobScheduler(createRegistryCenter(), createJobConfiguration("B")).init();
    }

    @Override
    public void contextDestroyed(ServletContextEvent event) {
        super.contextDestroyed(event);
    }

    private static CoordinatorRegistryCenter createRegistryCenter() {
        //elastic-job-demo 这个为1个zk环境的下的1个namespace 可以有多个 1个namespace下有多个job
        CoordinatorRegistryCenter regCenter = new ZookeeperRegistryCenter(
                new ZookeeperConfiguration("＊＊＊＊＊:2181", "elastic-job-demo"));
        regCenter.init();
        return regCenter;
    }

    private static LiteJobConfiguration createJobConfiguration(String jobParameter) {
        // demoSimpleJob 为jobname 0/15 * * * * ?为cron表达式  2 分片数量  0=北京,1=上海 分片对应内容  jobParameter 自定义参数
        // 定义作业核心配置
        JobCoreConfiguration simpleCoreConfig = JobCoreConfiguration
                .newBuilder("demoDataflowJob", "0 */2 * * * ?", 3)
                .shardingItemParameters("0=北京,1=上海,2=广州").failover(true).misfire(true)
                .jobParameter(jobParameter).build();
        // 定义DATAFLOW类型配置
        DataflowJobConfiguration dataflowJobConfig = new DataflowJobConfiguration(simpleCoreConfig, MyDataflowJob.class.getCanonicalName(), false);
        // 定义Lite作业根配置
        return LiteJobConfiguration.newBuilder(dataflowJobConfig).build();
    }
}
这是我的代码

**Comment by BaJingcheng** [comment]
我这边也试了一下失效转移，发现在zookeeper中并没有创建sharding/{item}/failover节点，感觉是这个原因导致的失效转移不成功

**Comment by zt994451054** [comment]
看了网上的说法和源码发现失效转移是通过主动抓取和节点监听(移除事件)
1：每次定时任务执行任务,抓取leader/failover/items节点   --通过调试发现,每次执行到这就返回false,没有这个节点
2：通过JobCrashedJobListener监听节点删除事件，但是执行到isAvailableServer这个方法的时候，确实如楼上所说,实例都已经不在了,还在判断服务是否有效
至今仍未解决

**Comment by cuiqunhao** [comment]
该问题解决了吗

**Comment by leokongwq** [comment]
> 该问题解决了吗

直到今天还是没有解决。今天早晨到现在几乎一致在分析这个问题，看了楼上的分析和我扒源代码的逻辑并且做实验得出了结论：该问题需要自己解决了。 
放弃了xxl-job而使用elastic-job最大的原因就是failover能力。

**Comment by zhouzhenghu** [comment]
现在解决了嘛
