### ISSUE TITLE
SpringBoot的java配置中没有设置job-exception-handler的方法

### ISSUE THREAD

**Issue by DerekSun96** [apache/shardingsphere-elasticjob#524]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
Elastic-Job版本：2.1.5

### Expected behavior （您预期的结果是）
希望知道在Java配置中如何设置扩展异常处理类（job-exception-handler）

### Actual behavior （实际运行的结果是）
在SpringCloud微服务工程中采用yml配置，无法使用异常处理类

### Steps to reproduce the behavior （可重现问题的操作步骤）
略

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
下面是我定义的异常处理类，但似乎没法用java方式配置到任务中：

package com.dangdang.ddframe.job.example.handler;

import com.dangdang.ddframe.job.executor.handler.JobExceptionHandler;

public class CustomJobExceptionHandler implements JobExceptionHandler {
    @Override
    public void handleException(String jobName, Throwable cause) {

        // TODO 日志输出
        System.out.println(String.format("Job '%s' exception occur in job processing", jobName));

        // TODO 钉钉通知

    }
}

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by newajax-1** [comment]
可以设置的
private LiteJobConfiguration getLiteJobConfiguration(final Class<? extends SimpleJob> jobClass,
        final String cron,
        final int shardingTotalCount, final String shardingItemParameters,
        final String jobParameter, final String description) {
        return LiteJobConfiguration.newBuilder(new SimpleJobConfiguration(
            JobCoreConfiguration.newBuilder(jobClass.getName(), cron, shardingTotalCount)
                .shardingItemParameters(shardingItemParameters).jobParameter(jobParameter)
                **.jobProperties("job_exception_handler","xxxxxx")**
                .failover(true).description(description).build(),
            jobClass.getCanonicalName())).overwrite(true).build();
    }
