### ISSUE TITLE
失效转移的问题讨论

### ISSUE THREAD

**Issue by huuusome** [apache/shardingsphere-elasticjob#526]
在使用Elastic-Job的失效转移功能时，遇到问题，kill掉服务进程或者断网处理后，没有达到失效转移的目的，配置中我已经设置了failover=true。
研究源码发现，源码中进入失效转移监听器的条件是instance下有节点被removed，我kill掉服务进程，instance下有节点被删除，可以正常进入监听器，但是在监听器内部要去查询该应用服务器分配的任务项并分配给其他空闲的应用服务器，在查询被removed的instance已分配任务项时，有一个限制条件instance必须存在，这跟进入监听器的条件instance被removed相矛盾。请有了解失效转移机制的同学一块交流一下

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Expected behavior （您预期的结果是）
kill掉进程或者断网，该instance上的任务项，应该由其他空闲服务器执行

### Actual behavior （实际运行的结果是）
kill掉进程或者断网后，该instance上的任务项，并没有转移到其他服务器执行，而是等到下次任务启动时，进行了任务的重新分片，相当于被kill掉的instance上任务少执行了一次

### Steps to reproduce the behavior （可重现问题的操作步骤）
配置failover=true，任务分10片，启动三台服务器，任务开始执行后，kill掉其中一个服务器，观察被kill的服务器上的任务没有转移到其他服务器

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by sssssssq** [comment]
关于这个问题，我在测试的时候发现，开启失效转移时，一定需要一台空闲的服务器。例如3个实例分了两片。那么在实际运行的过程中，才会触发失效转移。针对正在执行作业的服务器，无法在重新分片之前来执行前一次的失效任务。
