### ISSUE TITLE
Elastic-Job开启事件追踪功能之后，MySQL占用资源一直过高，导致服务器负载特别高

### ISSUE THREAD

**Issue by pescod106** [apache/shardingsphere-elasticjob#527]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
降低MySQL的资源占用情况
### Actual behavior （实际运行的结果是）
开启事件追踪功能导致MySQL资源占用过高
### Steps to reproduce the behavior （可重现问题的操作步骤）
打开时间追踪功能
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
<job:simple id="springSimpleJob"
                class="com.xiaoche.task.simple.SpringSimpleJob"
                registry-center-ref="regCenter"
                sharding-total-count="${sharding.total.count.springSimpleJob}"
                cron="*/10 * * * * ?"
                sharding-item-parameters="0=Beijing,1=Shanghai,2=Guangzhou"
                monitor-execution="false"
                monitor-port="9890"
                failover="true"
                description="Simple作业demo"
                job-exception-handler="com.xiaoche.handler.TaskExceptionHandler4Email"
                disabled="true"
                overwrite="true"
                **event-trace-rdb-data-source="elasticJobLog**"/>
Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
please clean trace records yourself
