### ISSUE TITLE
某节点应用出现较长gc后，该节点上开启了失效转移的job被转移到其他节点，被额外重新触发

### ISSUE THREAD

**Issue by ricky1024** [apache/shardingsphere-elasticjob#529]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite  2.1.5

### Expected behavior （您预期的结果是）
非running的job不会被重新触发

### Actual behavior （实际运行的结果是）
非running的job被额外重新触发

### Steps to reproduce the behavior （可重现问题的操作步骤）
jobA，分片数1，failover=“true”, monitor-execution="true", misfire="true", cron="0 0 19 * * ?"
同时部署到a和b两个节点，19:00正常在a节点触发后（执行5s结束），19:10分a节点模拟长时间gc（gc时间大于zk的session timeout），此时该job在b节点又重新触发了一次。

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
无特殊代码，跟文档中elastic-job-example类似。场景如上。

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by wangjianwen** [comment]
@ricky1024 ,我发现类似问题，目前已在[fix_issue_522/529](https://github.com/wangjianwen/elastic-job-lite/tree/fix_issue_522/529)修复，已供参考。等待elastic-job团队合并代码

**Comment by wangjianwen** [comment]
@ricky1024  我也发现类似问题，已提交[pull request](https://github.com/elasticjob/elastic-job-lite/pull/547)，等待审核和合并

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
