### ISSUE TITLE
Stream and connection not closed

### ISSUE THREAD

**Issue by hqq2023623** [apache/shardingsphere-elasticjob#531]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
version : 2.1.6-SNAPSHOT , branch : master
### Expected behavior （您预期的结果是）
close stream and connection when operation is done 
## 1、FileInputStream not closed
WwwAuthFilter#init , line 77
A FileInputStream is open but not closed
<img width="983" alt="image" src="https://user-images.githubusercontent.com/6971152/40401805-dc93ea1e-5e7a-11e8-9698-7e9ef0ba145a.png">

## 2、database connection not closed
EventTraceDataSource#init , line 49
A connection to database is created , but dose't assign it to any object and not closed
I wonder the reason why calling  DriverManager.getConnection() here without any operation with it .  Maybe just want to verify if the configuration is right ?
<img width="1025" alt="image2" src="https://user-images.githubusercontent.com/6971152/40401822-fb1c9a76-5e7a-11e8-929a-626bc8a455f9.png">

**Maybe this is the cause of issue #527** 

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Technoboy-** [comment]
Thanks for reporting this issue.
For 1&2, we have resolved them in our latest version .  We use http digest for authentication and keep the auth info in a simple way of retaining in memory . So loading properties file and querying db have been removed . We will release v3.0 soon or later.  
BTW, ejob is restarting, welcome to join the community!
