### ISSUE TITLE
请问有没有全局配置，可以设置所有的task是否执行？

### ISSUE THREAD

**Issue by MrChanLi2013** [apache/shardingsphere-elasticjob#534]
#### 请问有没有全局配置，可以设置所有的task是否执行？
例如：`enable.allTask=true`这样就可以开启全部task。

#### spring boot版本：1.3.3.RELEASE

**Comment by terrymanu** [comment]
the version is too old, please upgrede

**Comment by terrymanu** [comment]
please do not use SNAPSHOT version
