### ISSUE TITLE
一个节点进程还在，但是不再执行任务

### ISSUE THREAD

**Issue by zdf321** [apache/shardingsphere-elasticjob#535]
## 一个节点进程还在，但是不在执行任务，有没有办法监控到这种状态，然后kill掉该节点，让其他节点执行？

Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.2
### Expected behavior （您预期的结果是）
当节点异常不再执行任务时，进程关闭
### Actual behavior （实际运行的结果是）
节点进程还在，任务不再执行
### Steps to reproduce the behavior （可重现问题的操作步骤）
线上出现过该问题，日志不在了，暂时无法重现
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
还未定位出详细原因
Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Set reconcile to diagnose and fix system interval and automatically.
