### ISSUE TITLE
任务重启时IP所对应的状态被清空

### ISSUE THREAD

**Issue by Tank-zhu** [apache/shardingsphere-elasticjob#537]
### Steps to reproduce the behavior （可重现问题的操作步骤）
- job设置overwrite 为false  不覆盖ZK配置，以ZK配置为基础
- 当在WEB界面禁用某一个任务时，ZK上会将该任务的server目录下的IP状态改为 DISABLED
- 这个时候如果重启任务服务，该任务所对应的server目录下的IP的DISABLED状态被清空

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
- 下面是源码跟踪过程
- 当任务重启时调用 init方法

![image](https://user-images.githubusercontent.com/10337065/40963102-1b0957ac-68da-11e8-9626-8bb228973562.png)

![image](https://user-images.githubusercontent.com/10337065/40963155-3b506050-68da-11e8-8f33-69bf29e2c903.png)
![image](https://user-images.githubusercontent.com/10337065/40963170-4a74ab54-68da-11e8-903d-18360742bee7.png)
![image](https://user-images.githubusercontent.com/10337065/40963208-61e09758-68da-11e8-830b-ebbfdcd1bb13.png)

- 整个过程就是直接取了config目录的参数转成了一个LiteJobConfiguration 对象，可是LiteJobConfiguration这个对象里的disable 属性却并没有值  默认就会是false

![image](https://user-images.githubusercontent.com/10337065/40963971-7d056714-68dc-11e8-8256-0b80c11ebd29.png)
### 上面这个判断为true
![image](https://user-images.githubusercontent.com/10337065/40964201-0edee214-68dd-11e8-9ee0-ec0b90c28566.png)

![image](https://user-images.githubusercontent.com/10337065/40964071-bd68c616-68dc-11e8-944f-1afceb56dff0.png)

![image](https://user-images.githubusercontent.com/10337065/40964137-e6eb51b6-68dc-11e8-96e0-6ea0e520b912.png)

### 上面这一圈走下来后，原本已经禁用了的任务又被重新开启了。

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
ElasticJob is a `runtime` distributed job coordinator.
It is for cloud native which means the ip address maybe never reuse because the node in k8s is destroy.
So the design of ElasticJob is do not persist ip info after the job shutdown.
