### ISSUE TITLE
elasticJob java main方法运行时，不能选举主节点，导致线程一直挂起，如何解决？

### ISSUE THREAD

**Issue by a1197319946** [apache/shardingsphere-elasticjob#540]
程序是没问题的， 同样的代码在 git demo 里可以执行， 自己项目里无法选取主节点

**Comment by Ah39** [comment]
mark

**Comment by a1197319946** [comment]
@Ah39 你也碰到这个问题了吗

**Comment by a1197319946** [comment]
浪费近两天时间， 终于解决， 是由于org.apache.curator jar包冲突， 自己引入的dubbo 简介引入了2.8版本的，项目中需要的是2.10版本， 造成选举主节点失败，具体报错：com.dangdang.ddframe.job.reg.exception.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /elastic-job-example-lite-java/test/leader/election/instance
