### ISSUE TITLE
同样源码,在centos7.4上打包无法注册到注册中心

### ISSUE THREAD

**Issue by roaminlove** [apache/shardingsphere-elasticjob#541]
代码使用spring boot启动, 使用注解bean形式初始化注册中心bean, 手动调用了init方法, 日志打印都有打印.

相同的源码, 相同的java和maven版本, 在windows和ubuntu版本打包, 初始化玩都会在zookeeper中看到节点注册进来, 但是在centos打包的就无法注册zookeeper中, 日志也答应到已经调用初始化方法的了, 将jar包拿回本地运行也无法注册. 因为程序整体执行没问题, 就是elastic-job无法正确注册而已, 请问有什么特殊机制麽?

**Comment by terrymanu** [comment]
I suggest you find reason by yourself. no any additional special process here.

Please try to find the reason for different environments.
