### ISSUE TITLE
docker容器部署es-job注册中心等状态化据是存放在哪里？

### ISSUE THREAD

**Issue by lklkxcxc** [apache/shardingsphere-elasticjob#542]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Actual behavior （实际运行的结果是）

docker容器部署es-job每次启动后页面数据均为空，登记注册中心这些状态化数据是存放在哪里？

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
same with don't use docker, on zookeeper
