### ISSUE TITLE
zookeeper中断连接后导致部分任务crash

### ISSUE THREAD

**Issue by hurrica** [apache/shardingsphere-elasticjob#543]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
是什么原因导致zookeeper连接中断后的任务crash，是因为没有手动开启失效转移吗？
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
When zookeeper cannot connected, all jobs will pause, after re-connected, all jobs will resume.

**Comment by hurrica** [comment]
我的意思是，当zookeeper重新连接上之后，大部分的任务能够恢复，但是有极少个别的任务会被shutdown掉，你们自己没有遇见过这种问题吗？
