### ISSUE TITLE
Elasticjob Lite v2.1.5 Console在添加事件追踪数据源是否只支持mysql数据库？

### ISSUE THREAD

**Issue by xujun738** [apache/shardingsphere-elasticjob#551]
Elasticjob Lite v2.1.5 Console在添加事件追踪数据源时，在事件追踪数据源驱动的下拉框中只有mysql的驱动，为什么没有oracler的？

**Comment by terrymanu** [comment]
yes for now. 
If you want oracle, you can dev by yourself, codes is really similar and simple.
We appreciate if you provide a pr when finished.

**Comment by purgeyao** [comment]
哈哈 自己开发
