### ISSUE TITLE
击手动触发，定时任务会执行2次

### ISSUE THREAD

**Issue by robert-li-2018** [apache/shardingsphere-elasticjob#553]
2.1.5版本，点击手动触发，定时任务会执行2次，请问需要配置什么？谢谢

**Comment by 468120308** [comment]
我也遇到了相同的问题，请问需要怎么做才能执行一次呢？

**Comment by ShouldLi** [comment]
同问，2.1.5版本，手动触发，执行两次

**Comment by xieshanggao** [comment]
同样碰到这个问题 同问

**Comment by xieshanggao** [comment]
我的问题解决了。  
描述如下
我项目组件代码.  jobScheduler.init() 后，执行 jobScheduler.getSchedulerFacade().registerStartUpInfo(true);

源码中init()内部是有调用getSchedulerFacade().registerStartUpInfo()方法

这里重复调的话就产生新的线程去监听zk 节点。导致页面点击按钮触发时候会跑多一次任务

**Comment by Ah39** [comment]
misfire 设置为false 就行。手动触发，有一次会认为是misfire 。
在2.0.5版本是这样，不知道在2.1.5版本是不是也是这样

**Comment by ShouldLi** [comment]
> misfire 设置为false 就行。手动触发，有一次会认为是misfire 。
> 在2.0.5版本是这样，不知道在2.1.5版本是不是也是这样

misfire 默认不就是false吗

**Comment by Ah39** [comment]
![image](https://user-images.githubusercontent.com/2367243/48106311-e670c000-e275-11e8-83b0-182148334d37.png)
JobCoreConfiguration.java misfire 默认为true

**Comment by Technoboy-** [comment]
Please assign to me, I will try to do it later!

**Comment by nmyphp** [comment]
Mark

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
