### ISSUE TITLE
JOB状态为disable，但控制台展示为分片待调整状态

### ISSUE THREAD

**Issue by ho000easy** [apache/shardingsphere-elasticjob#554]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Steps to reproduce the behavior （可重现问题的操作步骤）
两台服务器，服务器A/服务器B。job使用elastic job中的测试代码即可
1. 在服务器A 启动job，job的override和disable设置为true，运行一段时间
2. 停止服务器A进程，启动服务器2进程，job的override设置为true，disable设置为false，运行一段时间
3. 停止服务器B进程，启动服务器A进程，此时打开elastic job控制台，此job状态一直为分片待调整

原因分析：
1. job在zookeeper目录下存储的servers有服务器A和服务器B，判断job的状态会先判断A和B是否全部为disable，如果全为disable，则job状态为失效。此场景中服务器B虽然下线，但还是存在server中且状态为enable
2. 在job不是失效状态下回去判断instance是否包含所有shard对应的ip，上述第三步进程启动后没有可用的instance，所以一直不会做分片，分片对应的ip还是服务器B的ip，导致显示分片待调整

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
