### ISSUE TITLE
数据库连接池连接获取之后，是不是应该手动关闭，归还连接池，否则这个连接一直占用

### ISSUE THREAD

**Issue by leorian** [apache/shardingsphere-elasticjob#557]
和标题描述的一样，我看了elastic-job-lite的源码，看到rdb相关的代码的时候，看到从datasource里面拿connection操作数据之后，并没有手动关闭，归还连接池，请问一下，这个会不会导致连接一直被占用，无法释放？

**Comment by KerwinAusten** [comment]
你说的是这种代码吗
```java
try (Connection conn = dataSource.getConnection()) {
}
```
这种是JDK7引入的 try-with-resources 语法，凡是实现了AutoCloseable接口的在语句结束完毕时会自动调用close方法

**Comment by leorian** [comment]
> 你说的是这种代码吗
> 
> ```java
> try (Connection conn = dataSource.getConnection()) {
> }
> ```
> 
> 这种是JDK7引入的 try-with-resources 语法，凡是实现了AutoCloseable接口的在语句结束完毕时会自动调用close方法

哎呀呀，我孤陋寡闻了,你说的对的
