### ISSUE TITLE
单机作业，配置作业监控端口, 方便开发者dump作业信息，启动报端口被占用

### ISSUE THREAD

**Issue by ShouldLi** [apache/shardingsphere-elasticjob#558]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
正常启动
### Actual behavior （实际运行的结果是）
端口被占用
### Steps to reproduce the behavior （可重现问题的操作步骤）
本地测试，单机作业
配置了monitorPort = 9888，
但是项目启动控制台显示Monitor server 运行，端口9888，然后 job_$_NON_CLISTERED 开始启动，这个不知道是哪来的，然后Monitor server又开始运行，9888已经被前一个Monitor server 占用了，所以就报错了，但是不影响后面的job执行
![image](https://user-images.githubusercontent.com/23274915/43568968-b5de344e-9668-11e8-881b-da7365700d3b.png)

怀疑是单机作业引起的

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by KerwinAusten** [comment]
他这里每个作业都会根据monitorPort启动一个socket监听，所以如果有多个作业启动的话就妥妥的会报错。可以考虑把MonitorService的内容复制到自己的代码里启动一个socket即可

**Comment by qingquaner** [comment]
显示设置monitorPort(-1) 试试看呢

**Comment by terrymanu** [comment]
Closed because of no response anymore.
