### ISSUE TITLE
与springboot结合时，有没有类似 @Scheduler的功能

### ISSUE THREAD

**Issue by davis1214** [apache/shardingsphere-elasticjob#559]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
3.0.0

### Expected behavior （您预期的结果是）
1、通过注解方式，比如@ElasticScheduler实现和springboot中调度相似功能
2、增加除了crontab外的调度配置方式

**Comment by xjzrc** [comment]
可以自己写spring-boot-starter实现，如：https://github.com/xjzrc/elastic-job-lite-spring-boot-starter/tree/v1.1.0
v1.1.0是注解方式配置任务
v2.0.0去除了注解方式，完全采用了配置方式配置任务
