### ISSUE TITLE
无法停掉当前正在执行的任务

### ISSUE THREAD

**Issue by ShouldLi** [apache/shardingsphere-elasticjob#563]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Expected behavior （您预期的结果是）
希望可以将当前正在执行的任务立即停掉不执行

### Actual behavior （实际运行的结果是）
点击失效或终止，一个长时间运行的任务仍然在执行

### Steps to reproduce the behavior （可重现问题的操作步骤）
一个需要执行10分钟的定时任务，执行了5分钟，点击失效或终止，任务显示已经失效或下线了，但是实际任务还在执行中

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
What is `点击失效或终止`? 
In web console or other place? where is the button?

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
