### ISSUE TITLE
job 执行多次

### ISSUE THREAD

**Issue by NoSugarIce** [apache/shardingsphere-elasticjob#570]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Expected behavior （您预期的结果是）
任务按照cron 表达式正确执行
### Actual behavior （实际运行的结果是）
偶然出现多次调用
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by 1594433168** [comment]
在AbstractDistributeOnceElasticJobListener中，偶尔会2次触发doBeforeJobExecutedAtLastStarted和doAfterJobExecutedAtLastCompleted方法

**Comment by compilerduck** [comment]
楼主提供的信息过少，在何种情况下出现多次调用？elastic job基于quartz构建，cron表达式最终会被quartz解释并执行。如果是指AbstractDistributeOnceElasticJobListener的方法会被执行多次，请参考#631，确实会在特定场景下触发多次执行。先关闭此issue了，请下次一定提供详细信息，提高沟通效率
