### ISSUE TITLE
失效转移不会触发

### ISSUE THREAD

**Issue by BaJingcheng** [apache/shardingsphere-elasticjob#571]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
在kill掉服务后当前执行任务会转移到可用服务器
### Actual behavior （实际运行的结果是）
并没有实现失效转移
### Steps to reproduce the behavior （可重现问题的操作步骤）
在两台机器上部署并等待任务执行，任务开始执行后，kill掉一台服务的job进程。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
beanconfig:
`public class SimpleJobConfig {

    @Resource
    private ZookeeperRegistryCenter regCenter;

    @Resource
    private JobEventConfiguration jobEventConfiguration;

    @Bean
    public SimpleJob simpleJob() {
        return new MyTestSimpleJob();
    }

    @Bean(initMethod = "init")
    public JobScheduler simpleJobScheduler(final SimpleJob simpleJob, @Value("${simpleJob.cron}") final String cron, @Value("${simpleJob.shardingTotalCount}") final int shardingTotalCount,
                                           @Value("${simpleJob.shardingItemParameters}") final String shardingItemParameters) {
        return new SpringJobScheduler(simpleJob, regCenter, getLiteJobConfiguration(simpleJob.getClass(), cron, shardingTotalCount, shardingItemParameters), jobEventConfiguration);
    }

    private LiteJobConfiguration getLiteJobConfiguration(final Class<? extends SimpleJob> jobClass, final String cron, final int shardingTotalCount, final String shardingItemParameters) {
        return LiteJobConfiguration.newBuilder(new SimpleJobConfiguration(JobCoreConfiguration.newBuilder(
                jobClass.getName(), cron, shardingTotalCount).shardingItemParameters(shardingItemParameters).failover(true).build(), jobClass.getCanonicalName())).overwrite(true).build();
    }
}`

ym;配置
simpleJob:
  cron: 0 08 17 * * ?
  shardingTotalCount: 2
  shardingItemParameters : 0=aaa,1=bbb,2=ccc
regCenter:
        serverList: 10.2.2.117:2182
        namespace: myJobTest
        baseSleepTimeMilliseconds: 1000  #等待重试的间隔时间的初始值 单位：毫秒
        maxSleepTimeMilliseconds: 3000  #等待重试的间隔时间的最大值
job:
public class MyTestSimpleJob implements SimpleJob {

    @Autowired
    TestMapper testMapper;

    private int jobCount=0;

    @Override
    public void execute(ShardingContext shardingContext) {

        System.out.println(String.format("------Thread ID: %s, 任务总片数: %s, 当前分片项: %s , 当前执行:%s，次数：%d",

                Thread.currentThread().getId(),shardingContext.getShardingTotalCount(), shardingContext.getShardingItem(),
                shardingContext.getShardingParameter(),jobCount++));
        int item = (500000/shardingContext.getShardingTotalCount());
        int start = shardingContext.getShardingItem() * item;
        int end = (shardingContext.getShardingItem()+1) * item;
        List<TestEntity> testEntities = testMapper.jobProcess(start,end);
        for (TestEntity testEntity : testEntities) {
                if(testEntity.getId() == 40000){
                    end = end/0;
                }
                testMapper.process(testEntity.getId());
        }
    }

}
Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by jimgreen2013** [comment]
@BaJingcheng 这个问题我也碰到了，你是怎么解决的呢？
