### ISSUE TITLE
原生的事件追踪是否可以去掉

### ISSUE THREAD

**Issue by superbool** [apache/shardingsphere-elasticjob#572]
初始化时创建了 JobEventRdbConfiguration 导致自动创建了事件追踪记录的相关表JOB_STATUS_TRACE_LOG  现在这张表越来越大，导致数据库有压力。

JobEventRdbConfiguration这个事件追踪是否能去掉呢，以及去掉之后有什么影响吗

**Comment by larrychao** [comment]
可以去掉，只要在构造schedule时不要传入JobEventRdbConfiguration就可以了。
事件追踪只是方便我们从控制平台查看job的进展，实际上自己从log也可。
