### ISSUE TITLE
failover bug

### ISSUE THREAD

**Issue by houzhanshanlinzhou** [apache/shardingsphere-elasticjob#577]
when I set the failover is true,I shutdown down the server,then the other server can't execute the failover's item.I found someone also find this problem in 2.1.5 version,  this is the url  https://blog.csdn.net/adi851270440/article/details/80498882   ,someone find the sourcecode bug,please check it;

**Comment by gzlicanyi** [comment]
两台机器调试了下，确实是bug

**Comment by cuiqunhao** [comment]
我也遇到了这个问题，现在解决了吗

**Comment by compilerduck** [comment]
Duplicated to #669
