### ISSUE TITLE
PostgreSQL数据库下，动态任务失败；内部表不能创建

### ISSUE THREAD

**Issue by apegeek** [apache/shardingsphere-elasticjob#584]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
相关的内部表可以正确创建
### Actual behavior （实际运行的结果是）
生成的create table语句含有``，导致出错
### Steps to reproduce the behavior （可重现问题的操作步骤）
使用postgresql数据库，动态添加任务
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

create
	table
		` JOB_EXECUTION_LOG ` (` id ` varchar( 40 ) not null,
		` job_name ` varchar( 100 ) not null,
		` task_id ` varchar( 255 ) not null,
		` hostname ` varchar( 255 ) not null,
		` ip ` varchar( 50 ) not null,
		` sharding_item ` int not null,
		` execution_source ` varchar( 20 ) not null,
		` failure_cause ` varchar( 4000 ) null,
		` is_success ` int not null,
		` start_time ` timestamp null,
		` complete_time ` timestamp null,
		primary key (` id `))

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Please add SQL with PostgreSQL dialect, ref #840
