### ISSUE TITLE
Postgresql下无法正常使用问题

### ISSUE THREAD

**Issue by apegeek** [apache/shardingsphere-elasticjob#585]
private void createJobStatusTraceTable(final Connection conn) throws SQLException {
        String dbSchema = "CREATE TABLE `" + TABLE_JOB_STATUS_TRACE_LOG + "` ("
                + "`id` VARCHAR(40) NOT NULL, "
                + "`job_name` VARCHAR(100) NOT NULL, "
                + "`original_task_id` VARCHAR(255) NOT NULL, "
                + "`task_id` VARCHAR(255) NOT NULL, "
                + "`slave_id` VARCHAR(50) NOT NULL, "
                + "`source` VARCHAR(50) NOT NULL, "
                + "`execution_type` VARCHAR(20) NOT NULL, "
                + "`sharding_item` VARCHAR(100) NOT NULL, "
                + "`state` VARCHAR(20) NOT NULL, "
                + "`message` VARCHAR(4000) NULL, "
                + "`creation_time` TIMESTAMP NULL, "
                + "PRIMARY KEY (`id`));";
        try (PreparedStatement preparedStatement = conn.prepareStatement(dbSchema)) {
            preparedStatement.execute();
        }
    }

这种写法，在PG下怎么支持？？？？？？

**Comment by IAMTJW** [comment]
本来就不支持pg吧

**Comment by apegeek** [comment]
我下载了源代码，并在其基础上做了修改

**Comment by apegeek** [comment]
> 本来就不支持pg吧

针对pg修改后，可以使用

**Comment by zj861222** [comment]
这个表只能mysql吧，你可以自己改成pg的建标语句

**Comment by compilerduck** [comment]
Seems the problem has been resolved, closing.
