### ISSUE TITLE
完全停止任务的最佳实践

### ISSUE THREAD

**Issue by vm-001** [apache/shardingsphere-elasticjob#589]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
如何实现完全停止任务？
### Actual behavior （实际运行的结果是）
在console管理界面失效、停止任务任务就会停下，一旦业务服务重启，任务又会重新开始执行，有没有什么办法可以实现完完全全的停止任务
### Steps to reproduce the behavior （可重现问题的操作步骤）
任意一个script任务启动后，在控制台停止，然后重启业务服务。任务就开始重新执行
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by vm-001** [comment]
如果客户端的配置的任务一开始使用disabled，等服务器启动后在console开启任务。如果使用kill -9杀掉服务的定时任务的进程。发现服务重启恢复后，定时任务也不会自动启动。
```
{"jobName":"myScript","jobClass":"com.dangdang.ddframe.job.api.script.ScriptJob","jobType":"SCRIPT","cron":"0/10 * * * * 
...
"reconcileIntervalMinutes":10,"disabled":true,"overwrite":false}
```
客户端overwrite为false，那么是以zk数据为准，那么在console如果disabled字段可以修改为true，是不是服务器重启后就能以zk数据为准？重新开始执行定时任务？

**Comment by zj861222** [comment]
@Dog-Lee  感觉按照你这种逻辑来会导致混乱，导致配置文件不生效，不知道实际现网环境中到底是什么值，

**Comment by kiwiflydream** [comment]
遇到了同样的问题，重启服务 失效、停止没有以 console 配置的为准，但是其它的配置倒是以 console 的为准了。

**Comment by mmx1960** [comment]
please assign to me

**Comment by mmx1960** [comment]
> please assign to me

talking with @terrymanu ,this is a ambiguous concept and we will describe clearly in the document. the function of `totaly pause the job`  doesn't exist now. we will design it  and  publish in next version.

**Comment by terrymanu** [comment]
Duplicated with #537
