### ISSUE TITLE
依赖包冲突导致类或方法找不到

### ISSUE THREAD

**Issue by BitgetLimited** [apache/shardingsphere-elasticjob#590]
### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
我们环境使用到是springboot 1.5.14，Curator 4.0.1，guava是23

### Actual behavior （实际运行的结果是）
运行时报Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService 等错误

所以必须在pom中指定curator等版本为2.10.0，以及guava为18，才能正常运行

### Steps to reproduce the behavior （可重现问题的操作步骤）
建议版本更新时，一并更新依赖包等版本

**Comment by BitgetLimited** [comment]
补充一下：
当只引入elastic-job和elastic-spring包时，curator-client,curator-framework,curator-recipes三个包的版本也是错误的
![image](https://user-images.githubusercontent.com/40291324/47899236-d9d61b80-deb3-11e8-9b47-be64795df90c.png)

**Comment by yunkaiOr2** [comment]
所以很少外部依赖是开源项目的一个重要指标。我打算用这个，然后发现依赖太旧了。想放弃了。
