### ISSUE TITLE
elastic-job-lite是基于quartz,在部署的时候需要在数据库中创建quartz相对应的表吗

### ISSUE THREAD

**Issue by martinko2009** [apache/shardingsphere-elasticjob#593]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
既然elastic-job-lite是基于quartz的话，部署的时候是否需要在数据库中创建quartz对应的表，比如qrtz_triggers,qrtz_cron_triggers等12张表
### Actual behavior （实际运行的结果是）
不知道该如何操作。
### Steps to reproduce the behavior （可重现问题的操作步骤）
主要是安装部署的问题，所以没有可重现问题的操作步骤。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by hunterwyld** [comment]
不会创建的，默认使用的是quartz的RAMJobStore

**Comment by martinko2009** [comment]
1、如果是用RAMJobStore，如果elastic-job-lite应用重启或者关闭后，再启动，所有调度信息都会丢失了。

**Comment by Leonidasz** [comment]
elastic-job-lite相关的配置是存储在zk中。

**Comment by terrymanu** [comment]
Closed because of no response anymore
