### ISSUE TITLE
定义了stream类型的job，调用jobOperateAPI.trigger 无法循环执行fetchdata方法

### ISSUE THREAD

**Issue by zj861222** [apache/shardingsphere-elasticjob#594]
### Which version of Elastic-Job do you using?
elastic-job-lite-spring  2.1.1

### Expected behavior 
期望能按照正常steam定时任务一样循环执行fetchData 和 processData

### Actual behavior 
实际结果是 fetcdata和 processData 只执行了一次。

### Steps to reproduce the behavior （可重现问题的操作步骤）
1.  定义一个steam类型的job
2. 调用 jobOperateAPI.trigger 方法去触发这个stream 类型的job

### 

debug了源码， 在 DataflowJobExecutor 这个类中。

**在 streamingExecute 方法中，getJobFacade().isEligibleForJobRunning() 跳出了循环**

    private void streamingExecute(final ShardingContext shardingContext) {
        List<Object> data = fetchData(shardingContext);
        while (null != data && !data.isEmpty()) {
            processData(shardingContext, data);
            if (**!getJobFacade().isEligibleForJobRunning()**) {
                break;
            }
            data = fetchData(shardingContext);
        }
    }

**Comment by terrymanu** [comment]
The new version (3.0.0-alpha) is upgrade this place, cloud you try it again?
