### ISSUE TITLE
jvm里查询作业运行信息

### ISSUE THREAD

**Issue by laohubuchiyu** [apache/shardingsphere-elasticjob#595]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

想在shutdown的时候 查询出还在运行的job信息 不知道怎么操作比较合理

**Comment by Leonidasz** [comment]
有控制台，http://elasticjob.io/docs/elastic-job-lite/02-guide/web-console/

**Comment by terrymanu** [comment]
Closed because of no response anymore
