### ISSUE TITLE
代码配置jobParameter不生效,读取值为空 (springboot)

### ISSUE THREAD

**Issue by hello2z** [apache/shardingsphere-elasticjob#600]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
```
<dependency>
    <groupId>org.apache.zookeeper</groupId>
    <artifactId>zookeeper</artifactId>
    <version>3.4.6</version>
</dependency>
<dependency>
	<groupId>com.dangdang</groupId>
    <artifactId>elastic-job-lite-core</artifactId>
    <version>2.1.5</version>
</dependency>
<dependency>
    <groupId>com.github.kuhn-he</groupId>
    <artifactId>elastic-job-lite-spring-boot-starter</artifactId>
    <version>2.1.5</version>
</dependency>
```

### Expected behavior （您预期的结果是）

```
@ElasticSimpleJob(cron = "0 * * * * ?", jobName = "shopAuthRefreshDailyJob",
        shardingTotalCount=2, shardingItemParameters = "0=AA,1=BB", jobParameter = "a=111&b=222&c=444", overwrite = true)
@Component
@Slf4j
public class ShopAuthRefreshDailyJob implements SimpleJob {
   @Override
    public void execute(ShardingContext shardingContext) {
        System.out.println("SpringSimpleJob 简单任务-------------任务名："+shardingContext.getJobName()+"\n"
                +"，---ShardingParameter:"+shardingContext.getShardingParameter()+"\n"
                +",----TaskId:"+shardingContext.getTaskId()+"\n"
                +",----JobParameter:"+shardingContext.getJobParameter()+"\n"
                +",----tShardingItem:"+shardingContext.getShardingItem()+"\n"
                +",----ShardingTotalCount:"+shardingContext.getShardingTotalCount()+"\n"
        );
    }
}

打印：jobParameter取值结果为空

按理论的jobParameter取值结果应该为：a=111&b=222&c=444
如果修改zk上的信息，则应用能读到zk上的值
```

### Actual behavior （实际运行的结果是）

```
get /shedule-shopcenter/com.test.shopcenter.job.ShopAuthRefreshDailyJob/config

{"jobName":"com.test.shopcenter.job.ShopAuthRefreshDailyJob","jobClass":"com.test.shopcenter.job.ShopAuthRefreshDailyJob","jobType":"SIMPLE","cron":"0 * * * * ?","shardingTotalCount":2,"shardingItemParameters":"0\u003dAA,1\u003dBB","jobParameter":"","failover":false,"misfire":true,"description":"","jobProperties":{"job_exception_handler":"com.dangdang.ddframe.job.executor.handler.impl.DefaultJobExceptionHandler","executor_service_handler":"com.dangdang.ddframe.job.executor.handler.impl.DefaultExecutorServiceHandler"},"monitorExecution":true,"maxTimeDiffSeconds":-1,"monitorPort":-1,"jobShardingStrategyClass":"","reconcileIntervalMinutes":10,"disabled":false,"overwrite":true}

```

### Steps to reproduce the behavior （可重现问题的操作步骤）

```
把zk上的节点删除了，然后启动应用服务，但是发现除了jobParameter的值没有被注册到zk上以外，其他的配置都可以写到zk上
```

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by junyi5257** [comment]
@

@ZaneRicky 

1，这个参数不能再这里获取，是由于这个@ElasticSimpleJob 注解的原因导致的吧，

@ElasticSimpleJob 注解，并不是 官方elastic-job-lite的,这个是其他人写的 对springboot的支持工具,你可以找这个 

<dependency>
    <groupId>com.github.kuhn-he</groupId>
    <artifactId>elastic-job-lite-spring-boot-starter</artifactId>
    <version>2.1.5</version>
</dependency>
的开发者。

谢谢

**Comment by Leonidasz** [comment]
@ZaneRicky 
Please contact the author of of ele-job-lite-spring-boot-starter to confirm the relevant question.In addition, the maintenance of elastic-job-lite has been restarted, and related springboot starter will be added in the future(#677). Please pay attention to to community.

elastic-job-lite-spring-boot-starter的相关问题，烦请联系其开源作者确认一下。另外，elastic-job-lite目前重启了相关维护工作，后续会增加相关的springboot starter(请参考#677)，也请关注社区的进展。

**Comment by ShawshankLin** [comment]
@Leonidasz JobPropertiesEnum怎么设置EXECUTOR_SERVICE_HANDLER的值，我需要修改DefaultExecutorServiceHandler，调大工作执行的线程数
