### ISSUE TITLE
elastic-job的lite在k8s上运行出现的问题

### ISSUE THREAD

**Issue by yinbucheng** [apache/shardingsphere-elasticjob#604]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by yinbucheng** [comment]
你好我用你们的elastic-job时版本为2.1.5采用java的api方法调用。出现问题是定时器有的无法注册上面去。不稳定。请求这是什么原因了。好像是zookeeper的注册instance的临时节点出现问题了
请问是k8s的网络不稳定还是你们框架lite不shiyo适应k8s

**Comment by yinbucheng** [comment]
难受，群也不能加。早知道用xx-job了。

**Comment by gaolin713** [comment]
单机有问题吗？我们是多机下任务会停止。。。

**Comment by Technoboy-** [comment]
ElasticJob restarts month ago, and donates to ASF, and will release the Apache version in the next two weeks if possible. 
You can give me an email, and join the IM group.

**Comment by terrymanu** [comment]
Expired because the current information cannot reproduce the issue.
