### ISSUE TITLE
ReconcileService无法释放回收

### ISSUE THREAD

**Issue by fangqj** [apache/shardingsphere-elasticjob#605]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
动态创建任务，执行完成删除任务。
删除zookepper job节点，以及删除任务后，任务相关实例 如ReconcileService能够回收，避免内存泄漏
### Actual behavior （实际运行的结果是）
删除节点后ReconcileService无法回收，一直在执行runOneIteration
![image](https://user-images.githubusercontent.com/31762409/49202698-71aa2500-f3e0-11e8-9b74-76a885eceb1f.png)
![image](https://user-images.githubusercontent.com/31762409/49202724-838bc800-f3e0-11e8-8344-95e7139ad3d3.png)

### Steps to reproduce the behavior （可重现问题的操作步骤）
1.手工创建任务
      new SpringJobScheduler(elasticJob, regCenter, liteJobConfiguration, jobEventRdbConfiguration, elasticJobListeners).init();
2.手工删除任务
  JobRegistry.getInstance().shutdown(jobName);  //清除对象和zookepper缓存
   regCenter.remove("/" + jobName);   //清除目录
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by zjypp** [comment]
楼主问题解决了吗？我也碰见这样的问题，动态创建一次性的问题，elasticjob隔1,2天就假死或者宕机，使用jconsole以后，发现大量的ReconcileService进程存在。也删除了zookeeper中的节点数据了

**Comment by caozhenhuamail** [comment]
楼主解决了这个问题了吗，一直运行ReconcileService 线程数一直递增控制不住那；
