### ISSUE TITLE
如何修改elastic-job-console绑定的ip地址？

### ISSUE THREAD

**Issue by gMan1990** [apache/shardingsphere-elasticjob#608]
RT

**Comment by qin4zhang** [comment]
你放在哪里运行这个console，都没关系，只要能连接到zk就可以吧

**Comment by gMan1990** [comment]
@qin4zhang 我是说这个console被访问的ip
比如绑定到127.0.0.1，那只能http://127.0.0.1:8899访问console

**Comment by compilerduck** [comment]
elastic-job-console是一个web项目，部署到哪台服务器上，就可以用那台服务器的ip地址服务，没有绑定的说法。

**Comment by gMan1990** [comment]
@compilerduck 就比如
- 绑定0.0.0.0 外部网络可以访问到elastic-job-console
- 绑定127.0.0.1 外部网络访问不到elastic-job-console

**Comment by compilerduck** [comment]
外部网络指的是公网吗？如果是，需要机房部署有独立公网IP的服务器，要么把elastic-job-console服务直接放上去，要么从这台服务器转发到部署有console服务的内部服务器。
如果指的是机房内部或办公网访问机房，只需要网络能连通就可以用ip地址访问了

**Comment by gMan1990** [comment]
@compilerduck 我是说 允许远程访问 还是 只能本机访问
就像 mysql https://www.jianshu.com/p/efeb209e6621
> 然后打开vim /etc/mysql/my.cnf
将bind-address = 127.0.0.1
设置成bind-address = 0.0.0.0（设备地址）

**Comment by compilerduck** [comment]
哦，大概了解了。Elastic Job不支持这样的功能，而且也不会支持。未来有可能加入权限控制，可允许多个用户访问系统，不同的用户可以有不同的权限。
