### ISSUE TITLE
servers 中只有一个IP  ，实际部属多个节点

### ISSUE THREAD

**Issue by HeroOnline** [apache/shardingsphere-elasticjob#609]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5 
### Expected behavior （您预期的结果是）
servers 中只有一个IP  ，实际部属多个节点
### Actual behavior （实际运行的结果是）
期望多少节点，servers 中就有多少个IP 
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
都是默认官方
Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by compilerduck** [comment]
无法复现此问题，正常多个节点启动会在zk的servers下注册多个ip。如果楼主还有此问题，请重开本新issue，并详细描述复现步骤，先关了。
