### ISSUE TITLE
从文档中没有发现有任务失败重试的配置呀

### ISSUE THREAD

**Issue by mrxlh** [apache/shardingsphere-elasticjob#612]
### Expected behavior （您预期的结果是）
控制台并没有提供失败重试的机制策略 ，查看咱们说明文档也没有，不知可否补充下web的使用相关文档
### Actual behavior （实际运行的结果是）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
http://elasticjob.io/

**Comment by terrymanu** [comment]
Closed because of no response anymore
