### ISSUE TITLE
还维护吗？生产准备用，我调研一下

### ISSUE THREAD

**Issue by yuanjinzhong** [apache/shardingsphere-elasticjob#616]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

还维护吗？

**Comment by IAMTJW** [comment]
感觉好像不维护了，可以看看xxl-job吧，已经转这个了

**Comment by yanmaipian** [comment]
一年没有更新了，应该不维护了。

**Comment by magicheng** [comment]
> 感觉好像不维护了，可以看看xxl-job吧，已经转这个了

xxl-job的分片功能弱吧？

**Comment by nmyphp** [comment]
@yuanjinzhong 
就现有功能来说，已经比较稳定和完善了，2.1.3版本目前接受了当当网订单团队的校验，从性能和稳定性来说，满足线上应用是绝对没问题的。也和作者亮哥沟通过这个问题，后面会继续维护，只是这段时间还投身在另一个项目中

**Comment by lawplus** [comment]
当时看到无需mysql DB， 并且我们又有zk集群， 所以就不选 xxl-job了。 现在生产稳定运行上万个elastic job，节点和cpu要准备充足些。

**Comment by Leonidasz** [comment]
会继续维护这个项目，目前有很多团队在生产环境上已经使用了。

**Comment by hiql** [comment]
一直在用，功能基本满足，当然也可以自己护展

**Comment by bbcdabao** [comment]
> @yuanjinzhong
> 就现有功能来说，已经比较稳定和完善了，2.1.3版本目前接受了当当网订单团队的校验，从性能和稳定性来说，满足线上应用是绝对没问题的。也和作者亮哥沟通过这个问题，后面会继续维护，只是这段时间还投身在另一个项目中

2.1.5 版本依然存在AbstractDistributeOnceElasticJobListener 多个实例，多次调用的坑

**Comment by compilerduck** [comment]
会继续维护，请关注社区。另外，AbstractDistributeOnceElasticJobListener多次调用的问题，请关注#487
