### ISSUE TITLE
失败重试次数配置没有找到呀

### ISSUE THREAD

**Issue by mrxlh** [apache/shardingsphere-elasticjob#617]
尊敬的开源作者，通过文档没有找到对应的失败重试次数的相关配置，不知能否提供该功能

（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by compilerduck** [comment]
能否详细描述您的需求，是指作业执行失败要重试？如果是这样，ElasticJob大概率不会提供这样的设置，你可以在你的业务逻辑中实现重试。先关闭此issue了，如果我的理解有误且你认为此功能有价值，请重新reopen并陈述理由，谢谢
