### ISSUE TITLE
SQL语句末尾有分号，导致写入Oracle数据库报无效字符错误。

### ISSUE THREAD

**Issue by zhulangfly** [apache/shardingsphere-elasticjob#619]
版本：2.1.5
bug：io\elasticjob\lite\event\rdb\JobEventRdbStorage.java 中的sql语句最后又“;” 导致写入Oracle时报错： (job-event-15) ORA-00911: 无效字符。
解决方案： 去掉sql语句的“;”号。

**Comment by terrymanu** [comment]
Please add SQL for oracle dialect. ref #840
