### ISSUE TITLE
ZookeeperRegistryCenter的cache线程不安全，存在并发故障的风险

### ISSUE THREAD

**Issue by liych05** [apache/shardingsphere-elasticjob#622]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Steps to reproduce the behavior （可重现问题的操作步骤）
频繁创建作业，并且作业执行完后手动对作业shutdown和remove（删除zookeeper的数据），ZookeeperRegistryCenter.cache就容易出现异常ConcurrentModificationException。

### 请问这个问题如何解决最安全？如果需要自己修改代码，git上的代码(2.1.6)是否有稳定版本的代码？

谢谢！

**Comment by compilerduck** [comment]
将会尽快修复这个bug，请关注社区，谢谢
