### ISSUE TITLE
xsd错误

### ISSUE THREAD

**Issue by B0B02333** [apache/shardingsphere-elasticjob#623]
### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5 版
### Expected behavior （您预期的结果是）
可以引入xsd文件
### Actual behavior （实际运行的结果是）

Referenced file contains errors (http://www.dangdang.com/schema/ddframe/reg/reg.xsd). For more information, right click on the message in the Problems View and select "Show Details..."

**Comment by Leonidasz** [comment]
http://elasticjob.io/docs/elastic-job-lite/02-guide/config-manual/
参看“2. Spring命名空间配置”
添加elastic-job-lite-spring模块的依赖
