### ISSUE TITLE
项目启动完成后执行一次，后续每1小时执行一次怎么配置？

### ISSUE THREAD

**Issue by gMan1990** [apache/shardingsphere-elasticjob#624]
1、项目启动后执行一次
2、后续每隔1小时执行一次，基于什么时间点无所谓

**Comment by nmyphp** [comment]
@gMan1990 
0 0 * * * *
每小时的00:00执行一次

**Comment by gMan1990** [comment]
@nmyphp 比如在01:08分程序运行了，得等50多分钟才执行

**Comment by Leonidasz** [comment]
0 0 */1 * * ?

**Comment by gMan1990** [comment]
@Leonidasz 项目启动完成后如何执行一次?

**Comment by Leonidasz** [comment]
elastic-job采用的trigger是CronTrigger，cron表达式不能覆盖你提出需求的效果。是否可以考虑采用上面两种比较接近的方式。
