### ISSUE TITLE
在不同的namespace下. 相同id的任务只能执行一个

### ISSUE THREAD

**Issue by wgou** [apache/shardingsphere-elasticjob#626]
Elastic-Job版本为:elastic-job-lite-code 2.1.5
您预期的结果是：在不同的namespace下 相同的任务id 完全隔离执行
实际运行的结果是：其中之一被运行，另一个不会运行

配置如下：spring-cdwm-job.xml
  <reg:zookeeper id="rebateJobCenter_cdwm" server-lists="10.13.3.10:2181" namespace="rebate-cdwm-local"    base-sleep-time-milliseconds="1000" max-sleep-time-milliseconds="3000" max-retries="3"/>
	<job:dataflow
			id="cxInvComJob"
			class="com.dmall.cx.rebate.biz.beans.job.CxInvComJob"
			registry-center-ref="rebateJobCenter_cdwm"
			cron="0 0/1 * * * ? *"
			sharding-total-count="4"
			monitor-execution="true"
			misfire="false"
			failover="false"
			overwrite="true"
			job-parameter="cdwm"
			streaming-process="true"
			description="实时库补订单生成及发送"/>

spring-dmall-job.xml

    <reg:zookeeper id="rebateJobCenter" server-lists="10.13.3.10:2181" namespace="rebate-dmall-locl"
          base-sleep-time-milliseconds="1000" max-sleep-time-milliseconds="3000" max-retries="3"/>
          
          <job:dataflow
			id="cxInvComJob"
			class="com.dmall.cx.rebate.biz.beans.job.CxInvComJob"
			registry-center-ref="rebateJobCenter"
			cron="0 0/1 * * * ? *"
			sharding-total-count="4"
			monitor-execution="true"
			misfire="false"
			failover="false"
			overwrite="true"
			job-parameter="dm"
			streaming-process="true"
			description="实时库补订单生成及发送"/>

console控制台 在rebate-cdwm-local 下 任务正常执行，在rebate-dmall-local下 任务为”分片待调整“。
根据源码发现注册的时候能注册进去，后一个会覆盖前一个，在start的时候，检查jobname已经注册过，直接就启动了已经存在的。

在 JobRegistry 中 的schedulerMap、regCenterMap key是以jobName命名的，是否可以考虑增加namespace+jobname 作为key。
  /**
     * 添加作业调度控制器.
     * 
     * @param jobName 作业名称
     * @param jobScheduleController 作业调度控制器
     * @param regCenter 注册中心
     */
    public void registerJob(final String jobName, final JobScheduleController jobScheduleController, final CoordinatorRegistryCenter regCenter) {
        schedulerMap.put(jobName, jobScheduleController);
        regCenterMap.put(jobName, regCenter);
        regCenter.addCacheData("/" + jobName);
    }

**Comment by Leonidasz** [comment]
I think there are two simple ways to do this: 1. Just change another jobId,  2. Run two job services using the same jobId in a different namespace of the same zk.
Using namespace+jobname as the key will increase the complexity of the  code logic (for subsequent treatment ) and add additional processing overhead. Instead, the "option" can be easily avoided.
我觉得这个问题有两种很简单的方式：1.就是换一个jobId，2.运行两个job服务，在同一个zk的不同命名空间下，使用同一个jobId。
使用namespace+jobname 作为key的修改方式会给后续的代码逻辑引入复杂度，增加额外的处理开销，而从业务配置上可以很简单的避开，所以不太建议调整。
