### ISSUE TITLE
配置了JobEventConfiguration，数据库没有自动创建表

### ISSUE THREAD

**Issue by liubo-tech** [apache/shardingsphere-elasticjob#628]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite    2.1.5
### Expected behavior （您预期的结果是）
自动创建两张日志表
### Actual behavior （实际运行的结果是）
没有创建两张日志表，并报错，Table 'world.job_execution_log' doesn't exist
### Steps to reproduce the behavior （可重现问题的操作步骤）
偶现，新创建数据库，运行程序，问题出现
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by dalaocu** [comment]
我也碰到了这个问题

**Comment by jackielgl** [comment]
我也有个问题，第一次启动，创建成功了表，JOB_EXECUTION_LOG和表JOB_STATUS_TRACE_LOG，再次启动，会报错： com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'JOB_EXECUTION_LOG' ，是不是没有判断表已经存在呢？

**Comment by Leonidasz** [comment]
@jackielgl 有判断

**Comment by simafei** [comment]
这个项目没人维护了，很多依赖的组件都不升级，guava还是18.0，与20.0以上版本都不兼容，mysql驱动8以上就不能创建表

**Comment by Leonidasz** [comment]
@simafei 
还在维护。组件版本冲突的问题在3.0分支中正在处理，相关的PR刚刚review通过。可以关注下这个分支。

**Comment by xhga** [comment]
遇到不能创建表的原因可能是由于驱动com.mysql.cj.jdbc.Drive导致的。我也是遇到不能创建表的问题，并解决了它。
并记录了不能创建表的原因。文章地址：https://blog.csdn.net/qq_37751454/article/details/90737740
希望可以帮助到有需要的朋友。
