### ISSUE TITLE
AbstractDistributeOnceElasticJobListener 分布式监听器不起作用

### ISSUE THREAD

**Issue by liubo-tech** [apache/shardingsphere-elasticjob#631]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
## Actual behavior （实际运行的结果是）
如介绍的那样，分布式监听器只执行一次
### Steps to reproduce the behavior （可重现问题的操作步骤）
继承AbstractDistributeOnceElasticJobListener，编写分布式监听器。启动两个应用，查看日志，开始时，
开始方法只执行一次，结束方法两个应用都执行。一段时间后，两个应用都会执行开始和结束方法。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by bbcdabao** [comment]
https://my.oschina.net/u/252559/blog/2223092#comments   
这个链接解答了你的问题，这个是一个很大很大的坑，我也是刚刚准备上线时发现，太坑

**Comment by compilerduck** [comment]
将会尽快修复这个问题，请关注社区动态。

**Comment by Leonidasz** [comment]
@terrymanu @compilerduck 
I have suggested some adjustment scheme about AbstractDistributeOnceElasticJobListener. Please access the following link and take a view.
简单整理了一下AbstractDistributeOnceElasticJobListener相关bug的几种改造方案，烦请参看下面链接的内容。

https://note.youdao.com/ynoteshare1/index.html?id=fc39cf1c29b17db47439a98ef4e7465a&type=note

**Comment by ZShUn** [comment]
@compilerduck 请问elastic job是打算重新维护了吗
