### ISSUE TITLE
elastic-job-console看不到历史记录

### ISSUE THREAD

**Issue by losymear** [apache/shardingsphere-elasticjob#634]
有作业操作，表`JOB_EXECUTION_LOG`和`JOB_STATUS_TRACE_LOG`有数据，但是作业历史显示`No matching records found`。

**Comment by MrRachelWong** [comment]
我也遇到这个问题了， 有解决方法吗？

**Comment by mmx1960** [comment]
控制台上面需要配置追踪的数据源

**Comment by born198x** [comment]
> 控制台上面需要配置追踪的数据源

已经配置了 一样看不到数据 怎么说

**Comment by terrymanu** [comment]
Can you provide more details?
Console is a simply CRUD project, the most passible reason is wrong data source configuration

**Comment by terrymanu** [comment]
Closed because of no response anymore
