### ISSUE TITLE
定时器会把所有任务都执行一遍

### ISSUE THREAD

**Issue by liujingjing5** [apache/shardingsphere-elasticjob#637]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite 2.1.5  

### Expected behavior （您预期的结果是）
定时器按配置 执行  

### Actual behavior （实际运行的结果是）
所有任务都执行一遍  

### Steps to reproduce the behavior （可重现问题的操作步骤）
一台机器，部署了两个tomcat，各自都有定时器项目。  
当关闭一台tomcat时，另一台tomcat的定时器就会把所有任务都走一遍。  

但是如果tomcat部署在两台机器时，没有出现这个情况

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by HUTchengxi** [comment]
ej的作业都是注册在zk上，正常情况下，两台服务器各自一个分片，比如0和1，当持有分片0的服务器挂掉了，ej会将分片0也分配给另一台服务器，所以存活的那台服务器会执行所有的任务，这是ej的弹性扩容特性

**Comment by compilerduck** [comment]
部署在两台机器上时，如果关闭了一台，被中断的任务没有failover补偿吗？楼主是这个意思吗？如果是，请参考issue #669。如果有别的意思，请重新reopen这个issue并说明情况。
