### ISSUE TITLE
JobScheduleController  add shutdown(boolean waitForJobsToComplete) method

### ISSUE THREAD

**Issue by douxiaofeng99** [apache/shardingsphere-elasticjob#638]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
>=2.0
### Expected behavior （您预期的结果是）
对于比较重要的定时任务，需要此次任务执行完成后才可以停止任务，也就是优雅的停止任务。
在JobScheduleController 有个shutdown方法，但不带参数，里面的调用也是直接调用quartz的shutdown方法，导致没办法优雅停止任务
### Actual behavior （实际运行的结果是）
无此方法
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Fixed by #798
