### ISSUE TITLE
job任务数量控制在多少比较合适?

### ISSUE THREAD

**Issue by lawplus** [apache/shardingsphere-elasticjob#640]
![image](https://user-images.githubusercontent.com/9402650/55636154-d9d89f80-57f4-11e9-9ac0-e15b56ef495f.png)
图片显示的是我线上应用的job真实数量, 注册中心也是zookeeper3.4.5, 3个集群节点(zk内存已占1g), task节点如图所示, task节点占用cpu日常在10-20%左右(还是挺高的).
了解了job-lite 会注册zk的监听事件的机制. 随着业务量的增长, job数量现已过万了.

并且查看应用所占线程数量, 应用运行一天,已开启了1w多 -  2w+ 的线程. 貌似线程数量没有控制到位?
ps huH p  {pid} | wc -l

**Comment by Leonidasz** [comment]
你目前作业节点集群的规模是多大?
esjob-lite中，考虑到分片作业的并发，作业执行是通过线程池实现的，为了保证不同作业之间的隔离性，一个作业对应一个线程池。你们目前job数过万，所以线程数1w多是很正常的事情。
个人觉得如果task节点足够的话，系统资源饱和度方面问题不大，但是zk集群可能后续会有一些问题，毕竟所有的作业配置以及调度、分片信息都在zk中，如果作业量过大的话，zk的性能会下降。所以建议从你们实际的业务或应用角度考虑把作业集群拆分一下，你们可以试着压一下你们的zk集群，看作业量在多少时表现比较合适。

**Comment by lawplus** [comment]
作业节点集群的规模? 共4个dubbo服务节点承载着elastic job lite的容器， 对外暴露dubbo接口供其他app调用来生成各种job

**Comment by glasses1989** [comment]
> 作业节点集群的规模? 共4个dubbo服务节点承载着elastic job lite的容器， 对外暴露dubbo接口供其他app调用来生成各种job

加我QQ 我们沟通下产线上遇到的坑吧，我们产线上目前1600个调度

**Comment by glasses1989** [comment]
> 作业节点集群的规模? 共4个dubbo服务节点承载着elastic job lite的容器， 对外暴露dubbo接口供其他app调用来生成各种job

QQ:2087663863
