### ISSUE TITLE
RegExceptionHandler的命名给人造成一种幻想

### ISSUE THREAD

**Issue by lxchinesszz** [apache/shardingsphere-elasticjob#642]
RegExceptionHandler 给人的第一感觉是，正则表达式异常处理器，但是其主要是处理,zk找不到job节点的异常，名字应该改为JobNodeExceptionHandler更好些。

**Comment by Leonidasz** [comment]
REG 是 register center注册中心的缩写，RegExceptionHandler是注册中心异常处理类。命名由此得来。

**Comment by lxchinesszz** [comment]
reg 可以看做是注册中心，也感觉是正则表达式。有点不明确。




| |
刘鑫
邮箱：13120725361@163.com
|

签名由 网易邮箱大师 定制

在2019年04月16日 12:03，Leonidaz 写道：

REG 是 register center注册中心的缩写，RegExceptionHandler是注册中心异常处理类。命名由此得来。

**Comment by compilerduck** [comment]
Reg是register的缩写
