### ISSUE TITLE
1.1.1版本连接zk集群时偶尔会报OperationTimeoutException

### ISSUE THREAD

**Issue by zhaoqiang1024** [apache/shardingsphere-elasticjob#644]
elastic-job版本:1.1.1
线上目前有9台服务器的集群，发现偶尔会出现打开超时的情况，异常名称为:org.apache.zookeeper.keeperexception$operationtimeoutexception: keepererrorcode = operationtimeout，查了zk版本发现为2014年的3.4.6版本，其它问题如防火墙问题应该不存在，线上为docker环境，且多次重启有一定机率会正常连接，所说是1.1.1版本bug或者zk客户端版本太低？

**Comment by zhaoqiang1024** [comment]
敢问大佬有遇到过种问题吗？

**Comment by compilerduck** [comment]
现在是否还有问题？有试过elasticjob的最新版本2.1.5吗？

**Comment by terrymanu** [comment]
Out of service for 1.x version
