### ISSUE TITLE
elastic-job-lite-console用户名和密码安全问题

### ISSUE THREAD

**Issue by itlaoge** [apache/shardingsphere-elasticjob#646]
### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
用户名和密码不能被破解，虽然一般部署在内网

### Actual behavior （实际运行的结果是）
F12查看浏览器network，抓取出header里的Authorization，是用Base64编解码的，很容易就能解码出用户名和密码

### Steps to reproduce the behavior （可重现问题的操作步骤）
登录elastic-job-console，F12查看network，复制header里的Authorization进行Base64解码，用户名和密码显示明文

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
com.dangdang.ddframe.job.security.doFilter方法

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by 13917030454** [comment]
启动job控制台报错 Exception in thread "main" java.lang.NoClassDefFoundError: com/dangdang/ddframe/job/lite/console/ConsoleBootstrap

**Comment by luky116** [comment]
may i try this issue?

**Comment by terrymanu** [comment]
@luky116  Cool, I just assign it to you

**Comment by luky116** [comment]
> @luky116 Cool, I just assign it to you

thank you！

**Comment by itlaoge** [comment]
张亮大神



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liang Zhang"<notifications@github.com&gt;; 
发送时间: 2020年7月2日(星期四) 中午12:58
收件人: "apache/shardingsphere-elasticjob-lite"<shardingsphere-elasticjob-lite@noreply.github.com&gt;; 
抄送: "js阿超"<2330466260@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/shardingsphere-elasticjob-lite] elastic-job-lite-console用户名和密码安全问题 (#646)





 
@luky116  Cool, I just assign it to you

**Comment by thicv** [comment]
看提交记录，@haocao 也是个大神啊，代码提交量一点也不输亮神

**Comment by thicv** [comment]
> 张亮大神

看提交记录，@haocao 也是个大神啊，代码提交量一点也不输亮神

**Comment by itlaoge** [comment]
都是大神，就我最菜




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "thicv"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 晚上6:04
收件人: "apache/shardingsphere-elasticjob-lite"<shardingsphere-elasticjob-lite@noreply.github.com&gt;; 
抄送: "js阿超"<2330466260@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/shardingsphere-elasticjob-lite] elastic-job-lite-console用户名和密码安全问题 (#646)





  
张亮大神
  
看提交记录，@haocao 也是个大神啊，代码提交量一点也不输亮神
