### ISSUE TITLE
建议大家生产环境不要使用elastic-job

### ISSUE THREAD

**Issue by henryjun0** [apache/shardingsphere-elasticjob#648]
原打算在生产环境用elastic-job，现发现坑太多，而且最大问题，项目已经停止维护，很多奇怪的问题无人理会，建议准备在生产环境用的朋友三思而后行

**Comment by bbcdabao** [comment]
正在准备生产环境使用，哎！ 测试发现 AbstractDistributeOnceElasticJobListener  监听器会在一个job的多个实例同时调用的bug ， 真实坑人

**Comment by misskeyjoy** [comment]
文档不是推荐AbstractDistributeOnceElasticJobListener这个吧

**Comment by liuchu** [comment]
我们项目在用elastic-job。
关于fixed-delay，我在release note里没看到相关的，想在这里请问下你们现在的版本，是否支持这个特性？
@henryjun0 谢谢！

**Comment by Leonidasz** [comment]
@liuchu 
Elastic-job使用的是crontrigger，对于fixed-delay，某些比较特殊的场景，可能覆盖不了。

**Comment by Leonidasz** [comment]
@bbcdabao 
这个问题，可以考虑结合分布式锁来处理。

**Comment by lawplus** [comment]
生产用了1年了， 有什么问题大家@下我看看能否帮忙解决

**Comment by bbcdabao** [comment]
> 处理

谢谢您,，您说的很对，分布式锁可以修改这个bug，这个问题已经解决，采用0片任务负责分配任务，

**Comment by compilerduck** [comment]
@henryjun0 感谢关注Elastic Job社区，因团队核心成员变动，暂停了一段时间。目前我们已重启了维护，如果您有任何建议或问题可在社区提出
@bbcdabao，AbstractDistributeOnceElasticJobListener在个别情况下执行多次的问题，请关注#487，我们后续会在#487中回复相关处理状态。
@liuchu 后续可能会支持fixed-rate，因为quartz scheduler本身就支持，fixed-delay还有待进一步论证
