### ISSUE TITLE
同一namespace，修改cron表达式，任务未实时更新

### ISSUE THREAD

**Issue by hmapleleaf** [apache/shardingsphere-elasticjob#649]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by hmapleleaf** [comment]
版本2.1.5
预期：修改cron表达式，重启任务，定时规则更新
实际：10秒更新一次，修改cron重启后仍旧10s更新一次

**Comment by Leonidasz** [comment]
作业执行的cron表达式在何处修改的？

**Comment by hmapleleaf** [comment]
代码，配置文件里面。由10s执行一次修改成，每天16点执行




------------------ 原始邮件 ------------------
发件人: "Leonidaz"<notifications@github.com>; 
发送时间: 2019年6月3日(星期一) 下午2:37
收件人: "elasticjob/elastic-job-lite"<elastic-job-lite@noreply.github.com>; 
抄送: "l.clever"<592871815@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [elasticjob/elastic-job-lite] 同一namespace，修改cron表达式，任务未实时更新 (#649)




作业执行的cron表达式在何处修改的？

**Comment by hmapleleaf** [comment]
修改namespace后，任务才更新

**Comment by Leonidasz** [comment]
LiteJobConfiguration中有个overwrite属性，你设置一下true。cron表达式没有改的原因是因为你再次启动作业的话，还是默认从zk中读取作业配置，设置了这个属性后，作业启动会将配置文件中的配置覆盖zk中的。

**Comment by hmapleleaf** [comment]
ok,thankyou
