### ISSUE TITLE
动态的数据源应该怎么传入，我的项目里有读写分离的操作

### ISSUE THREAD

**Issue by wasd345** [apache/shardingsphere-elasticjob#650]
动态的数据源应该怎么传入，我的项目里有读写分离的操作，配置的是多个数据源，目前没发现怎么可以动态传入数据源

**Comment by Leonidasz** [comment]
动态的数据源，是指运行的作业需要连接的数据源是动态的么？可以考虑作业连接配置中心，如appolo

**Comment by wasd345** [comment]
> 动态的数据源，是指运行的作业需要连接的数据源是动态的么？可以考虑作业连接配置中心，如appolo

已找到变通解决方案，目前把主库的数据源名字传了过去,我们的主库负责增删改逻辑，两个从库负责的读操作，是1主2从的mysql配置模式
