### ISSUE TITLE
控制台打包报错

### ISSUE THREAD

**Issue by wasd345** [apache/shardingsphere-elasticjob#651]
[ERROR] Failed to execute goal on project elastic-job-lite-console: Could not resolve dependencies for project io.elasticjob:elastic-job-lite-console:jar:3.0.0.M1-SNAPSHOT: Failed to collect dependencies at io.elasticjob:elastic-job-lite-lifecycle:jar:3.0.0.M1-SNAPSHOT: Failed to read artifact descriptor for io.elasticjob:elastic-job-lite-lifecycle:jar:3.0.0.M1-SNAPSHOT: Could not transfer artifact io.elasticjob:elastic-job-lite-lifecycle:pom:3.0.0.M1-SNAPSHOT from/to archiva.snapshots (http://192.168.1.99:8081/repository/snapshots/): Connect to 192.168.1.99:8081 [/192.168.1.99] failed: Connection refused: connect -> [Help 1]

**Comment by compilerduck** [comment]
看这个异常日志，是连不到你的仓库？这不是elastic job问题，是maven仓库管理方面的。如果是本机仓库，尝试打开.m2\repository\io\elasticjob\elastic-job-lite-lifecycle\3.0.0.M1-SNAPSHOT，把其中的文件都删掉试试。
