### ISSUE TITLE
分片的数量是越多越好吗，如果采用平均算法，分片数量越大，最后一个分片的压力比较大，不能被整除的数据都被分给了最后一个分片

### ISSUE THREAD

**Issue by wasd345** [apache/shardingsphere-elasticjob#652]
分片的数量是越多越好吗，如果采用平均算法，分片数量越大，最后一个分片的压力比较大，不能被整除的数据都被分给了最后一个分片

**Comment by wasd345** [comment]
我们的数据id是uuid所以目前采用的是分页查询的方式处理业务数据

**Comment by Leonidasz** [comment]
分片的数量是应该和自身的业务还有作业节点服务器的性能等方面综合考虑的，也不是分片越多就越好，分片的策略的详细说明可以看一下官网http://elasticjob.io/docs/elastic-job-lite/02-guide/job-sharding-strategy/
，如果采用默认的分片策略，不能整除的多余分片将依次追加到序号小的服务器，而不是最后一个。且分片数也只是比其他服务器多一个而已。
