### ISSUE TITLE
通过api添加的任务，当服务重启后可否通过zk获取job信息自动注册启动

### ISSUE THREAD

**Issue by shuohao** [apache/shardingsphere-elasticjob#654]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
服务重启后，从zk中获取IP对应的所有的job信息，然后重新注册启动
### Actual behavior （实际运行的结果是）
通过API添加的任务，服务重启后不会重新注册启动job
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
通过哪个api添加的任务？服务注册成功后，在zk中有对应的注册配置信息么？

**Comment by suyehe** [comment]
可以单独把任务名称按照一定的规则做前缀 启动的时候遍历zk节点 然后根据config信息重新加载任务

**Comment by compilerduck** [comment]
因楼主未提供进一步信息，先关闭此issue。如果有进一步想说明的，可reopen。
