### ISSUE TITLE
elastic-job-lite-console-2.1.5有bug，注册中心连不上

### ISSUE THREAD

**Issue by wasd345** [apache/shardingsphere-elasticjob#655]
elastic-job-lite-console-2.1.5有bug，注册中心连不上

**Comment by Leonidasz** [comment]
有排查连接不上的日志么？realease的版本一般不会存在这么关键的bug问题。

**Comment by wasd345** [comment]
找到原因了 需要填写内网的ip,才可以连上，我们是5台linux服务器


------------------ 原始邮件 ------------------
发件人: "Leonidaz"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 上午9:03
收件人: "elasticjob/elastic-job-lite"<elastic-job-lite@noreply.github.com>;
抄送: "wangxiaodong"<813723897@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [elasticjob/elastic-job-lite] elastic-job-lite-console-2.1.5有bug，注册中心连不上 (#655)




有排查连接不上的日志么？realease的版本一般不会存在这么关键的bug问题。

**Comment by glasses1989** [comment]
找到原因为啥不关闭问题

**Comment by Leonidasz** [comment]
@compilerduck 这个issue可以关闭了。
