### ISSUE TITLE
elastic-job-lite docker bridge模式 多网络情况下，获取ip会获取到多个网络段的ip

### ISSUE THREAD

**Issue by henryjun0** [apache/shardingsphere-elasticjob#656]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
只获取到client所在的docker容器的ip
### Actual behavior （实际运行的结果是）
获取到了不只是docker容器所在网络的ip，还获取到了其他网络的ip
### Steps to reproduce the behavior （可重现问题的操作步骤）
每次
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Fixed by #1069
