### ISSUE TITLE
2.1.5启动报索引超出767 bytes错误，数据库mysql5.6

### ISSUE THREAD

**Issue by zhouzhiy** [apache/shardingsphere-elasticjob#657]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by compilerduck** [comment]
提供的信息过少，请最起码把错误信息粘出来，现在还能复现吗？鉴于提供的信息不完整，先关闭此issue了，有问题再reopen吧。

**Comment by zhouzhiy** [comment]
ok




------------------ 原始邮件 ------------------
发件人: "Shengjun"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 下午4:49
收件人: "elasticjob/elastic-job-lite"<elastic-job-lite@noreply.github.com>;
抄送: "戒烟"<920488881@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [elasticjob/elastic-job-lite] 2.1.5启动报索引超出767 bytes错误，数据库mysql5.6 (#657)




提供的信息过少，请最起码把错误信息粘出来，现在还能复现吗？鉴于提供的信息不完整，先关闭此issue了，有问题再reopen吧。
