### ISSUE TITLE
应用启动时选主会产生大量临时节点，偶尔有个别临时节点无法删除导致阻塞，从而引起应用启动卡住

### ISSUE THREAD

**Issue by glasses1989** [apache/shardingsphere-elasticjob#661]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
选主正常
### Actual behavior （实际运行的结果是）
选主阻塞
### Steps to reproduce the behavior （可重现问题的操作步骤）
测试环境
作业数量：1800左右
实例数量：580
个别应用系统在启动的时候会出现/{jobName}/leader/election/latch下选主产生的临时节点无法删除，造成选主线程一直阻塞从而导致应用启动卡住，且没有相关日志；
初步看来是由于/{jobName}/leader/election/latch 节点由curator选主功能会产生大量临时节点，其中最小的临时顺序节点没有删除导致选主阻塞；目前只会在重启的时候会发生；
zookeeper client版本3.4.8   server部署的版本是3.4.5；

测试环境遇到过几次这样的问题后，把那个最小的临时顺序节点删除后就正常了，没有保存相关截图和dump文件，待后面遇到我再补充
有没有大佬遇到相同的问题？

补充：怀疑业务系统某一台服务实例启动失败，但是quartz线程仍在执行，和zk的连接也一直存在，但是选主等操作异常导致最小的临时顺序节点没有删除，造成其他服务实例的选主的时候阻塞住；

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by lawplus** [comment]
有错误日志么？ 类似这样的： 错误日志：[2019-07-26 10:17:09,707][ERROR][][LeaderLatch:532] Can't find our node. Resetting. Index: -1

？

**Comment by glasses1989** [comment]
> 有错误日志么？ 类似这样的： 错误日志：[2019-07-26 10:17:09,707][ERROR][][LeaderLatch:532] Can't find our node. Resetting. Index: -1
> 
> ？

你这个是选主错误，跟我的情况不一样。
我看了下源码好像这个日志对应的逻辑是正常的，观察下选主功能是否正常，如果正常，关闭curator的日志。忽略吧

**Comment by ZShUn** [comment]
其实可以这样解决把job的zk拆分出来，因为有可能在你重启的那个时间段zk比较繁忙导致job 假死（其实内部源码时个debug日志）

**Comment by terrymanu** [comment]
Because the version 1.x and 2.x use curator 2.10 which can support ZooKeeper 3.4.6 only.
Your ZooKeeper version is not suitable.
