### ISSUE TITLE
不支持fixedRate特性  initialDelay特性，导致迁移困难

### ISSUE THREAD

**Issue by purgeyao** [apache/shardingsphere-elasticjob#662]
因@Scheduled 注解 fixedRate特性  initialDelay特性  elasticjob暂不支持
导致迁移过程困难

**Comment by Leonidasz** [comment]
目前Elastic-job的调度触发器是crontrigger。

**Comment by johnyannj** [comment]
@purgeyao 如果支持fixedRate  initialDelay， 你怎么保证所有节点同时执行任务啊~~

**Comment by terrymanu** [comment]
fixedRate initialDelay is not suitable for distribute schedule.
