### ISSUE TITLE
告警处理

### ISSUE THREAD

**Issue by zyd007** [apache/shardingsphere-elasticjob#664]
任务未执行，任务未正确结束，如何告警？

**Comment by Leonidasz** [comment]
lite版有事件追踪，可以从mysql中查询出作业执行的情况。如果需要对作业执行情况进行告警，可以针对作业设置SLA告警。

**Comment by glasses1989** [comment]
我们这边的告警是基于zabiix调用告警脚本，脚本定时请求控制台提供的接口。
大概逻辑：
1.轮询低频调度（我们改写了源码，加入了高低频标识，一天执行小于48次就为低频，高频的需要特殊配置才可以告警，否则默认不监控），
2.针对每一个调度作业根据cron表达式计算出当前调度截止当前日期应该执行的次数；
3.再捞取数据库里面截止目前记录的日志条数；
4.如果2、3步骤的结果不一致则认为调度作业执行有异常，返回异常结果给zabbix服务器
5.zabbix定时请求上述接口，并把异常信息以邮件、短信的方式发送给相关人员
希望对你有帮助。
