### ISSUE TITLE
[ERROR][][LeaderLatch:532] Can't find our node. Resetting. Index: -1

### ISSUE THREAD

**Issue by lawplus** [apache/shardingsphere-elasticjob#665]
[ERROR][][LeaderLatch:532] Can't find our node. Resetting. Index: -1

/elastic-job-lite 2.1.5 版本， 每天都会产生这样的ERROR日志。有人碰到过么？

**Comment by compilerduck** [comment]
这个出错信息是Curator报出来的，看源码是因为选主时会在zk中建立类似节点：/leader/election/latch/_c_89beae59-f590-4b93-9068-b32653d830d6-latch-0000000000，如果该节点为null，则会报这个错误。所以请看下，是否选主过程中zk节点表现异常？参考LeaderLatch第532行。
