### ISSUE TITLE
1单次任务执行后删除自己发生异常2.大量任务同时执行，偶尔会有一条任务没有触发

### ISSUE THREAD

**Issue by aboluo-gy** [apache/shardingsphere-elasticjob#667]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
lite-2.1.5

### Expected behavior （您预期的结果是）
1.大量单次执行任务执行结束后，手动调用删除任务方法删除自己可以删除成功
2.开启了错过执行（默认）后，多个并发的任务（比如100个）都可以执行

### Actual behavior （实际运行的结果是）
1.大量单次执行任务执行结束后，手动调用终止任务方法可以终止（偶有报错，但是不影响使用），
 jobSettingsConfig. getJobJobOperateConfiguration().shutdown(Optional.of(jobName), Optional.<String>absent());
调用删除任务的方法removeJobSettings会有很大几率报错
jobSettingsConfig.getJobSettingsConfiguration().removeJobSettings(jobName);
，在监听器后执行任务里面删除任务依然报错。
2.任务漏执行，开启了错过执行（默认）后，多个并发的任务（比如100个），有时候只执行了99个，如果是单次任务，就永远错过了执行时间，也不会执行了

### Steps to reproduce the behavior （可重现问题的操作步骤）
for循环添加100个单次执行的任务测试多次，并在任务执行后删除自己。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example 
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.

**Comment by keepmeup** [comment]
这个问题有结果了吗

**Comment by aboluo-gy** [comment]
亮哥后面回复过让用英文重新issue，就把这个关了，比较忙就没有重新提交，问题应该没有解决，我后面使用其他定时任务框架了。 阿波罗 ***@***.*** 签名由 网易邮箱大师 定制 在2021年05月06日 09:27，keepmeup 写道： 这个问题有结果了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 15168326318** [comment]
@aboluo-gy   很多问题没解决就直接关闭了，哎。
