### ISSUE TITLE
失效转移失败

### ISSUE THREAD

**Issue by cuiqunhao** [apache/shardingsphere-elasticjob#669]
问题：失效转移在两台机器实验下不生效，请问是否是我的实验方式有问题？
场景：
两台机器：192.168.206.202；192.168.206.191，
任务配置如下：
@ElasticJobConf(name = "MySimpleJob_1",
		cron = "* 0/5 * * * ?",
		failover = true,
		shardingItemParameters = "0=0,1=1,2=2,3=3",
		shardingTotalCount=4,description = "简单ce任务")

操作步骤：
1、两台机器先后上线
2、等第一次任务执行完成
3、删除zk节点（jobName/instances下的某个实例节点）
4、触发fialoverlistenermanager中的JobCrashedJobListener
5、但是在获取失效分片的时候shardingService.getShardingItems(jobInstanceId)，有如下代码，直接返回空的失效分片集合了：
 if (!serverService.isAvailableServer(jobInstance.getIp())) {
            return Collections.emptyList();
        }

**Comment by johnyannj** [comment]
感觉这个代码确实有毛病，当一个节点挂了的时候，需要设置failover标记。

com.dangdang.ddframe.job.lite.internal.failover.FailoverListenerManager.JobCrashedJobListener#dataChanged

这个方法里的两个分支，都不会走到。

**Comment by johnyannj** [comment]
@cuiqunhao  我觉得这个逻辑也有问题~~~   

com.dangdang.ddframe.job.lite.internal.failover.FailoverListenerManager.JobCrashedJobListener#dataChanged

两个分支都走不到。

**Comment by johnyannj** [comment]
这部分逻辑，完全逻辑混乱，特别是
com.dangdang.ddframe.job.lite.internal.failover.FailoverService.FailoverLeaderExecutionCallback

            // TODO 不应使用triggerJob, 而是使用executor统一调度
            JobScheduleController jobScheduleController = JobRegistry.getInstance().getJobScheduleController(jobName);
            if (null != jobScheduleController) {
                jobScheduleController.triggerJob();
            }

**Comment by johnyannj** [comment]
假设修正了这个bug。

每次有节点挂掉，这个节点所属的分片任务都会立即被执行一次，也不符合逻辑。

**Comment by compilerduck** [comment]
We reproduce the case you described, will have a further investigation and see if a fix needed.
我们复现了这个问题，需要进一步研究看要如何修复。

**Comment by leokongwq** [comment]
> We reproduce the case you described, will have a further investigation and see if a fix needed.
> 我们复现了这个问题，需要进一步研究看要如何修复。

我在使用过程中，尝试修复了该问题，目前能实现failover和failover后的立即执行问题。具体思路如下：
1. 直接获取Job每个分片的执行实例instanceId，和crash的实例instanceId进行比较，匹配则加入需要failover的结果集中
2. running节点改为持久节点，正常运行时，数据为空。crash后，写入数据'interrupted' ，用来表示Job真实的运行情况。

修改后的核心代码如下：

### ShardingService.getShardingItems -> ShardingService.getShardItemsForFailover

```java
public List<Integer> getShardItemsForFailover(final String jobInstanceId) {
        List<Integer> result = new LinkedList<>();
        for (String item : jobNodeStorage.getJobNodeChildrenKeys(ShardingNode.ROOT)) {
            int shardIndex = Integer.parseInt(item);
            String willFailoverInstance = jobNodeStorage.getJobNodeData(ShardingNode.getInstanceNode(shardIndex));
            // 该IP负责执行的任务分片(前提是每个ip只启动一个实例)
            boolean isInstanceMatchShardItem = jobInstanceId.equals(willFailoverInstance);
            boolean isJobShardItemRunning = jobNodeStorage.isJobNodeExisted(ShardingNode.getRunningNode(shardIndex));
            if (isInstanceMatchShardItem && isJobShardItemRunning) {
                jobNodeStorage.fillJobNode(ShardingNode.getRunningNode(shardIndex), INTERRUPTED);
                result.add(shardIndex);
            }
        }
        return result;
 }
```

### ExecutionContextService.isRunning

` 
private boolean isRunning(final int shardingItem) {
        return isRunningNodeExist(shardingItem) && jobNodeStorage.getJobNodeData(ShardingNode.getRunningNode(shardingItem)).equals("");
}
`
### ExecutionService.registerJobBegin
```java
public void registerJobBegin(final ShardingContexts shardingContexts) {
        JobRegistry.getInstance().setJobRunning(jobName, true);
        if (!configService.load(true).isMonitorExecution()) {
            return;
        }
        for (int each : shardingContexts.getShardingItemParameters().keySet()) {
            jobNodeStorage.fillJobNode(ShardingNode.getRunningNode(each), "");
        }
}
```

**Comment by compilerduck** [comment]
如果对修复此问题感兴趣，请提交一个pull request，注意不要使单元测试覆盖率下降（所以你需要写必要的单元测试）。

**Comment by compilerduck** [comment]
请注意，在dev分支上提交pull request，不要在master上提交。

**Comment by leokongwq** [comment]
![image](https://user-images.githubusercontent.com/7894659/66898285-7e9d2a80-f02b-11e9-98d4-bd6c8df4db9e.png)

**Comment by Leonidasz** [comment]
@leokongwq 
感谢你的提供的建议。此处有一点内容需要讨论，按照以上思路调整，需要通过running节点进行作业状态状态的判断，也可以理解为开启“monitorExecution”开关（默认为false）。如果结合“monitorExecution”来修复failover的话，我觉得会限制其应用场景。

**Comment by Leonidasz** [comment]
@terrymanu @compilerduck 
I have collected some issues about failover. Please access the following link (skip the source code analysis and just go to "related issue").
大致收集了一下issue上关于failover的一些问题，并简单梳理了一下，烦请参看下面链接的内容（附上了部分源码解析，issue整理的内容请直接跳至“相关issue整理”）。

https://note.youdao.com/ynoteshare1/index.html?id=a31f6bd6f85db0ab9326ba93a9afbfa8&type=note

**Comment by johnyannj** [comment]
@Leonidasz 
关于你的总结  《2. Failover多余补偿》这一章节总结，还是没有包括https://github.com/elasticjob/elastic-job-lite/issues/671的情况。
671描述的是，一个活着的节点连续抢了两个failover 分片，执行了两次trigger job，其中一次trigger 会把两个分片都执行完，后面的一个trigger是多余的，造成作业重复执行。

**Comment by Leonidasz** [comment]
@johnyannj 
Thanks for your attention , as well as for the collation and discussion of the issues. In the "4. TriggerJob handles" section, I recorded the problem of triggerJob.
: )感谢你对相关问题的重视，以及之前的整理和讨论，triggerJob多余处理的这个问题记录在“4. triggerJob处理”这一小节里。
