### ISSUE TITLE
 失效转移导致任务重复执行

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#671]
### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
任务不要重复执行
### Actual behavior （实际运行的结果是）
任务重复执行
### Steps to reproduce the behavior （可重现问题的操作步骤）
3个节点 
1分钟执行一次任务。0 *  * * * ?
场景一、
在 25秒的时候， kill掉其中一个节点， 这个节点的任务会迅速被其它节点获取并立即执行。
（备注：  假设修复了https://github.com/elasticjob/elastic-job-lite/issues/669  这个bug）
在下一个分钟的0秒的时候，重新分片，全部分片执行。

那么这次失效转移的分片 不就是提前重复执行了一次吗？

场景二、
存活的节点每抢占一个分片，都会触发jobScheduleController.triggerJob()，
但是job在执行的时候，是批量获取的failover分片啊
```
    @Override
    public ShardingContexts getShardingContexts() {
        boolean isFailover = configService.load(true).isFailover();
        if (isFailover) {
            **List<Integer> failoverShardingItems** = failoverService.getLocalFailoverItems();
            if (!failoverShardingItems.isEmpty()) {
                return executionContextService.getJobShardingContext(failoverShardingItems);
            }
        }
```

那么触发的job执行次数就是过剩的，最后剩下的job 就会执行分片操作，并执行属于本节点的分片任务。
重复执行。

**Comment by johnyannj** [comment]
com.dangdang.ddframe.job.lite.internal.failover.FailoverListenerManager.JobCrashedJobListener#dataChanged
里的下面也是矛盾的。
```
 }
                List<Integer> failoverItems = failoverService.getFailoverItems(jobInstanceId);
                if (!failoverItems.isEmpty()) {
                    for (int each : failoverItems) {
                        failoverService.setCrashedFailoverFlag(each);
                        failoverService.failoverIfNecessary();
                    }
                } 
```
failoverService.getFailoverItems(jobInstanceId); 就是获取/sharding/$item/failover的节点
  failoverService.setCrashedFailoverFlag(each); 会判断没有/sharding/$item/failover 才会set failover flag....

**Comment by vran-dev** [comment]
`场景一` 确实是一个问题，这是因为 Elastic-Job-Lite 简单的认为实例下线就是失效了，我觉得失效的条件应该是 `实例下线时有作业还在运行中`， 这样才应该进行补偿。

`场景二`  存活节点的确是一次只抢占一个分片（有加分布式锁），但是后面的批量获取分片也是只获取属于存活节点的分片。 
> 也就是说抢占的节点会和节点进行绑定，节点后面也只会获取到已经抢占到的节点。

**Comment by johnyannj** [comment]
@vran-dev 
现在的逻辑是 抢占一个failover分片 就triggerjob（但是这个triggerjob 是异步的哟），这会导致任务还没有执行，又抢了一个，又会trigger job一次。 第一次的trigger job 会执行两个failover分片任务，第二次trigger的就是多余的。

**Comment by vran-dev** [comment]
> @vran-dev
> 现在的逻辑是 抢占一个failover分片 就triggerjob（但是这个triggerjob 是异步的哟），这会导致任务还没有执行，又抢了一个，又会trigger job一次。 第一次的trigger job 会执行两个failover分片任务，第二次trigger的就是多余的。

可以参考 `JobScheduler.getBaseQuartzProperties()` 方法， 为Quartz配置的线程池的线程总数为1。

`分配失效分片 -> 删除失效标记 -> triggerJob` ， 第二次`triggerJob`时，如果第一次还没执行完成，是会被阻塞的。（因为只有一个线程）
> 也就是说话多次trigger其实同步的

**Comment by johnyannj** [comment]
@vran-dev 

大哥，我的意思是：

抢了一个分片 triggerJob，这个job不会立即执行的。循环判断当前没有执行的任务，它会又抢一个分片，并triggerjob。 

第一次trigger的job 会把两个分片都执行掉。 第二triggerjob就是重复执行。 

我说的是重复执行，不是并发执行。

**Comment by vran-dev** [comment]
> @vran-dev
> 
> 大哥，我的意思是：
> 
> 抢了一个分片 triggerJob，这个job不会立即执行的。循环判断当前没有执行的任务，它会又抢一个分片，并triggerjob。
> 
> 第一次trigger的job 会把两个分片都执行掉。 第二triggerjob就是重复执行。
> 
> 我说的是重复执行，不是并发执行。

你说的对，确实会重复执行，你有什么解决思路吗？
感觉要解决这个问题，作业执行时要知道这次触发原因是失效转移才行

**Comment by johnyannj** [comment]
@vran-dev 
作者 在com.dangdang.ddframe.job.lite.internal.failover.FailoverService.FailoverLeaderExecutionCallback写了一行TODO注释：
  // TODO 不应使用triggerJob, 而是使用executor统一调度

可能就是考虑到了这个问题。

**Comment by Leonidasz** [comment]
@johnyannj 
你提到的场景2：
```java
List<Integer> failoverShardingItems = failoverService.getLocalFailoverItems();
```
这里并不是批量获取的failover分片，请注意**FailoverLeaderExecutionCallback**中：
```java
int crashedItem = Integer.parseInt(jobNodeStorage.getJobNodeChildrenKeys(FailoverNode.ITEMS_ROOT).get(0));
```
实际上是“领”了一个分片。
作者原本的思路，JobFacade#failoverIfNecessary() 方法，只会抓取一个失效转移的作业分片，这样带来的好处是，多个作业分片可以一起承担执行失效转移的分片集合。

场景1和场景3你提到的情况，我们会再详细讨论，谢谢~

**Comment by johnyannj** [comment]
@Leonidasz 同学可能你理解错了
List<Integer> failoverShardingItems** = failoverService.getLocalFailoverItems();
是任务执行时查询，就是查询本节点抢到的所有failover分片

JobFacade#failoverIfNecessary() 是只会抓一个，但是抓了一个还没有执行的话，他会接着抓。


failover的执行  和抓 failover分片是两个地方执行的。

抓分片是 JobCrashedJobListener干的，有节点挂了，JobCrashedJobListener判断当前没有任务执行，他就抓，每次抓一个，抓完了投到quartz里，如果当前还是没有任务执行，他还会抓。

问题在于投到quartz里执行是有延迟的，这会导致连续抓了多个。投入quartz多个trigger。

当第一个trigger执行的时候，
它会查询所有抓取到的failover分片执行List<Integer> failoverShardingItems** = failoverService.getLocalFailoverItems();

那后面的trigger 发现没有failover分片了，就执行本节点的分片： 这就是一次多余的执行

**Comment by Leonidasz** [comment]
@johnyannj 
按照首次发送failover，当作业instance发生crash时，JobCrashedJobListener会把crash的instance之前分配到的分片项全部抓取过来，然后设置failover标志，并进行失效转移（如必要）。
```java
    for (int each : shardingService.getShardingItems(jobInstanceId)) {
        failoverService.setCrashedFailoverFlag(each);
        failoverService.failoverIfNecessary();
    }
```
如果失效instance拥有多个分片项的话，会多次执行failoverService.failoverIfNecessary()（当然这和AbstractElasticJobExecutor.execute()中的jobFacade.failoverIfNecessary()有些重复，需要优化考虑下。），但是并不是每次调用都会触发triggerJob，因为在needFailover()有isJobRunning(jobName)的判断，如果当前已经有job在运行那么是不会触发triggerJob，也即如果有job已经触发正在failover处理了，是会从一定程度上限制triggerJob。
```java
    private boolean needFailover() {
        return jobNodeStorage.isJobNodeExisted(FailoverNode.ITEMS_ROOT) && !jobNodeStorage.getJobNodeChildrenKeys(FailoverNode.ITEMS_ROOT).isEmpty()
                && !JobRegistry.getInstance().isJobRunning(jobName);
    }
``` 
另外，jobScheduleController.triggerJob()如果当前没有运行的作业，triggerJob是立即执行的，所以不一定第一次triggerJob时，就能拿到所有的failover分片。

**Comment by johnyannj** [comment]
@Leonidasz 

> 但是并不是每次调用都会触发triggerJob，因为在needFailover()有isJobRunning(jobName)的判断，如果当前已经有job在运行那么是不会触发triggerJob，也即如果有job已经触发正在failover处理了，是会从一定程度上限制triggerJob。

====》问题就在于这里，他是triggerjob，triggerjob是往quartz里放入一个提trigger而已，要等到quartz的调度任务触发这个trigger，真正跑起来才会isJobRunning(jobName)， 这个过程是有时间差的。
并不是triggerjob了 ， isJobRunning(jobName)就会返回true

**Comment by terrymanu** [comment]
Because the issue is too old and we'd like to use English to communicate now.
I just close the issue. If the issue still exist, please submit a new issue to discuss. 
Thank you very much.
