### ISSUE TITLE
job_status_trace_log 日志如何关闭

### ISSUE THREAD

**Issue by wasd345** [apache/shardingsphere-elasticjob#673]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
job_status_trace_log 日志不插入
### Actual behavior （实际运行的结果是）
不管如何设置都不起作用，删除了事件追踪源配置还是不行。
### Steps to reproduce the behavior （可重现问题的操作步骤）
删除了事件追踪源配置还是不行，还是依旧会往库里插入日志。

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by compilerduck** [comment]
new JobScheduler对象时不使用带有JobEventConfiguration参数的构造函数就可以了吧

**Comment by xqq1994** [comment]
楼上正解
