### ISSUE TITLE
我们的场景是每天创建很多动态任务，这些任务都是一次性的，这些任务执行完成以后，zookeeper的节点信息会删除吗

### ISSUE THREAD

**Issue by zjypp** [apache/shardingsphere-elasticjob#674]
我们的场景是每天创建很多动态任务，这些任务都是一次性的，这些任务执行完成以后，zookeeper的节点信息会删除吗，

起了一个A任务，A任务是每半个小时执行支持，A任务里面动态的创建了很多一次性的任务，这些一次性任务也是会在zookeeper里面生成节点信息的，这些一次性任务执行完以后，zookeeper的节点信息会自动删除吗？还是需要我们手动删除？目前看，这些节点信息好像一直存在，节点数据会越来越大

**Comment by vran-dev** [comment]
作业节点不会删除的，针对你的问题也有解决方案
-  另外开启一个作业，专门用来定时删除这些临时任务。 （可以将这类任务放在一个 `namespace` 下）
- 修改源码 `JobShutdownHookPlugin` ，在里面添加作业节点删除的逻辑

另外再说一下，目前 Elasticc-Job-Lite 这样创建的动态任务是无法有效利用到分片机制的，但是任务的执行是没有问题的。

**Comment by johnyannj** [comment]
@vran-dev  删除zk里的数据， 是递归删除的，不是一下子删除的，这会导致一些节点监听节点变化，进行选主、设置分片标记，在zk下面存留垃圾数据~~

**Comment by Leonidasz** [comment]
@zjypp 
The job data in zookeeper will be not delete automatically. If the dynamic jobs you created have independent job names in zk as nomal as the job configed, then the dynamic jobs can be removed manually, you can do that through elastic-job-lite-console. But please note that first "shutdown" and then "remove".If delete the job date node in zookeeper directly, the job services may not stop, and some internal processing logic leads to retained garbage data.
zk里作业的相关数据节点是不会自动删除的，不太清楚你们创建的动态job的逻辑，如果你们创建的动态作业和常规配置启动的job一样，有独立的job name，那么是可以手动删除的，通过elastic-job-lite-console就可以操作，但请注意需要先“终止”再“删除”，直接删除zk上的job数据节点的话，job服务可能未停止，内部有一些处理逻辑会导致留存垃圾数据。
