### ISSUE TITLE
分片参数配置导致实际分片数目不正确

### ISSUE THREAD

**Issue by heureuxQ** [apache/shardingsphere-elasticjob#676]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite-spring-shaded
2.1.5
### Expected behavior （您预期的结果是）
配置shardingTotalCount = 1; shardingItem = 1=xxxx
期望单台实例运行Job
### Actual behavior （实际运行的结果是）
两台实例都运行了Job
### Steps to reproduce the behavior （可重现问题的操作步骤）
SpringBoot启动实例
配置参数shardingTotalCount = 1; shardingItem = 1=xxxx

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
使用SimpleJobConfig即可

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by compilerduck** [comment]
Hi heureuxQ，没有办法复现这个问题。如果已经起了一个实例并且正常运行，第二个实例分到的分片项应该为空，不会执行的。具体你可以在AbstractElasticJobExecutor.execute(ShardingContexts,ExecutionSource)第一行上设置下断点，看是否是这样。

**Comment by compilerduck** [comment]
如果有问题，请再reopen issue吧
