### ISSUE TITLE
Add a Spring Boot Starter: elastic-job-lite-starter

### ISSUE THREAD

**Issue by Leonidasz** [apache/shardingsphere-elasticjob#677]
I suggest adding a Spring Boot Starter for elastic-job-lite.

**Comment by legiorange** [comment]
guest what

https://github.com/yinjihuan/elastic-job-spring-boot-starter

**Comment by compilerduck** [comment]
> guest what
> 
> https://github.com/yinjihuan/elastic-job-spring-boot-starter

Looks cool, we can take a look at the code and see if there is something good that can be used in the official version.

**Comment by xjzrc** [comment]
注：以下项目已停止维护，仅供代码参考
配置文件版本
https://github.com/xjzrc/elastic-job-lite-spring-boot-starter
注解版版本
https://github.com/xjzrc/elastic-job-lite-spring-boot-starter/tree/v1.1.0

**Comment by terrymanu** [comment]
The version 2.x is expired, we will create new issue with spring boot starter with new 3.x API
