### ISSUE TITLE
Really hope registry support Eureka

### ISSUE THREAD

**Issue by legiorange** [apache/shardingsphere-elasticjob#678]
But ...
Latest commit 2 years ago.

**Comment by Leonidasz** [comment]
Maintenance of the project has been restarted, so please pay more attention to elastic-job-lite. Of course, we also welcome the participation of open source enthusiasts  , if there are good Suggestions and ideas.

By the way, We will deliberate on the enhancements and adjustments of registry center, but maybe not now.

In my opinion, resume the iteration and release of elastic-job-lite as soon as possible is much more important.

**Comment by compilerduck** [comment]
> But ...
> Latest commit 2 years ago.

You will see commits soon :-)

**Comment by terrymanu** [comment]
It is not the necessary task, and we have no plan to do it now.
