### ISSUE TITLE
Add checkstyle check on pull request validation

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#679]
Before pull request merge, we need to add checkstyle to check the code format and style.
Define a checkstyle template and add it to maven validation phase is a good practice.

We can use ShardingSphere's checkstyle template directly, there is in:
https://github.com/apache/incubator-shardingsphere/blob/dev/src/resources/checkstyle_ci.xml

**Comment by compilerduck** [comment]
OK, having a checkstyle is a good thing, not sure if existing code can pass the check, we will have a try.
