### ISSUE TITLE
Upgrade quartz's version

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#680]
We are using quartz 2.2.1 which is using C3P0. The license of C3P0 is LGPL which is not friendly for Apache license.

We should Upgrade quartz's version to 2.3.0 at least that using DBCP instead of C3P0 and is friendly for Apache license.

**Comment by compilerduck** [comment]
Latest version of quartz is 2.3.1. For safety purpose, we can use 2.3.0 which might be verified by more people. By the way, we will upgrade Curator from 2.10.0 to 4.1.0. Of course, we need fully test.
