### ISSUE TITLE
ExecutorServiceHandlerRegistry有内存泄漏风险(risk of memory leak)

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#683]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
关闭任务的清理资源
### Actual behavior （实际运行的结果是）
内存增长
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

ExecutorServiceHandlerRegistry 这个类，在任务关闭的时候，没有清理对应job的线程池。

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
Can you give more details about the problem or some code snippet of the issue?

**Comment by johnyannj** [comment]
hi @Leonidasz

when one job is shutdown， the “ExecutorServiceHandlerRegistry.remove(String jobName)”  is not call.

when we add job and shutdown job more and more.

" Map<String, ExecutorService> REGISTRY"  in ExecutorServiceHandlerRegistry will be more and more 

OOM at last.
