### ISSUE TITLE
多实例场景下执行间隔时间不对

### ISSUE THREAD

**Issue by yanglikun** [apache/shardingsphere-elasticjob#685]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
代码：一个简单的simpleJob 每三秒打印一个log
期望：每3秒打印一个log
### Actual behavior （实际运行的结果是）
实际：顺序启动了4个实例，到后来运行的间隔时间不是3秒了，而且不固定
### Steps to reproduce the behavior （可重现问题的操作步骤）
顺序启动simplejob-springboot下的dev.shizhan.DemoApplication 4个实例
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
代码见：https://github.com/yanglikun/elastic-job  中的simplejob-springboot工程
Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by yanglikun** [comment]
![image](https://user-images.githubusercontent.com/1728527/67086540-91eafa00-f1d3-11e9-88e9-fe5899cf48ca.png)

**Comment by Leonidasz** [comment]
You run 4 instances of the job, the sharding total count is 3?
你的这个作业运行了4个实例，分片数设置的是3么？

**Comment by shizhandev** [comment]
> You run 4 instances of the job, the sharding total count is 3?
> 你的这个作业运行了4个实例，分片数设置的是3么？

分片总数是3

**Comment by Leonidasz** [comment]
3 sharding with 3 instances is sufficient for testing, and the result should be one sharding per instance. According to the log, between 18:02 and 18:03, the execution interval on the three instances which running sharding item is 1 minute. Can you make sure the execution duration of the job is just 3 seconds ?
如果是为了测试的话，3个分片使用3个实例就足够了，最后的效果应该是一个实例上分配一个分片。从贴出的日志上看，18:02 至18:03分这段，三个运行分片的实例上执行的间隔都是1分钟，确定job的执行时间一定是3秒？

**Comment by shizhandev** [comment]
I recorded a video explaining the problem I encountered. See：https://youtu.be/aSec6iJm1Qk
我录制了一个视频了说明遇到的问题。请参见：https://youtu.be/aSec6iJm1Qk

**Comment by yanglikun** [comment]
I recorded a video explaining the problem I encountered. See：https://youtu.be/aSec6iJm1Qk
我录制了一个视频了说明遇到的问题。请参见：https://youtu.be/aSec6iJm1Qk

**Comment by Leonidasz** [comment]
Video I have seen, I also simulated in the development environment, but can not reappear the question.When the scheduling of job was incorrect, the interval is both 35 seconds of the 2 instances. I cannot see your job implementation clearly. I suggest you debug your job implementation. In  version 2.1.5, there wouldn't be such an obvious mistake in scheduling of the srouce code , please also check the local code encapsulation of your own.
视频我看了，在开发环境也模拟了一下，无法复现你们描述的情况。视频中两个instance实例出现调度不准确的时候，都是间隔为35秒，看不清你的job实现类，建议你debug一下你的job执行情况。2.1.5版本，源码调度这块是不会存在如此明显的问题，所以这块也请排查一下本地的封装。

**Comment by yanglikun** [comment]
你可以把你的代码发我一下么？我在自己的电脑上试试
May you send me your code? I try on my own computer

**Comment by yanglikun** [comment]
> Video I have seen, I also simulated in the development environment, but can not reappear the question.When the scheduling of job was incorrect, the interval is both 35 seconds of the 2 instances. I cannot see your job implementation clearly. I suggest you debug your job implementation. In version 2.1.5, there wouldn't be such an obvious mistake in scheduling of the srouce code , please also check the local code encapsulation of your own.
> 视频我看了，在开发环境也模拟了一下，无法复现你们描述的情况。视频中两个instance实例出现调度不准确的时候，都是间隔为35秒，看不清你的job实现类，建议你debug一下你的job执行情况。2.1.5版本，源码调度这块是不会存在如此明显的问题，所以这块也请排查一下本地的封装。

你可以把你的代码发我一下么？我在自己的电脑上试试
May you send me your code? I try on my own computer

**Comment by Leonidasz** [comment]
给个邮箱地址或是QQ号吧。

**Comment by yanglikun** [comment]
> 给个邮箱地址或是QQ号吧。

yanglikun0@gmail.com

**Comment by yanglikun** [comment]
1、已经收到邮件代码代码，并且在本地试了下，也有同用的问题(有时候35秒执行)。
2、因为本地是用docker启动的zk，看了下docke的时区是 UTC 0时区的。不是+8的。
3、后来不用docker，用本地的zk和一个远程服务器zk(都是东八区) 分别试了下，执行都是正常的。
4、结论：如果client时区 和 zk 时区不一致，还会有问题？

**Comment by Leonidasz** [comment]
这个结论需要确认一下，如果你们有环境，可以跟进debug一下确认具体是哪个环境导致的问题。谢谢~
