### ISSUE TITLE
在任务shutdown后很多资源没有清理

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#686]
资源一：
ReconcileService 线程，这个已经有人 提过单了
https://github.com/elasticjob/elastic-job-lite/issues/605

资源二：
RegistryCenterConnectionStateListener
每个job会给zk的client加一个RegistryCenterConnectionStateListener，但是任务关闭的时候没清除。

资源三：
ExecutorServiceHandlerRegistry里的ExecutorService
每个job一个线程池记录在此，在shutdown任务的时候 没释放。
已经提单
https://github.com/elasticjob/elastic-job-lite/issues/683

资源四：
这个是最难发现的一个资源未释放的
Quartz资源无法释放
JobShutdownHookPlugin把Quartz的关闭 注册给了JVM的 shutdownhook。
这导致即便quatz调度关闭，对象也无法GC回收。
正确的做法应该是在JobShutdownHookPlugin的shutdown方法里，把hook线程 从JVM里remove掉。（当然如果是jvm关闭执行的时候 remove会抛IllegalStateException，异常可忽略）

如果你考虑动态添加删除任务，至少要修改以上四点。

**Comment by Leonidasz** [comment]
Thank you for your suggestion and arrangement. We need a full discussion about these points.
非常感谢你的建议和整理，这几点需要讨论一下。

**Comment by compilerduck** [comment]
问题1已复现

**Comment by kuguobing** [comment]
com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage 类中，所有关于DB操作的资源没有主动释放掉：
1、Connection
2、PreparedStatement
3、ResultSet 
没有finally close掉~

**Comment by terrymanu** [comment]
Fixed by #705
