### ISSUE TITLE
config “reconcile-interval-minutes” with placeholder in Spring will  report errors

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#689]
File Path： elastic-job-lite/elastic-job-lite-spring/src/main/resources/META-INF/namespace/job.xsd 

“reconcile-interval-minutes” is declared as an integer 
```
<xsd:attribute name="reconcile-interval-minutes" type="xsd:int" default="10"/>
```

when config “reconcile-interval-minutes” with placeholder in Spring as follows:
```
    <job:simple id="xxx" class="xxxxxx"
                registry-center-ref="regCenter"
                sharding-total-count="2" cron="0/10 * * * * ?"
                reconcile-interval-minutes="${job.reconcile.interval.minutes}"
            />
```
it will report error:
org.xml.sax.SAXParseException; lineNumber: 30; columnNumber: 35; cvc-datatype-valid.1.2.1: '${job.reconcile.interval.minutes}' 不是 'integer' 的有效值。

Because when spring reads XML, it already validates XSD, which happens before  resolving placeholders. So it's going to report a mistake.

**Comment by compilerduck** [comment]
The issue has been reproduced, will fix ASAP.
