### ISSUE TITLE
项目启动报错，任务不能执行

### ISSUE THREAD

**Issue by qingqing2022** [apache/shardingsphere-elasticjob#690]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Actual behavior （实际运行的结果是）>>>>启动报错
error log：
 INFO  org.quartz.core.QuartzScheduler 305 - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'xxxxJob' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
The log you provide is not the error log, iust the info log printed by the QuartzScheduler.
你提供的日志不是错误日志，是QuartzScheduler打印的info日志。

You sure your job is not executed? How do you configure cron expression of your job?The job is executed only when cron expression triggered.
你的job是没有执行么？你配置的cron表达式是怎么配置的？作业只有当cron表达式触发的时候才会执行。

**Comment by qingqing2022** [comment]
是这样的，我在配置文件配置了执行时间，开始任务是可以执行的，但是我在配置文件里改了几次触发时间的cron表达式，重启几次服务之后就不work了，目前是服务器是还可以work，但是我本地任务不能触发了，连得是本地zk

**Comment by Leonidasz** [comment]
Sorry, I didn't get your point. Can you confirm the reason why the job does not execute? Is it caused by changing cron or restarting the service? Can you mak sure your local job has finished last schedule  work before the cron is triggered ? 
抱歉，没太明白你描述的意思。作业不执行的原因能确认一下么，是改了cron导致的还是重启了服务导致的？你本地任务不触发，是否是本地执行的作业分片上个周期的调度还未完成？

**Comment by qingqing2022** [comment]
我找到问题了，本地配置文件改了表达式，但是zk上还是原来的表达式，所以任务没有按新表达式的时间执行。原因是overwrite参数使用默认，并没有覆盖zk上表达式，把overwrite设置成true，就可以按新表达式的时间执行了。这是我的问题，谢谢大神支持。
