### ISSUE TITLE
任务执行问题咨询

### ISSUE THREAD

**Issue by wkhappy1** [apache/shardingsphere-elasticjob#695]
版本2.1.5
问题如果我把任务设置每10分钟执行一次
如果第一个10分钟任务执行超过了10分钟，比如15分钟
此时第二个10分钟任务会怎么执行，是等待第一个任务执行完，还是放弃执行

**Comment by Leonidasz** [comment]
If misfire set false in JobCoreConfiguration, the misfired task will not execute.
If misfire set true in JobCoreConfiguration, the misfired job will execute after the pre task completed.
如果JobCoreConfiguration中配置misfire为false，则在你描述的场景中，misfire任务不会执行。
如果JobCoreConfiguration中配置misfire为true，则等第一个任务执行完后，会执行misfire的任务。
