### ISSUE TITLE
Job Event Database操作资源未释放

### ISSUE THREAD

**Issue by kuguobing** [apache/shardingsphere-elasticjob#697]
### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-common-core-2.1.5.jar；其他版本这块代码应该一样
https://github.com/elasticjob/elastic-job-lite/blob/master/elastic-job-common/elastic-job-common-core/src/main/java/com/dangdang/ddframe/job/event/rdb/JobEventRdbStorage.java

https://github.com/elasticjob/elastic-job-lite/blob/master/elastic-job-common/elastic-job-common-core/src/main/java/com/dangdang/ddframe/job/event/rdb/JobEventRdbStorage.java

### Expected behavior （您预期的结果是）
com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage 
com.dangdang.ddframe.job.event.rdb.JobEventRdbSearch
com.dangdang.ddframe.job.statistics.rdb.StatisticRdbRepository 中关于DB的读写操作，资源应该释放：
1、Connection 连接池取完后要释放
2、PreparedStatement  执行完后需要关闭释放
3、ResultSet  遍历完数据后应关闭释放
finally应该关闭以上几个对象资源

### Actual behavior （实际运行的结果是）
 比如： 查询列表，见下代码
  private List<JobExecutionEvent> getJobExecutionEvents(final Condition condition) {
        List<JobExecutionEvent> result = new LinkedList<>();
        try (
                **Connection** conn = dataSource.getConnection();
                **PreparedStatement** preparedStatement = createDataPreparedStatement(conn, TABLE_JOB_EXECUTION_LOG, FIELDS_JOB_EXECUTION_LOG, condition);
                _ResultSet_ resultSet = preparedStatement.executeQuery()
                ) {
            while (resultSet.next()) {
                JobExecutionEvent jobExecutionEvent = new JobExecutionEvent(resultSet.getString(1), resultSet.getString(2), resultSet.getString(3), resultSet.getString(4),
                        resultSet.getString(5), JobExecutionEvent.ExecutionSource.valueOf(resultSet.getString(6)), Integer.valueOf(resultSet.getString(7)), 
                        new Date(resultSet.getTimestamp(8).getTime()), resultSet.getTimestamp(9) == null ? null : new Date(resultSet.getTimestamp(9).getTime()), 
                        resultSet.getBoolean(10), new JobExecutionEventThrowable(null, resultSet.getString(11)) 
                        );
                result.add(jobExecutionEvent);
            }
        } catch (final SQLException ex) {
            // TODO 记录失败直接输出日志,未来可考虑配置化
            log.error("Fetch JobExecutionEvent from DB error:", ex);
        }
        return result;
    }

### Steps to reproduce the behavior （可重现问题的操作步骤）
见上代码

**Comment by johnyannj** [comment]
try-with-resources 语法 和 finally是等效的，已经释放了
