### ISSUE TITLE
elastic-job 依赖jar包升级问题

### ISSUE THREAD

**Issue by 3tem** [apache/shardingsphere-elasticjob#698]
elastic-job 2.1.5版本，但是依赖的，zk 以及 Curator-* 版本依旧很低，是否有考虑过升级依赖jar包版本？
如果去掉elastic-job  中的zk相关依赖包进行单独进行升级，能否给出些升级参考意见？

**Comment by Leonidasz** [comment]
Yes, we have considered upgrade the dependency versoin, and we also intend to use the raw client of zk. You can refer to #475 first, and if you have any idea, you can discuss here or finish the idea and commit the pr.

**Comment by 3tem** [comment]
ok

**Comment by terrymanu** [comment]
Duplicated with #753
