### ISSUE TITLE
win10环境启动 控制台报错

### ISSUE THREAD

**Issue by 13917030454** [apache/shardingsphere-elasticjob#701]
C:\Users\BML\Desktop\elastic-job-lite-console-2.1.5\bin>if """" == """" set PORT=8899

C:\Users\BML\Desktop\elastic-job-lite-console-2.1.5\bin>java  -cp "C:\Users\BML\Desktop\elastic-job-lite-console-2.1.5\bin\..\lib\*;C:\Users\BML\Desktop\elastic-job-lite-console-2.1.5\bin\.." com.dangdang.ddframe.job.lite.console.ConsoleBootstrap 8899
Exception in thread "main" java.lang.NoClassDefFoundError: com/dangdang/ddframe/job/lite/console/ConsoleBootstrap

**Comment by 13917030454** [comment]
我已解决，以管理员身份运行就可以了

**Comment by Leonidasz** [comment]
: ) Please close this issue, thanks~
