### ISSUE TITLE
 ReconcileService线程数一直在陡增

### ISSUE THREAD

**Issue by caozhenhuamail** [apache/shardingsphere-elasticjob#702]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite：2.1.5
Expected behavior （您预期的结果是）
如何把ReconcileService和Curator-TreeCache 线程数稳定住，现在一直在增加
Actual behavior （实际运行的结果是）
每天这两个线程大概增加一倍的数量
Steps to reproduce the behavior （可重现问题的操作步骤）

1.手工创建任务
new SpringJobScheduler(elasticJob, regCenter, liteJobConfiguration, jobEventRdbConfiguration, elasticJobListeners).init();
2.手工删除任务
JobRegistry.getInstance().shutdown(jobName); //清除对象和zookepper缓存
regCenter.remove("/" + jobName); //清除目录

1. 提供接口触发elasticjob任务，然后延迟30s执行
2. 实时触发的时候实际是修改定时任务的cron的值
3. 但是发现"ReconcileService"  prio=5 os_prio=0 tid=0x00007f9330386800 nid=0x2dae1 waiting on condition [0x00007f9220ad1000] 和"Curator-TreeCache-2"  daemon prio=5 os_prio=0 tid=0x00007f94f0010800 nid=0x29a6f waiting on condition [0x00007f93196dd000]  线程数一直在增加. 其实我们的定时任务只有10个，每天就是修改这10个任务的相应执行实际；
4. 不知道这样使用是否有什么问题？ 以前我们是要实现实时任务就是新增定时任务，就是延迟1min来执行，但是这样会产生大量的任务；线程数同样也是没法控制住；最终我们采用修改时间的办法来实现，发现这两个线程的数量是一致的.

Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
We are already revising this problem, new version will fix it.
这个问题我们已经在处理中，新版本会修复相关问题。

**Comment by caozhenhuamail** [comment]
请问下新版本大概在什么时间点上线那，另外有计划增加任务依赖的功能吗，还有任务编排，还有任务分组功能？

**Comment by Leonidasz** [comment]
The focus of the new version is to fix some prominent problems received from the community before, the new features will be arranged and considered later. We will release it as soon as possible.
新版本重点是修复之前社区反馈的一些比较突出的问题，新功能方面后续会安排考虑，新版本的发布时间点不太好确定，我们会尽快推动。
另外，请修改一下issue的标题，还有就是也麻烦调整一下内容中“#”号的使用，会引用到无关的issue，谢谢！

**Comment by caozhenhuamail** [comment]
好的

**Comment by caozhenhuamail** [comment]
能否告知下解决方案那，如果相对比较简单想自己先升级下。 我们接入的任务越来越多，线程问题是个比较大的问题。

**Comment by Leonidasz** [comment]
Your e-mail, please~

**Comment by caozhenhuamail** [comment]
caozhenhuamail@sina.com

**Comment by Leonidasz** [comment]
Please check your email. As soon as possible, we'll fix these problems in new branches 3.0, so stay tuned.

**Comment by caozhenhuamail** [comment]
elasticjob:3.0 已经解决了线程数的问题了吗？能用于生产了吗

**Comment by Leonidasz** [comment]
@caozhenhuamail 
If you are in a hurry, you can adjust the code according to the ideas in last email. If there are any questions, you can send emails.
The pr for resource clean has been submitted and is currently under review.
The new release will include other bug fixes, so it will take some time to validate and test.
上次邮件里有相关的改造方案，如果生产需求比较着急的话，可以按照相关思路进行调整。如果有问题，可以邮件沟通。
资源释放相关的调整的pr已经提交，目前在review阶段。
新版本发布，会一并包含其他一些bug修复，所以需要花费一些时间验证和测试。

**Comment by caozhenhuamail** [comment]
非常感谢您的回复

**Comment by suyehe** [comment]
望提前告知解决方案 邮件: zhouxiangyang@dxy.cn

**Comment by Leonidasz** [comment]
@CowardY 
#705 please.

**Comment by suyehe** [comment]
收到谢谢  quartz 线程并不随着任务销毁而销毁这个问题好像这个commit里没有处理

**Comment by Leonidasz** [comment]
@CowardY 
In ```JobShutdownHookPlugin```, use a  simpler way.
有处理，在JobShutdownHookPlugin中，用了一个比较简单的方式。
链接里是之前整理的方案
http://note.youdao.com/noteshare?id=44e0767eb8a68b26808aa3ef0de2f802&sub=28EE6C5FC3EF426CAF424139202AC8D9
也可以参考 #686

**Comment by suyehe** [comment]
谢谢 quartz的那个 还需要把线程组关闭 我看上面好像遗漏了 可以通过把线程组设置成守护线程组来。

**Comment by terrymanu** [comment]
Fixed by #605 and #798
