### ISSUE TITLE
Sharding item for job 'Manage.DelayedSendingNoticeJob' is empty.

### ISSUE THREAD

**Issue by taikeung** [apache/shardingsphere-elasticjob#704]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Actual behavior （实际运行的结果是）
出现`Sharding item for job 'Manage.DelayedSendingNoticeJob' is empty.`会是哪些问题导致的？现在有一两个任务出现这种情况。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
It means that the current instance did not get the sharding item. This may be normal, you should confirm the sharding items of other instances at that moment.
这个表示当前实例没有获取到分片，这不一定表示异常，需要确认一下，其他实例在对应的调度期内，所获取的分片数情况。

**Comment by terrymanu** [comment]
Closed because of no response anymore.
