### ISSUE TITLE
服务重启后，原来的任务不会执行

### ISSUE THREAD

**Issue by hwgkill** [apache/shardingsphere-elasticjob#706]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by hwgkill** [comment]
通过api动态添加

     JobCoreConfiguration configuration = JobCoreConfiguration.newBuilder(jobConfig.getJobName(),
                    jobConfig.getCron(), 1)
                    .misfire(false)
                    .description(jobConfig.getDescription())
                    .jobParameter(jobConfig.getJobParameter())
                    .build();
            JobTypeConfiguration type=new SimpleJobConfiguration(configuration, jobType.getCanonicalName());
            LiteJobConfiguration liteJobConfiguration = LiteJobConfiguration
                    .newBuilder(type)
                    .disabled(false)// 作业是否启动时禁止
                    .overwrite(false)// 本地配置是否可覆盖注册中心配置
                    .build();
            JobScheduler jobScheduler = new JobScheduler(registryCenter, liteJobConfiguration);
            jobScheduler.init();

**Comment by ShortFinger** [comment]
我也有这个问题，如果我起了几个lite服务  但是lite服务现在全挂了就只能手动从zookeeper上找到任务节点然后恢复吗？或者我们要用自己的数据库保存任务信息，当所有lite服务都挂了重新启动时能恢复任务？

**Comment by Leonidasz** [comment]
@hwgkill 
Please provide detailed steps for repeating the problem. LiteJobConfiguration set overwrite false, so the job configuration added from the API is still based on the registry center. It is recommended to check the relevant configuration in registry, or delete the data of zk and restart.
最好提供一下能复现问题的详细步骤，另外LiteJobConfiguration设置了overwrite(false)，那么从api添加的作业配置还是以注册中心为准，建议核查一下注册中心的相关配置，或者删除zk的数据，重启试试。

@ShortFinger 
Normally, if the lite service is restarted, it will reconnect to the registry, join the job cluster, participate in the sharding, and when the schedule is triggered, the logic resumes.Elastic-job-lite is a highly available, stretchable architecture that does not require additional processing on the business side of logic. If the job is not executed after restarting, please confirm the reason first.
正常情况下lite服务如果重启后，会重连注册中心，加入作业集群，参与分片，调度触发后，会恢复执行相关逻辑。elastic-job-lite是高可用，弹性扩缩的架构，这块不需要业务侧再额外处理框架层面的逻辑。如果作业重启后不执行了，请先确认排查下不执行的原因。

**Comment by Fuselage** [comment]
Elastic-Job Cloud版本中，

**Comment by Fuselage** [comment]
Elastic-Job Cloud。重启任务服务器，注册中心会把部分任务（随机）置为无效；导致任务不执行。linux服务器中，重启任务服务；K8S中重启任务服务都是一样的结果。本地windows却没有问题。

**Comment by WengyXu** [comment]
我也遇到这个问题
```java
@ScheduledJob(name = "processExecutionRecordsJob", cron = "${job.cron.execution-records}", shardingTotalCount = 2, overwrite = true, failover = true, misfire = true)
public class ExecutionRecordsJob implements SimpleJob {

```
首次部署后任务执行正常，但当我更新部署后，任务则失效了。版本2.1.5

**Comment by Yenuo** [comment]
> 我也有这个问题，如果我要恢复几个精简服务，但是精简现在全挂了就只能手动从动物园管理员上找到任务节点然后恢复吗？我们需要自己的数据库保存任务信息，当所有精简服务都挂了膨胀启动时能不能恢复任务？
@ShortFinger
现在我使用的是3.0.0 也遇到这个问题？请问是如何解决的呢？

@Leonidasz @terrymanu    How did you solve it?
