### ISSUE TITLE
elastic-job重启启动，请问在3.0分支会有啥新特性？

### ISSUE THREAD

**Issue by ZShUn** [apache/shardingsphere-elasticjob#710]
rt

**Comment by compilerduck** [comment]
Yes, we restarted maintainence of Elastic-Job, in a new branch 3.0. Main changes include package change (from com.dangdang to i.elasticjob), version upgrade for some dependencies and some emergent bug fixes. 
是的，elastic-job重新启动维护，3.0分支不发布新特性，主要有以下变动：
1.包名从com.dangdang变成了io.elasticjob
2.某些依赖包的版本较低，会进行升级
3.修复社区反馈的比较多的bug，比如failover相关、分布式唯一任务不唯一、任务结束后资源不释放等问题，具体你可以参考近期提交的pull request。

**Comment by ZShUn** [comment]
那么3.0相当于一个过度版本咯，是否考虑长期维护下去？

**Comment by compilerduck** [comment]
开源软件的活力在于社区是否活跃，未来我们会致力于社区活跃性建设，需要你、我和大家的积极参与及回馈，如果你对此项目感兴趣，欢迎参与到ElasticJob的维护开发中来，参与的人多了，项目就活起来了:)

**Comment by gzdzss** [comment]
会考虑支持更多多注册中心吗,  比如 nacos

**Comment by compilerduck** [comment]
多注册中心支持在3.0版发布后，会进行考虑，到时候会排一下优先级，会优先做社区呼声高的功能，同时也鼓励大家多多参与。

**Comment by liubaochuan** [comment]
3.0 什么时间发布

**Comment by Leonidasz** [comment]
@liubaochuan 
会尽量争取在春节前，如果赶不上的话就春节过后了。

**Comment by CYXK** [comment]
现在能确定发布的具体时间了吗？

**Comment by neeuq** [comment]
同问，之前版本某些依赖包（如curator）的有点低，需要新版本升级。赞同上述3.0的改动，先做些维护性的调整，类似dubbo的重新开源之路。

**Comment by johnyannj** [comment]
又跳票了吗？

**Comment by Leonidasz** [comment]
@johnyannj 
首先抱歉，日期延后了，疫情也确实对发布造成了一定的影响。本人自1月23日起，低烧以及不适持续了10多天，且不说身体状况，在这个疫情爆发的时期，心理的情况可想而知。但是，esjob的发布工作一直在进行，并没有搁置，目前3.0版本计划发布的修改基本全部完成，也都提交了pr，近期我们的member还抽空review通过过了一个比较关键的pr。后续review工作完成后，我们会再进行一个整体回归测试，然后将新版本发布出来。
出于对代码质量的要求，member对pr提交的内容审核的比较仔细，相关问题也会反复沟通推敲，我们希望最终发布的版本是稳定可控的。
借用作者的一句话“开源不易”，参与esjob开源工作的同伴，都有本职的工作，参与开源工作都是不计报酬，仅凭一份内心的喜爱。
请各位理解，多多给予支持。
如果确实比较着急，也可以参看下我提交的几个pr，先行在项目中试用，如有问题，也可以在社区中沟通讨论。

**Comment by neeuq** [comment]
理解作者，开源都不容易。

**Comment by johnyannj** [comment]
@Leonidasz 
理解作者，支持作者，保重身体~

**Comment by johnyannj** [comment]
@Leonidasz  请问下 当前工作停滞在哪里了，我可以加入群中，贡献一份力量吗？

**Comment by Leonidasz** [comment]
@johnyannj 
Your QQ number, please~

**Comment by johnyannj** [comment]
@Leonidasz 497736866 谢谢

**Comment by terrymanu** [comment]
Please discuss on mail list:
https://lists.apache.org/thread.html/ra9f5c8053415d951ae34406422478b4f43b9039b9dd56ee1b814d321%40%3Cdev.shardingsphere.apache.org%3E
