### ISSUE TITLE
重构能把curator-framework升级到高版本吗?

### ISSUE THREAD

**Issue by WinSuperStar** [apache/shardingsphere-elasticjob#711]
2.1.x的curator-framework 和其他框架整合的时候要处理冲突，虽然用低版本在某些情况下也没什么问题，但是毕竟覆盖不了全场景，重构之后能否尽量适配下高版本，或者做两个适配版本出来，供使用者自由选择。

**Comment by Leonidasz** [comment]
Version conflicts for dependent components such as the curator and guava will be resolved in the 3.0 branch.
3.0 分支中会解决curator以guava等依赖组件的版本冲突问题。

**Comment by WinSuperStar** [comment]
got it

**Comment by fjxmhsl** [comment]
我也遇到了这个问题，客户公司安全组要求升级guava版本到28.1-jre，然后升级了curator-framework到4.1.0版本，启动直接报错了。

**Comment by zgooa1** [comment]
curator版本冲突问题有比较好的解决方案吗

**Comment by terrymanu** [comment]
duplicated with #753
