### ISSUE TITLE
是否支持不同节点不同权重？

### ISSUE THREAD

**Issue by ronyongxian** [apache/shardingsphere-elasticjob#715]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
最新版

### Expected behavior （您预期的结果是）
某个节点能抢先分配任务，如果任务被其他节点抢到，也能抢过来

### Actual behavior （实际运行的结果是）
所有节点对等分配任务

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
Elastic-job-lite支持自定义分片策略:
http://elasticjob.io/docs/elastic-job-lite/02-guide/job-sharding-strategy/

**Comment by ronyongxian** [comment]
> Elastic-job-lite支持自定义分片策略:
> http://elasticjob.io/docs/elastic-job-lite/02-guide/job-sharding-strategy/

均分 但某执行节点能优先获得作业 这种能否实现？

**Comment by terrymanu** [comment]
> > Elastic-job-lite支持自定义分片策略:
> > http://elasticjob.io/docs/elastic-job-lite/02-guide/job-sharding-strategy/
> 
> 均分 但某执行节点能优先获得作业 这种能否实现？

Yes, it is passible
