### ISSUE TITLE
集群有6个节点，任务有上万个，集群重启后部分定时服务无论如何都无法运行

### ISSUE THREAD

**Issue by lawplus** [apache/shardingsphere-elasticjob#717]
以下为生产的线程镜像：
`"order-autoconfirmreceive-job-0ff1c802d8df43dca22c251cd159d0d0_QuartzSchedulerThread" #6964 prio=5 os_prio=0 tid=0x00007f375dd9a800 nid=0x8a3f in Object.wait() [0x00007f36033c2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool.blockForAvailableThreads(SimpleThreadPool.java:452)
	- locked <0x00000000c7d59588> (a java.lang.Object)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:263)

"order-autoconfirmreceive-job-0ff1c802d8df43dca22c251cd159d0d0_Worker-1" #6963 prio=5 os_prio=0 tid=0x00007f375dd98800 nid=0x8a3e waiting on condition [0x00007f36034c3000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.dangdang.ddframe.job.util.concurrent.BlockUtils.sleep(BlockUtils.java:32)
	at com.dangdang.ddframe.job.util.concurrent.BlockUtils.waitingShortTime(BlockUtils.java:27)
	at com.dangdang.ddframe.job.lite.internal.sharding.ShardingService.blockUntilShardingCompleted(ShardingService.java:125)
	at com.dangdang.ddframe.job.lite.internal.sharding.ShardingService.shardingIfNecessary(ShardingService.java:108)
	at com.dangdang.ddframe.job.lite.internal.schedule.LiteJobFacade.getShardingContexts(LiteJobFacade.java:115)
	at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.execute(AbstractElasticJobExecutor.java:103)
	at com.dangdang.ddframe.job.lite.internal.schedule.LiteJob.execute(LiteJob.java:26)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
	- locked <0x00000000c7d59880> (a java.lang.Object)
`

这种任务无需sharding， 但是被block，一旦修改里面其对于zk的某个的属性值，对应目录就会消失掉，但是任务没执行。。

例如： set /elastic-job-lite/order-autoconfirmreceive-job-0ff1c802d8df43dca22c251cd159d0d0/leader/election/instance 10.72.27.53@-@86594

求助有没解决办法。正在研习源代码中

**Comment by Leonidasz** [comment]
Can you provide the detailed steps to reproduce the problem? 
能给出重现问题的详细步骤么？越详细越好。

**Comment by lawplus** [comment]
sure. here try to desc this problem as detail as I can:
1. 业务场景： 订单类自动确认收货的、时间段价格自动过期的等等（无需sharding分片），都是采用了此框架，这样造成了quartz线程池的爆炸性增长，于是
2. 我这边加了一些自己的逻辑，将此框架用于瞬时任务的执行，将此类瞬时（即cron表达式只执行一次的）任务对应的线程池关闭掉
3. 待进入standby的周期时间时，自动恢复这些瞬时任务
结果，现在的情况时，有相当一部分此类瞬时任务在二次重启后其线程执行都跌入了 BlockUtils.waitingShortTime。 

私人的邮箱是： cnpaul2005@163.com， 方便我们电邮沟通。

**Comment by lawplus** [comment]
get /elastic-job-lite/order-autoconfirmreceive-job-1810a1dab95241189c53be8297c27a1a/leader/election/instance
-- 是其本机进程 10.72.27.53@-@86594

get /elastic-job-lite/order-autoconfirmreceive-job-0ff1c802d8df43dca22c251cd159d0d0/leader/election/instance
-- 是其他机器的进程	10.72.27.161@-@11792

以上两个job都是被分配在 10.72.27.53@-@86594 ， 但是第二个是无法执行的。当修改第二个的instance节点的值时 (补充： 或者关掉 10.72.27.161@-@11792 的job进程 +_+ )，其整个job node立即消失掉，以为已执行了逻辑 实际没有。此时线程堆栈只剩下一个quarz work线程，没有quartz主线程了

附件附上我的瞬时job的实现类：
[SimpleJobScheduler.java.txt](https://github.com/elasticjob/elastic-job-lite/files/4091592/SimpleJobScheduler.java.txt)

10.72.27.53 有4个job进程， 161机器、61机器各有一个job进程节点

**Comment by lawplus** [comment]
是否是quartz设置的问题呢：
`private Scheduler createScheduler() {
        Scheduler result;
        try {
            StdSchedulerFactory factory = new StdSchedulerFactory();
            factory.initialize(getBaseQuartzProperties());
            result = factory.getScheduler();
            result.getListenerManager().addTriggerListener(schedulerFacade.newJobTriggerListener());
        } catch (final SchedulerException ex) {
            throw new JobSystemException(ex);
        }
        return result;
    }

    private Properties getBaseQuartzProperties() {
        Properties result = new Properties();
        result.put("org.quartz.threadPool.class", org.quartz.simpl.SimpleThreadPool.class.getName());
        result.put("org.quartz.threadPool.threadCount", "1");
        result.put("org.quartz.scheduler.instanceName", liteJobConfig.getJobName());
        result.put("org.quartz.jobStore.misfireThreshold", "1");
        result.put("org.quartz.plugin.shutdownhook.class", JobShutdownHookPlugin.class.getName());
        result.put("org.quartz.plugin.shutdownhook.cleanShutdown", Boolean.TRUE.toString());
        return result;
    }`

misfire 的设置？ misfireThreshold为1秒呢

**Comment by Leonidasz** [comment]
The config is ok, set misfire threshold is 1 millisecond, just set the condition of  misfire trigger. The misfire functionality in elastic-job-lite is actually self-implemented, not entirely based on quartz.
misfire的设置没有问题，配置misfireThreshold为1毫秒，只是设定misfire的触发条件，elastic-job-lite中misfire的功能实际上还是自行来实现的，并不是完全依托于quartz。

**Comment by Leonidasz** [comment]
抱歉还是没有太明白问题的具体流程？能否单纯从流程及执行逻辑层面说明下，不要描述业务内容。

**Comment by lawplus** [comment]
> 抱歉还是没有太明白问题的具体流程？能否单纯从流程及执行逻辑层面说明下，不要描述业务内容。

或者您簡述下如何設置job config，代碼不會進入 - .LiteJobFacade.getShardingContexts 這個方法？
又沒相關文章介紹整個job的執行過程可以推薦給我？若方便的話，可以加我QQ - 184974868 進行聊天。感謝！

**Comment by lawplus** [comment]
cron表达式为： 47 30 16 17 01 ? 2020

**Comment by Leonidasz** [comment]
[Job config(official)](http://elasticjob.io/docs/elastic-job-lite/02-guide/config-manual/)

[Job example(suggest)](https://github.com/elasticjob/elastic-job-example/tree/master/elastic-job-example-lite-springboot)

[Source analysis (recommend)](http://www.iocoder.cn/categories/Elastic-Job-Lite/)

Your cron expression measn the jobs will trigger only once ,just at 2020-01-17 16:30:47.

**Comment by Leonidasz** [comment]
@rongmin 
Notice the friend request of your QQ, please~

**Comment by rongmin** [comment]
![image](https://user-images.githubusercontent.com/9402650/73000618-13d66900-3e3c-11ea-84d8-f1da59b878bd.png)

**Comment by johnyannj** [comment]
elastic-job 一个任务会创建几个线程的， 你有1万了任务？ 还能跑的起来？

**Comment by terrymanu** [comment]
Any conclusion? can we close this issue?

**Comment by terrymanu** [comment]
Closed because of response anymore.

**Comment by lawplus** [comment]
yes,  my cluster can support 10w+ tasks with my some tuning codes. most tasks is one-time job.
and about this problem, it seems it's resource leak problem. coz after I restart my cluster every mid-night, this issue neven happened again...
and I will plan to upgrade the version which fixed leak problem
