### ISSUE TITLE
如何实现多服务器实例的任务轮询机制

### ISSUE THREAD

**Issue by furaul** [apache/shardingsphere-elasticjob#720]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Expected behavior （您预期的结果是）
当任务是单分片，同时有多个服务器实例时，希望任务可以在各个服务器轮流执行。
比如JOB单分片，三台服务器A，B，C，执行时间间隔1小时，10点开始触发。
希望10点在服务器A执行，11点在服务器B执行，12点在服务器C执行。

### Actual behavior （实际运行的结果是）
各个分片策略，在将分片分配到指定服务器之后，一直都会使用该服务器执行。
比如默认分片策略，单分片分配到服务器A之后，10点、11点、12点，该任务分片都在A执行。

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
多作业节点一般是为多分片提供分摊（多节点均摊多分片，提高作业分布式并发能力），或是为单分片提供高可用保障（当然，多分片的情况下也能保证高可用）。
你的需求比较特殊，定制化的分片策略也解决不了你的需求，因为作业就单分片，而且从你的需求来看，还不太好触发重分片。
不过有一种方式，你看是否可以参考一下：
3个节点上的作业，分别配置不同的调度cron，例如：A节点配置从0点开始，每3个小时执行一次；B节点配置从1点开始，每3个小时执行一次；C节点配置从2点开始，每3个小时执行一次；
这样应该可以满足你的需求，但是实际上你的集群中，作业是3个，而不是原先计划的1个了，如果你有高可用方面的考虑，可以为每个节点增加一个standby的节点。

**Comment by furaul** [comment]
> 多作业节点一般是为多分片提供分摊（多节点均摊多分片，提高作业分布式并发能力），或是为单分片提供高可用保障（当然，多分片的情况下也能保证高可用）。
> 你的需求比较特殊，定制化的分片策略也解决不了你的需求，因为作业就单分片，而且从你的需求来看，还不太好触发重分片。
> 不过有一种方式，你看是否可以参考一下：
> 3个节点上的作业，分别配置不同的调度cron，例如：A节点配置从0点开始，每3个小时执行一次；B节点配置从1点开始，每3个小时执行一次；C节点配置从2点开始，每3个小时执行一次；
> 这样应该可以满足你的需求，但是实际上你的集群中，作业是3个，而不是原先计划的1个了，如果你有高可用方面的考虑，可以为每个节点增加一个standby的节点。

感谢回复，我们参考下。
