### ISSUE TITLE
官方QQ群都满了，还有别的QQ群吗？

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#721]
官方群：
官方群(目前已满，请加官方2群)： 430066234（仅限于讨论与Elastic-Job相关的话题。我们希望您在入群前仔细阅读文档。并在入群后阅读公告以及修改群名片。谢谢合作。）
官方2群： 460139727

两个群都满了，还有别的群可以加入吗？

**Comment by Leonidasz** [comment]
回头我跟作者沟通一下。目前如果有什么需要讨论的话，可以通过issue交流，
