### ISSUE TITLE
云桌面运行任务，未生成任务执行日志

### ISSUE THREAD

**Issue by small-wang** [apache/shardingsphere-elasticjob#722]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Expected behavior （您预期的结果是）
Run a job and query a record in job_execution_log(执行一次任务，并且可以获取到执行日志)

### Actual behavior （实际运行的结果是）
Success run a job, but can not get a record in job_execution_log(成功执行一次任务，但是无法获取到执行日志)

### Steps to reproduce the behavior （可重现问题的操作步骤）
Env:HwCloudDeskTop(环境：华为云桌面)
Ops:Define a job and run regularly(操作：定义任务，并定时运行)

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
@Slf4j
@Component
public class TenderReportJob implements SimpleJob{
    @Autowired
    private TenderService tenderService;

    @Override
    public void execute(ShardingContext shardingContext) {
        log.info("准备检测生成填报任务...");
        tenderService.generateReportTask();
        log.info("结束检测生成填报任务...");
    }
}

### Reason
IpUtils.getIp() return null.

![1060898785](https://user-images.githubusercontent.com/13375317/76279370-590a0980-62c9-11ea-8cf6-399c238118e5.jpg)

**Comment by Leonidasz** [comment]
@small-wang 作业未执行的原因是在华为云环境下，IpUtils.getIp()返回为空，是么？

**Comment by small-wang** [comment]
> @small-wang 作业未执行的原因是在华为云环境下，IpUtils.getIp()返回为空，是么？

是的，NetworkInterface.getNetworkInterfaces()可以获取到部分网络接口，但是不包含有效的接口。该问题复现场景比较特殊，我尝试解决了，如果该问题被接受我可以提交PR看看。

**Comment by Leonidasz** [comment]
@small-wang 可以将你的解决方案在isuue中说明一下，这样也方便大家沟通讨论，如果最终方案ok的话，再麻烦提一下PR，THX~

**Comment by small-wang** [comment]
> @small-wang 可以将你的解决方案在isuue中说明一下，这样也方便大家沟通讨论，如果最终方案ok的话，再麻烦提一下PR，THX~

因为我本地同时使用了dubbo和elasticjob框架，dubbo框架可以正常获取本地ip并注册至zk，所以思路是参考dubbo获取本地ip实现：
1.尝试通过InetAddress获取本地ip并做合法性校验，合法则返回；
2.尝试通过NetworkInterface获取本地ip并做合法性校验，合法则返回；
3.返回null；

**Comment by terrymanu** [comment]
Fixed by #1069
