### ISSUE TITLE
springboot启动阻塞

### ISSUE THREAD

**Issue by Fdemo123** [apache/shardingsphere-elasticjob#724]
项目引用2.1.5的elastic-job-lite-core和elastic-job-lite-spring 后 启动日志打印：
 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate  - Multiple Spring Data modules found, entering strict repository configuration mode!
后自动停止

**Comment by Leonidasz** [comment]
应该是项目依赖spring data版本不一致导致的，可以检查一下自身的相关dependencies。
