### ISSUE TITLE
社区是否可以在3.0释放之前出一个2.1.x的稳定版本

### ISSUE THREAD

**Issue by johnyannj** [apache/shardingsphere-elasticjob#725]
@Elastic-job作者您好

我司在生产环境使用了elastic-job的2.1.5版本。也在使用过程中发现了诸多问题，同时反馈给了社区。

但是社区迟迟没有释放新的版本，前段时间呼之欲出的3.0版本，貌似也停滞了下来。

因为我司的开源政策，两年没有发布版本的软件，视为社区不活跃的开源软件，有未来无法升级维护的风险，是不建议采用的，所以我们当前面临重新技术选型的岔路口。

elastic-job的2.1.5版本已经是2017年发布的版本，距今已经快有3年了。目前社区issue已经积累了大量的issue，还有就是依赖的陈旧的第三方软件。相信应该有很多elastic-job的使用者可能会因为这个原因放弃使用elastic-job。

所以如果3.0分支有较长的版本计划的当前，我建议社区有必要基于当前社区的反馈，修正一些明显的bug，升级一些开源软件，释放一个新的稳定版本，这也是对社区反馈的回应，给使用者以信心。

望作者采纳。

**Comment by RocketTH** [comment]
我认同这个观点，我觉得在3.0出来之前，有必要出一个2.1.X的稳定版本，把这个版本的bug修复即可，还有一种做法可以和jdk一样，双向进行，2.1.X版本bug修复和3.0版本开发同时进行

**Comment by CYXK** [comment]
@johnyannj HW的？

**Comment by ZhiQinIsZhen** [comment]
me too

**Comment by fjxmhsl** [comment]
3.0版本有说什么时候发布吗

**Comment by terrymanu** [comment]
ElasticJob将于近期作为Apache ShardingSphere的子项目，会改包名和maven坐标的名字，因此不会再发布2.x版本了。
3.x版本会在近期规划，欢迎讨论。因此这个issue我先关闭了。

**Comment by miaogr86** [comment]
3.0计划什么时候发布？
