### ISSUE TITLE
怎样区分任务是 被 手动执行的还是 定时正常执行的？

### ISSUE THREAD

**Issue by kute** [apache/shardingsphere-elasticjob#726]
目前发现 任务被重复执行了，且在 不同的时间点，想问问 怎样区分任务是 被 手动执行的还是 定时正常执行的？有什么比较关键的日志吗？

**Comment by terrymanu** [comment]
You can use event-trace, FYI: http://elasticjob.io/docs/elastic-job-lite/02-guide/event-trace/

**Comment by kute** [comment]
thks
