### ISSUE TITLE
Discuss about donate Elastic-Job as a subproject of Apache ShardingSphere

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#728]
Hello everyone,

I am the founder of Elastic-Job, the project is established by dangdang.com.
I have no time to develop Elastic-Job and maintain the community during recent 3 years.

Currently, we need a distribute scheduler framework to process data migration of Apache ShardingSphere(https://github.com/apache/shardingsphere), I am VP of  Apache ShardingSphere too. I want start a discussion about donate elastic-job as a subproject of Apache ShardingSphere.

The benefits are:

1.  Apache ShardingSphere is an active community, there are more contributors to deal with Elastic-Job.
2.  We can continuous develop more features of Elastic-Job.

The challenge for current community is:

1. All issue and pull request need change to English.

Please give some advice. If no suitable reason to reject, I will try to ask dangdang.com provide SGA for donation and start to write the proposal.

Welcome give me some feedback, thank you very much.

**Comment by yu199195** [comment]
good idea.

**Comment by readazusa** [comment]
can I use chinese?

**Comment by terrymanu** [comment]
> can I use chinese?

请便，毕竟目前还没有结论说要捐入Apache

**Comment by FangOba** [comment]
+1

**Comment by kekerzzZ** [comment]
very good!
I learning source code during this time.   if possible I want to contribute to this project.

**Comment by dongzl** [comment]
This is a good idea. Elastic-Job is a very excellent project. Donate to Apache ShardingSphere will attract more people to develop it.

But I suggest to make Elastic-Job as a independent project and doesn't over coupling with ShardingSphere, for this user can use Elastic-Job independently even if they don't use ShardingSphere.

**Comment by terrymanu** [comment]
> very good!
> I learning source code during this time. if possible I want to contribute to this project.

Welcome, we can talk further if the project donated to ASF

**Comment by terrymanu** [comment]
> This is a good idea. Elastic-Job is a very excellent project. Donate to Apache ShardingSphere will attract more people to develop it.
> 
> But I suggest to make Elastic-Job as a independent project and doesn't over coupling with ShardingSphere, for this user can use Elastic-Job independently even if they don't use ShardingSphere.

Sure, it should be different projects, the new name should be `apache-shardingsphere-elasticjob`

**Comment by qixiaobo** [comment]
So maybe we need change package name again?

**Comment by terrymanu** [comment]
> So maybe we need change package name again?

You still can use current version

**Comment by lovepoem** [comment]
Exciting news, very awesome scheduling framework is coming back ！！！

**Comment by taojintianxia** [comment]
I personally believe the shardingspehre community will make elasticjob resurrected.

The strong evidence is that shardingsphere become the top class project of apache,  it's on the apache way , which means the community is professional and powerful . the statistics of shardingsphere is awesome, it's the honour for China internet industry

The donation of elasticjob not only make this project resurrected , but also attract more excellent commiter from shardingsphere community to keep on contributing.

please, please make this fantastic project alive  ASAP

**Comment by cherrylzhao** [comment]
looking forward to contribute again in shardingsphere !

**Comment by EasonFeng5870** [comment]
Carry on

**Comment by lvaolin** [comment]
好主意   期待中

**Comment by herozeng** [comment]
Good news, we can discuss new feature

**Comment by scorp2010** [comment]
It's so cool

**Comment by huyanfu** [comment]
good idea, The company is using.

**Comment by keven0706** [comment]
support

**Comment by PegasusS** [comment]
Come On！Just Do It！

**Comment by tanjunchen** [comment]
Nice Job! It is beneficial to the development of the project.  +1
if possible I want to contribute to this project.

**Comment by gzdzss** [comment]
期待

**Comment by kailbin** [comment]
👍

**Comment by ZhiQinIsZhen** [comment]
good for elasticjob

**Comment by neeuq** [comment]
+1

**Comment by tanjunchen** [comment]
@terrymanu 
for 
The challenge for current community is:
    All issue and pull request need change to English.
the comment of source code is also needed to change to en,right?

**Comment by johnyannj** [comment]
我认为elastic-job-lite实现比较粗糙，特别是可靠性 一致性方面。
不如重新构建一个好了。没必要捐赠当前这个。

**Comment by terrymanu** [comment]
The ElasticJob Donation Proposal:
https://cwiki.apache.org/confluence/display/SHARDINGSPHERE/ElasticJob+Donation+Proposal

Mailinglist:
https://lists.apache.org/thread.html/rd6171e2065be6bcfbeb7aba7e5c876eeed04db585c6ab78fc03a581c%40%3Cdev.shardingsphere.apache.org%3E

**Comment by terrymanu** [comment]
> 我认为elastic-job-lite实现比较粗糙，特别是可靠性 一致性方面。
> 不如重新构建一个好了。没必要捐赠当前这个。

你好，在捐入Apache之前，我们还能用中文交流哈。
我不太认同实现比较粗糙就需要重新做，社区就是为了集中大家的力量将它做好。社区优于代码，代码只是现状，活跃的社区代表着未来。
@johnyannj

**Comment by terrymanu** [comment]
> The challenge for current community is:
> All issue and pull request need change to English.
> the comment of source code is also needed to change to en,right?

Yes, it is better to establish a global and diversity community.

@tanjunchen

**Comment by tristaZero** [comment]
Hi Liang,

Thanks for this proposal. 
IMO, SGA and simple dependencies help this project become sub-project of Apache ShardingSphere easier. 

What concerns me a bit is that the core committer is only one person, Liang Zhang (Please correct if I missed something). 
Besides, the Chinese ISSUE list is supposed to be taken care of before ElasticJob steps on the international stage. 
I am glad to see a more active community of ElasticJob.

Best,
Trista

**Comment by Technoboy-** [comment]
Cool.

**Comment by wangfengstar** [comment]
调度的统一层面扩展，包括融入云原生体系的容器化方面的特性。这方面我们自己研发的平台已经在mesos、kubernetes中大规模使用。另外考虑计算模型编排方面，我们通过统一的流水线编排模型来统一多种依赖或者单个job的管理。-----英文写起来太困难，哈哈~

**Comment by terrymanu** [comment]
> Hi Liang,
> 
> Thanks for this proposal.
> IMO, SGA and simple dependencies help this project become sub-project of Apache ShardingSphere easier.
> 
> What concerns me a bit is that the core committer is only one person, Liang Zhang (Please correct if I missed something).
> Besides, the Chinese ISSUE list is supposed to be taken care of before ElasticJob steps on the international stage.
> I am glad to see a more active community of ElasticJob.
> 
> Best,
> Trista

I just reply in the mailing list

**Comment by Patrick0308** [comment]
这个事情有结论了吗

**Comment by terrymanu** [comment]
Voting: https://lists.apache.org/thread.html/r427b355c63376386e6444cb7849e77a1ce16877d5b0bee62fffca77a%40%3Cdev.shardingsphere.apache.org%3E

**Comment by terrymanu** [comment]
Voting passed[1].
I will start to process ElasticJob donation to Apache ShardingSphere community soon.

[1] https://lists.apache.org/thread.html/rbbc1d5fa7bf69d8e75476154d635774cb432943aade21d7a01eba11c%40%3Cdev.shardingsphere.apache.org%3E

**Comment by ailanjieqi** [comment]
好事是好事 我想知道啥时候可以多写些设计文档

**Comment by munanzi** [comment]
Does Elastic-Job have a visual interface like xxljob？

**Comment by FN20200222** [comment]
啥时候发布新版本啊，上个版本还是2017年的，好多人都跑到xxl-job那边了，啥时候可以使用springboot start
