### ISSUE TITLE
el-job指定任务时间轮询不生效的原因有哪些？

### ISSUE THREAD

**Issue by DKodak** [apache/shardingsphere-elasticjob#729]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
指定每半小时轮询应该按正常隔半小时执行一次
### Actual behavior （实际运行的结果是）
不执行，但是指定单独的时间运行可以运行
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Can you provide more details?

**Comment by DKodak** [comment]
> 您能否提供更多详细信息？

Of course, the situation we met at that time was as follows: five timing tasks were triggered at 10:30, but it was found that another 10:30 timing task was added later, but it was not triggered, so it was triggered at the specified time and then changed back to 10:30, and it was not triggered, which was a bit bad

**Comment by terrymanu** [comment]
Did the previous job finish before job trigger?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
