### ISSUE TITLE
LeaderLatch 永久阻塞主线程

### ISSUE THREAD

**Issue by liubaochuan** [apache/shardingsphere-elasticjob#730]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite-spring 2.1.5
curator 4.2.0
zk 3.5.5
### Expected behavior （您预期的结果是）
重启后正常能注册和选择leader不阻塞主线程
### Actual behavior （实际运行的结果是）
"main" - Thread t@1
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <1f732c94> (a org.apache.curator.framework.recipes.leader.LeaderLatch)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.curator.framework.recipes.leader.LeaderLatch.await(LeaderLatch.java:331)
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.executeInLeader(JobNodeStorage.java:189)
	at com.dangdang.ddframe.job.lite.internal.election.LeaderService.electLeader(LeaderService.java:54)
	at com.dangdang.ddframe.job.lite.internal.schedule.SchedulerFacade.registerStartUpInfo(SchedulerFacade.java:114)
	at com.dangdang.ddframe.job.lite.api.JobScheduler.init(JobScheduler.java:110)

查询zk上节点数据发现 ：
/XXjob/leader/election/latch 在计划任务应用都停掉的情况下有个临时节点一直不消失
_c_dfef2441-28cc-4cd2-91a7-30f92f636358-latch-0000000002

### Steps to reproduce the behavior （可重现问题的操作步骤）
不一定能马上复现，我们计划任务项目反复重启会偶尔出现。这时如果修改namespace重启就回复正常
，更换namespace后leader选择不会阻塞主线程
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
ZookeeperConfiguration zkConfig = new ZookeeperConfiguration(this.config.getZkAddressList(), this.config.getNamespace());
        zkConfig.setMaxRetries(this.config.getMaxRetries());
        CoordinatorRegistryCenter coordinatorRegistryCenter = new ZookeeperRegistryCenter(zkConfig);
        coordinatorRegistryCenter.init();

 LiteJobConfiguration.Builder builder = LiteJobConfiguration.newBuilder(jobTypeConfiguration);
        //覆盖配置
        builder.overwrite(true);
 new SpringJobScheduler(job, coordinatorRegistryCenter, builder.build()).init();

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
ElasticJob just use curator 2.1.0, I can not guarantee the dependency updated.
