### ISSUE TITLE
Library Upgrade

### ISSUE THREAD

**Issue by xlofhappy** [apache/shardingsphere-elasticjob#753]
the Google-Guava Library is too old, please upgrade it

**Comment by terrymanu** [comment]
We can not update them directly, it need to test.

**Comment by dalaocu** [comment]
Yes, I met the same problem. It used some deprecated methods, such as com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()

**Comment by terrymanu** [comment]
Upgrade by #864, any other lib need to be upgraded?

**Comment by xlofhappy** [comment]
I have not seen it, it's version still be 18.0

**Comment by dalaocu** [comment]
> Upgrade by #864, any other lib need to be upgraded?

guava

**Comment by xlofhappy** [comment]
> > Upgrade by #864, any other lib need to be upgraded?
> 
> guava

I checked twice, guava.version not be changed

**Comment by terrymanu** [comment]
@xlofhappy Can you submit a pull request to upgrade guava?

**Comment by terrymanu** [comment]
Will closed soon if no upgrade needed.

**Comment by QWRDA** [comment]
> @xlofhappy Can you submit a pull request to upgrade guava?

I think I don't have enough knowledge to do it. If no one submit a PR, will the guava stop at Version(18.0)?

**Comment by terrymanu** [comment]
Updated by #1060
