### ISSUE TITLE
Support redis registry center

### ISSUE THREAD

**Issue by CYXK** [apache/shardingsphere-elasticjob#774]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No!

### Describe the feature you would like.
current registry center only zookeeper,so could we provide other registry center like redis or etcd etc...

**Comment by terrymanu** [comment]
This issue is not necessary, I just keep it as volunteer wanted to open discuss and seek for contributor who want to do it.

**Comment by nilIfNull** [comment]
Want Nacos as a registration center

**Comment by terrymanu** [comment]
Because they are unnecessary, and it seems like nobody want to do it, I just close this issue.
