### ISSUE TITLE
Refactor MonitorService

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob#782]
## Feature Request
Currently, if a job has something wrong, and need to dump data, we have to configure a monitor port per job. As the job increases, the port grows. I think monitor service is an useful function that should support by default. And every project, we should only config one monitor service and dump with command 'dump jobName' is much more better.  So I would like to talk about the refactoring about MonitorService.
1. We need to add monitor config namespace as like 'reg' and 'job'.
2. Monitor config relies on reg due to current implementation, so still keep it.
3. Monitor config should have a default port and be enabled by default.
4. Refactor the codes that involves with MonitorService.
And please give some more advise.

**Comment by Technoboy-** [comment]
@terrymanu

**Comment by terrymanu** [comment]
@Technoboy- This is a good idea, we can try to do it.
