### ISSUE TITLE
Use spring boot to refactor elastic-job-lite-console

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#836]
The current elastic-job-lite-console is using jetty.

For convenient reason, it is better to change it to spring boot.
After change to spring boot, we need use it to handle job event dao with spring boot + JPA.

**Comment by viviel** [comment]
May I try this task？

**Comment by kekerzzZ** [comment]
I want to try this task.

**Comment by terrymanu** [comment]
@kekerzzZ Welcome, assigned
