### ISSUE TITLE
Use spring boot + JPA to deal with statistics dao

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#838]
Current statistics dao is using JDBC which can not adapt different database dialects.
It is better to use spring boot + JPA to more databases.

**Comment by rudy2steiner** [comment]
I want pick up this as my fisrt issue ,please assign it to me

**Comment by dhc575757** [comment]
May I try this task?

**Comment by cocodroid** [comment]
May I try this issue?

**Comment by nmyphp** [comment]
I will do my best, please assign to me.

**Comment by Mark-WJQ** [comment]
I want to try this

**Comment by Mark-WJQ** [comment]
May i get this task? And which version of springBoot will use?

**Comment by terrymanu** [comment]
Sorry to reply late, I just assign the issue to you guys, maybe you can discuss how to team work on this issue.

**Comment by Mark-WJQ** [comment]
It's better to modify trace and console together,because they are use same modle class

**Comment by rudy2steiner** [comment]
thanks! i will try my best
