### ISSUE TITLE
Add SQL dialect for event tracing storage

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#840]
The current event tracing storage use properties file to process SQL which to distinguish different SQL dialects.
 
MySQL, H2 properties have finished, SQL92 need to be polish. 
The PostgreSQL, Oracle, SQLServer, DB2 are missing.
Developer can add properties in to `META-INF\sql` folder.

- [x] Add `META-INF\sql\postgresql.properties` and provide correct SQL for PostgreSQL
- [x] Add `META-INF\sql\oracle.properties` and provide correct SQL for Oracle
- [x] Add `META-INF\sql\sqlserver.properties` and provide correct SQL for SQLServer
- [x] Add `META-INF\sql\db2.properties` and provide correct SQL for DB2
- [x] Update `META-INF\sql\sql92.properties` and provide correct SQL for SQL92

**Comment by tianbin1001** [comment]
please assign to me

**Comment by terrymanu** [comment]
@tianbin1001 Welcome

**Comment by dhc575757** [comment]
please assign to me

**Comment by terrymanu** [comment]
@dhc575757 Cool, assigned

**Comment by jiang2015** [comment]
I will try postgresql,thanks.

**Comment by jiang2015** [comment]
I think  this sql [CREATE INDEX TASK_ID_STATE_INDEX ON JOB_STATUS_TRACE_LOG (task_id, state)];

it is better like this [CREATE INDEX TASK_ID_STATE_ORIGINAL_TASK_ID_INDEX ON JOB_STATUS_TRACE_LOG (task_id, state, original_task_id)]

for this sql [SELECT original_task_id FROM JOB_STATUS_TRACE_LOG WHERE task_id=? and state='TASK_STAGING' LIMIT 1] 

 [TASK_ID_STATE_ORIGINAL_TASK_ID_INDEX]  using Covering index(覆盖索引),  避免二次回表查询, @terrymanu

**Comment by terrymanu** [comment]
I can not decide because add field in index may cause insert slower. We need to have a performance test report to support our decision.

**Comment by jiang2015** [comment]
table [JOB_EXECUTION_LOG] column [is_success INT NOT NULL]  I think in MYSQL: [is_success tinyint(1) NOT NULL] is better,  IN JAVA class [JobExecutionEvent], [is_success] style is boolean, I test in my local , it is the same result. @terrymanu
