### ISSUE TITLE
Remove JDBC driver dependency for elastic-job-lite-console

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#841]
The current elastic-job-lite-console depend MySQL which the license cannot compatible with ASF.
We need to remove MySQL dependency and add new ext-lib to permit user introduce JDBC driver by themselves.

- [x] Add ext-lib folder
- [x] Update start script, setup ext-lib into classpath
- [x] Remove MySQL dependency
- [x] Update document for adding customized JDBC driver  dependency

**Comment by TeslaCN** [comment]
@terrymanu I can make it. Please assign to me.
