### ISSUE TITLE
Will update spring version?

### ISSUE THREAD

**Issue by Mark-WJQ** [apache/shardingsphere-elasticjob#852]
I notice that the newest version of spring is 5.0+, but ejob use version is 4.0 +。So will you have a plan,that , import the lastest spring and springBoot project ?

**Comment by terrymanu** [comment]
Any contributor interesting this issue?

**Comment by Technoboy-** [comment]
> Any contributor interesting this issue?

If @Mark-WJQ wanna to do ,leave it to him. Otherwise, I will take it.

**Comment by Mark-WJQ** [comment]
> > Any contributor interesting this issue?
> 
> If @Mark-WJQ wanna to do ,leave it to him. Otherwise, I will take it.

I think i will do that,so which version will up to?

**Comment by terrymanu** [comment]
Great. It is better if the spring version is range, the upper should be open.
