### ISSUE TITLE
Replace JobSettings to YamlJobConfiguration

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#866]
It is better to reuse YamlJobConfiguration instead of JobSettings because of they are similar.

The tasks are:

- [x] Use YamlJobConfiguration instead of JobSettings in console backend
- [x] Make sure JSON transform with YamlJobConfiguration between frontend and backend are corrected.
- [x] Update frontend to make sure update properties are corrected (`stream.process` and `script.command.line`).
- [x] Rename JobSettingsAPI.
- [x] Remove JobSettings.
- [x] Fix test cases.

**Comment by DreamcatcherGo** [comment]
Please assign to me.

**Comment by terrymanu** [comment]
@DreamcatcherGo Thank you, assigned
