### ISSUE TITLE
Add features relate to statistics

### ISSUE THREAD

**Issue by nmyphp** [apache/shardingsphere-elasticjob#871]
The class RDBStatisticRepository is not used.

**Comment by terrymanu** [comment]
This feature didn't finish, do you interesting about to do it?

**Comment by nmyphp** [comment]
Yes, I want to finish it.

**Comment by terrymanu** [comment]
@nmyphp Welcome, I just assign to you

**Comment by nmyphp** [comment]
So sorry~, I've been busy with my work recently,  who can help me complete this issue.

**Comment by nmyphp** [comment]
经过梳理发现，遇到两个阻碍：
1. 统计功能不适合放在console，因为console模块的数据源不是用户级的，统计完了存到哪个数据源。感觉统计功能应该放到tracing。
2. 界面需要哪些指标展示，这个目前没设计。
这块儿要不先放放，等console重构完了再做？

**Comment by terrymanu** [comment]
Sure, we can leave it there for now. I just close this issue.
