### ISSUE TITLE
这个版本是否支持重启后自动加载通过API创建的任务？

### ISSUE THREAD

**Issue by chenyongyin** [apache/shardingsphere-elasticjob#888]
在2.65的版中，系统重启后spring xml配置的任务能够重新加载并执行，但是通过java api动态创建的任务不会被重新加载，为了解决这个问题，我们修改了源码，通过zk的配置重新加载任务。不知道当前版本是否还存在这个问题

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
