### ISSUE TITLE
官网挂了

### ISSUE THREAD

**Issue by makf-fly** [apache/shardingsphere-elasticjob#905]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by Technoboy-** [comment]
Looks good, nothing wrong!
http://shardingsphere.apache.org/elasticjob/
