### ISSUE TITLE
Can you remove the quartz dependency and implement your own time scheduling framework

### ISSUE THREAD

**Issue by readazusa** [apache/shardingsphere-elasticjob#914]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by yu199195** [comment]
please for english

**Comment by terrymanu** [comment]
Any reason for remove the quartz dependency?

**Comment by readazusa** [comment]
To reduce the dependence of the framework and improve the controllability of scheduling, I hope elastic job can create its own scheduling implementation, 
just like SS removed ‘durid’ SQL statement parsing and used its own set of SQL parsing. This is just an idea of my own, thank you.

**Comment by readazusa** [comment]
To reduce the dependence of the framework and improve the controllability of scheduling, I hope elastic job can create its own scheduling implementation, 
just like SS removed ‘durid’ SQL statement parsing and used its own set of SQL parsing. This is just an idea of my own, thank you.

**Comment by terrymanu** [comment]
Reuse is better than create a new one, did you find some problems on QuartZ and can not be resolved?

About the dependency of QuartZ, I can not imagination that user will use QuartZ and ElasticJob together, is it?

ShardingSphere is different situation, user can use ShardingSphere-JDBC and Druid together.

**Comment by terrymanu** [comment]
Closed because of no response anymore
