### ISSUE TITLE
Fix check style problem with class BasePageRequest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#932]
The class `org.apache.shardingsphere.elasticjob.lite.console.dto.request.BasePageRequest` is break rule of check style.
There are use `// CHECKSTYLE:OFF` to avoid checkstyle validate, but protected field modifiers do not allow.

Please remove `// CHECKSTYLE:OFF` and provide protected getter and setter method to instead of protect fields.

**Comment by TeslaCN** [comment]
I can make it, please assign to me. @terrymanu

**Comment by terrymanu** [comment]
already fixed
