### ISSUE TITLE
The job can not enable for disabled job integrate test sometimes

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#953]
The job can not enable for disabled job integrate test sometimes, it is better to investigate why enable operation can not in effect.
The test case class is `org.apache.shardingsphere.elasticjob.lite.integrate.assertion.disable.ScheduleDisabledJobIntegrateTest`, please open the comment lines to reproduce it.

**Comment by kekerzzZ** [comment]
I can try.

**Comment by terrymanu** [comment]
@kekerzzZ Thank you, assigned.

**Comment by terrymanu** [comment]
The problem still existed
