### ISSUE TITLE
2.1.5 not support job-instance-id???

### ISSUE THREAD

**Issue by luguohong** [apache/shardingsphere-elasticjob#964]
## Question

2.1.5 not support job-instance-id?

i use spring xml to config job,like:
<job:simple id="testTask" class="com.service.TestTask"
                registry-center-ref="regCenter"
                cron="0/10 * * * * ?"
                sharding-total-count="1"
                sharding-item-parameters="0=A"
    />
when i add job-instance-id,like:
job-instance-id="testTask-${server.port}"
and run then log show that
cvc-complex-type.3.2.2: 元素 'job:simple' 中不允许出现属性 'job-instance-id'
the 'job-instance-id' i found in https://shardingsphere.apache.org/elasticjob/lite/02-guide/config-manual/

**Comment by terrymanu** [comment]
The document should be updated, we will update it before 3.0.0 release

**Comment by luguohong** [comment]
when 3.0.0 release？？？Expect it to show up
Whether upgrading from 2.1.5 to 3.0.0 is supported？？？

**Comment by terrymanu** [comment]
The version 3.x is not compatible with version 2.x. 
It must rename the package name because of the apache release.
And the new Job API is designed by #792
