### ISSUE TITLE
Consider about rename monitor service

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#973]
The current monitor service is not good name for the proposal.
`snapshot` maybe a better name which can explain to dump job runtime snapshot for user.
The tasks need to do:

- [x] Rename MonitorService to SnapshotService
- [x] Rename monitorPort to dumpPort
- [x] Rename <elasticjob:monitor> to <elasticjob:snapshot> for spring namespace
- [x] Update document and exampe

**Comment by Technoboy-** [comment]
Ok, please assign to me!
